### ISSUE TITLE
Developing local packages can be a bit annoying

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#1005]
Let's say we have created some local unregistered packages (A, B, C, D) in the following dependency graph:

```` 
    A
   / \
  B    C
 /
D
```` 

If we want to `dev A` we need to "manually" resolve the dependency graph by doing:

```
dev path/to/D
dev path/to/B
dev path/to/C
dev path/to/A
```

even if `B, C, A` have Projects / Manifests so they can find all their dependencies. If we just do `dev path/to/A` straight away we will get an error that we don't know about `B` and `C`.

What we could do is have a step where we e.g. search in the `LOAD_PATH` for packages that we currently don't know about. So then we would have `push!(LOAD_PATH, path/to)` and then `dev path/to/A`. We would then find `B` and `C` in the `LOAD_PATH` and then `D` etc recursively.

**Comment by StefanKarpinski** [comment]
Here's what I was thinking. If all four packages are already cloned into `~/.julia/dev` and you add `~/.julia/dev` to `LOAD_PATH` then you would be able to do `pkg> add A` and it would work as long as all of the packages have project files and UUIDs. Does that make sense?

**Comment by fredrikekre** [comment]
This is part of why I wanted #492.

**Comment by krrutkow** [comment]
Similar to #698

**Comment by fredrikekre** [comment]
`pkg> dev path/to/A path/to/B path/to/C path/to/D` doesn't work?

**Comment by KristofferC** [comment]
This is fixed now via the recursive "search" for other developed packages via their manifest.
