### ISSUE TITLE
Support for `archive` in the registry

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#102]
Right now, the way that tarballs are downloaded is by pattern matching on the `repo` url and redirect to an archive.

In addition, perhaps the registry should allow an `archive` URL for a version of a package.

Alternatively, we could allow hooking into the pattern matching which is a bit "uglier" but might work ok.

cc @aviks

**Comment by StefanKarpinski** [comment]
I think it's better to have links for both that way people can have local policies about which they prefer to use.
