### ISSUE TITLE
Indirect dependencies and special state

### ISSUE THREAD

**Issue by 00vareladavid** [JuliaLang/Pkg.jl#1024]
I thought a package tracking a repo must necessarily be a direct dependency. This is not the case.

Users can enter this state with:
- Start with a dependency graph which requires `A`
- `dev A#master`
- `rm A`

This is a weird situation because there is no way to reach this state directly through the current API. We could conceivably support this, but the whole point of specifying direct dependencies is to define an environment's interface. In other words, I'm having a difficult time thinking of a case where user requires constraints on a node in the dependency graph where that node is not a direct dependency.

**Comment by 00vareladavid** [comment]
Related to #836

**Comment by fredrikekre** [comment]
Duplicate of #461?

**Comment by 00vareladavid** [comment]
Yep. I misinterpreted "freed" to mean "pruned" :sweat_smile:
