### ISSUE TITLE
dev with new path to same package does not show a diff

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg.jl#1027]
```
(v1) pkg> dev .
 Resolving package versions...
  Updating `~/.julia/environments/v1/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1/Manifest.toml`
 [no changes]

(v1) pkg> st
    Status `~/.julia/environments/v1/Project.toml`
  [7876af07] Example v0.5.1+ [`../../../dev/Example`]

(v1) pkg> dev /home/fredrik/dev/Example/
 Resolving package versions...
  Updating `~/.julia/environments/v1/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1/Manifest.toml`
 [no changes]

(v1) pkg> st
    Status `~/.julia/environments/v1/Project.toml`
  [7876af07] Example v0.5.1+ [`~/dev/Example`]
```

**Comment by StefanKarpinski** [comment]
In general the diff doesn't capture enough information: there are a number of things that can change in the manifest and we don't display it. It would be nice, now that we have a fully-specified data model for the manifest if we could indicate any changes in the diff somehow, even if only to print the line and somehow indicate visually that _something_ has changed, even if not what.

**Comment by KristofferC** [comment]
Should be enough to look at the `.path` field here: https://github.com/JuliaLang/Pkg.jl/blob/06fe92fe50d742655b00712ab22fddae0e1d0eff/src/Display.jl#L150-L151.

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/Pkg.jl/issues/587
