### ISSUE TITLE
rm removes [targets]

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/Pkg.jl#1039]
Self-contained example in a repo, `v"1.2.0-DEV.268"`.

https://github.com/tpapp/PkgBugDemo.jl

**Comment by fredrikekre** [comment]
Duplicate of #876? Should be fixed by https://github.com/JuliaLang/Pkg.jl/pull/985

**Comment by tpapp** [comment]
I thought that building from source would use the latest `Pkg`. Or only the released version?

**Comment by KristofferC** [comment]
It uses https://github.com/JuliaLang/julia/blob/master/stdlib/Pkg.version.

**Comment by tpapp** [comment]
I guess it is the exact same issue. Feel free to close, and sorry for the noise, search did not turn that issue up.

Incidentally, is a Pkg version bump planned in the near future for Julia `master`?

**Comment by fredrikekre** [comment]
> Incidentally, is a Pkg version bump planned in the near future for Julia master?

Yea, would be good with an alpha soon since there have been some major refactorings in Pkg.
