### ISSUE TITLE
Can't dev packages with git@github.com:... url

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/Pkg.jl#1044]
```
(v1.2) pkg> dev git@github.com:vchuravy/Cthulhu.jl.git
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Cloning git-repo `git@github.com:vchuravy/Cthulhu.jl.git`
ERROR: failed to clone from git@github.com:vchuravy/Cthulhu.jl.git, error: GitError(Code:ERROR, Class:Net, unsupported URL protocol)
julia> versioninfo()
Julia Version 1.2.0-DEV.204
Commit d821a111a3* (2019-01-23 17:48 UTC)
Platform Info:
  OS: Linux (ppc64le-redhat-linux)
  CPU: unknown
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, pwr9)

```

**Comment by StefanKarpinski** [comment]
Is this a Pkg limitation or a libgit2 limitation?

**Comment by fredrikekre** [comment]
Works for me on mac and linux.

**Comment by 00vareladavid** [comment]
I think in this case we just hand off the URL to libgit

**Comment by StefanKarpinski** [comment]
@vchuravy: are you using a system libgit2 or anything like that?

**Comment by vchuravy** [comment]
@Keno This was just a plain source build on Power9, right?
I think I have seen that on 1.2 on Linux as well before.

**Comment by Keno** [comment]
> @Keno This was just a plain source build on Power9, right?

Yep, I think so

**Comment by Keno** [comment]
For me on 1.2, I get:
```
(v1.2) pkg> dev git@github.com:vchuravy/Cthulhu.jl.git
   Cloning git-repo `git@github.com:vchuravy/Cthulhu.jl.git`
Private key location for 'git@github.com':
```
though it works fine on 1.1

**Comment by Keno** [comment]
Maybe we're somehow missing libssh2 support in the power build?

**Comment by grahamas** [comment]
This is still a problem on v1.6.  I remember there's a simple workaround that I've used before and currently forget, but I want to bump this first.  If you come across this issue and post before I've edited it with the workaround, please feel free to poke me.

**Comment by fredrikekre** [comment]
What system are you on? Using official binaries? Since it works for everyone else it and we don't know what the issue really is it seems premature to add a warning.You get a pretty descriptive error message after all.

**Comment by grahamas** [comment]
Sorry, I failed to notice that this is not quite the same error I'm seeing, which I've been running into for quite a while.  However, it also boils down to "Can't dev packages with git@github.com:... url", just with a different underlying cause.  The problem that I get is that ssh insists on using a key and doesn't pay attention to config'd keys (#1733). Also in that case, the error message isn't particularly helpful in guiding you to use `https`.
