### ISSUE TITLE
Argument error while importing one module into another module.

### ISSUE THREAD

**Issue by yashcodes** [JuliaLang/Pkg.jl#1081]
hey,
Actually I am trying to `import`a module named `Strategy` into other other module named `SortedVector` but while doing that I am getting this Argument error. Can anyone help me what I am doing wrong here. 
```
julia> using IntervalOptimisation
[ Info: Precompiling IntervalOptimisation [c7c68f13-a4a2-5b9a-b424-07d005f8d9d2]
ERROR: LoadError: LoadError: ArgumentError: Package IntervalOptimisation does not have Strategy in its dependencies:
- If you have IntervalOptimisation checked out for development and have
  added Strategy as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with IntervalOptimisation
Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:836
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1044
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /Users/yash/.julia/dev/IntervalOptimisation/src/IntervalOptimisation.jl:1
 [6] top-level scope at none:0
 [7] include at ./boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1044
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:319 [inlined]
 [12] eval(::Expr) at ./client.jl:393
 [13] top-level scope at ./none:3
in expression starting at /Users/yash/.julia/dev/IntervalOptimisation/src/SortedVectors.jl:43
in expression starting at /Users/yash/.julia/dev/IntervalOptimisation/src/IntervalOptimisation.jl:7
ERROR: Failed to precompile IntervalOptimisation [c7c68f13-a4a2-5b9a-b424-07d005f8d9d2] to /Users/yash/.julia/compiled/v1.0/IntervalOptimisation/Af1Uc.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at ./loading.jl:1203
 [2] _require(::Base.PkgId) at ./loading.jl:960
 [3] require(::Base.PkgId) at ./loading.jl:858
 [4] require(::Module, ::Symbol) at ./loading.jl:853
```

**Comment by StefanKarpinski** [comment]
Does `IntervalOptimisation` have `Strategy` in its dependencies?

**Comment by yashcodes** [comment]
No `IntervalOptimisation` does'nt have `Strategy` in its dependencies. `Strategy` is a new file containing module `Strategy` made by me, I am not getting it clearly which project file are you talking about ??

**Comment by yashcodes** [comment]
According to error I think I need to add `Strategy` in dependency of `IntervalOptimisation`. How can we do that ??

**Comment by yashcodes** [comment]
Actually what I really want to do is that, that their is a function in module `Strategy` to which I have to add a method, to do so I need to import `Strategy` in module `SortedVector` and this error is coming while importing the module `Strategy`.  And module `IntervalOptimisation` is using `SortedVector`.

_this is the situation_
module Strategy
function func( )
end
export func
end

module SortedVector

import Strategy.func    # this is where error comming

function func() .           #adding method
 end 

end
  
module IntervalOptimisation

Include("SortedVector.jl")
using .SortedVector

end

**Comment by dpsanders** [comment]
I think you need 
```
import ..Strategy: func
```

**Comment by yashcodes** [comment]
Already tried. Not works :( 
It gives the this error
_julia> using IntervalOptimisation
[ Info: Precompiling IntervalOptimisation [c7c68f13-a4a2-5b9a-b424-07d005f8d9d2]
ERROR: LoadError: LoadError: UndefVarError: Strategy not defined
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1044
 [3] include at ./sysimg.jl:29 [inlined]_

**Comment by KristofferC** [comment]
You also need:

```
module IntervalOptimisation
include("Strategy.jl") # <-------- missing for you
include("SortedVector.jl")
using .SortedVector
end
```

**Comment by yashcodes** [comment]
ohh it works with `Strategy : func`.

**Comment by yashcodes** [comment]
But there is another problem. After successfully adding a method to function `func` in module `SortedVector`, the added method get automatically vanished when the control again come back `IntervalOptimisation` and again function `func` is left with only one original method which was defined in `Strategy`
