### ISSUE TITLE
Conditional Dependencies

### ISSUE THREAD

**Issue by 00vareladavid** [JuliaLang/Pkg.jl#1085]
Crazy idea. Support "conditional dependencies"/"features" in a "sandbox"-analogous manner. (Note this is just meant to prod the search space, not as a serious/complete solution)

```
Foo
├── feature
│   ├── A
│   │   ├── Project.toml
│   │   └── src
│   │       └── A.jl
│   └── B
│       ├── Project.toml
│       └── src
│           └── B.jl
├── Project.toml
└── src
    └── Foo.jl
```

When someone runs `add --feature=A Foo`, `Pkg` will sandbox `Foo` in `Foo/feature/A` and add the result to the active dependency graph.

So `Foo/src/Foo.jl` will contain the core logic. `Foo/feature/A/src/A.jl` will contain the "A feature" logic.

Advantages:
-  No need to query for which features are activated, it is apparent from the filesystem location
- Conceptually reinforces "environments" as an organizational unit.

**Comment by StefanKarpinski** [comment]
I like it. This seems like a promising idea.

**Comment by aaowens** [comment]
If this were to happen it could help with https://github.com/JuliaStats/Distributions.jl/issues/702 without needing Distributions to require Optim.

**Comment by cscherrer** [comment]
Doesn't Flux have some trick to handle this problem? I don't see `CuArrays` as a dependency, but...
https://fluxml.ai/Flux.jl/stable/gpu/

**Comment by KristofferC** [comment]
It uses Requires.jl, see #1285

**Comment by KristofferC** [comment]
I think https://github.com/JuliaLang/Pkg.jl/issues/1285 is a bit more recent take on this.

**Comment by 00vareladavid** [comment]
For the purpose of history, this proposal more closely resembles #1233, not #1285.
