### ISSUE TITLE
Make Pkg warn on case dependent file names

### ISSUE THREAD

**Issue by laborg** [JuliaLang/Pkg.jl#1094]
It's completely fine to build a package on Linux that uses case sensitive files, but the same package will error on Mac OS and Windows (E.g. during test).

Having Pkg warn on files that only differ by lower/uppercase would, IMHO, be a nice feature.

With pointers to the source code I might be able to prepare a PR.

**Comment by StefanKarpinski** [comment]
At what point would you want the error about files that differ only by case?

**Comment by laborg** [comment]
At `test` appears natural. Or is there some kind of validation command (comparable to Rs "check")?

In this PR it's only implemented as a warning, but I don't see why it shouldn't be strict.
https://github.com/JuliaLang/Pkg.jl/pull/1099

**Comment by laborg** [comment]
Are there any plans to add general package validation functions into Pkg.jl? See http://r-pkgs.had.co.nz/check.html for inspiration:

- Checking for hidden files and directories. 
- Checking for portable file names.
- Checking for sufficient/correct file permissions.
- Checking installed package size. 
- ...

Or would this be better fit into a new package (e.g. PkgChecks) ?

**Comment by StefanKarpinski** [comment]
Yes, this should all be checked. Can you file an issue on [Registrator.jl](https://github.com/JuliaComputing/Registrator.jl)?

**Comment by KristofferC** [comment]
Don't think there is anything left to do here.
