### ISSUE TITLE
Support specifying a range of versions

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaLang/Pkg.jl#1096]
(Note this may be a duplicate of #843 - cannot quite tell - feel free to close if it is)

Currently, to support multiple "breaking change" versions of a packlage requires writing out the list of all supported versions in the `[compat]` section of the Project.toml file
e.g. `Example = "0.22, 0.23, 0.24, 0.25, 0.26, 0.27"`

It would be convenient if this were possible to specify this with a range (or other compact syntax), 
e.g. `Example = "0.22 - 0.27"`

I suspect this is a common enough use-case that it is worth having compact syntax for it.

**Comment by StefanKarpinski** [comment]
Dup of https://github.com/JuliaLang/Pkg.jl/issues/843.
