### ISSUE TITLE
Generalize REPL interface (into separate package)

### ISSUE THREAD

**Issue by chakravala** [JuliaLang/Pkg.jl#1101]
It would be fantastic if the REPL interface of this package could be generalized into some kind of separate repository, so that other packages can use the whole GIT and REPL package management code for purposes other than just julia package management.

So basically, I need to be able to hook in and use a similar repository download framework but with my own custom database and functions as operations (beside the standard repository operations)

**Comment by StefanKarpinski** [comment]
I don't think anyone here has any interest in being responsible for helping support and not breaking LaTeX, vim, etc. repl modes.

**Comment by StefanKarpinski** [comment]
There's no real actionable item on this repo.

**Comment by chakravala** [comment]
It shouldn't be very difficult to make this work, all the functions I need are these right here:
```Julia
import Pkg.REPLMode: OptionSpec, OptionSpecs, ArgSpec, CommandSpec, CommandSpecs, SuperSpecs, QString, unwrap, Option, wrap_option, is_opt, parse_option, Statement, lex, tokenize, core_parse, parse, Command, enforce_option, MiniREPL
```
if those set of functions can be turned into an API, then it would be very convenient

**Comment by KristofferC** [comment]
This package has an MIT license so with attribution you are free to copy paste whatever you want into your project.

**Comment by chakravala** [comment]
Thanks for letting me know, yes I have already copied the necessary code and it is working.

For the time being, that will do, but my hope was that I could import the code from `Pkg.REPLMode` once it becomes stable here... the abstract command parsing is a feature needed in multiple packages

**Comment by StefanKarpinski** [comment]
The command parsing is pretty ad hoc and likely to change. Less ad hoc now that @00vareladavid has worked it over than when I originally wrote it, but still not intended as a general command parsing system.

**Comment by chakravala** [comment]
Alright, so I have now committed the new `REPLMode` to my repo in the following files

https://github.com/chakravala/VerTeX.jl/blob/master/src/repl.jl
https://github.com/chakravala/VerTeX.jl/blob/master/src/specs.jl
https://github.com/chakravala/VerTeX.jl/blob/master/src/completions.jl
https://github.com/chakravala/VerTeX.jl/blob/master/src/args.jl
https://github.com/chakravala/VerTeX.jl/blob/master/src/cmd.jl

which accounts for all the features for making the argument parsing

```Julia
vtx> vim gaps/sieve.vtx
```
this is my new `vtx>` prompt from which I can do advanced non-linear document editing with LaTeX

as I said above, the following commands could theoretically be imported from `Pkg.REPLMode`
```Julia
OptionSpec
OptionSpecs
ArgSpec
CommandSpec
CommandSpecs
SuperSpecs
QString
unwrap
Option
wrap_option
is_opt
parse_option
Statement
lex
tokenize
core_parse
parse
Command
enforce_option
MiniREPL
```
thanks to @00vareladavid for making the contributions, it helped me a lot, hope to see this go further

**Comment by StefanKarpinski** [comment]
If you want shell-like command parsing, then you probably want to look at the implementation of backticks in Base, not this command parser which is very different than the shell.

**Comment by chakravala** [comment]
no, that's not what this does... this runs Julia code, launches an editor, and then runs a bunch of scans on the output, it is much more than a shell command, it triggers hundreds of lines of julia code and updates a decentralized information database.

the command is only named `vim` due to the editor choice, but is actually not a shell command, it's more

**Comment by 00vareladavid** [comment]
IMO the last round of refactoring left the REPL in a fairly general state, I was very happy with it. The only thing I don't like is that the autocomplete system is too brittle. I would like to redesign it, but it should hold over for a while more.

@chakravala I can't commit to maintaining much more than `Pkg` right now. If you want to copy the code, note the [declaration format](https://github.com/JuliaLang/Pkg.jl/blob/master/src/REPL/command_declarations.jl)  **is** the API. All that would need to be done is to make the declaration format a bit more user friendly, perhaps with a macro.
