### ISSUE TITLE
instantiate an instantiated env should be a no-op

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg.jl#1108]

**Comment by KristofferC** [comment]
What does it do now?

**Comment by fredrikekre** [comment]
Updates registries and repos. Although I guess not repos since #1102.

**Comment by 00vareladavid** [comment]
Dup of #852 then?

But yes, I think being more conservative with registry updates would be good. This should be fairly straightforward for `instantiate`, but it is a bit tricky in general.

**Comment by felipenoris** [comment]
Yes, I was talking about this on Slack.
I share julia projects among many users and they use a standard Jupyter notebook to run stuff. So everytime someone runs the notebook, which is quite often, the `Pkg.instantiate()` hangs for about 5secs looking for repos on github.
If the user already have the exact versions for deps listed on the manifest file, there should have no need to go to the internet to update repos.

**Comment by KristofferC** [comment]
Closing as dup of https://github.com/JuliaLang/Pkg.jl/issues/1108

**Comment by felipenoris** [comment]
But this is #1108

**Comment by KristofferC** [comment]
Thanks I updated.

I always(!) do this.
