### ISSUE TITLE
Windows or appveyor "loses" branch-specified dependency

### ISSUE THREAD

**Issue by timholy** [JuliaLang/Pkg.jl#1115]
When developing a package that depends on an unmerged PR in another package, the recommended workflow seems to be to commit the `Manifest.toml` (e.g., #770). In this context it's interesting to see the following two CI runs (which occurs for https://github.com/timholy/Rebugger.jl/pull/61 at the same commit):
- https://travis-ci.org/timholy/Rebugger.jl/builds/507646043?utm_source=github_status&utm_medium=notification
- https://ci.appveyor.com/project/timholy/rebugger-jl/builds/23143365

The odd part here is the
```
path C:\Users\appveyor\.julia\packages\Revise\LQBZj for package Revise no longer exists. Remove the package or `develop` it at a new path
```

Note that I had committed a `Manifest.toml` created with `add Revise#teh/lowered`. The relevant section of the manifest is
```
[[Revise]]
deps = ["CodeTracking", "Distributed", "FileWatching", "InteractiveUtils", "JuliaInterpreter", "LibGit2", "LoweredCodeUtils", "OrderedCollections", "Pkg", "REPL", "Random", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "305cd05470a88221025a16db4b1f5d1501791b7c"
repo-rev = "teh/lowered"
repo-url = "https://github.com/timholy/Revise.jl.git"
uuid = "295af30f-e4ad-537b-8983-00126c2a3abe"
version = "1.1.0+"
```
It's funny that it lists `version = "1.1.0+` when that branch's Project.toml file has `version = "2.0.0"`. That seems likely to be a problem; what I don't understand is why Travis/Unix is different from Appveyor/Windows.

**Comment by timholy** [comment]
Hmm, the version number may be a red herring; I played with a commit that bumps it (https://github.com/timholy/Rebugger.jl/pull/61/commits/c367f52eacacd89e0db527ceb26240a9dfcccf2f), and it didn't help.

**Comment by KristofferC** [comment]
What happens if you add a `Pkg.instantiate()` before the `Pkg.add`?

**Comment by timholy** [comment]
I should have tried that earlier. With registered packages the problem has disappeared.

I am pretty sure, though, that on the docs build for Linux, it was caused by having committed a `Manifest.toml` also to the `docs/` directory. Once I deleted that, the problem went away. Feel free to close if you think that's it.

**Comment by KristofferC** [comment]
Not sure what is actionable there. Closing for now.
