### ISSUE TITLE
A strange error while installing a package [Kuber.jl] on Windows

### ISSUE THREAD

**Issue by findmyway** [JuliaLang/Pkg.jl#1116]
Following are the error messages while installing [Kuber.jl](https://github.com/JuliaComputing/Kuber.jl) on Windows:

```
ERROR: Error when installing package Kuber:
AssertionError: length(dirs) == 1
Stacktrace:
 [1] install_archive(::Array{String,1}, ::Base.SHA1, ::String) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:482
 [2] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:596 [inlined]
 [3] (::getfield(Pkg.Operations, Symbol("##26#29")){Symbol,Pkg.Types.Context,Dict{Base.UUID,Base.SHA1},Dict{Base.UUID,Array{String,1}}})() at .\task.jl:259
```

```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-1630 v3 @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
```

Ref: https://github.com/JuliaComputing/Kuber.jl/issues/12

**Comment by KristofferC** [comment]
When we extract the tarball for the package we assume that there is only one directory in it, the directory of the release. This seems to fail here. Is it only for this package?

It could be something similar as the workaround at:

https://github.com/JuliaLang/Pkg.jl/blob/896505fc88de2bf29660055098f1f05fc81ac568/src/Operations.jl#L492-L494

**Comment by findmyway** [comment]
Yeah, for now I only find the error with Kuber.jl

**Comment by KristofferC** [comment]
It does have a bunch of more files:

![kuber](https://user-images.githubusercontent.com/1282691/54636928-c05ef600-4a87-11e9-967d-72a13a52a02e.PNG)

Perhaps we can just take the directory that starts with the name of the package?

**Comment by StefanKarpinski** [comment]
Do we know why it has all that other stuff in there?

**Comment by KristofferC** [comment]
I found https://stackoverflow.com/questions/34688392/paxheaders-in-tarball but I don't know why this package specifically has these files.

**Comment by StefanKarpinski** [comment]
@tanmaykm, any idea?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/Pkg.jl/issues/1943#issuecomment-670208333

**Comment by KristofferC** [comment]
> Tar.jl knows how to extract tarballs with POSIX extended features, so it will correctly extract these.

**Comment by StefanKarpinski** [comment]
Summary (for myself as much as anyone else): we used to use `7z` to extract tarballs, but it doesn't understand POSIX extended headers so if anyone created a package or artifact with very long file names or deeply nested paths, the old Pkg client would be unable to correctly extract the tarball with `7z`. We now use `Tar.extract` which does know how to extract these, so this is no longer a problem.
