### ISSUE TITLE
Error to install Pkg.add  Unsatisfiable requirements detected for package DebuggerFramework 

### ISSUE THREAD

**Issue by Jeffguitarhero** [JuliaLang/Pkg.jl#1118]
I am trying to install in Julia v 1.1.0 many package but I obtain  like the following:

julia> Pkg.add("GLPK")
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package DebuggerFramework [67417a49]:
 DebuggerFramework [67417a49] log:
 ├─possible versions are: 0.1.0-0.1.2 or uninstalled
 ├─restricted by compatibility requirements with Atom [c52e3926] to versions: 0.1.0-0.1.2
 │ └─Atom [c52e3926] log:
 │   ├─possible versions are: [0.1.0-0.1.1, 0.2.0-0.2.1, 0.3.0, 0.4.0-0.4.6, 0.5.0-0.5.10, 0.6.0-0.6.17, 0.7.0-0.7.15, 0.8.0-0.8.1] or uninstalled
 │   └─restricted to versions 0.7.14 by an explicit requirement, leaving only versions 0.7.14
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

julia> Pkg.add("Ipopt")
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package DebuggerFramework [67417a49]:
 DebuggerFramework [67417a49] log:
 ├─possible versions are: 0.1.0-0.1.2 or uninstalled
 ├─restricted by compatibility requirements with Atom [c52e3926] to versions: 0.1.0-0.1.2
 │ └─Atom [c52e3926] log:
 │   ├─possible versions are: [0.1.0-0.1.1, 0.2.0-0.2.1, 0.3.0, 0.4.0-0.4.6, 0.5.0-0.5.10, 0.6.0-0.6.17, 0.7.0-0.7.15, 0.8.0-0.8.1] or uninstalled
 │   └─restricted to versions 0.7.14 by an explicit requirement, leaving only versions 0.7.14
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

julia> Pkg.add("CSV")
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package DebuggerFramework [67417a49]:
 DebuggerFramework [67417a49] log:
 ├─possible versions are: 0.1.0-0.1.2 or uninstalled
 ├─restricted by compatibility requirements with Atom [c52e3926] to versions: 0.1.0-0.1.2
 │ └─Atom [c52e3926] log:
 │   ├─possible versions are: [0.1.0-0.1.1, 0.2.0-0.2.1, 0.3.0, 0.4.0-0.4.6, 0.5.0-0.5.10, 0.6.0-0.6.17, 0.7.0-0.7.15, 0.8.0-0.8.1] or uninstalled
 │   └─restricted to versions 0.7.14 by an explicit requirement, leaving only versions 0.7.14
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

This error appears from today March 21, 2019, previously I installed normally in this version.

**Comment by KristofferC** [comment]
Try to `Pkg.rm("DebuggerFramework")` first.

**Comment by Jeffguitarhero** [comment]
I obtain this:

julia> Pkg.rm("DebuggerFramework")
┌ Warning: `DebuggerFramework` not in project, ignoring
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:1131
[ Info: No changes

**Comment by KristofferC** [comment]
Ok try `rm -m DebuggerFramework` (in the Pkg REPL).

**Comment by Jeffguitarhero** [comment]
Many thanks, it was solved with that

**Comment by ABMSUH** [comment]
Hi,
I am facing the same problem.
But I am not clear about "Ok try rm -m DebuggerFramework (in the Pkg REPL)" .
Could you please clarify how I will do in Julia ( windows 10) ?

I mean .....
julia>

**Comment by KristofferC** [comment]
Press `]` and then enter the command.

**Comment by ABMSUH** [comment]
Okay

**Comment by ABMSUH** [comment]
Then, will I do  "rm -m DebuggerFramework"  ?

**Comment by KristofferC** [comment]
Yeah

**Comment by ABMSUH** [comment]
(v1.1) pkg>  rm -m DebuggerFramework
  Updating `C:\Users\Pechman\.julia\environments\v1.1\Project.toml`
  [c52e3926] - Atom v0.7.14
  Updating `C:\Users\Pechman\.julia\environments\v1.1\Manifest.toml`
  [e6d88f4b] - ASTInterpreter2 v0.1.1
  [bf4720bc] - AssetRegistry v0.1.0
  [c52e3926] - Atom v0.7.14
  [7057c7e9] - Cassette v0.2.2
  [53a63b46] - CodeTools v0.6.4
  [67417a49] - DebuggerFramework v0.1.2
  [33d173f1] - DocSeeker v0.2.0
  [de31a74c] - FunctionalCollections v0.5.0
  [cd3eb016] - HTTP v0.7.1
  [9fb69e20] - Hiccup v0.2.2
  [83e8ac13] - IniFile v0.5.0
  [7c4cb9fa] - LNR v0.2.0
  [50d2b5c4] - Lazy v0.13.2
  [739be429] - MbedTLS v0.6.8
  [510215fc] - Observables v0.2.3
  [fa939f87] - Pidfile v1.1.0
  [88034a9c] - StringDistances v0.3.1
  [0796e94c] - Tokenize v0.5.3
  [37b6cedf] - Traceur v0.3.0
  [a2a6695c] - TreeViews v0.3.0
  [0f1e0344] - WebIO v0.7.0
  [104b5d7c] - WebSockets v1.4.0
  [cc8bc4a8] - Widgets v0.5.1
  [7b1f6079] - FileWatching

**Comment by ABMSUH** [comment]
Next, what should I do for "Pkg.add("Distributions")" ?

**Comment by ABMSUH** [comment]
julia> using Pkg

julia> Pkg.add("Distributions")
 Resolving package versions...
 Installed Compat ───────────── v2.1.0
 Installed Parsers ──────────── v0.2.22
 Installed TranscodingStreams ─ v0.9.3
 Installed Optim ────────────── v0.18.1
  Updating `C:\Users\Pechman\.julia\environments\v1.1\Project.toml`
  [31c24e10] + Distributions v0.16.4
  Updating `C:\Users\Pechman\.julia\environments\v1.1\Manifest.toml`
  [34da2185] ↑ Compat v2.0.0 ⇒ v2.1.0
  [429524aa] ↑ Optim v0.17.2 ⇒ v0.18.1
  [69de0a69] ↑ Parsers v0.2.20 ⇒ v0.2.22
  [3bb67fe8] ↑ TranscodingStreams v0.9.2 ⇒ v0.9.3

**Comment by ABMSUH** [comment]
julia> using Distributions

Oh my god, It is working........................Thanks a lot for your kind cooperation.

**Comment by ABMSUH** [comment]
Hi,
I have a problem, with PyPlot in julia as:


julia> using PyPlot

julia> x = range(0,stop=2*pi,length=1000); y = sin.(3*x + 4*cos.(2*x))
1000-element Array{Float64,1}:
 -0.7568024953079282
 -0.7687979429150046
 -0.7801330261327849
 -0.790830536475742
  ⋮
 -0.7166271329853839
 -0.7307395907784272
 -0.7441239200875579
 -0.7568024953079278

julia> plot(x, y, color="red", linewidth=2.0, linestyle="--")
ERROR: MethodError: no method matching plot(::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, ::Array{Float64,1}; color="red", linewidth=2.0, linestyle="--")
Closest candidates are:
  plot(::Any, ::Union{Array{Layer,1}, Function, Element, Theme, Type}...; mapping...) at C:\Users\Pechman\.julia\packages\Gadfly\09PWZ\src\Gadfly.jl:287
  plot(::Any, ::Dict, ::Union{Array{Layer,1}, Function, Element, Theme, Type}...) at C:\Users\Pechman\.julia\packages\Gadfly\09PWZ\src\Gadfly.jl:321 got unsupported keyword arguments "color",
"linewidth", "linestyle"
Stacktrace:
 [1] top-level scope at none:0

**Comment by fredrikekre** [comment]
Please post questions at https://discourse.julialang.org/.

**Comment by ABMSUH** [comment]
Hi,
I am facing a big problem in Julia as follow:

“We tried to lunch Julia from:
C:\Users\Pechman\AppData\Local\Julia-1.1.0\bin\julia.exe
This path can be changed in the settings.
Details:
Access is denied.”

Please advise me to fix it…

**Comment by fredrikekre** [comment]
Please post questions at https://discourse.julialang.org/.
