### ISSUE TITLE
Pkg clone/add from Private Offline Repository?

### ISSUE THREAD

**Issue by usmcamp0811** [JuliaLang/Pkg.jl#1119]
I have an offline system and a private Git repository with a lot of Julia Packages how can I go about installing those packages from my repository? Every time I try it Pkg try's to find `github.com` and well thats not possible.. the system is offline. 

I tried to dig around in `julia/share/julia/stdlib/v1.0/Pkg/src` looking for references of github but the one place I found so far doesn't seem to help.. 

Thanks

**Comment by fredrikekre** [comment]
I am guessing the problem is that Pkg tries to update the registry. If the system is completely offline I guess you don't want to use the General registry anyway, so might as well just remove that and then Pkg should not try to update it.

**Comment by usmcamp0811** [comment]
I've got a clone of the [Generl](https://github.com/JuliaRegistries/General) in my git repo.. can I just change the point from github to there?

**Comment by fredrikekre** [comment]
Yea, sure.

**Comment by usmcamp0811** [comment]
any idea where that would be?

**Comment by fredrikekre** [comment]
What do you mean? Where the local copy of the registry is? It should be in `~/.julia/registries`.

**Comment by usmcamp0811** [comment]
I dont have a file there.. sorry I'm still pretty new to Julia.. I've used it enough to know I want to use it more.. but am still learning all of its secrets.. I'll keep digging around thanks for the help

**Comment by StefanKarpinski** [comment]
If you put the cloned `General` repo in `~/.julia/registries` then Pkg will use that without having to connect to the internet. Of course it will still need to connect to the internet to get packages so that may just kick the can down the road a bit for your problem.

**Comment by usmcamp0811** [comment]
Thanks all I think I got it working now!
