### ISSUE TITLE
project instantiate - ignore missing [git-tree-sha1] entry

### ISSUE THREAD

**Issue by phlavenk** [JuliaLang/Pkg.jl#1123]
Would it be possible to only issue a warning if a manifest does not contain a [git-tree-sha1] section.

In my case it happens for tutorial notebook with a project file. The problem is I have to specify the [git-tree-sha1] for the package where the tutorial project file is in. As soon as I change the entry, the SHA for package is also changed. If I could specify only the version number for this package, problem would be solved.

**Comment by StefanKarpinski** [comment]
How is the code being found? By path?

**Comment by KristofferC** [comment]
If it is found by path we already leave out `git-tree-sha1`.

**Comment by StefanKarpinski** [comment]
That's why I was asking. If it's not found by path or git-tree-sha1 then how is it found? Those are the only two ways as far as I'm aware.

**Comment by phlavenk** [comment]
The idea is to only allow this for a registered package - use the registry to find the path based on UUID and version string.

**Comment by KristofferC** [comment]
Code loading cannot and shouldn't have to look in the registry.
