### ISSUE TITLE
Better docs on compatibility version numbers

### ISSUE THREAD

**Issue by felipenoris** [JuliaLang/Pkg.jl#1126]
The [Compatibility section](https://julialang.github.io/Pkg.jl/v1/compatibility/) of the docs give a few examples on version ranges.

At one point, it gives an example as:

```
julia = "1.0"
```

Later, it gives examples as `>= 1.2.3` or `^1`, but it doest not say anything about the `"` character.

Is any of this valid?
```
julia = "^1.0"
julia = ^1.0
julia >= ^"1.0"
```

I would suggest to clarify that in the docs.

**Comment by StefanKarpinski** [comment]
Only this one is valid:
```toml
julia = "^1.0"
```
The file uses TOML format, which does not include any syntax for version ranges or things like `>=` between keys and values. The value is a string which Pkg parses an interprets as a semver specifier.

**Comment by StefanKarpinski** [comment]
Part of the confusion may come from the mix of TOML format in the docs section for this with pseudo-syntax to explain what different kinds of version specifiers mean. Perhaps the distinction between those could be made clearer or even better the explanation could always use valid TOML syntax.

**Comment by felipenoris** [comment]
@StefanKarpinski , yes, that is what I was trying to point out. If it would make easier for you, I could send a PR for that.

**Comment by StefanKarpinski** [comment]
Sure, that would be great!
