### ISSUE TITLE
Better guidance for users in resolving pkg conflicts

### ISSUE THREAD

**Issue by timholy** [JuliaLang/Pkg.jl#1131]
In my various repos, I get a continuous stream of "I can't install pkg X" issues, most of which arise from a conflict between Y and Z, neither of which has anything to do with X. But because the user wanted X and encountered an error and doesn't know what to do, the bug report gets filed in X's repository. After a while, such bug reports begin to annoy the developer(s) of X.

I'm not quite sure what better guidance would mean in practice, but here are some options:
- a line "You have encountered a Pkg conflict. See *some url* for more information"
- a line "This package conflict may have nothing to do with X. Please read the message below carefully before reporting an issue."
- a bot that package developers can instanll that screens these issues and blocks them from being filed if none of the conflicting packages have anything to do with the repo to which it's being reported.

**Comment by tpapp** [comment]
I would suggest combining the first two:

> You have encountered a package conflict, which may not be related to the operation you were trying to perform. See https://julialang.github.io/Pkg.jl/v1/conflicts

(the url above is fictional at this point)

**Comment by StefanKarpinski** [comment]
I'm working on a new SAT-based version resolver which should hopefully make it easier to give useful diagnostic information when there are unresolvable requirements like this. In the meantime, I'm not sure if there's something better we can do with the current resolver.

**Comment by KristofferC** [comment]
I don't think this issue is much about improving the resolver itself but having a dedicated doc page, linked to from the resolver error, that gives a bit of info on why this happens and how to resolve (huehue) it.

**Comment by oxinabox** [comment]
Can this be closed now, I head the new docs are much better

**Comment by timholy** [comment]
Hah, I had forgotten I'd filed this when I submitted #1798.
