### ISSUE TITLE
Optional post upgrade precompilation option

### ISSUE THREAD

**Issue by musm** [JuliaLang/Pkg.jl#1132]
Would it be possible to allow for precompilation after running an `up` command?  I'm more inclined to wait for all my packages to upgrade and precompile after running `up`, as opposed to when trying to work and loading packages, where it is far more annoying to wait for precompilation to complete.

**Comment by fredrikekre** [comment]
`pkg> up; precompile`?

**Comment by musm** [comment]
I suppose we don't feel confident in setting this as the default after running `up`?

**Comment by KristofferC** [comment]
Not really, no.
