### ISSUE TITLE
Pkg.activate should throw error if can't find project

### ISSUE THREAD

**Issue by felipenoris** [JuliaLang/Pkg.jl#1136]
This kind of problem occurs often, and it's hard for users to understand the cause.

If one tries to activate a project with an invalid location to the project files, like so

```julia
Pkg.activate("/wrong/path/to/Project")
```

There's no error message. But then `using Project` complains.

``` 
Package Project not found in current path:
- Run `import Pkg; Pkg.add("Project")` to install the Risk package.
```

I would guess that in this case the `activate` command should throw an error.
Currently, given that there's no error message on the `activate` command, users assume that the given path is correct and the problem should be related to `using Project` command.

**Comment by StefanKarpinski** [comment]
It doesn't throw an error because activating a project that doesn't exist yet is how you create a new one.

**Comment by felipenoris** [comment]
Oh, I see. I would argue that for that there should exist a

```julia
Pkg.create("path/to/new/project")
```

And

```julia
Pkg.activate("/path/to/project", create=false)
```

I would also argue that `Pkg.activate(path; create::Bool=false` should be the default behavior, since activating a project without creating a new one is the common scenario.

**Comment by felipenoris** [comment]
Even if you reject my input, which is fine, this looks like does nothing, because it fails to create a new project, since the path is not valid.

```julia
julia> Pkg.activate("/x/x/x/jkalsdjfklasjdfkl")                                                                                                 
[ Info: activating new environment at /x/x/x/jkalsdjfklasjdfkl.                                                                                 
"/x/x/x/jkalsdjfklasjdfkl"
```

**Comment by fredrikekre** [comment]
The `activating new environment` message is meant for this purpose, to notify that there does not exist a `Project.toml` file there.
