### ISSUE TITLE
Test deps not required on nightly

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg.jl#1144]
e.g. https://travis-ci.org/JuliaGraphs/LightGraphs.jl/builds/519328333

**Comment by KristofferC** [comment]
I'm guessing the `LOAD_PATH` is no longer correctly set on the spawned process?

**Comment by fredrikekre** [comment]
Also happens for build https://discourse.julialang.org/t/travis-ci-configuration-with-new-project-toml-file/23942

**Comment by 00vareladavid** [comment]
Can you elaborate on the issue? The original isolation is not working anymore?

**Comment by fredrikekre** [comment]
Probably caused by https://github.com/JuliaLang/Pkg.jl/pull/1058 which we backported to 1.0.4 and 1.1.1 so not this bug is there too :tada:

**Comment by fredrikekre** [comment]
Another example; https://travis-ci.org/libAtoms/ASE.jl/builds/543072251

**Comment by KristofferC** [comment]
I think what happens is that recursive dependencies gets put into the project file but those should only be put into the manifest file.

**Comment by fredrikekre** [comment]
Yea, I was trying to fix that, but I think the reason we add them to the project is that the resolver can only keep project-deps fixed on a version. I tried just pinning them in the manifest, but seems like it is beeing ignored.
