### ISSUE TITLE
dev . in nested directories

### ISSUE THREAD

**Issue by cossio** [JuliaLang/Pkg.jl#1160]
If you do `dev .` in a deeply nested directory containing a package, it adds the package with a path like `../../../../home/cossio/ ...`, that is, it traveses back up to the root directory and then goes back in. It would be nicer if it just computed a clean absolute path and used it.

**Comment by fredrikekre** [comment]
This is a feature, `.` is a relative path and we thus record the path relative the project.

**Comment by cossio** [comment]
I see. Is there a way to get an absolute path to the current directory (without having to type it) instead of a relative one (like `.`)?

**Comment by fredrikekre** [comment]
```
Pkg.develop(PackageSpec(path = pwd()))
```
