### ISSUE TITLE
Surprising loading of unsupported dependencies

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/Pkg.jl#1177]
@jagot first observed this. 

BlockBandedMatrices.jl v0.4.2 only supports BlockArrays.jl v0.8: 

https://github.com/JuliaMatrices/BlockBandedMatrices.jl/blob/33a2c2bf89bfb8134818c75d61c12d4ff277656b/Project.toml

as tagged in 

https://github.com/JuliaRegistries/General/pull/330

But for some reason BlockArrays.jl v0.9 is loaded: see, for example,

https://travis-ci.org/JuliaApproximation/ApproxFunSingularities.jl/jobs/525100380

**Comment by fredrikekre** [comment]
No bounds in the registry.

**Comment by dlfivefifty** [comment]
Sorry, can you explain? I put `BlockArrays = "0.8"` in the Project.toml, why aren't there bounds in the registry?

**Comment by fredrikekre** [comment]
Because Registrator doesn't honor that.

**Comment by dlfivefifty** [comment]
So how do you set upper bounds??

**Comment by KristofferC** [comment]
Registrator should not remove the upper bounds. I would consider that a bug in Registrator.

**Comment by fredrikekre** [comment]
> Registrator should not remove the upper bounds. I would consider that a bug in Registrator.

That is not what happened though, the normalization script automatically removes them and consider all 0.X to be compatible. IMO you did the right thing and had `BlockArrays = "0.8"` in the project file, but people got "upset" (https://discourse.julialang.org/t/dependency-problem-with-fillarrays/23238) and there was also some weird upper bounds left in there from the conversion script from general so all bounds where messy...

**Comment by KristofferC** [comment]
> That is not what happened though, the normalization script automatically removes them and consider all 0.X to be compatible.

From what I see, stuff like `0.8` now gets "normalized" to `0.8 - 0` or something.
