### ISSUE TITLE
excise `ext/*`

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/Pkg.jl#118]
It would be great if we could excise the copied dependencies in `ext/*`,
which is needed by https://github.com/JuliaLang/julia/pull/25714

Probably moving TOML to `JuliaLang` would be sensible and for the rest we should be able to use upstream.

**Comment by KristofferC** [comment]
We only need a little bit from BinaryProvider so that could probably be seen as an implementation detail. For TOML, we could make it an stdlib or keep it as `ext`.

**Comment by bicycle1885** [comment]
Just in case you're interested, I've written a TOML parser that is v0.4.0 compatible (as far as I'm aware of) this weekend. It is still in alpha quality, but may be useful for Pkg3.jl in the future. The code is here: https://github.com/bicycle1885/TOML.jl.

**Comment by StefanKarpinski** [comment]
I'd really like to have a TOML parser that let's me pull out specific values and generates a custom state machine that can scan through extracting those values at maximal speed. Essentially something that can _generate_ the kinds of methods I've written in `base/loading.jl` to do this with regular expressions:

https://github.com/JuliaLang/julia/blob/c4c93ea692e9972a97a3f7149d79c92ad5d8106d/base/loading.jl#L480-L510

That's a fairly involved project, however, but it would be generally useful.

**Comment by 00vareladavid** [comment]
Closing in favor of #1011
