### ISSUE TITLE
Pkg no longer removes unneeded packages from the Manifest file

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#1185]
https://discourse.julialang.org/t/travis-failure-when-testing-required-code-on-julia-v1-0/23986/6

**Comment by KristofferC** [comment]
This is only when using `resolve`.

**Comment by StefanKarpinski** [comment]
@00vareladavid or @carlobaldassi—either of you have any clue what might have cause this?

**Comment by KristofferC** [comment]
I'm pretty sure it has to do with some refactoring of printing the Manifest file.

Before we did some analysis and removed the packages that didn't have any dependee (recursively) in the Project file.
