### ISSUE TITLE
st Some* should return a list of packages starting with Some

### ISSUE THREAD

**Issue by cossio** [JuliaLang/Pkg.jl#1186]
It would be nice if typing `pkg> st Some*` returned the status of all packages with names starting with `Some`.

**Comment by KristofferC** [comment]
"All packages" where? Installed or in available registries?

**Comment by fredrikekre** [comment]
Since `st X` work on the current project I am assuming that this would be the same. However, then you might just do `st Some<TAB>` for the same effect.

**Comment by StefanKarpinski** [comment]
Since `st` only applies to packages in your project, presumably in the project file only.

**Comment by cossio** [comment]
> Since `st X` work on the current project I am assuming that this would be the same. However, then you might just do `st Some<TAB>` for the same effect.

`st Some<TAB>` only prints the package names, not the full status info line (version, path if dev, etc.).

**Comment by StefanKarpinski** [comment]
Another option would be to allow `| cmd` at the end of any `pkg>` mode command to pipe its output to that command and then do `pkg> st | grep ^Some`. Just thinking out loud about more general ways to do this kind of thing.

**Comment by fredrikekre** [comment]
I don't really see when you want to see the status for all packages starting with some letter combination, they are probably completely unrelated.

> st Some<TAB> only prints the package names, not the full status info line (version, path if dev, etc.).

What? That works:

```
(v1) pkg> st Example
    Status `~/.julia/environments/v1/Project.toml`
  [7876af07] Example v0.5.1
```

> Another option would be to allow | cmd at the end of any pkg> mode command to pipe its output to that command and then do pkg> st | grep ^Some.

With https://github.com/fredrikekre/jlpkg:
```
$ jlpkg st | grep Ex
  [7876af07] Example v0.5.1
```
:)

**Comment by cossio** [comment]
> What? That works:

I meant `pkg> st Some<TAB>`, that is, pressing TAB, not Enter. Since you said that this was equivalent, I was just point out that `pkg> st Some<TAB>` only prints the package names that start with `Some`, but doesn't list their status.

However my original intention in this issue is that `pkg> st Some*` could print the status of matching packages.

But this is a good point:

> I don't really see when you want to see the status for all packages starting with some letter combination, they are probably completely unrelated.

I just happened to have a bunch of packages with similar names because of a project I'm working on. But that maybe just my particular situation.

**Comment by fredrikekre** [comment]
> I just happen to have a bunch of packages with similar names now, related to a project.

Typically `status` is used to answering "What is the complete status of my project?" (`pkg> status`) or answering "What version of this specific package have I installed?" (`pkg> status Example`).

I just don't really see the usecase of `pkg> status Some*`. When do you ask yourself the question "What is the status of packages starting with `Some`?"?

**Comment by cossio** [comment]
When you are working in a project named `Some` and all your package names start with `Some...`. Ok, maybe is not that common.
