### ISSUE TITLE
gen_project.jl: stdlib packages can be specified redundantly in [extras]

### ISSUE THREAD

**Issue by garrison** [JuliaLang/Pkg.jl#1195]
Now that #1189 has been merged, when `gen_project.jl` is run, the uuids for stdlib packages will be given under `[extras]`, even if they are already listed under `[deps]`.  I believe this is redundant and therefore unintended (though it is rather benign).

For instance, for one project I tried it on, the script created a `Project.toml` that looks like (irrelevant portions truncated):

```
[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test"]
```

Note that this seems to occur *only* for stdlib packages, and not others.  In the example I used to generate the above code, both the source code and the tests actually depend on both `LinearAlgebra` and `StaticArrays`, but only `LinearAlgebra` is listed redundantly.

The below output would therefore seem to be sufficient:

```
[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
```

**Comment by 00vareladavid** [comment]
Seems harmless
