### ISSUE TITLE
Feature request: easy "throw away" environments

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaLang/Pkg.jl#1201]
Would it be nice if we had a `julia --project=@tmp` command (syntax TBD) for creating a "throw away" environment whcih exists only for the duration of the repl session?

E.g. operates in a `tmp` directory and automatically deletes `/Project.toml` and `/ Manifest.toml` afterwards; so `julia --project=@tmp` again gives a new "throw away" environment.

Use case:
- Not editing any specifc package, so don't want `julia --project=@.`,
- Want to test something out, e.g. try reproduce a bug report
- Load `julia` and inevitably end up adding packages, e.g. the bugged package, 
- Your "base" `v1.1` environment ends up having tons of packages <-- something we might wish to avoid.

**Comment by nickrobinson251** [comment]
workaround suggested by @fredrikekre on slack:
 `julia --project=(mktemp -d)` (fish) or
 `julia --project=$(mktemp -d)` (sh)

**Comment by KristofferC** [comment]
I don't really think there needs to be a command line option for this. It should be enough that Pkg has some easy way of activating the temp env.

**Comment by KristofferC** [comment]
Why close, would still be nice to have it available in Pkg?

**Comment by oxinabox** [comment]
I still want this very regularly.


At least 4 timed in the last 2 days.
