### ISSUE TITLE
Support relative paths for `dev` in Manifest

### ISSUE THREAD

**Issue by Datseris** [JuliaLang/Pkg.jl#1214]
It would be very advantageous to tell Manifest.toml to use a relative path instead of a global for some cases, specifically for cases where the path to the package is a direct sub-path of the path of the `Manifest` file.

For example, I have a strcture like:
```
Folder
- src/PackageA/src...
- Project.toml
- Manifest.toml
```
I `dev` packageA but manifest saves the absolute path instead of relative to `Folder`. When I send my project folder to a colleague he cannot use `PackageA` anymore.

related with #867

**Comment by fredrikekre** [comment]
If you dev a relative path it will store a relative path.

**Comment by Datseris** [comment]
Oooooooooooooops. I was not aware of that. Should I close this?

**Comment by Datseris** [comment]
Actually, I don't understand how to do this:
```
(MagneticBilliardsLyapunovs) pkg> dev "./src/InverseStadium"
   Cloning git-repo `./src/InverseStadium`
ERROR: failed to clone from ./src/InverseStadium, error: GitError(Code:ERROR, Class:Net, unsupported URL protocol)

(MagneticBilliardsLyapunovs) pkg> dev "src/InverseStadium"
   Cloning git-repo `src/InverseStadium`
ERROR: failed to clone from src/InverseStadium, error: GitError(Code:ERROR, Class:Net, unsupported URL protocol)
```

**Comment by fredrikekre** [comment]
Does `pwd()/src/InverseStadium` exist?

**Comment by Datseris** [comment]
Okay I fixed it. For it to work the Julia working directory has to also be the same as the manifest directory (which is why `pwd()` matters in your suggestion). I will update my PR #1215  accordingly, thanks!

**Comment by fredrikekre** [comment]
> For it to work the Julia working directory has to also be the same as the manifest directory

No, but the path you enter is treated relative `pwd`, just like any other path you use.

**Comment by jebej** [comment]
Would it be possible for the path to be relative to the location of the toml file? As-is I feel this makes it less useful than it could be.

Otherwise, is there a way on windows to make path relative to the user folder?

The use case is to use the same repo directory on multiple computers, with different absolute locations.

**Comment by jebej** [comment]
As far as I can tell, the path is relative to whatever `pwd()`, and not to the location of the toml file.
The PR merged says it's relative to the toml file, which is not the case.

**Comment by StefanKarpinski** [comment]
It absolutely should be relative to the TOML file, so if that's not the case, that's a bug.

**Comment by fredrikekre** [comment]
The stored path is relative to the toml file, but what path you enter is relative to pwd.

**Comment by jebej** [comment]
I opened #2291 with more details.

**Comment by jebej** [comment]
> The stored path is relative to the toml file, but what path you enter is relative to pwd, maybe that is what is confusing you?

No, please see the issue.
