### ISSUE TITLE
Race conditions

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/Pkg.jl#1219]
The race conditions with `precompile` (https://github.com/JuliaLang/julia/issues/17320) are a real pain when working with multiple processes. Other package operations (such as `build`) can also trigger race conditions, e.g. when working on a cluster with a shared file system.

Mutating global state is a difficult problem, so I'm not sure what the best solution is. One option is to do file locking at the depot level: this would require adding something like [Pidfile.jl](https://github.com/vtjnash/Pidfile.jl) as a stdlib (https://github.com/JuliaLang/julia/issues/7176).

**Comment by simonbyrne** [comment]
Another related issue to precompilation is https://github.com/JuliaLang/julia/pull/30174

**Comment by simonbyrne** [comment]
Precompile was fixed by #36416. `Pkg.build` still has race conditions, but is less of an issue now that fewer packages make use of it.

**Comment by IanButterworth** [comment]
This is fixed on master and due to be in v1.10
