### ISSUE TITLE
TOML: should handle keys that are `Symbol`

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaLang/Pkg.jl#1227]
I guess keys in TOML are kind of symbols anyway, since they don't have quotes.  It seems appropriate that TOML should support keys that are symbols as well as keys that are strings, and do whatever conversion automatically.  The uppermost missing method right now is `printkey(io, ::Vector{Symbol})`.

**Comment by KristofferC** [comment]
Internally the keys are strings though. Could discuss this more when TOML becomes a stdlib but for now, I think we keep it the way it is.
