### ISSUE TITLE
Test specific groups of tests

### ISSUE THREAD

**Issue by cossio** [JuliaLang/Pkg.jl#1241]
Can we have something like `pkg> test MyPkg tests_names`, where `tests_names` refers to, say, the name of a `testset`? Some packages have very long tests which can take a long time to complete. When you are making modifications to specific part of it, you only want to test the affected areas repeatedly and hopefully quickly, and then maybe do a full test at the end.

**Comment by StefanKarpinski** [comment]
Sure, I think that functionality needs to exist in the `Test` stdlib first, however. Once it does, we can expose it here.

**Comment by KristofferC** [comment]
I think what we will end up doing is https://github.com/JuliaLang/Pkg.jl/pull/1226 and then leave the rest to whatever test library people want to use.

**Comment by DilumAluthge** [comment]
Also, if you do use the `Test` stdlib, the post in https://github.com/JuliaLang/Pkg.jl/pull/1226 has some example code that you'll be able to use once the pull request is merged.
