### ISSUE TITLE
"Error:Invalid Token" when dev-ing specific branch from registered package

### ISSUE THREAD

**Issue by AriMKatz** [JuliaLang/Pkg.jl#1257]
Some of the various combination I've tried  (please excuse the DataFrames typos)
![image](https://user-images.githubusercontent.com/44276225/61565456-1dbf7f80-aa47-11e9-93af-2a9493c6b23b.png)

**Comment by fredrikekre** [comment]
`dev`ing specific git references is not allowed, so it is "correct", but could perhaps be a better error message.

**Comment by AriMKatz** [comment]
thanks

**Comment by KristofferC** [comment]
Can reopen to improve the error message.
