### ISSUE TITLE
No good syntax to exclude a version number

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/Pkg.jl#1258]
We wanted to exclude `0.8.6` of one of our dependencies, which broke us. There's no good syntax for this, so we had to write this:
```
Dep = "=0.8.0, =0.8.1, =0.8.2, =0.8.3, =0.8.4, =0.8.5"
```

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/Pkg.jl/issues/1089
