### ISSUE TITLE
Allow version conflicts when packages are checked out for dev

### ISSUE THREAD

**Issue by travigd** [JuliaLang/Pkg.jl#1260]
As in title.

For example, WebIO v0.8.6 doesn't work with the latest Blink, but I get errors trying to work with the latest Blink and WebIO (in order to make it work) because Blink has the dependency pinned at != 0.8.6.

Since I have both Blink and WebIO checked out for development, this should be a warning rather than an error (for now I just edited Blink's Project.toml to remove the WebIO compat line).

**Comment by DilumAluthge** [comment]
Could we preserve the current behavior by default, and make this an opt-in feature?

So `Pkg.develop(["Foo", "Bar"])` would throw an error if version conflicts were detected, but `Pkg.develop(["Foo", "Bar"]; allow_version_conflicts = true)` would give a warning instead of an error. And the default value would be `allow_version_conflicts = false`.

**Comment by travigd** [comment]
Either that (maybe with a shorter name like `force`) or issue a warning. I also think that `st` should show the conflicting packages in bright bold red to make sure that the issue is surfaced. :^)

**Comment by DilumAluthge** [comment]
I think that we should preserve the current behavior of throwing an error by default. I think that most people expect the package manager to resolve versions and throw an error if there is a conflict. Overriding that behavior should be an opt-in.

A keyword argument named `force` (with default value `force = false`) sounds good to me! Example usage:
- `Pkg.develop("Foo"; force = true)`
- `Pkg.develop(["Foo", "Bar"]; force = true)`
- `Pkg.develop(Pkg.PackageSpec(name="Foo"); force = true)`
- `Pkg.develop([Pkg.PackageSpec(name="Foo"), Pkg.PackageSpec(name="Bar")]; force = true)`
