### ISSUE TITLE
Changing mirror as build in function?

### ISSUE THREAD

**Issue by Losses** [JuliaLang/Pkg.jl#1271]
Accessing github is really painful in China because the reason everyone know, if the mirror could be changed as a build in function, life will be easier...

**Comment by KristofferC** [comment]
Yes, we are planning on adding functionality along these lines.

For now, one possible way to work around it could be to fork the registry (https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/309) and replace all URLs with the mirror and then use that registry. Not ideal, but might work in the short term.

**Comment by Losses** [comment]
@KristofferC Okay, thanks a lot :D~

**Comment by KristofferC** [comment]
This is implemented with the `PKG_SERVER` environment variable. It still need some docs though but I think this can be closed.
