### ISSUE TITLE
Untrack a Manifest

### ISSUE THREAD

**Issue by cossio** [JuliaLang/Pkg.jl#1276]
When you `] instantiate` a project, it automatically tracks the corresponding `Manifest.toml` file. This means that even if you no longer use that project, `] gc` will not clean up the packages it depended on.

On the slack it was suggested I could just delete the `Manifest.toml` file of the project. But this is not ideal because I might want to `] instantiate` this project again in the future. I could also rename it but that is hackish. I think there should be an official API to control which Manifests are being tracked and whose dependencies will be preserved by `] gc`.

**Comment by fredrikekre** [comment]
Duplicate of #621

**Comment by cossio** [comment]
Yes, that's what I mean. Thanks.
