### ISSUE TITLE
Why not julia_args::Cmd and test_args::Cmd?

### ISSUE THREAD

**Issue by tkf** [JuliaLang/Pkg.jl#1278]
Thanks to @DilumAluthge, as of #1226 we have

https://github.com/JuliaLang/Pkg.jl/blob/f75bed67ad869e408455fcedfe0ec7362059a7fa/src/API.jl#L231-L234

But why not use `julia_args::Cmd` and `test_args::Cmd`?  Isn't `Cmd` the best API for handling command line arguments?  That is to say, isn't

```julia
Pkg.test(julia_args=`--compiled-modules=no --compile=min`, test_args=`foo bar`)
```

better than

```julia
Pkg.test(julia_args=[`--compiled-modules=no`, `--compile=min`], test_args=["foo", "bar"])
```

?

Previous discussion: https://github.com/JuliaLang/Pkg.jl/pull/1226#discussion_r297584441

**Comment by KristofferC** [comment]
Seems reasonable to me.

**Comment by DilumAluthge** [comment]
Seems fine to me!
