### ISSUE TITLE
Missing tab completion

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/Pkg.jl#1289]
Tab completing `MLJ<tab>` in `pkg>` mode does not list `MLJModels`, even though it’s a registered package.

**Comment by KristofferC** [comment]
The reason is that MLJModels doesn't declare any compat with Julia and we interpret that erroneously to mean that there is no compatibility at all.

**Comment by dpsanders** [comment]
Cc @ablaom

**Comment by ablaom** [comment]
@dpsanders Thanks. Fixed on master.
