### ISSUE TITLE
`notarealprotocol` test unnecessarily slow

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/Pkg.jl#1291]
The `notarealprotocol` test causes `libgit2` to hang for about 60 seconds while running tests;  It would be great if we could set the timeout to something lower to speed the tests up a bit, but sadly it appears that `libgit2` does not expose that functionality, at least at the moment.  Is there some other way we can run this test without blocking the rest of the testing environment for a minute just waiting for a timeout to expire?

**Comment by 00vareladavid** [comment]
Is it blasphemous to suggest moving the test so that it is not run when `include("test/runtests.jl")`? It is really annoying when you have to run tests frequently. Also, the case it is testing is not really critical to the rest of the code.
