### ISSUE TITLE
support for artifact files

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/Pkg.jl#13]
See discussion here: https://github.com/StefanKarpinski/Pkg3.jl/issues/5. Want some way to provide the ability to download and use artifacts in projects without needing to check them into the project git repo. The concept is adding the concept of content-addressed artifacts to Pkg3, registering them, and then allowing projects to declare that they need them.

**Comment by staticfloat** [comment]
Looking back at this, I just have to chuckle a bit.  At least we're staying faithful to the early issues.

**Comment by KristofferC** [comment]
Artifacts merged.
