### ISSUE TITLE
Should we ever clean out the registry for pre 0.7 packages / versions?

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#1302]
Personally, I think a big sweep that removes all versions of packages in the registry that only support <= julia version 0.6 would be a good idea. Packages with no versions left would be completely removed. These versions cannot ever be installed, they make the resolver slower, they make resolver error messages more verbose etc etc.

The only argument people might have is that they feel they have "dibs" on a package name they like and that want to keep that, but haven't updated their package to 0.7. However, there has been a long enough time that I think we can let those names go without a bad conscience.

**Comment by StefanKarpinski** [comment]
Package name collisions are also allowed now, so they don't have dibs in any sense.

**Comment by KristofferC** [comment]
We haven't really decided on that exact policy for General itself, but sure.

**Comment by fredrikekre** [comment]
From triage:

> Cleaning out GeneralRemove any versions that aren’t compatible with Julia 1.0+
> Remove any versions that aren’t installable
> - package deleted
> - version no longer on a branch/tag
> - no compatible version set of dependencies exists
> Remove packages with no remaining versions (edited)

**Comment by KristofferC** [comment]
For step 1:

> Remove any versions that aren’t compatible with Julia 1.0+

I have a script here: 
https://gist.github.com/KristofferC/e6d9bbed08f689705f73cbcb0f672866

with the resulting diff: https://github.com/JuliaRegistries/General/commit/38b95911f36f32d26a89840b225e64353fdbcf70

**Comment by KristofferC** [comment]
The process for this has started.

**Comment by KristofferC** [comment]
Done, 100k lines deleted from the registry.
