### ISSUE TITLE
More structured/faster tests

### ISSUE THREAD

**Issue by 00vareladavid** [JuliaLang/Pkg.jl#1305]
This seems to be annoying everyone.

- First, how do people feel about modifying existing tests? I tend to just pile on the tests. I'm afraid of breaking any existing tests :grimacing: 
- Is there really that much of an expected difference between Linux and Mac/Windows? Or are we hitting some bad case regarding the latter? Was there a point where was not such a huge difference?
- test "Isolation". Perhaps they way we are `temp_pkg_dir` is wasteful? I definitely feel like I abuse it at points. Is some part of creating temp directories expensive on Windows?
- redundancy in what is being tested
- separation between network facing and internal operations. More structured tests would mean we can be more deliberate in choosing when we hit the network.

I'm just spitballing here. Any advice/concerns? Would it be a good idea to restructure tests? Any ideas about what is causing Windows to be so slow? I'm willing to put in some elbow grease to push this forward

**Comment by KristofferC** [comment]
It would be good if we could get an overview of what is actually taking time.

**Comment by 00vareladavid** [comment]
K, I guess a Windows virtualbox + something like https://github.com/vchuravy/PProf.jl is a good start?

**Comment by KristofferC** [comment]
Using Julias built-in profiler will not work so well, it gives too "fine-grained" results. My guess is that trying to update the registry over and over takes quite a lot of time.

We could turn that off when testing because we are getting a fresh clone in the start.
We could also try using the Windows bots on Travis, maybe they are faster than AV.

**Comment by 00vareladavid** [comment]
Ok, I finally got around to poking around Windows. And holy crap! :grimacing: updating the registry takes an obscene amount of time.

I noticed the 'Antimalware Service' spike at the same time. Could that be the cause of the slowdown?

**Comment by StefanKarpinski** [comment]
We've seen evidence elsewhere of AV and other security systems not liking git. Maybe we should default to just downloading a complete compressed copy of the registry? Compressed it's about 1.2MB which is not that large these days.

**Comment by KristofferC** [comment]
I'm also fine to just redo the tests from scratch, going feature by feature and making sure that coverage looks good. It is a bit scary but if we identify the purpose of every test and structure things a bit better, it's probably beneficial in the long run.

**Comment by KristofferC** [comment]
The first step would probably be to structure up the existing tests a bit.

**Comment by 00vareladavid** [comment]
> We could also set things up so the tests could be run in parallel. Assuming we get more than one core per worker on AV, perhaps that could speed things up.

Even if it just speeds things up locally, it would make developing `Pkg` much more pleasant.
