### ISSUE TITLE
chmod bug

### ISSUE THREAD

**Issue by ppalmes** [JuliaLang/Pkg.jl#1313]
to replicate:
1. remove or  mv ~/.julia to start from zero packages
2. run julia and update to initialize .julia
3. ]add TSML breaks with *chmod error* but ]add TSML#v2.3.7 works
Note: both points to the latest version which should be exactly the same.
4. also, ]add TSML again works after the chmod error

Note: I used Reexport recently. Is it possible it has something to do with the macro?

errors:
-----------
ERROR: Error when installing package TSML:
IOError: chmod: no such file or directory (ENOENT)
Stacktrace:
 [1] uv_error at ./libuv.jl:85 [inlined]
 [2] #chmod#16(::Bool, ::Function, ::String, ::UInt64) at ./file.jl:834
 [3] chmod at ./file.jl:833 [inlined]
 [4] set_readonly(::String) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:70
 [5] macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:598 [inlined]
 [6] (::getfield(Pkg.Operations, Symbol("##26#29")){Symbol,Pkg.Types.Context,Dict{Base.UUID,Base.SHA1},Dict{Base.UUID,Array{String,1}}})() at ./task.jl:259

**Comment by fredrikekre** [comment]
The fact that it does not error on both is that we fail to `chmod` when adding from a branch, see https://github.com/JuliaLang/Pkg.jl/issues/729.

So the problem here is why we try to chmod something that does not exist (?).

**Comment by ppalmes** [comment]
can we disable the chmod? chmod is not called when you do ]add Package#version but is called when you do ]add Package

**Comment by fredrikekre** [comment]
No, it should be called on both, we want the files to be read only.

**Comment by ppalmes** [comment]
I'm not sure why other julia packages can be installed but my TSML recently has this issue. I just refactored it to Reexport some packages to the Main module including DataFrames, Dates, Random, etc. It's hard to check for the bug because I have to register it again if I want to find out which commands in my code causes it. I do the dynamic addition of some files during testing and remove them. Is this related to this while other packages in Julia doesnt create files on the fly during testing?

**Comment by ppalmes** [comment]
is it possible it is due to the paper subdirectory which i added for the juliacon proceedings? maybe the latex files and other related docs mess the install process and causes the bug?
