### ISSUE TITLE
The Pkg precompile script does a clone of the default registry

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#1320]
This can take a while making Julia slower than necessary to build. At the same time, we do want to precompile these paths since they are important for the latency of Pkg. Ideally, there would be some static, mini registry, that could be used.

Also, it is not ideal that we will precompile less in places that have no internet access. We should probably have a mini local registry, and a mini local package that we bundle with Pkg and use that in the precompilation script.

**Comment by vtjnash** [comment]
It's funny the code here says "doesn't require internet access"
```
#### inputting statement: ####
"Pkg.add(\"Test\") # adding an stdlib doesn't require internet access"
####
julia> Pkg.add("Test") # adding an stdlib doesn't require internet access
   Cloning default registries into `/tmp/jl_qWv33P`
   Cloning registry from "https://github.com/JuliaRegistries/General.git"
    Fetching: [==>                                      ]  2.7 %
```

**Comment by KristofferC** [comment]
Yes, because the logic for when the default registry is cloned changed.

**Comment by vtjnash** [comment]
So, can we fix this? I'm wondering if this is contributing towards our infrequent issues with the FreeBSD bot getting stuck here (e.g. https://build.julialang.org/#/builders/26/builds/8291/steps/7/logs/stdio)
