### ISSUE TITLE
Always respect compat entries

### ISSUE THREAD

**Issue by rofinn** [JuliaLang/Pkg.jl#1352]
Currently, compat entries are ignored unless they're in `[deps]` or `[extras]`, however, sometimes we need to restrict a specific package version because the rest of the package ecosystem hasn't been updated.

# Example

```
name = "MyPkg"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsUtils = "d94fc345-0ff4-56ba-a2b2-f5d62e4638cc"

[compat]
CSV = ">= 0.5"
CategoricalArrays = "0.5"
DataFrames = "0.17, 0.18, 0.19"
StatsUtils = "1"
julia = "1"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV", "Random", "SHA", "StatsBase", "Test"]
```

In the above case, we needed to add CategoricalArrays.jl as a direct dependency in order to restrict it to version 0.5. CSV hadn't been updated to include that release version yet and since CSV is only installed/resolved at test time the CSV >=0.5 constraint will just error because CategoricalArrays 0.6 is already installed. It'd be nice if we could just add the `CategoricalArrays` constraint without adding it as a direct dependency (e.g., the constraint is only ignored if the package is never installed).

**Comment by KristofferC** [comment]
With https://github.com/JuliaLang/Pkg.jl/pull/1330, CategoricalArrays would get downgraded.

**Comment by KristofferC** [comment]
I think #1330 closes this.

**Comment by rofinn** [comment]
Doesn't #1330 mean that you'd be testing on different package versions than your package would otherwise be operating under? I guess the correct answer is to go fix the upstream packages to work properly?

**Comment by KristofferC** [comment]
It will not operate outside your compat entries.
