### ISSUE TITLE
What is the purpose of `rm --manifest`?

### ISSUE THREAD

**Issue by 00vareladavid** [JuliaLang/Pkg.jl#1359]
We have API support for this, but I'm struggling to find a reason why this would be needed

**Comment by KristofferC** [comment]
I use it when I try to add package `B` it is incompatible with something in the manifest (`C`) and I really want to use `B` so I want to nuke everything with `C` so I do `rm --m C; add B`.

**Comment by 00vareladavid** [comment]
gotcha, does seems useful
