### ISSUE TITLE
Julia 1.2-rc2 creates but doesn't remove folders in /tmp

### ISSUE THREAD

**Issue by lbilli** [JuliaLang/Pkg.jl#1396]
When adding or updating **local** projects in Julia v1.2-rc2, _i.e._
```julia
] add /home/user/somefolder/JuliaProject.jl
```
folders like:
```julia
/tmp/jl_2hWN1V
/tmp/jl_J8emmU
...
```
are created and never deleted. Those folders contains copies of the local projects themselves.
This doesn't happen in Julia v1.1.

**Comment by StefanKarpinski** [comment]
Given that 1.2 is no longer maintained and this doesn't happen on 1.1 or 1.3, I think this can be closed.
