### ISSUE TITLE
Create `test/runtests.jl` on running `Pkg.generate("Package")`

### ISSUE THREAD

**Issue by kdheepak** [JuliaLang/Pkg.jl#1425]
Should Pkg.jl create a `test` folder with a `runtests.jl` file? Running the following:

```bash
$ julia -e "using Pkg; Pkg.generate(\"Package\")"
```

could create:

```
.
├── Project.toml
├── src
│  └── Package.jl
└── test
   └── runtests.jl
```

where `runtests.jl` is simply 

```julia
using Package
```

This would allow users to generate a package with the minimal set up for testing. 

___

I'm also of the opinion that we can go further. We could have `src/Package.jl` as the following:

```julia
module Package

greet() = greet(stdout)
greet(io) = print(io, "Hello World!")

end # module
```

with `test/runtests.jl` as the following:

```julia
using Test

using Package

@testset "test greet" begin

    iob = IOBuffer()
    Package.greet(iob)
    @test String(take!(iob)) == "Hello World!"

end

end
```

with `Project.toml` being:

```
name = "Package"
uuid = "62c4e2f8-7435-4113-a541-48e9cda26fdb"
authors = ["John Doe <me@johndoe.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
```

Additionally, I think we should also create a `README.md` with the following contents:

````
# Package.jl

## Usage

Import the package:

```julia
using Package
```

## Development

Run tests:

```bash
julia -e "using Pkg; Pkg.test()"
```

````

Thoughts?

**Comment by DilumAluthge** [comment]
This was previously considered in https://github.com/JuliaLang/Pkg.jl/pull/1213

The consensus from triage was to leave `generate` the way it is, and direct users to PkgTemplates.

A note about PkgTemplates was added to the documentation in https://github.com/JuliaLang/Pkg.jl/pull/1360
