### ISSUE TITLE
[feature request] more verbose mode for updating

### ISSUE THREAD

**Issue by daviehh** [JuliaLang/Pkg.jl#1426]
A more verbose output switch for the update command may be beneficial, especially to find out which package may be preventing others from updating to the newest version. Or, printout a warning by default when such package exists.

**Comment by KristofferC** [comment]
Suggested features is a dup of https://github.com/JuliaLang/Pkg.jl/issues/1774.

**Comment by KristofferC** [comment]
Meant https://github.com/JuliaLang/Pkg.jl/issues/1655
