### ISSUE TITLE
Incorrect reading of compat bounds when the same version is found multiple times

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg.jl#1434]
```
$ cat Project.toml 
[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"

$ pkg instantiate
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `/tmp/tmp.DbIs12c3Sk/Project.toml`
  [35a29f4d] + DocumenterTools v0.1.2
  Updating `/tmp/tmp.DbIs12c3Sk/Manifest.toml`
  [ffbed154] + DocStringExtensions v0.7.0                <-- What?
  [35a29f4d] + DocumenterTools v0.1.2
[...]
```
which is weird, because [`DocumenterTools@0.1.2` declares that it is compatible with `DocStringExtensions@0.8`](https://github.com/JuliaRegistries/General/blob/0a75c48ef01672cb1cc3405b2b95ba9f93f4a87e/D/DocumenterTools/Compat.toml#L10)
```
$ pkg add DocStringExtensions@0.8
 Resolving package versions...
ResolverError: Unsatisfiable requirements detected for package DocStringExtensions [ffbed154]:
 DocStringExtensions [ffbed154] log:
 ├─possible versions are: [0.1.0, 0.2.0-0.2.1, 0.3.0-0.3.4, 0.4.0-0.4.6, 0.5.0, 0.6.0, 0.7.0, 0.8.0-0.8.1] or uninstalled
 ├─restricted to versions 0.8 by an explicit requirement, leaving only versions 0.8.0-0.8.1
 └─restricted by compatibility requirements with DocumenterTools [35a29f4d] to versions: 0.7.0 — no versions left
   └─DocumenterTools [35a29f4d] log:
     ├─possible versions are: 0.1.0-0.1.2 or uninstalled
     └─restricted to versions 0.1.2 by an explicit requirement, leaving only versions 0.1.2
```

Works on Julia master though, but maybe takes another code path in the tiered resolver and there is something wrong with the first one still?

```
$ pkg --julia=julia-master add DocStringExtensions@0.8
 Resolving package versions...
  Updating `/tmp/tmp.DbIs12c3Sk/Project.toml`
  [ffbed154] + DocStringExtensions v0.8.1
  Updating `/tmp/tmp.DbIs12c3Sk/Manifest.toml`
  [ffbed154] ↑ DocStringExtensions v0.7.0 ⇒ v0.8.1
  [8f399da3] + Libdl
```

**Comment by KristofferC** [comment]
Can't repro.

**Comment by fredrikekre** [comment]
Okay, I can only repro on 1 of 4 computers. What could cause this? I verified that the registry is up to date.

**Comment by fredrikekre** [comment]
Doesn't happen with official binaries...

**Comment by fredrikekre** [comment]
Okay, I happened to have an outdated registry in `DEPOT_PATH[2]`... I guess there must have been a mismatch between compat/versions in them.

**Comment by fredrikekre** [comment]
Turns out the compat bounds was overwritten by the second registry due to how we do the compression(ish). Basically we need something like https://github.com/JuliaLang/Pkg.jl/pull/887 or a version thereof.

**Comment by fredrikekre** [comment]
Reproducer:
```sh
$ depot1=$(mktemp -d) && depot2=$(mktemp -d) &&
  export JULIA_DEPOT_PATH=$depot1:$depot2 &&
  git -C $depot1 clone --branch=fe/depot1 https://github.com/JuliaRegistries/General.git registries/General &&
  git -C $depot2 clone --branch=fe/depot2 https://github.com/JuliaRegistries/General.git registries/General &&
  jlpkg --project=$(mktemp -d) add DocumenterTools
```

**Comment by fredrikekre** [comment]
Basically; this compat for version `0.1.2` of `DocumenterTools` https://github.com/JuliaRegistries/General/blob/2b8684b9b7b68790eb8830bf4a68c303df6039a2/D/DocumenterTools/Compat.toml#L6 in the first depot is overwritten by this compat: https://github.com/JuliaRegistries/General/blob/308f67fae04b66b55b9f8a0e18890a952c4d561e/D/DocumenterTools/Compat.toml#L2 in the second depot.

I think this is what we should do:
 - When version `X` is found we need to read compat and deps for that version *from the same registry*.
 - If we encounter version `X` again, in a different registry, or different depot; ignore it completely.

I guess the problem is in what order we should read the registries. It seems obvious to prioritize based on the `DEPOT_PATH`, but what if `X` is found in two registries in the same `DEPOT_PATH` entry?
