### ISSUE TITLE
no tilde expansion leads to confusing behaviour 

### ISSUE THREAD

**Issue by dahtah** [JuliaLang/Pkg.jl#1435]
It seems that Pkg.jl does not perform tilde expansion, which leads it to interpret absolute paths as relative paths, and to confusing behaviour:
```
(v1.2) pkg> generate ~/tmp/TestPackage
Generating project TestPackage:
    ~/tmp/TestPackage/Project.toml
    ~/tmp/TestPackage/src/TestPackage.jl
```
Here nothing is created at the stated location, but rather at ~/.julia/config/. Maybe issue a warning, since as far as I understand JuliaLang/julia#1136 there seems to be problems with supporting tilde expansion.

**Comment by StefanKarpinski** [comment]
I thought we changed things to do user expansion everywhere? cc @00vareladavid

**Comment by KristofferC** [comment]
It seems to not happen for `generate` but only when parsing something as a "package" (package url, package path):

https://github.com/JuliaLang/Pkg.jl/blob/a3349fb54a0e4592f75fc2aac9d3cd6d0090e509/src/REPLMode/argument_parsers.jl#L80

**Comment by StefanKarpinski** [comment]
Ah, ok. We should do it for generate too then.

**Comment by fredrikekre** [comment]
Isn't generate supposed to take just a package name?

**Comment by StefanKarpinski** [comment]
It could take a path and derive the package name from the last part of the path. Either that or it should throw an error if the package name contains weird characters.

**Comment by KristofferC** [comment]
Oh yeah, that's the way it works. Straightforward fix is to verify the package name.

**Comment by StefanKarpinski** [comment]
The simple check is `Base.isidentifier(name)`.
