### ISSUE TITLE
ERROR: LoadError: ArgumentError: Package Pkg not found in current path

### ISSUE THREAD

**Issue by kdheepak** [JuliaLang/Pkg.jl#1443]
I added the following line to `deps/build.jl`.

```
# deps/build.jl

using Pkg.Artifacts

```

When I open the `Pkg` REPL and type `build`, I get the following error:

```
(Package) pkg> build
  Building Package → `~/gitrepos/Package.jl/deps/build.log`
 Resolving package versions...
[ Info: No changes
┌ Error: Error building `Package`:
│ ERROR: LoadError: ArgumentError: Package Pkg not found in current path:
│ - Run `import Pkg; Pkg.add("Pkg")` to install the Pkg package.
│
│ Stacktrace:
│  [1] require(::Module, ::Symbol) at ./loading.jl:887
│  [2] include at ./boot.jl:328 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1105
│  [4] include(::Module, ::String) at ./Base.jl:31
│  [5] include(::String) at ./client.jl:432
│  [6] top-level scope at none:5
│ in expression starting at /Users/USER/GitRepos/Package.jl/deps/build.jl:1
└ @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Pkg/src/backwards_compatible_isolation.jl:649

(Package) pkg>
```

I'm using Julia 1.3.0-rc3.0

```
julia> versioninfo()
Julia Version 1.3.0-rc3.0
Commit b5ccd0f2ef (2019-10-04 01:57 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, ivybridge)

julia>
```

**Comment by fredrikekre** [comment]
Well, did you add Pkg as a dependency?

**Comment by kdheepak** [comment]
Well, you are right. I thought I did but I must have add a stale REPL open. Sorry for the noise.

**Comment by mechanicalcodingfreak** [comment]
Hello
I am running Julia 1.4.0 in a Jupyter notebook and I wanted to have PyPlot installed to use the legends feature. Despite including the Pkg dependency
`ENV["PYTHON"]=""
import Pkg; Pkg.add("Pkg")
Pkg.build("PyCall")
using PyCall
using PyPlot 
Pkg.add("Plots")` 
 I get the following error repeatedly:
`Resolving package versions...
   Updating `C:\Users\SURYA\.juliapro\JuliaPro_v1.4.0-1\environments\v1.4\Project.toml`
 [no changes]
   Updating `C:\Users\SURYA\.juliapro\JuliaPro_v1.4.0-1\environments\v1.4\Manifest.toml`
 [no changes]
   Building Conda ─→ `C:\Users\SURYA\.juliapro\JuliaPro_v1.4.0-1\packages\Conda\3rPhK\deps\build.log`
┌ Error: Error building `Conda`: 
│ ERROR: LoadError: ArgumentError: Package Pkg not found in current path:
│ - Run `import Pkg; Pkg.add("Pkg")` to install the Pkg package.
│ 
│ Stacktrace:
│  [1] require(::Module, ::Symbol) at .\loading.jl:892
│  [2] include(::Module, ::String) at .\Base.jl:377
│  [3] load_julia_startup() at .\client.jl:316
│  [4] exec_options(::Base.JLOptions) at .\client.jl:259
│  [5] _start() at .\client.jl:484
│ in expression starting at C:\Users\SURYA\AppData\Local\JuliaPro-1.4.0-1\Julia-1.4.0\etc\julia\startup.jl:5
└ @ Pkg.Operations C:\Users\julia\AppData\Local\Julia-1.4.0\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:892
   Building PyCall → `C:\Users\SURYA\.juliapro\JuliaPro_v1.4.0-1\packages\PyCall\zqDXB\deps\build.log`
┌ Error: Error building `PyCall`: 
│ ERROR: LoadError: ArgumentError: Package Pkg not found in current path:
│ - Run `import Pkg; Pkg.add("Pkg")` to install the Pkg package.
│ 
│ Stacktrace:
│  [1] require(::Module, ::Symbol) at .\loading.jl:892
│  [2] include(::Module, ::String) at .\Base.jl:377
│  [3] load_julia_startup() at .\client.jl:316
│  [4] exec_options(::Base.JLOptions) at .\client.jl:259
│  [5] _start() at .\client.jl:484
│ in expression starting at C:\Users\SURYA\AppData\Local\JuliaPro-1.4.0-1\Julia-1.4.0\etc\julia\startup.jl:5
└ @ Pkg.Operations C:\Users\julia\AppData\Local\Julia-1.4.0\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:892
┌ Info: Precompiling PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0]
└ @ Base loading.jl:1260
ERROR: LoadError: LoadError: PyCall not properly installed. Please run Pkg.build("PyCall")
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at C:\Users\SURYA\.juliapro\JuliaPro_v1.4.0-1\packages\PyCall\zqDXB\src\startup.jl:44
 [3] include(::Module, ::String) at .\Base.jl:377
 [4] include(::String) at C:\Users\SURYA\.juliapro\JuliaPro_v1.4.0-1\packages\PyCall\zqDXB\src\PyCall.jl:1
 [5] top-level scope at C:\Users\SURYA\.juliapro\JuliaPro_v1.4.0-1\packages\PyCall\zqDXB\src\PyCall.jl:34
 [6] include(::Module, ::String) at .\Base.jl:377
 [7] top-level scope at none:2
 [8] eval at .\boot.jl:331 [inlined]
 [9] eval(::Expr) at .\client.jl:449
 [10] top-level scope at .\none:3
in expression starting at C:\Users\SURYA\.juliapro\JuliaPro_v1.4.0-1\packages\PyCall\zqDXB\src\startup.jl:41
in expression starting at C:\Users\SURYA\.juliapro\JuliaPro_v1.4.0-1\packages\PyCall\zqDXB\src\PyCall.jl:34
Failed to precompile PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0] to C:\Users\SURYA\.juliapro\JuliaPro_v1.4.0-1\compiled\v1.4\PyCall\GkzkC_5zzd4.ji.

Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272
 [3] _require(::Base.PkgId) at .\loading.jl:1029
 [4] require(::Base.PkgId) at .\loading.jl:927
 [5] require(::Module, ::Symbol) at .\loading.jl:922
 [6] top-level scope at In[120]:4`

**Comment by StefanKarpinski** [comment]
Seems like an unrelated problem, @mechanicalcodingfreak?

**Comment by KristofferC** [comment]
Seems like the startup file in JuliaPro is using Pkg and that gets loaded when the build step runs. This should only happen if one starts julia with `startup=yes` explicitly. Does JuliaPro do that?
