### ISSUE TITLE
move to a decoupled caching model

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/Pkg.jl#1449]
Passing various kinds of cache objects around seems to account for a large fraction of the complexity in Pkg. There's also, I think we've all seen, little reason for caches to be specific to each operation: it would be even better if they persisted across operations. To that end, I'd like to propose a different approach where we maintain an implicit global cache instead:

* Key global caches by path name at the parse step, e.g. `read_registry`
* Either use inotify to invalidate when a path changes or use an `mtime` comparison
* May want to use `crc32c` to double-check false positive changes, not sure if worth it

**Comment by KristofferC** [comment]
I think this is done now. There is a cache for any parsed TOML file read that uses `mtime` etc and the registry is cached via the tree hash given by the Pkg server and it is persistent across operations.
