### ISSUE TITLE
File permissions on compiled .ji code within a shared depot

### ISSUE THREAD

**Issue by rsrock** [JuliaLang/Pkg.jl#1450]
This is a continuation of JuliaLang/Julia#12876.  

I am setting up a shared Julia depot for a lab computer. To do this, from an account that owns the julia directories, I'm running `popfirst!(DEPOT_PATH)`, and then `]add foo bar baz...` to my heart's content.  These packages end up in `/usr/local/julia-1.2.0/local/share/julia`.  I also `export JULIA_LOAD_PATH=@:@v#.#:@stdlib:/usr/local/julia-1.2.0/local/share/julia/environments/v1.2` in all user shells, to be able to reach that location. So far, so good.

But then, I'm running into the exact permission problem noted here:
https://github.com/JuliaLang/julia/issues/12876#issuecomment-136157275.  The precompiled files block other users from loading the shared libraries.

My extreme solution is to nuke them: `rm -rf /usr/local/julia-1.2.0/local/share/julia/compiled`. That seems to work (compiled files then end up in `~/.julia`), but I will have to do that routinely when adding or updating packages system-wide.  Is there a better way?

Opening permissions on the shared depot `compiled` folder may not be the best idea, as noted here https://github.com/JuliaLang/julia/issues/12876#issuecomment-234823443

**Comment by KristofferC** [comment]
Pkg.jl doesn't actually do anything with precompilation, that is totally a part of the Julia loading system. The reason I write this is because there isn't really much we can do from here.

**Comment by StefanKarpinski** [comment]
Closing in favor of reopening the original issue.
