### ISSUE TITLE
Suggestion: Not activate (and print info) if the project-to-be activated is the one already active

### ISSUE THREAD

**Issue by Datseris** [JuliaLang/Pkg.jl#1452]
Hello,

Just a suggestion. At the moment upon doing `activate thing` you get a message along the lines:
```
Activating environment at `C:\Users\datseris\ownCloud\MyScience\Projects\TimeseriesPrediction - Jonas Isensee\embeddingresearch-george\Project.toml`
```
This happens even if the active directory is the one to be activated.

I was wondering if there is a way to avoid doing this in the case where the directory to be activated is the one already active. If it is possible please let me know, I'd like to implement it in [DrWatson](https://github.com/JuliaDynamics/DrWatson.jl). Of course, if you think it is of general use, we could add it here instead.

**Comment by fredrikekre** [comment]
Why is it problematic?

**Comment by Datseris** [comment]
Problematic is too strong of a word. There is no problem here for sure.

I opened this because I don't want to populate my console with information that is not important.

**Comment by fredrikekre** [comment]
If you do `activate thing`, don't you want a confirmation that you indeed activated `thing`?

**Comment by Datseris** [comment]
Yes of course, in general. For me personally, I would not want this information if the `thing` is what is already active. But this is clearly a matter of taste.

In any case, what I am asking if it is _possible_ to do this, not necessarily if you should do it in Pkg.jl. I can still do it on my end and everyone remains happy. Right?

**Comment by Datseris** [comment]
I have decided to do this on my end, I can't handle being spammed this message every time I run something.

@fredrikekre could you please answer the following question:
* Is there any benefit whatsoever in re-activating the already active project? Does julia do something internally extra? Because to me it seems there isn't any benefit and I want to stop it being possible on my end.

**Comment by fredrikekre** [comment]
> Is there any benefit whatsoever in re-activating the already active project?

No, but I don't think we should change the default behaviour.

> I can't handle being spammed this message every time I run something.

Maybe just call activate like this then:
```
with_logger(Logging.NullLogger()) do
    Pkg.activate(...)
end
```

**Comment by Datseris** [comment]
> No, but I don't think we should change the default behaviour.

Yes, sure, no problem here. I'll do it on my end. Thanks for the suggestion!
