### ISSUE TITLE
Possible mistake in [[compat]] docs

### ISSUE THREAD

**Issue by dehann** [JuliaLang/Pkg.jl#1454]
With the [recent zeptodoctor auto-merging, I was forced back](https://github.com/JuliaRegistries/General/pull/4440#issuecomment-542928302) to the Pkg.jl docs and found this part to be confusing:
>  ```
>  [compat]
>  Example = "1.2, 2"
>  ```
>  will result in [1.2.0, 3.0.0).

Since I get error messages locally that would suggest the actual behavior is in fact (not as advertised):
```
Example = [1.2.0-1.3.0, 2.0.0-3.0.0]
```
but not any of the versions including `1.3.1, 1.4, 1.5, ...`.

EDIT:  Perhaps its specific to the leading zero case -- i.e. `ExampleB = 0.2, 1`

It might be a bug or documentation error, but after some trail and error I have been forced to do this (and is really the only way I could get broad version apertures):
https://github.com/JuliaRobotics/IncrementalInference.jl/pull/414/files#diff-910a7b3ca0075d545dcec45cb7335ca9R47

Part of the problem might be that the following case is not documented either:
```
Example = "^0.1" == "0.1.0-0.2.0"
```

My current understanding is that there is no way to define a compatibility which stretches from 
`0.x through 1.0 or 1.x` 
or is there and I'm just not finding it?

#### Reference

In the docs just above this:
https://julialang.github.io/Pkg.jl/v1/compatibility/index.html#Caret-specifiers-1

- I'm on Julia 1.2

**Comment by DilumAluthge** [comment]
Your issue here is specific to the leading zero case.

**Comment by DilumAluthge** [comment]
What compat range are you trying to use?

**Comment by DilumAluthge** [comment]
I suspect that https://github.com/JuliaLang/Pkg.jl/pull/1410 will meet your needs. But that PR is not ready yet.

**Comment by DilumAluthge** [comment]
If you need to document `0.x` through `1.x`, you’ll need to list out all of the breaking versions, for example `0.5, 0.6, 0.7, 0.8, 1.0, 1.1, 1.2, 1.3`

**Comment by DilumAluthge** [comment]
But ask yourself: do I really need to maintain compatibility with all of those different versions. Can’t I just drop compat for the `0.x` versions and use a nice simple compat entry such as `^1.0.0`?

**Comment by DilumAluthge** [comment]
`^1.0.0` means that you are compatible with `1.0`, `1.1`, `1.2`, `1.3`, and so on. But you are not compatible with `2.0`.

**Comment by dehann** [comment]
Out of roughly 100 package dependencies, most of them are still in the v0.x range, and all moving along day by day.  That means I need to write long lists of dependencies which randomly need to be updated.  I still think there should probably be an option for easily scoping `[0.x, 1.0]`.  But also, the current docs a somewhat misleading regarding a leading zero or not.

**Comment by DilumAluthge** [comment]
> I still think there should probably be an option for easily scoping `[0.x, 1.0]`.

https://github.com/JuliaLang/Pkg.jl/pull/1410

**Comment by dehann** [comment]
oh great, thanks!  That's much simpler to work with!
