### ISSUE TITLE
dev doesn't allways get the latest version of a package

### ISSUE THREAD

**Issue by rafaqz** [JuliaLang/Pkg.jl#1460]
Sometimes `dev https://github.com/someone/SomePackage.jl` gives you an old version of a package from the clones folder without pulling the latest changes. It doesn't error or tell you it has done this. 

The solution is to just delete the `clones` folder and the current `dev/SomePackage` folder and start again, which is very clunky.

**Comment by fredrikekre** [comment]
Duplicate of #465
