### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by yakir12** [JuliaLang/Pkg.jl#1490]
The link to the `gen_project.jl` script is broken in the docs:
https://julialang.github.io/Pkg.jl/v1/creating-packages/#**5.**-Creating-Packages-1
but not in the github version:
https://github.com/JuliaLang/Pkg.jl/blob/master/docs/src/creating-packages.md#5-creating-packages

Could be becuase they point to different places:
in docs: https://github.com/JuliaLang/Pkg.jl/blob/master/bin/gen_project.jl
in github: https://github.com/JuliaLang/Pkg.jl/blob/934f8b71eb436da6d2bdb30ccfc80e5e11891c5b/bin/gen_project.jl

The former does not exist.

**Comment by DilumAluthge** [comment]
The links have been fixed in master: https://julialang.github.io/Pkg.jl/dev/creating-packages/
