### ISSUE TITLE
Yanking all versions of a package breaks Pkg.resolve

### ISSUE THREAD

**Issue by tkf** [JuliaLang/Pkg.jl#1491]
Quoting a reproducer https://github.com/JuliaRegistries/General/pull/5000#issuecomment-551321806:

> So it seems that this breaks `resolve` (which I expected to work):
> 
> ```console
> $ cd $(mktemp -d)
> ...
> 
> $ jlpkg --project=. add ProgressMeterLogging
> ...
> 
> $ cd ~/.julia/registries/General
> ...
> 
> $ git checkout tkf/patch-1
> ...
> 
> $ cd -
> ...
> 
> $ jlpkg --project=. resolve
>  Resolving package versions...
> ResolverError: Unsatisfiable requirements detected for package ProgressMeterLogging [b0e84e9e]:
>  ProgressMeterLogging [b0e84e9e] log:
>  ├─ProgressMeterLogging [b0e84e9e] has no known versions!
>  └─restricted to versions 0.1.0 by an explicit requirement — no versions left
> ```
> 
> Instantiation works, though:
> 
> ```console
> $ mkdir -p depot/registries
> 
> $ ln -s ~/.julia/registries/General depot/registries
> 
> $ JULIA_DEPOT_PATH=$PWD/depot jlpkg --project=. instantiate
>  Installed LoggingExtras ──────── v0.3.0
>  Installed ProgressMeter ──────── v1.1.0
>  Installed ProgressMeterLogging ─ v0.1.0
> 
> $ ls depot/packages
> LoggingExtras  ProgressMeter  ProgressMeterLogging
> ```

(Edit: fixed the first example)

**Comment by tkf** [comment]
Actually, this is a dup of #1249.

**Comment by KristofferC** [comment]
What is the expected behaviour though?

**Comment by fredrikekre** [comment]
The version that already is in the current project should be valid, same as if we instantiate it I guess?

**Comment by KristofferC** [comment]
I think this is working as expected. `instantiate` is supposed to work (since it just replicates an existing environment) but you cannot do a new resolve when there are no versions available.
