### ISSUE TITLE
Feature request: interface for updating `Compat.toml` in a registry

### ISSUE THREAD

**Issue by tkf** [JuliaLang/Pkg.jl#1492]
Continuing discussion in https://github.com/JuliaRegistries/General/pull/5098:

I find manually updating `Compat.toml` is hard and rather scary as it's error-prone, especially because `Compat.toml` does some kind of "compressing" (or generating reverse dict or something?).  It would be nice to have an automated tool to introduce new bounds in `Compat.toml`.

(I'm not sure if Pkg.jl is the perfect place to file this issue but it's hard to find a better place. Also maybe overlapping with/dup of #1190.)

**Comment by KristofferC** [comment]
Maybe reopen at https://github.com/JuliaRegistries/RegistryTools.jl?

**Comment by tkf** [comment]
Good idea!
