### ISSUE TITLE
document that uuid4 is recommended

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/Pkg.jl#1493]
#1173 suggests that `uuid4` is the recommended way to generate UUIDs (as opposed to `uuid1`), it would be useful to document this somewhere.

This is of course relevant mostly to package template generators and similar.

I think the best place for this is [the toml docs](https://julialang.github.io/Pkg.jl/dev/toml-files/#The-uuid-field-1), I will wait for suggestions then make a PR.

**Comment by StefanKarpinski** [comment]
Yes, that seems like a good place for it at least. Doesn't mean it can't also be mentioned elsewhere.
