### ISSUE TITLE
GitError(Code:EMERGECONFLICT, Class:Checkout, 260 conflicts prevent checkout)

### ISSUE THREAD

**Issue by hpompom** [JuliaLang/Pkg.jl#1505]
When I try to add a new pkg, Appear the error. I try to reinstall or delate the file of registries, but it seeming useless.
Julia 1.1.1.1 OS X Majave

**Comment by fredrikekre** [comment]
Can you post the code you execute and include the full error?

> Julia 1.1.1.1

Looks like JuliaPro? Maybe contact their support then?

**Comment by hpompom** [comment]
> Can you post the code you execute and include the full error?
> 
> > Julia 1.1.1.1
> 
> Looks like JuliaPro? Maybe contact their support then?

code is add DataFrames, I update the juliapro1.1.1.1 to Juliapro 1.2.0 to solve this problem .Thank you!
