### ISSUE TITLE
Removing and re-adding a package is blocked when Compat entry present

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/Pkg.jl#1508]
I added a Compat entry for a dependency for my package (not intended for the registry). Then I tried to remove and re-add the package to troubleshoot something. When I tried to add the package back, I received the error:

`ERROR: Compat `<package>` not listed in `deps` or `extras` section.`

Removing the compat entry allowed me to re-add the package.

**Comment by fredrikekre** [comment]
Fixed by https://github.com/JuliaLang/Pkg.jl/pull/1324
