### ISSUE TITLE
Version bounds with a space not a comma

### ISSUE THREAD

**Issue by mcabbott** [JuliaLang/Pkg.jl#1511]
I made the mistake of writing this
```
julia = "0.7 1.0"
```
over [here](https://github.com/JuliaMath/VML.jl/pull/24/commits/1e2c6200b405d44ee879c034b1d7daa05cd37a2f), which leads to warnings when loading the package on Julia 1.3.

@fredrikekre points out that this is parsed as follows:
```
julia> Pkg.Types.semver_spec("0.7 1.0")
VersionSpec("0.71”)
```
Surely I’m not the only guy who’ll ever make this mistake. Perhaps it should either be an error, or be accepted?

**Comment by DilumAluthge** [comment]
I don’t think we should accept spaces as a substitute for commas.

For example, in the current hyphen syntax for specifying ranges, we require a space on either side of the hyphen. That is, `1.2 - 3.4` is a valid range, but `1.2-3.4` is not a valid range. This is necessary to avoid confusion with the server prerelease syntax.

So I think it would be confusing to have spaces mean one thing in one context, and a different thing in different contexts.

**Comment by KristofferC** [comment]
Yeah, would be best for that to error.
