### ISSUE TITLE
`] dev ~` tab-autocompletion is incorrect

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/Pkg.jl#1520]
My home directory is `/Users/dilum`.

On `Version 1.4.0-DEV.535 (2019-11-30)` (`Commit 9babbf5dc6`), when I type `] dev ~` and press tab, it autocompletes to:

```julia  
(v1.4) pkg> dev /Users/dilum/dilum
```

---

For comparison:

On `Version 1.2.0 (2019-08-20)`, when I type `] dev ~` and press tab, it autocompletes to:
```julia
(v1.2) pkg> dev /Users/dilum
```

On `Version 1.3.0 (2019-11-26)`, when I type `] dev ~` and press tab, it autocompletes to:
```julia
(v1.3) pkg> dev /Users/dilum
```

**Comment by KristofferC** [comment]
Maybe caused by https://github.com/JuliaLang/Pkg.jl/pull/1365.

**Comment by KristofferC** [comment]
I guess this got fixed:

```
(@v1.7) pkg> dev /Users/kristoffercarlsson/
```

Feel free to open with more info if this is still an issue.
