### ISSUE TITLE
Wrong fallback gen_unpack_command

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/Pkg.jl#1524]
I ran into the following:

```
ERROR: MethodError: no method matching (::Pkg.PlatformEngines.var"#3#5")(::String, ::String, ::Nothing)
Closest candidates are:
  #3(::AbstractString, ::AbstractString; excludelist) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/PlatformEngines.jl:41
Stacktrace:
 [1] #unpack#91(::Bool, ::typeof(Pkg.PlatformEngines.unpack), ::String, ::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/PlatformEngines.jl:744
 [2] unpack(::String, ::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/PlatformEngines.jl:723
```

From a cursory look at the code, I think that the `gen_unpack_cmd` fallback (that displays an error) has the wrong signature:
https://github.com/JuliaLang/Pkg.jl/blob/0c2dddd40e4d7492d2a7337be54c345011e5f1e1/src/PlatformEngines.jl#L40-L42

vs. the use:
https://github.com/JuliaLang/Pkg.jl/blob/0c2dddd40e4d7492d2a7337be54c345011e5f1e1/src/PlatformEngines.jl#L744

Only happens if the platform hasn't been probed. After that the signatures seem correct:
https://github.com/JuliaLang/Pkg.jl/blob/0c2dddd40e4d7492d2a7337be54c345011e5f1e1/src/PlatformEngines.jl#L316

**Comment by KristofferC** [comment]
I think this code has been removed.
