### ISSUE TITLE
Nightly failing with "gzip: stdin: not in gzip format"

### ISSUE THREAD

**Issue by timholy** [JuliaLang/Pkg.jl#1525]
Example: https://travis-ci.org/JuliaDebug/JuliaInterpreter.jl/jobs/620379082?utm_medium=notification&utm_source=github_status

From https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/353

**Comment by DilumAluthge** [comment]
The last time I saw this error, it was an issue with the Julia subscription to Google Cloud Engine.

@staticfloat

**Comment by KristofferC** [comment]
Think this is fixed.
