### ISSUE TITLE
disabling --diff on 1.3, bug?

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/Pkg.jl#1528]
Which part of the documentation am I overlooking when I think that in the following case it should not print the diff but the whole project.toml?
```julia
julia> versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8

(DataFrames) pkg> st
Project DataFrames v0.19.3
    Status `C:\Users\Matthis\.julia\dev\DataFrames\Project.toml`
  (no changes since last commit)
```

**Comment by StefanKarpinski** [comment]
If the project is in a git repo, it shows the diff since last commit; if it's not in a git repo, it shows the whole project file (since there's nothing to compare it with).

**Comment by KristofferC** [comment]
Yeah but we disabled that unless you give `--diff`.

**Comment by 00vareladavid** [comment]
Yeah #1205, but I can't reproduce

**Comment by rapus95** [comment]
It is indeed very weird. I only have that problem for my DataFrames clone... Couldn't infer why for now :/

**Comment by rapus95** [comment]
I now went into debugging and found these code lines:
https://github.com/JuliaLang/Pkg.jl/blob/49ab53e7e70afc319d23436ae6f68691d2be7358/src/Display.jl#L37-L38
https://github.com/JuliaLang/Pkg.jl/blob/49ab53e7e70afc319d23436ae6f68691d2be7358/src/Display.jl#L67-L88
Now, that in the last 3 lines we make the diff between two identical snapshots (as the if is not called) I see, why I get "no changes". Thus, my question now is not, why it doesn't work as intended for DataFrames but why does it work everywhere else? It shouldn't, from my very basic understanding...

**Comment by rapus95** [comment]
I recently created a new Package locally (whose status should be empty) which now also only shows me a diff. (at least it says so)
```julia
(GridEnhancing) pkg> st
Project GridEnhancing v0.1.0
    Status `C:\Users\Matthis\.julia\dev\GridEnhancing\Project.toml`
  (no changes since last commit)
```
