### ISSUE TITLE
Unable to add private package on Julia 1.4

### ISSUE THREAD

**Issue by omus** [JuliaLang/Pkg.jl#1546]
On Julia version 1.4 (including the latest version of `1.4.0-DEV.611`) if I attempt to add a private package which contains another private package as a dependency I get the following exception:
```julia
(@v1.4) pkg> add AWSBatch
 Resolving package versions...
ERROR: Error when installing package AWSBatch:
MethodError: Cannot `convert` an object of type Nothing to an object of type String
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:AbstractString at strings/basic.jl:209
  convert(::Type{T}, !Matched::AbstractString) where T<:AbstractString at strings/basic.jl:210
  convert(::Type{T}, !Matched::T) where T at essentials.jl:170
Stacktrace:
 [1] convert(::Type{Pair{String,Bool}}, ::Pair{Nothing,Bool}) at ./pair.jl:71
 [2] push!(::Array{Pair{String,Bool},1}, ::Pair{Nothing,Bool}) at ./array.jl:883
 [3] macro expansion at /Users/omus/Development/Julia/latest/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:669 [inlined]
 [4] (::Pkg.Operations.var"#45#48"{Bool,Pkg.Types.Context,Dict{Base.UUID,Array{String,1}},Channel{Any},Channel{Any}})() at ./task.jl:349
```
Private packages that have no private dependencies work fine.

**Comment by omus** [comment]
Looking over our CI history it appears that the last nightly version to pass was `1.4.0-DEV.529` and the earliest version that started failing was `1.4.0-DEV.531`

**Comment by omus** [comment]
Started failing with: https://github.com/JuliaLang/julia/pull/33971

**Comment by omus** [comment]
Ok, [this change](https://github.com/JuliaLang/Pkg.jl/commit/258d74ecd4104aadb34ff65f384782eb9a8eacd5#diff-920ed338dcbd9d62489c6d12dc2fbb18R644) calls `get_archive_url_for_version` and expects that a `String` will always be returned which isn't the case for non-github URLs.

**Comment by KristofferC** [comment]
Yep, that needs a handle for `nothing`

**Comment by StefanKarpinski** [comment]
So what's the appropriate fix? Just make `get_archive_url_for_version` handle `url = nothing`?

**Comment by KristofferC** [comment]
Either make https://github.com/JuliaLang/Pkg.jl/commit/258d74ecd4104aadb34ff65f384782eb9a8eacd5#diff-920ed338dcbd9d62489c6d12dc2fbb18R644 handle the `return nothing` from `get_archive_url_for_version` or make `get_archive_url_for_version` return the original URL when it doesn't find a match. Seems like that should do the same thing.

**Comment by omus** [comment]
It would be good if some tests could be added for private registries as well

**Comment by KristofferC** [comment]
There are test for multiple registries (https://github.com/JuliaLang/Pkg.jl/blob/master/test/registry.jl, https://github.com/JuliaRegistries/Test). It just needs a package with a non-github url.
