### ISSUE TITLE
Packages fail during tests if they don't have a `Project.toml` file

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/Pkg.jl#1550]
For example:
- https://github.com/maleadt/BasePkgEvalReports/blob/adfa530cc2662ca9abd85544d3ed41aa6d0ad95f/pkgeval-daily_2019_12_16/logs/Permutations/1.4.0-DEV-a6bf74a2f9.log#L36-L65

Right now, we believe that this was probably caused by https://github.com/JuliaLang/Pkg.jl/pull/1427

cc: @00vareladavid

**Comment by 00vareladavid** [comment]
#1549
