### ISSUE TITLE
Make artifact hash strings case-insensitive?

### ISSUE THREAD

**Issue by azurefx** [JuliaLang/Pkg.jl#1569]
Using artifacts with uppercase hash strings in `Artifacts.toml` causes an error:
```
┌ Error: Hash Mismatch!
│   Expected sha256:   1F2C2590B029482F152B1CF8DB7E3FC30FB31B30F22654632F88142175D670F9
│   Calculated sha256: 1f2c2590b029482f152b1cf8db7e3fc30fb31b30f22654632f88142175d670f9
└ @ Pkg.PlatformEngines /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Pkg/src/PlatformEngines.jl:985
```
https://github.com/JuliaLang/Pkg.jl/blob/b9bcd6afdea6b10586e97a0e3b13ffc3b6b1a747/src/PlatformEngines.jl#L1237-L1241

How about making the comparison case-insensitive?

**Comment by fredrikekre** [comment]
Why not use lowercase? Seems to be what most programs output.

**Comment by StefanKarpinski** [comment]
Seems fairly harmless to allow case differences, though, no? Most programs that accept hexadecimal hashes value ignore their case.

**Comment by azurefx** [comment]
> Why not use lowercase? Seems to be what most programs output.

I copied this string from PowerShell's `Get-FileHash -Algorithm SHA256` command, and it produces uppercase hash.
