### ISSUE TITLE
audit uses of homedir()

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/Pkg.jl#1586]
At least one usage of `homedir()` seems incorrect: https://github.com/JuliaLang/Pkg.jl/blob/b6e2ac29effb8a636dd297735296589cf80e3bae/src/REPLMode/argument_parsers.jl#L107

I'd suggest using `expanduser` here, but it seems like it might actually be a URL here from the subsequent assignment of the result to the `.url` field of something?

**Comment by StefanKarpinski** [comment]
Yes, this is pretty sketchy. The situation here is that the URL can either be a real URL or a local path. In the case of a local path, we want to do the homedir expansion. I suspect that calling `expanduser` would be fine since it returns the argument as-is unless it begins with `~`, in which case it cannot possibly be a URL.

**Comment by StefanKarpinski** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/1595 fixes the only inappropriate usage of `homedir`.

**Comment by vtjnash** [comment]
The other usage seems suspect too, though for a slightly different reason. Appearing to indexing a string with `expanduser(s)[textwidth(homedir()) - 1]` (iiuc) just sounds very odd:
https://github.com/JuliaLang/Pkg.jl/blob/a5df9271ac47415ddbc00f1d0ed1643100d803da/src/REPLMode/completions.jl#L31

**Comment by StefanKarpinski** [comment]
Yeah, that seems super broken just because it misunderstands how to do to Unicode string stuff.

**Comment by vtjnash** [comment]
Also `expanded_user = expanduser(s) != s` might be better? Though I don't know what the purpose of `endswith(homedir(), completion[1])` later is either (which checks if the end of the path matches the homedir folder)

**Comment by 00vareladavid** [comment]
likely causing #1520

**Comment by vtjnash** [comment]
Yes, that odd code seems to have been from https://github.com/JuliaLang/Pkg.jl/pull/1365
