### ISSUE TITLE
'test' can't find local package when dev'd in test/Project.toml

### ISSUE THREAD

**Issue by dalejordan** [JuliaLang/Pkg.jl#1587]
If you have a question please search or post to our Discourse site: https://discourse.julialang.org.
We use the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

**Comment by dalejordan** [comment]
Julia 1.3

In the test environment for a package (`activate Foo/test`), `dev MyLocalPkg` appears to work properly (according to `status`).  But activating Foo and running `test` proclaims: ERROR: Package MyLocalPkg [9478e6a4-9dc6-11e8-3ebe-c1739d81bd01] not found in a registry.  This is true but that is why the `dev`.

**Comment by 00vareladavid** [comment]
This should be working after #1427
