### ISSUE TITLE
Yanked package is still installed during CI

### ISSUE THREAD

**Issue by travigd** [JuliaLang/Pkg.jl#1612]
CC @MaximeBouton

When testing a package, Pkg installs a yanked version of `JSExpr`.

https://travis-ci.org/sisl/AutoViz.jl/jobs/635593670?utm_medium=notification&utm_source=github_status

**Comment by travigd** [comment]
Looking a bit further, I think this is actually just because yanking was implemented after Julia 1.0 and tests are running against Julia 1.0.

Running `]add JSExpr` installs the yanked version on 1.0 but installs the latest, non-yanked version on 1.1+.

**Comment by fredrikekre** [comment]
yea, 1.0 does not support that feature.

**Comment by travigd** [comment]
Is there any way to otherwise revoke the bad JSExpr releases then?

**Comment by 00vareladavid** [comment]
You should still be able to set `compat` as described here: https://julialang.github.io/Pkg.jl/v1/compatibility/

**Comment by KristofferC** [comment]
Tag a new working patch version?

**Comment by travigd** [comment]
The issue is that there's a reverse dependency. So JSExpr itself doesn't need to change, WebIO needs to change and that's a bit further off.
