### ISSUE TITLE
Big try catch in code for getting the registry from Pkg server

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#1622]
The code:

https://github.com/JuliaLang/Pkg.jl/blob/f78c1e1ad6d4ade6d72ab6b283f8c9b65a879c2a/src/Types.jl#L862-L882

has a very big try catch block.  This could easily disquise typos which might go unnoticed on CI since it will fallback to getting the registry from git. 

It would be better if the try catch could only enclose the actual `download` call, and also perhaps check the type of the exception.

cc @StefanKarpinski

**Comment by StefanKarpinski** [comment]
I don't know what I was thinking when I wrote some of this code. Why are the try/catch blocks so damned big? Yeah, I'll fix this and we can backport it to the 1.4 release.

**Comment by KristofferC** [comment]
In addition, the line `mktemp() do tmp_path, io` is problematic on Windows because it opens the file and Windows doesn't like to overwrite opened files. It is likely better to use `tempname`.
