### ISSUE TITLE
Dropping a dependency in a build version doesn't have effect in the registry

### ISSUE THREAD

**Issue by giordano** [JuliaLang/Pkg.jl#1631]
I'm not sure this is a problem of Pkg or RegistryTools or a related package, but I was suggested to open the issue here.

Long time ago, we made the mistake to have a huge JLL package collecting several Xorg libraries.  For context, that was meant to be consumed mainly by `BinaryProvider.jl`, with which managing several dependencies is a huge pain, so having all those libraries in a single tarball made thing easier.  However, a JLL package, [`X11_jll`](https://github.com/JuliaBinaryWrappers/X11_jll.jl), was created at some point.  Later on, we moved to a more fine-grained approach, and in https://github.com/JuliaPackaging/Yggdrasil/pull/92 we completely removed `X11_jll` from Yggdrasil.

I thought I'd have never heard of `X11_jll` any more, until today, when I found that a lot of packages in the General registry actually still depend on it, _in addition_ to their replacements.  For example, I triggered a rebuild of `Libglvnd_jll` hoping that the dependency of `X11_jll` would be dropped, but in https://github.com/JuliaRegistries/General/pull/8389 there is no change to the dependencies.  As of this writing, `Libglvnd_jll` [depends](https://github.com/JuliaRegistries/General/blob/5853067d2d7e63da0b41791a877a19c57dc6d66c/L/Libglvnd_jll/Deps.toml) on `X11_jll`, `Xorg_glproto_jll`, `Xorg_libX11_jll`, `Xorg_libXext_jll`, but the last three packages were meant to replace `X11_jll`, not to be added to it.

@DilumAluthge should have some ideas about why the dependency of `X11_jll` was never actually dropped in the registry, despite the fact the JLL package don't actually depend on it.

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/Pkg.jl/issues/1568?

**Comment by DilumAluthge** [comment]
This is primarily an issue in the `Compress` functionality, which used to live in `Pkg` (as a sub module called `Pkg.Compress`, but now lives in `RegistryTools`.

But the `Compress` functionality is built upon types defined in `Pkg`, such as:
- `Pkg.Types.VersionBound`
- `Pkg.Types.VersionRange`
- `Pkg.Types.VersionSpec`

So in order to fix this in `RegistryTools`, we need to modify those `Pkg` types to understand build versions. So I suppose this is related to https://github.com/JuliaLang/Pkg.jl/issues/1568

**Comment by staticfloat** [comment]
X-ref: https://github.com/JuliaRegistries/General/pull/8645

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/Pkg.jl/issues/1568
