### ISSUE TITLE
gen_project.jl fails due to undefined function

### ISSUE THREAD

**Issue by jlapeyre** [JuliaLang/Pkg.jl#1632]
```
$ cd MyPackage
$ julia ~/gen_project.jl
ERROR: LoadError: UndefVarError: METADATA_compatible_uuid not defined
Stacktrace:
 [1] uuid(::String) at /home/lapeyre/gen_project.jl:45
 [2] top-level scope at /home/lapeyre/gen_project.jl:118
 [3] include(::Module, ::String) at ./Base.jl:377
 [4] exec_options(::Base.JLOptions) at ./client.jl:288
 [5] _start() at ./client.jl:484
in expression starting at /home/lapeyre/gen_project.jl:98
```
Julia Version 1.5.0-DEV.115

**Comment by DilumAluthge** [comment]
Yeah, the `gen_project.jl` script does not work on the latest Julia. Try running it with Julia 1.2 or Julia 1.3.

**Comment by StefanKarpinski** [comment]
Should probably be deleted and functionality replaced elsewhere if people still want it.

**Comment by KristofferC** [comment]
It is deleted.

**Comment by DilumAluthge** [comment]
Ah yes. And then we added links in the doc that point to the old commit. Whoops.

**Comment by DilumAluthge** [comment]
Probably time to remove those links from the docs. They are in a couple places in the Pkg.jl docs. I think on the page about creating projects.

**Comment by KristofferC** [comment]
> . And then we added links in the doc that point to the old commit. 

That was intentional though. I think we can just say that you need to use Julia 1.3 there.
