### ISSUE TITLE
`Pkg.status` printing

### ISSUE THREAD

**Issue by 00vareladavid** [JuliaLang/Pkg.jl#1649]
#1621 changed the printing from this:
```
Status `~/pkg/pkg_master/ex1/Project.toml`
  [7876af07] Example v0.5.3
  [682c06a0] JSON v0.21.0 #master (https://github.com/JuliaIO/JSON.jl.git)
  [dcb67f36] Unregistered v0.2.0 [`~/.julia/dev/Unregistered`]
  [d6f4376e] Markdown 
```
to this:
```
     Status `~/pkg/pkg_master/ex1/Project.toml`
   7876af07 Example v0.5.3
   682c06a0 JSON v0.21.0 `https://github.com/JuliaIO/JSON.jl.git#master`
   dcb67f36 Unregistered v0.2.0 `~/.julia/dev/Unregistered`
   d6f4376e Markdown
```

I find this a lot cleaner. But I want to double check if there is disagreement over this. 

In particular, perhaps the packages tracking path/repos do not stand out enough? I personally use them a lot, so the extra symbols only add noise. But if someone only has a few, then they could be useful delimiters. Perhaps a good middle ground is to make path/repo description bold.

Any other concerns/improvements that could be made to `status` formatting?

Because of the refactor, it should now be easy to implement #686. It would be useful for really big projects. I'm thinking of something like `status --filter=[path|repo|registry]`. This way you don't have to use your eyeballs to filter the info you are looking for.

**Comment by KristofferC** [comment]
🤷 , it is probably fine the way it is now
