### ISSUE TITLE
Corrupted path when developing packages on different drive than C on Windows

### ISSUE THREAD

**Issue by AnHeuermann** [JuliaLang/Pkg.jl#1653]
When generating and developping a new package on Windows and you are not working on `C:` the path used by `pkg dev` will be corrupted and have "C:\" before the correct path.

Steps to reproduce the bug:
```julia
julia> cd("D:\\")
(v1.3) pkg> generate PackageName
Generating project PackageName:
    PackageName\Project.toml
    PackageName/src/PackageName.jl
julia> cd("PackageName")
(v1.3) pkg> dev .
 Resolving package versions...
ERROR: path C:\D:\PackageName for package PackageName no longer exists. Remove the package or `develop` it at a new path
```

Julia version: Version 1.3.1 (2019-12-30)
pkg version: 1.3
OS: Win10 64bit

**Comment by StefanKarpinski** [comment]
Yeah, that's very suspicious. Looks like there's some code somewhere that's not calling `joinpath`.

**Comment by visr** [comment]
Hmm, also hitting this on 1.4RC1. The info message shows the indentifier is correctly resolved to the path:
```julia
(@v1.4) pkg> generate MyPkg
 Generating  project MyPkg:
    MyPkg\Project.toml
    MyPkg\src/MyPkg.jl

(@v1.4) pkg> dev MyPkg
[ Info: Resolving package identifier `MyPkg` as a directory at `D:\MyPkg`.
Path `MyPkg` exists and looks like the correct package. Using existing path.
  Resolving package versions...
ERROR: expected package `MyPkg [e4d92ad3]` to exist at path `C:\D:\MyPkg`
```

Here is was working from the v1.4 project env which is on my C drive, as it will for most. However when working from a project on the D drive, this is fine:

```julia
(@v1.4) pkg> activate .
 Activating new environment at `D:\Project.toml`

() pkg> generate MyPkg2
 Generating  project MyPkg2:
    MyPkg2\Project.toml
    MyPkg2\src/MyPkg2.jl

() pkg> dev MyPkg2
[ Info: Resolving package identifier `MyPkg2` as a directory at `D:\MyPkg2`.
Path `MyPkg2` exists and looks like the correct package. Using existing path.
  Resolving package versions...
   Updating `D:\Project.toml`
  [6cc37cc3] + MyPkg2 v0.1.0 [`MyPkg2`]
   Updating `D:\Manifest.toml`
  [6cc37cc3] + MyPkg2 v0.1.0 [`MyPkg2`]
```

I haven't verified this, but I'm suspecting this code:
https://github.com/JuliaLang/Pkg.jl/blob/5345ec0a04fde1d83307982a686b2ecd31e1e8a5/src/Operations.jl#L732-L734

There is no relative path from `C:\` to `D:\`.

**Comment by StefanKarpinski** [comment]
Hmm. The correct behavior for a relpath call from one drive to a different one is to give an absolute path to the destination, which has the desired property that joinpath will give the right location in the end.

**Comment by giordano** [comment]
Yesterday I did some debugging in https://github.com/JuliaLinearAlgebra/MKL.jl/pull/68#issuecomment-787470459.  Not sure whether this is fixed on `master` of Pkg though, because the issue wasn't triggered there

**Comment by visr** [comment]
Looks to me like https://github.com/JuliaLang/julia/pull/38259 might have fixed this.
