### ISSUE TITLE
Can't download registry from Pkg Server on Windows

### ISSUE THREAD

**Issue by shihaoyan2018** [JuliaLang/Pkg.jl#1658]
Can't download registry from Pkg Server on Windows , but it can download registry from Pkg Server on Linux , and I can access `pkg.julialang.org/docs` normally.
versioninfo():

` julia> versioninfo()`
`Julia Version 1.4.0-rc1.0`
`Commit b0c33b0cf5 (2020-01-23 17:23 UTC)`
`Platform Info:`
  `OS: Windows (x86_64-w64-mingw32)`
  `CPU: AMD Ryzen 3 3200G with Radeon Vega Graphics`
  `WORD_SIZE: 64`
 ` LIBM: libopenlibm`
 `LLVM: libLLVM-8.0.1 (ORCJIT, znver1)`
`Environment:`
 `JULIA_PKG_SERVER = pkg.julialang.org`

and the warning:

`┌ Warning: could not download https://pkg.julialang.org/registries`

`└ @ Pkg.Types D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Types.jl:879`

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/Pkg.jl/issues/1642
