### ISSUE TITLE
Excessive writes to `manifest_usage.toml`

### ISSUE THREAD

**Issue by ericphanson** [JuliaLang/Pkg.jl#1664]
I instantiated a manifest (on Julia 1.3.1) and it added 9 entries (for the same manifest at very close timestamps) to `.julia/logs/manifest_usage.toml`.

I had a bunch of corrupted entries in there (probably from interrupting Pkg operations) which caused `Pkg.gc()` to fail, and it seems like maybe there would be fewer opportunities for corrupted entries if Pkg didn't write to that file so much.

(I first reported this on Slack).

**Comment by ericphanson** [comment]
It might be nice also if interrupt exceptions during these writes were handled somehow so as to not corrupt the toml file.

**Comment by KristofferC** [comment]
Yeah, and also handling corrption in the file better (trying to recover)

**Comment by KristofferC** [comment]
@IanButterworth, how many writes are done to `manifest_usage.toml` now?

**Comment by IanButterworth** [comment]
The number of writes is the same, but each manifest is only entered once, and the corruption won't happen. 

If that doesn't mean this issue can be closed, feel free to reopen.

**Comment by ericphanson** [comment]
I actually tried to reproduce this last night to see if it should be reopened but instantiating a Manifest (on Pkg 1.3) only added one entry to that file, not 9. So I’m not sure what was different the first time. So I think it’s ok for this to stay closed unless there’s a reproducible issue w/excessive writes.

Thanks a lot for the locking fix btw, the corruption was definitely the most annoying part. Will ctrl-c at the wrong time cause corruption still, do you think?
