### ISSUE TITLE
Detect if the powershell is too old on Windows and give the appropriate error message on updating it

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/Pkg.jl#1672]
This command, which is used to download tarballs gives an error on Windows 7, which I am using through VirtualBox.
```
cmd = `powershell -NoProfile -Command '[System.Net.ServicePointManager]::SecurityProtocol =    [System.Net.SecurityProtocolType]::Tls12;$webclient = (New-Object System.Net.Webclient);$webclient.UseDefaultCredentials = $true;$webclient.Proxy.Credentials = $webclient.Credentials;$webclient.Headers.Add("user-agent", "Pkg.jl (https://github.com/JuliaLang/Pkg.jl)");$webclient.DownloadFile("https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+5/SuiteSparse.v5.4.0.i686-w64-mingw32.tar.gz", "C:\Users\Viral\AppData\Local\Temp\jl_D359.tmp-download.gz")'`

run(cmd)
```

Note that changing Tls12 to Tls as suggested in the error message only suppresses that part. The download still fails.

![Screen Shot 2020-02-12 at 9 55 59 AM](https://user-images.githubusercontent.com/744411/74369660-be8ad900-4da3-11ea-85c1-d983217e6d7e.png)

Packages are getting downloaded by git cloning, which is the fallback when the tarball downloads are not working. Artifacts do not have such a fallback.

**Comment by ViralBShah** [comment]
@kdheepak reported the same on his Travis build. Also cc'ing @staticfloat @musm.

**Comment by aviks** [comment]
Is is this? Have you tried installing the `easy_fix` referenced in that post? https://discourse.julialang.org/t/errors-for-git-pkg/9351

**Comment by ViralBShah** [comment]
These errors are not with git, but just with the http download. The git cloning is working fine.

**Comment by ViralBShah** [comment]
Just installed the `easy_fix` but that didn't change anything.

**Comment by ViralBShah** [comment]
If this issue does not exist on Windows 10, perhaps it is a good reason for us to drop Win 7 support.

**Comment by ViralBShah** [comment]
So, what I needed was a more recent Powershell. We used to have a prominent message before  for WMF and it only became relevant now that Artifacts requires the downloads to work. Pkg was quietly switching to git.

I doubt that people will install WMF however prominently it is shown (and I am not convinced we should do it for Win 7 users, since it is EOL anyways). But I think it would be useful to detect at runtime that we have an old Powershell and issue the appropriate error message.

**Comment by KristofferC** [comment]
Should be fixed by using Downloads.jl
