### ISSUE TITLE
Disallow cycles in the dependency graph for required dependencies 

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/Pkg.jl#1698]
> Good to fix this, but we may want to hard disallow cyclic dependencies in the future.

_Originally posted by @StefanKarpinski in https://github.com/JuliaLang/Pkg.jl/pull/1696#issuecomment-590376516_

**Comment by KristofferC** [comment]
Why?

**Comment by DilumAluthge** [comment]
At least for regular required dependencies it seems like we should disallow it.

I guess we can allow it in test-only dependencies.

**Comment by KristofferC** [comment]
Since the code is still needed for test only dependencies, what is the gain in disallowing it for normal dependencies. You could add a warning (like `build` already does when it notices that the graph is not a DAG) but why error when you can just work instead?

**Comment by DilumAluthge** [comment]
Hmmm I see what you mean. Maybe a warning is better.

**Comment by DilumAluthge** [comment]
Although, what is the use decade for cyclic required dependencies?

**Comment by KristofferC** [comment]
Might be an accident that one of your dependencies depend on you. Not ideal but it isn't that hard to handle so let's just do that.
