### ISSUE TITLE
Segfault when installing or updating packages

### ISSUE THREAD

**Issue by prosoitos** [JuliaLang/Pkg.jl#1700]
Trying to update my packages caused a segfault and Julia crash. Restarting Julia and rebooting my system had no effect.

I uninstalled all my packages one by one, hoping that the problem would come from one of them and that reinstalling that package would solve things, but I still have the problem without any installed package.

As adding packages causes the same crash, I cannot reinstall them either :stuck_out_tongue: 

---
System info:

```jl
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
```
---
Error I get after crash:

```jl
signal (11): Segmentation fault
in expression starting at none:0
unknown function (ip: 0x7f1f57fd3e73)
http_parser_execute at /usr/bin/../lib/libhttp_parser.so.2.9 (unknown line)
unknown function (ip: 0x7f1f57fd5390)
unknown function (ip: 0x7f1f57fd7770)
unknown function (ip: 0x7f1f57fd9b58)
unknown function (ip: 0x7f1f57fd7f91)
git_remote_fetch at /usr/bin/../lib/libgit2.so (unknown line)
unknown function (ip: 0x7f1f6a8e8cb2)
unknown function (ip: 0x7f1f6a8ea0d8)
unknown function (ip: 0x7f1f6a8f3000)
unknown function (ip: 0x7f1f6a9124de)
unknown function (ip: 0x7f1f6a914101)
unknown function (ip: 0x7f1f6a9928df)
unknown function (ip: 0x7f1f6a992c1a)
unknown function (ip: 0x7f1f6a90caeb)
do_add! at /build/julia/src/julia-1.3.1/usr/share/julia/stdlib/v1.3/Pkg/src/REPLMode.jl:505
jl_f__apply at /usr/bin/../lib/libjulia.so.1 (unknown line)
jl_f__apply_latest at /usr/bin/../lib/libjulia.so.1 (unknown line)
unknown function (ip: 0x7f1f6a8a682b)
jl_f__apply at /usr/bin/../lib/libjulia.so.1 (unknown line)
unknown function (ip: 0x7f1f6aa1e522)
unknown function (ip: 0x7f1f6a9c4104)
unknown function (ip: 0x7f1f6a9c452d)
unknown function (ip: 0x7f1f6a9c82e8)
unknown function (ip: 0x7f1f6a9c8416)
jl_f__apply at /usr/bin/../lib/libjulia.so.1 (unknown line)
jl_f__apply_latest at /usr/bin/../lib/libjulia.so.1 (unknown line)
unknown function (ip: 0x7f1f6aaa6ce1)
unknown function (ip: 0x7f1f6aab9d9e)
unknown function (ip: 0x7f1f6aabacd1)
unknown function (ip: 0x7f1f6a8ccd9c)
unknown function (ip: 0x7f1f6a8cd358)
jl_f__apply at /usr/bin/../lib/libjulia.so.1 (unknown line)
jl_f__apply_latest at /usr/bin/../lib/libjulia.so.1 (unknown line)
unknown function (ip: 0x7f1f6a7e0717)
unknown function (ip: 0x7f1f6a7e6ff2)
unknown function (ip: 0x7f1f6a7e7512)
unknown function (ip: 0x7f1f6a7e7655)
unknown function (ip: 0x5604883f34fe)
unknown function (ip: 0x5604883f30a7)
__libc_start_main at /usr/bin/../lib/libc.so.6 (unknown line)
unknown function (ip: 0x5604883f315d)
Allocations: 945982 (Pool: 945715; Big: 267); GC: 1
[1]    3241 segmentation fault (core dumped)  julia
```

**Comment by johnnychen94** [comment]
Can you verify if this issue happens when you use a new package location?

For example, try to install packages with `JULIA_DEPOT_PATH=~/tmp/julia julia`. If that works normally, you can then rebuild your `~/.julia` folder. If not, then can you report what package causes the segfault.

**Comment by prosoitos** [comment]
Same problem.

And as for the package: it does not seem to be linked to any package. The same thing happens whatever package I am trying to add.

**Comment by prosoitos** [comment]
I can try to re-install Julia maybe.

**Comment by prosoitos** [comment]
Uninstalling Julia, removing the `~/.julia`, rebooting, and re-installing did not help.

**Comment by prosoitos** [comment]
Arch upgraded from julia 1.3.0 to 1.3.1 at the beginning of January and I don't think that I tried to add or upgrade packages after that. So maybe there is something up with 1.3.1??

I could try to downgrade and try again...

**Comment by prosoitos** [comment]
Same problem with 1.3.0 :slightly_frowning_face: 

Not sure what else to try :slightly_frowning_face:

**Comment by DilumAluthge** [comment]
Are you using the official binaries from julialang.org?

**Comment by prosoitos** [comment]
Yes.

I am on Arch Linux and I installed Julia through the community repository: https://www.archlinux.org/packages/community/x86_64/julia/

**Comment by DilumAluthge** [comment]
I am not sure if Arch Linux uses the official julialang.org binaries.

Can you download the binaries from https://julialang.org/downloads/ and see if you can still reproduce the bug?

**Comment by KristofferC** [comment]
That distro release is known to be bugged. The supported way of installing julia is through the binaries on the download page that has been linked already.

**Comment by prosoitos** [comment]
I just tried using the binaries directly and indeed, this fixed the problem. I reported the problem to the Arch package manager.

Thank you for the help.

**Comment by prosoitos** [comment]
Now that I am aware of this question of official binaries vs packages provided by distro managers, I realized that there is a package in the AUR which downloads and installs the official binaries.

This allows to have Julia managed by pacman (with the nicer integration in the system and easy updating) while using the official binaries, so I am posting it here in case it helps other Arch users.

https://aur.archlinux.org/packages/julia-bin/

**Comment by johnnychen94** [comment]
emmm... I seem to over-advertise it but I would say https://github.com/johnnychen94/jill.py makes such thing much easier (supports all platforms)

**Comment by cauachagas** [comment]
The arch-linux upgrade the `http-parser 2.9.2 -> 2.9.3`, that is incompatible with julia

So, let's downgrade to the 2.9.2
```bash
sudo pacman -S downgrade 
sudo downgrade http-parser # ignore update for http-parse
wget http://archlinux.arkena.net/archive/packages/h/http-parser/http-parser-2.9.2-1-x86_64.pkg.tar.xz
sudo pacman -U http-parser-2.9.2-1-x86_64.pkg.tar.xz
```

Please, report the solution to the Arch package manager.

**Comment by prosoitos** [comment]
Thanks. Apparently it has already been fixed.
