### ISSUE TITLE
Pkg.add results in defunct process

### ISSUE THREAD

**Issue by tanmaykm** [JuliaLang/Pkg.jl#1702]
Observed in docker containers. I wasn't able to simulate this on a bare machine. Neither was I able to get more than one defunct processes by repeating the same Pkg operations. It seems harmless , but may be good to find the reason.

```sh
$ docker pull julia:1.3.1-stretch

$ docker run -it julia:1.3.1-stretch 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.1 (2019-12-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia>
```

Get the Julia process pid:

```sh
$ ps -ef | grep julia
tan      15813 31987  1 10:59 pts/3    00:00:00 docker run -it julia:1.3.1-stretch
root     15872 15846 50 10:59 pts/0    00:00:01 julia
```

Add a package:

```julia
julia> using Pkg

julia> Pkg.add("JSON")
...

```

Check the Julia process:

```sh
$ ps -ef | grep 15872
root     15872 15846 16 10:59 pts/0    00:00:18 julia
root     16399 15872  0 11:01 pts/0    00:00:00 [julia] <defunct>
```

There's a defunct process associated with Julia.

**Comment by KristofferC** [comment]
What operations happened when adding `JSON`? Did it run any build steps for the packages? Just adding a new package shouldn't spawn a new process at all I would think.

**Comment by fredrikekre** [comment]
It spawns the `curl` process.

**Comment by KristofferC** [comment]
I guess this doesn't happen anymore since we don't spawn `curl` or `tar` now... Feel free to reopen if this still happens.
