### ISSUE TITLE
Only apply compat from a registry to versions found in that registry

### ISSUE THREAD

**Issue by kescobo** [JuliaLang/Pkg.jl#1711]
From discussion on slack:

My package Microbiome.jl has versions 0->0.4.0 registered in General, and versions 0.4.1+ registered in the BioJulia registry. When [I added](https://github.com/JuliaRegistries/General/pull/10262) compat entries to Microbiome.jl in General applying to `[0]`, those entries seemed to spill-over or block the compat from BioJulia.

```
ERROR: Unsatisfiable requirements detected for package Microbiome [3bd8f0ae]:
 Microbiome [3bd8f0ae] log:
 ├─possible versions are: [0.3.0-0.3.2, 0.4.0-0.4.1, 0.5.0-0.5.1, 0.6.0-0.6.3] or uninstalled
 ├─restricted to versions 0.6.3 by an explicit requirement, leaving only versions 0.6.3
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

Note: before that PR, which added an upper bound to julia itself at 1.0 in General, things were working ok. Is there something different about julia bounds and package bounds, or was that a coincidence (that is, other versions of the dependencies just happened to work)?

When I changed my local version of General to have the Microbiome compat for `["0-0.4.0"]`, it seems to work again ([PR here](https://github.com/JuliaRegistries/General/pull/10324)). Kristoffer suggested on slack that the resolver should only apply compat entries from a Registry to versions of a package found in that registry. Eg, since Microbiome only has versions up to `0.4.0` in the General `Versions.toml`, compat entries for `[0]` in general should be implicitly limited to `["0-0.4.0"]`. 

I'm not sure, but Frederik said he had a related issue (possibly #1434 ?). Not sure if this is a duplicate...

**Comment by fredrikekre** [comment]
> I'm not sure, but Fredrik said he had a related issue (possibly #1434 ?). Not sure if this is a duplicate...

It is
