### ISSUE TITLE
Handle `.jl` in name?

### ISSUE THREAD

**Issue by 00vareladavid** [JuliaLang/Pkg.jl#1712]
Someone tried to add a package with `Pkg.add("Foo.jl")`. This seems like a reasonable mistake for a beginner to make.

We can detect this case and remove the extension automatically. This is not too magic because the original string can never be a valid package name in the first place.

**Comment by fredrikekre** [comment]
Maybe an informative error message: `Did you mean Foo instead of Foo.jl` is better than to do things magically?

**Comment by StefanKarpinski** [comment]
I'd favor just handling it. I tried early on to only use the `.jl` extension in places where it was needed to identify something as a Julia package, but that didn't work out. In this case, it's not like `Foo.jl` is a valid package name, so I don't see the harm in just making it work.

**Comment by KristofferC** [comment]
This is now handled automatically in REPL mode and gives a good error message in API mode.
