### ISSUE TITLE
Add support for Overrides.toml next to Project.toml/Manifest.toml

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/Pkg.jl#1726]
Would it be possible to add the following functionality to the artifacts story:

if there is an `Overrides.toml` next to the `Project.toml` that is the active project, then apply the information from that `Overrides.toml`. Essentially it would be a non-global option for `Overrides.toml`.

**Comment by DilumAluthge** [comment]
Would the Overrides file be added by the end user?

If so, that moves us back towards package contents being mutable.

I really think we should move towards package contents being completely immutable.

**Comment by StefanKarpinski** [comment]
Intent satisfied quite differently by #1727 plus searching the project for `packages`.

**Comment by DilumAluthge** [comment]
> plus searching the project for `packages`

This part is implemented in https://github.com/JuliaLang/julia/pull/35195

**Comment by davidanthoff** [comment]
Yes, these new approaches are way better than my original idea here. I'll close this issue.
