### ISSUE TITLE
Docs for Pkg 1.4 are missing?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/Pkg.jl#1729]
When you go to https://julialang.github.io/Pkg.jl/v1/, the available options in the dropdown version selector are:
- `v1.3.0`
- `v1.3`
- `v1.2`
- `v1.1`
- `v1.0`
- `dev`

Missing from this list is `v1.4`.

**Comment by fredrikekre** [comment]
Fixed.
