### ISSUE TITLE
Pinning of packages in CI changed in 1.4

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaLang/Pkg.jl#1737]
In Plots.jl we temporarily need to pin FixedPointNumbers to version 0.7 for testing.
Doing `using Pkg; Pkg.pin(PackageSpec(name="FixedPointNumbers", version="0.7")); Pkg.build(); Pkg.test(coverage=true)` worked pre 1.4.
After asking on Slack, I changed that to `using Pkg; Pkg.resolve(); Pkg.pin(PackageSpec(name="FixedPointNumbers", version="0.7")); Pkg.build(); Pkg.test(coverage=true)`
which works on 1.4, but fails on 1.0.
See https://github.com/JuliaPlots/Plots.jl/pull/2499.

**Comment by KristofferC** [comment]
This seems stale now, feel free to comment if this is still an actual issue.
