### ISSUE TITLE
gc documentation should include collect_delay

### ISSUE THREAD

**Issue by bayesthm** [JuliaLang/Pkg.jl#1740]
Apologies if this duplicates the intent of https://github.com/JuliaLang/Pkg.jl/issues/1697#issue-569932852.

Users would find it helpful for the documentation on the `gc` function to include information on the `collect_delay` optional argument.  

Some description of this is already included in the API.jl source code:
https://github.com/JuliaLang/Pkg.jl/blob/5de608c7b1837a24ed84eaaa14dde017986cb460/src/API.jl#L273-L275

**Comment by KristofferC** [comment]
Should be fixed
