### ISSUE TITLE
artifacts often redownloads randomly?

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/Pkg.jl#1744]
I just did `./julia -e 'using ApproxFun'` twice in a row, and the second run printed "Downloading artifact: OpenSpecFun; Downloading artifact: OpenBLAS". Seems like something about artifacts is broken?

**Comment by KristofferC** [comment]
Can you repro?

**Comment by StefanKarpinski** [comment]
Are you using a pkg server or not?

**Comment by vtjnash** [comment]
Not predictably.

I haven't set any options, just a fairly vanilla build of Julia master.

**Comment by StefanKarpinski** [comment]
That depends on where the artifacts are being served from which might well be flaky. Can you try doing `export JULIA_PKG_SERVER=geo.pkg.julialang.org` and seeing if that helps? This is one of the major reasons we need the pkg protocol since relying on random origin servers is not great.

**Comment by vtjnash** [comment]
Why would we be trying to do major stateful operations during `using` and why are they dependent on some environment variable?

**Comment by KristofferC** [comment]
Please take griping about the artifact system to #gripes or another issue and let's focus on the eventual bug here.

**Comment by StefanKarpinski** [comment]
I assumed incomplete downloads. But the issue description isn't very clear, so 🤷‍♂

**Comment by vtjnash** [comment]
This is approximately what I see happen:
```
$ ./julia -e 'using ApproxFun' && echo SUCCESS
SUCCESS
$ ./julia -e 'using ApproxFun'
Downloading artifact: OpenSpecFun
Downloading artifact: OpenBLAS
SUCCESS
```
This seems to indicate the code is broken in some way?

**Comment by StefanKarpinski** [comment]
That is odd. @staticfloat, any idea what could be happening?

**Comment by staticfloat** [comment]
What system and Julia version are you using?  I can't reproduce on any of my systems.  If you have a system that it's happening on that I can SSH into, I can also remote in and inspect the system.

**Comment by vtjnash** [comment]
It's on arctic4 (/dev/sda1 on /data type btrfs (rw,relatime,space_cache,subvolid=5,subvol=/)), and is unpredictable in occurrence.

**Comment by staticfloat** [comment]
I've replicated your setup as best I can: I used julia `v1.4.0` (which I assume is what you were using), with the default depot in `~/.julia` on `arctic4`.  I installed `ApproxFun` into the global environment once, then ran `./julia -e 'using ApproxFun'` 10 times with `julia` sitting on the home drive, and also sitting in `/data/staticfloat`.  I never saw the artifacts get downloaded.  Any other details that might be relevant?

**Comment by staticfloat** [comment]
It's possible that an extraction was half-finished, but there's no case that I can think of where it should load successfully one time, then fail to load successfully in the future.

**Comment by KristofferC** [comment]
Maybe I encountered this:

```
(@v1.4) pkg> add MKL_jll
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
  Installed XML2_jll ─ v2.9.9+4
Downloading artifact: XML2
   Updating `~/.julia/environments/v1.4/Project.toml`
 [no changes]
   Updating `~/.julia/environments/v1.4/Manifest.toml`
  [02c8fc9c] ↑ XML2_jll v2.9.9+3 ⇒ v2.9.9+4

julia> using MKL_jll
[ Info: Precompiling MKL_jll [856f044c-d86e-5d09-b602-aeab76dc8ba7]
Downloading artifact: MKL
##                                                                         2.8%
```

**Comment by staticfloat** [comment]
No, `MKL_jll` is a lazy artifact, so it has explicitly opted in to that
behavior.
-E

**Comment by KristofferC** [comment]
Yeah, sorry. I deleted my message.

**Comment by fredrikekre** [comment]
Here is a repro: [artifacts.tar.gz](https://github.com/JuliaLang/Pkg.jl/files/4532965/artifacts.tar.gz). Unpack and run:
```
$ docker-compose up --build
Building julia-server
Step 1/5 : FROM julia
 ---> 248f01656dfd
Step 2/5 : COPY *.toml /
 ---> Using cache
 ---> 3036901d1553
Step 3/5 : ENV JULIA_PKG_SERVER="https://eu.pkg.julialang.org"
 ---> Using cache
 ---> 1b8748268d57
Step 4/5 : RUN julia --project=/ -e 'using Pkg; Pkg.instantiate()'
 ---> Using cache
 ---> 52ce2332ed25
Step 5/5 : ENTRYPOINT ["julia", "--project=/", "/run.jl"]
 ---> Using cache
 ---> 3fd2833b5313
Successfully built 3fd2833b5313
Successfully tagged julia-http:latest
Recreating julia ... done
Attaching to julia
julia           | Downloading artifact: MbedTLS
######################################################################## 100.0%
```

**Comment by KristofferC** [comment]
Isn't that https://github.com/JuliaLang/Pkg.jl/issues/1775?

**Comment by fredrikekre** [comment]
Ah, yea...

**Comment by fredrikekre** [comment]
Maybe this issue is also #1775?

**Comment by KristofferC** [comment]
No because it say that this was when doing `using` twice in a row.

**Comment by KristofferC** [comment]
Needs a repro or something. I'm still a bit doubtful that things happened exactly as described.
