### ISSUE TITLE
Julia 1.4 REQUIRE file support

### ISSUE THREAD

**Issue by jebej** [JuliaLang/Pkg.jl#1745]
I couldn't find an issue for this, and am not sure if that was intended, but it appears Julia 1.4 dropped support for REQUIRE files. This means that packages with no Project.toml files that worked under Julia 1.0 - 1.3 do not get installed anymore.

Reported here: https://discourse.julialang.org/t/install-of-thinkjulia-jl/36913

**Comment by fredrikekre** [comment]
It only breaks if the package is in a checked out state. If you have it in such a state you are probably developing the package and should add a Project.toml file.

**Comment by jebej** [comment]
Did you try
```
add https://github.com/BenLauwens/ThinkJulia.jl
```

**Comment by fredrikekre** [comment]
No, but that will of course not work.

**Comment by jebej** [comment]
I'm not sure if I am misunderstanding or not, but to me it appears that the package is not in any state, since it does not even get downloaded:

![image](https://user-images.githubusercontent.com/11141558/78291722-e3721180-74f3-11ea-84ee-f6b31e725f76.png)

**Comment by fredrikekre** [comment]
Right, but you are not adding a version, you are checking out a specific commit with that command. It has been almost 2 years since the new Pkg, its time to add a Project.toml file to the repo :man_shrugging:

**Comment by aquarelle233** [comment]
Hello fredrikekre,
Does it mean that Ben Lauwens (see the last post of jebej) should add a Project.toml file in his repository?

**Comment by fredrikekre** [comment]
Yes.
