### ISSUE TITLE
support specifying both lower and upper compatibility bounds

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/Pkg.jl#1748]
I would like to declare that PyPlot is compatible with `1.90 ≤ PyCall < 2`, but there seems to be no way to do this currently.

Hyphenated ranges like `1.90 - 2` were added in #1410, but that would correspond to `1.90 ≤ PyCall ≤ 2`, whereas I want `< 2`.

**Comment by KristofferC** [comment]
Isn't that just `1.90`?

**Comment by stevengj** [comment]
Oh... right, 1.90 with semver means `1.90 ≤ PyCall < 2`.
