### ISSUE TITLE
"Activating environment at ..." message is confusing to new users

### ISSUE THREAD

**Issue by marius311** [JuliaLang/Pkg.jl#1761]
I sent a project to a collaborator who is a new-ish Julia user. This included a `Project.toml` / `Manifest.toml`. They were aware that `Manifest.toml` includes the exact versions of things so that its what is needed to fully recreate an environment. 

When they ran `activate project_folder/` to start setting things up, it prints:

```
Activating environment at project_folder/Project.toml
```

However, this confused them because they thought maybe they were supposed to have "activated `Manifest.toml`" rather than `Project.toml`, since its the former that actually contains the package versions they knew were neeed. Although I hadn't thought of this myself, looking through the eyes of a new user, I actually totally agree this is confusing. 

Is there a reason to explicitly highlight `Project.toml` in that message? I wonder if it might better to just say `Activating environment at project_folder/` to avoid confusion?

**Comment by KristofferC** [comment]
Yeah, that seems fine. I also think we should say project instead of environment.
