### ISSUE TITLE
Remove code here for generate and make it delegate to packages

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/Pkg.jl#1762]
Its been long discussed to remove `generate` functionality from Pkg in favour of it being in packages. In particular PkgTemplates.

The main reason for this is that creating a package should in general do things like setting up CI. But also that CI vendors change there config file formats sometimes (like how Travis did not so long ago, breaking everyone's docs), and it is not reasonable for Pkg to keep up with them since it is tied to julia's release schedule.

I propose we actually do this at some point (and I couldn't find the issue).

I suggest if someone runs `generate`
then a teminal menu is displayed and they can chose from an number of options.
Such as:
 - PkgTemplates (cc @christopher-dG)
 - PkgSkeleton (cc  @tpapp)
 - PkgDev (/PkgButler) (cc  @davidanthoff)
 - `activate`
 - Cancel

And if one of the packages is selected, Pkg installs that to the global enviroment.

Maybe we could require these to all provide a `entrypoint_for_pkg_generate` function that would be called? Which would give the user additional prompts over stdin if more info is required. Like PkgTemplate's  `generate_interactive`. 
Not sure about this.

I suggest we have requirements formally specified for what it takes to get added to this list.
In particular i think those should focus on maturity, e.g. require the thing to have tagged v1.0,  and have been around and been in use for > 1 year, by > 1 person.
(I know PkgTemplates, and PkgSkeleton currently does not meet that, since it is yet to tag 1.0, idk about others, but I figure we will be talking through this for a little while)

**Comment by rapus95** [comment]
No matter how it looks at the end, I'd like to have the ability to set a default which is not tied to the requirements you specified. Maybe even to allow adding more packages to the local list. In other words IMO the requirements should only restrict what is provided by default.

**Comment by oxinabox** [comment]
> No matter how it looks at the end, I'd like to have the ability to set a default which is not tied to the requirements you specified. Maybe even to allow adding more packages to the local list. In other words IMO the requirements should only restrict what is provided by default.

Why?

I don't see huge attraction of being able to use X random package creation method via `] generate ...`.
Over using the package creation methods normal way, e.g,
```
using PkgTemplatesAlternative
generate_interactive(...)
```

Its not like I am proposing removing the current way in the package.
I am proposing removing the current (strictly inferior) way that is in Pkg right now.

**Comment by rapus95** [comment]
You wrote:
> Maybe we could require these to all provide a `entrypoint_for_pkg_generate` function that would be called? Which would give the user additional prompts over stdin if more info is required. Like PkgTemplate's generate_interactive.

I just proposed that not to be any expected interface but to allow arbitrary functions to be registered for that purpose. 

I envision to configure `] generate MyName` to generate a package according to a template in PkgTemplates which I created before which just needs a name as remaining input. That's why I passed it as an argument to generate. The freedom to arbitrarily prefill parts of a template of any of those systems according to MY (own) needs is what would make it a strong feature.
pkg"generate MyX" would just trigger my default generation machinery. And that should be arbitrarily customizable IMO.
I'd be fine with defining it in the startup file as it should be a matter of personal taste like the chosen editor. If you need something that works the same everywhere don't rely on the generate entrypoint but on the package you want to rely on.

**Comment by davidanthoff** [comment]
I think I would just remove `generate` entirely and call it a day and let other packages pick up that functionality.

I think designing some generic UI that installs packages etc. is way too involved, for in the end fairly little benefit. I think if someone is capable of building a package, we can probably safely assume that they can figure out how to install PkgTemplate or PkgDev and use that.

**Comment by rapus95** [comment]
I just realized that Pkg.jl is the wrong place for what I wanted. So I may change my opinion to prefer to remove generate from the Pkg.jl REPL entirely.
This is the IMO better approach I came up with: https://github.com/invenia/PkgTemplates.jl/issues/160

**Comment by KristofferC** [comment]
There is a barebone package generator here but the docstring contains a reference to PkgTemplates.
