### ISSUE TITLE
tree_hash of empty directories

### ISSUE THREAD

**Issue by cossio** [JuliaLang/Pkg.jl#1765]
The docs for Pkg.GitTools.tree_hash say that `... attempting to take the tree hash of an empty directory will throw an error.`. However I just tested `tree_hash` on empty directories and it seems to work fine. So either the doc string needs to be updated, or `tree_hash` is doing something unexpected on empty directories.

**Comment by StefanKarpinski** [comment]
Want to make a PR just deleting that sentence?

**Comment by fredrikekre** [comment]
> However I just tested tree_hash on empty directories and it seems to work fine.

Is that a "correct" hash though? I think it might just return garbage since it is not defined.

**Comment by StefanKarpinski** [comment]
I don't know where the idea that git can't hash empty trees came from. It ignores empty subtrees but it's perfectly possible to have the full tree be empty. See, e.g. https://stackoverflow.com/questions/9765453/is-gits-semi-secret-empty-tree-object-reliable-and-why-is-there-not-a-symbolic

**Comment by StefanKarpinski** [comment]
And yes, we give the correct hash value for the empty tree. I fixed this when I was adding that at a test case. Only the documentation needs to be fixed.

**Comment by cossio** [comment]
> Want to make a PR just deleting that sentence?

https://github.com/JuliaLang/Pkg.jl/pull/1770
