### ISSUE TITLE
Adding package in project overwrites dependency version used by other packages in the project

### ISSUE THREAD

**Issue by essenciary** [JuliaLang/Pkg.jl#1771]
Per the issue here: 
https://github.com/GenieFramework/Genie.jl/issues/226

The user had `SearchLightSQLite` which uses SQLite 0.9 as a dependency. Then the user installed `SQLite` at v 1.0.3. This caused other packages (namely `SearchLight` which uses `SearchLightSQLite`) to use `SQLite` v 1.0.3. This caused an error as the SQLite v1.x API is different than 0.x.

**Comment by KristofferC** [comment]
Yes, this is how things work. If `SearchLightSQLite` doesn't work with SQLitr v1 it shouldn't declare itself as compatible with it.

**Comment by essenciary** [comment]
But `SearchLightSQLite` didn't declare itself to be compatible with `SQLite` v1. It was compatible with `SQLite` 0.9.

**Comment by KristofferC** [comment]
Okay, then it would be good with a repro where the wrong version is installed.

**Comment by essenciary** [comment]
OK, I'll try to reproduce (meanwhile I updated SQLite to v1 as well).
