### ISSUE TITLE
Add package from link without REPL

### ISSUE THREAD

**Issue by azev77** [JuliaLang/Pkg.jl#1773]
The following works in repl:
`add https://github.com/Evovest/EvoTrees.jl`

The following does not:
`Pkg.add("https://github.com/Evovest/EvoTrees.jl")`

How can I add a package from a link w/o REPL?

**Comment by DilumAluthge** [comment]
```julia
Pkg.add(Pkg.PackageSpec(url = "https://github.com/Evovest/EvoTrees.jl"))
```

**Comment by azev77** [comment]
Thanks bro!
