### ISSUE TITLE
Feature Request: Pkg to notify user if latest version of a package cannot be installed

### ISSUE THREAD

**Issue by azev77** [JuliaLang/Pkg.jl#1774]
As discussed on [Discourse](https://discourse.julialang.org/t/julia-v1-4-0-has-been-released/36324/16?u=albert_zevelev):

I installed Julia 1.4.0, then rm -rf ~/.julia.
Next installed MLJ.jl, followed by Distributions.jl.
Here is the message I got:

(@v1.4) pkg> add Distributions
  Resolving package versions...
   Updating `~/.julia/environments/v1.4/Project.toml`
  [31c24e10] + Distributions v0.22.6
   Updating `~/.julia/environments/v1.4/Manifest.toml`
 [no changes]

Next when I check status:

(@v1.4) pkg> status
Status `~/.julia/environments/v1.4/Project.toml`
  [31c24e10] Distributions v0.22.6
  [add582a8] MLJ v0.10.1

It would be great if
1. Julia warns me when it adds a package which is not the latest or some kind of Pkg incompatability error as @tim.holy mentions:
`Note you have installed Distributions v0.22.6, not the latest 
Distributions v0.23.0 because it conflicts with MLJ v0.10.1.`  

2. Let Pkg.status() display two columns, the package I have & the latest version:
```
Package         Installed version	Latest version
Distributions   v0.22.6	                v0.23.0
MLJ             v0.10.1	                v0.10.1
```

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/Pkg.jl/issues/1774

**Comment by azev77** [comment]
@KristofferC 
I think we accidentally closed both issues, both this one 1774 & 1426

**Comment by KristofferC** [comment]
Sorry, I meant https://github.com/JuliaLang/Pkg.jl/issues/1655.
