### ISSUE TITLE
`pkg> instantiate` doesn't download artifacts

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/Pkg.jl#1775]
I now have a repo for this. Download [this](https://gist.github.com/davidanthoff/6f7a9f195de1c3c4e4108b925158017e) project into a folder. Make sure the NodeJS [artifacts](https://github.com/davidanthoff/NodeJS.jl/blob/master/Artifacts.toml) are not in your artifacts folder downloaded.

Then run `pkg> instantiate` on the project. The artifacts are not downloaded. If you then run `pkg> resolve`, they do get downloaded.

Tested on Julia 1.4.1 on Windows 10.

**Comment by fredrikekre** [comment]
See https://github.com/JuliaLang/Pkg.jl/issues/1338 which was supposedly fixed in https://github.com/JuliaLang/Pkg.jl/pull/1374

**Comment by davidanthoff** [comment]
That fix is in 1.4.1, right? If so, it didn’t fix the problem I’m reporting here.

**Comment by KristofferC** [comment]
Yeah, can repro. Looks bugged.

**Comment by KristofferC** [comment]
My guess is that it doesn't consider the active project as a package that can have artifacts. It only consider dependencies. Haven't verified though.

**Comment by fredrikekre** [comment]
It is a regular project, not a package.

**Comment by fredrikekre** [comment]
I think https://github.com/JuliaLang/Pkg.jl/blob/eff9f0194dd52ea2e09ff5ea11b1097035ffd5ff/src/Operations.jl#L598-L599 is the problem since we filter out all packages -- they are not instantiated yet!

**Comment by KristofferC** [comment]
> It is a regular project, not a package.

True, not sure what I was thinking...

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/1777

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/Pkg.jl/issues/1678.
