### ISSUE TITLE
[SOLVED] ERROR: failed to clone from https://github.com/JuliaRegistries/General.git

### ISSUE THREAD

**Issue by zenny** [JuliaLang/Pkg.jl#1811]
Hi,

OS: Voidlinux (rolling release). Julia installed is at v1.4.1
```
$ julia --version
julia version 1.4.1
```
However, whenever I try to do anything with pkg or jlpkg, It pops out an error as of below:

```
(@v1.4) pkg> update
    Cloning default registries into `~/.julia`
    Cloning registry from "https://github.com/JuliaRegistries/General.git"
ERROR: failed to clone from https://github.com/JuliaRegistries/General.git, error: GitError(Code:ERROR, Class:Invalid, invalid version 0 on git_proxy_options)
```
Any clue? Thanks and cheers,
/z

**Comment by zenny** [comment]
SOLVED by pulling the registry to ~/.julia/registries/General manually:

```
$ git clone https://github.com/JuliaRegistries/General.git ~/.julia/registries/General
```

**Comment by jtande** [comment]
My ubuntu 18.04 is behind proxy and this solution couldn't resolve the issue. This is the error I got
@v1.5) pkg> update
 Installing known registries into `~/.julia`
┌ Warning: could not download https://pkg.julialang.org/registries
└ @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Types.jl:951
┌ Warning: could not download https://pkg.julialang.org/registries
└ @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Types.jl:951
    Cloning registry from "https://github.com/JuliaRegistries/General.git"
ERROR: failed to clone from https://github.com/JuliaRegistries/General.git, error: GitError(Code:ERROR, Class:Net, SSL connections to proxy are not supported)

**Comment by StefanKarpinski** [comment]
What is your proxy setup? Unless we can reproduce it there is, unfortunately, little chance of improving this.

**Comment by jtande** [comment]
@StefanKarpinski  thanks for getting back. What I was missing was the proxy environment variable. I set it up using the site below
https://computingforgeeks.com/how-to-set-system-wide-proxy-on-ubuntu-debian/

**Comment by bokveizen** [comment]
> SOLVED by pulling the registry to ~/.julia/registries/General manually:
> 
> ```
> $ git clone https://github.com/JuliaRegistries/General.git ~/.julia/registries/General
> ```

Thank you! You are my hero
