### ISSUE TITLE
Add a addusing convenience function

### ISSUE THREAD

**Issue by yakir12** [JuliaLang/Pkg.jl#1812]
Very often I want to use a package immediately after adding it. A `Pkg.addusing` convenience function would be therefore nice. It adds a package and if successfully added, it `using` it.

**Comment by fredrikekre** [comment]
I don't like commands that do multiple things. The next guy might want to run tests just after adding, should we then add `addtest`?

**Comment by yakir12** [comment]
Agree. But it's all about how widespread the need for this might be. I mean, I could say that most functions do, at least at some level, multiple things. 
I can poll it somewhere and see how popular this is, or give it up. It's just a matter of convenience.

**Comment by KristofferC** [comment]
Yeah, this is a bit excessive heh. Something like a query about auto installation when `using` an uninstalled package might make sense though.
