### ISSUE TITLE
More helpful error messages if TOML files are corrupted

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/Pkg.jl#1818]
As already described in JuliaLang/TOML.jl#20, my `~/.julia/logs/manifest_usage.toml` somehow got corrupted. I managed to eventually track it down, but it wasn't a very fun experience. It would be great to provide more details on which file and which line is affected and some additional context on the specific entry affected. Maybe also some tips for how to fix this? This already came up in #1017, but as that is quite a long thread, I though it made sense to track this in a dedicated issue.

**Comment by StefanKarpinski** [comment]
Honestly, I think TOML needs a rewrite/redesign. On my todo list, but hasn't made it to the top yet.

**Comment by KristofferC** [comment]
Heh I was actually also thinking of just rewriting it...

**Comment by oxinabox** [comment]
A basic start is:
https://github.com/JuliaLang/Pkg.jl/pull/1832

**Comment by StefanKarpinski** [comment]
ok, but https://github.com/JuliaLang/julia/pull/36018
