### ISSUE TITLE
CREATING NEW LANGUAGES

### ISSUE THREAD

**Issue by taaehk** [JuliaLang/Pkg.jl#1825]
If you have a question please search or post to our Discourse site: https://discourse.julialang.org.
We use the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

All code cannot be read.
Do download sample items for new languages from:
https://alumniuitm.uitm.edu.my/read-blog/7
Click the: 'This items won't load right now' diplay ico.
thanks! 
"UiTM Languages"

**Comment by rfourquet** [comment]
Please clarify what the purpose of this issue is.

**Comment by taaehk** [comment]
Basic, all of julialang cannot be read. Try what i state above. Open using 'cmd'.
Then you know what is languages, and how for create it.

**Comment by rfourquet** [comment]
The website you link to doesn't seem related to Julia, how is this connected to `Pkg` ? I will close.
