### ISSUE TITLE
Use libCURL instead of platform engines

### ISSUE THREAD

**Issue by aviks** [JuliaLang/Pkg.jl#1830]
_This is very speculative, so mainly for brainstorming_

Currently HTTTP downloads within Pkg are done using the `PlatformEngines` subsystem, which shell out to locally installed commandline tools to perform the download. This generally means the `curl`/`wget`/`fetch` executables on unix and `PowerShell` on windows. This code is reasonably complex and difficult to maintain (I think)

In order to make things streamlined, one thought is to replace this with HTTP.jl. However, that is a large library, and splitting it will be some effort. 

Another idea is to use libCurl. 

* libCURL is *widely* used and *very* stable. Every car, phone and TV has multiple instances. 
* It's very efficient, in CPU and memory -- it can do multiple downloads simultaneously in async mode. 
* There is now a well maintained libCURL_jll, and the recent jll work on base julia makes it easy to pull in. One important feature here is that the jll correctly builds against the mbedTLS jll
* libCURL has http2 support (and ftp support and a dozen other protocols ...)

A few concerns, not insurmountable:

* libCURL has a low level C API. A higher level Julia API [needs to be written](https://curl.haxx.se/libcurl/c/libcurl-tutorial.html), ideally using the [multi-api](https://curl.haxx.se/libcurl/c/libcurl-multi.html). There are julia examples using the [easy api](https://github.com/JuliaWeb/LibCURL.jl#example-fetch-a-url)
* proxies (potentially authenticated)  need to be handled 
* root certificates needs to be handled

cc: @StefanKarpinski @staticfloat

**Comment by KristofferC** [comment]
Yeah, I have thought the exact same thing. It is also in the spirit of the artifact system in that it doesn't rely (too much) on the state of the user's system. I think this would be a good idea.

Tangentially, I think Cargo also uses libcurl.

**Comment by StefanKarpinski** [comment]
I spent a while yesterday looking at the libcurl multi API and it is... complicated. We can probably get this to work but figuring out how to make it work nicely with our event loop feels non-trivial.

**Comment by KristofferC** [comment]
I don't see why "our event loop" is relevant. Wouldn't we just call the multi API from a single-threaded synchronous Julia loop (as in https://ec.haxx.se/libcurl/libcurl-drive/libcurl-drive-multi).

**Comment by StefanKarpinski** [comment]
That `wait` call is blocking and we don't want to block all tasks.

**Comment by KristofferC** [comment]
Alright, so it is the socket system (https://ec.haxx.se/libcurl/libcurl-drive/libcurl-drive-multi-socket) that we need to use?

**Comment by StefanKarpinski** [comment]
Yes, the multi_socket API seems like it might be the right one. I'm still processing the docs on that one but it seems like the one we'd want to use (no blocking, maximum scalability).

**Comment by aviks** [comment]
There is an example of using libuv with the multi api, which might be instructive?  https://curl.haxx.se/libcurl/c/multi-uv.html

**Comment by aviks** [comment]
That example users `uv_run` which I'm hoping can be offloaded into a Task in Julia?

**Comment by StefanKarpinski** [comment]
Nice! Yes, I don't see any obviously blocking operations in that so it may well work.

**Comment by aviks** [comment]
A very old version of code using `curl_multi_perform` already exists, with polling using sleep/yield:

https://github.com/JuliaWeb/HTTPClient.jl/blob/master/src/HTTPC.jl#L623

**Comment by ViralBShah** [comment]
One of the issues with PlatformEngines is that you get different types of outputs on different platforms. Here's one from Alpine. I originally thought it was Pkg printing it.

![screen_shot_2020-06-27_at_4 50 57_pm](https://user-images.githubusercontent.com/744411/85951168-5510fe80-b92f-11ea-91be-c3c11705fbec.png)

**Comment by StefanKarpinski** [comment]
Yeah, it’s a mess. I’m working on using libcurl instead.

**Comment by musm** [comment]
Glad to see this issue tackled and I see there's already good progress being made by Stefan using LibCurl!

Shouldn't  this functionality should go in Base or and Stdlib so we can get rid of the shelling that the `download` function there uses and also suffers from the same problem.  There's an open issue discussing the future of download over at the Julia repo regarding this.
