### ISSUE TITLE
Add .jl editing automatically to Pkg URLs

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/Pkg.jl#1831]
At least consider it, or give a warning if you think might be a security issue:

```
(@v1.5) pkg> add https://github.com/zachmatson/ArgMacros
    Cloning git-repo `https://github.com/zachmatson/ArgMacros`
Username for 'https://github.com': PallHaraldsson
Password for 'https://PallHaraldsson@github.com': 
ERROR: failed to clone from https://github.com/zachmatson/ArgMacros, error: GitError(Code:ERROR, Class:Net, unexpected HTTP status code: 404)
```

People don't have to add registered packages that often, and we're used to add working either way, without (or with) .jl ending:

```
(@v1.5) pkg> add Revise.jl
```

**Comment by KristofferC** [comment]
I don't think completing a URL is a good idea. There might be (another) package at the `zachmatson/ArgMacros` URL but we do not allow `.jl` in package names so there is no risk for mix up there.

**Comment by PallHaraldsson** [comment]
Yes I thought so, and e.g. the other might exist as say C code, and .jl a wrapper for.

However, there there was no other package. I was thinking why is github suddenly asking for username (not all might realize why), and with no package I'm not sure it should. I quickly realized, but a warning, or less misleading action might help. I could make a PR (for a warning), unless actively not wanted.

**Comment by KristofferC** [comment]
I think you might just have to enter the URL properly when you want to download a package (or a file) from a URL.
