### ISSUE TITLE
revisiting elimination of version conflicts

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/Pkg.jl#1837]
I want to add (building as needed), precompile and use `ThisPkg`. I do not want to encounter "Unsatisfiable requirements" or version impediments from other packages.

Some of these other package driven conflicts can be resolved by providing more than one version of the other package[s] locally where doing so makes the trouble vanish. One situation in which that trouble does not vanish so easily is where there are multipath dependencies that ask for distinct versions of some other package.  Some of those conflicts can be resolved by allowing the more recent of the requested versions for _other package_ be used (supercede) in every circumstance where it specified e.g.
```
[versions]  
0.1~0.4        # version 0.4.2 can replace lower versions down to 0.1.0, 0.3.x ...
0.5~0.9        # version 0.9 can replace ... 
1              # versions 1.x.x cannot replace lower versions
```

And some more refined assistance for pkg devs to generate [versions] would be good.

**Comment by JeffreySarnoff** [comment]
Here is a current example of a solvable requirements "unsatisfiablity".
I add `Gnuplot` which causes  `↓ UnicodePlots v1.2.0 ⇒=> v1.1.0` -- and that is not ok with me. So I try adding back UnicodePlots v1.2.0, and this results:
```
    Cloning git-repo `https://github.com/Evizero/UnicodePlots.jl.git`
   Updating git-repo `https://github.com/Evizero/UnicodePlots.jl.git`
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package StatsBase [2913bbd2]:
 StatsBase [2913bbd2] log:
 ├─possible versions are: [0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.28.0-0.28.1, 0.29.0, 0.30.0, 0.31.0, 0.32.0-0.32.2, 0.33.0] or uninstalled
 ├─restricted to versions 0.33 by Gnuplot [dc211083], leaving only versions 0.33.0
 │ └─Gnuplot [dc211083] log:
 │   ├─possible versions are: 1.3.0 or uninstalled
 │   └─Gnuplot [dc211083] is fixed to version 1.3.0
 └─restricted to versions 0.32 by UnicodePlots [b8865327] — no versions left
   └─UnicodePlots [b8865327] log:
     ├─possible versions are: 1.2.0 or uninstalled
     └─UnicodePlots [b8865327] is fixed to version 1.2.0
```
So Gnuplot [compat] has StatsBase = "0.33.0" and UnicodePlots [compat] has StatsBase = "0.32.0"  and the current version of StatsBase is v"0.33.0".  StatsBase v0.33.0 changed the return types for `trim` and `windsor` to be iterators. That was the only change that, in the very specific case that `trim` or `windsor` is used, would break use of StatsBase v0.32. Neither Gnuplot.jl nor UnicodePlots.jl calls `trim` or `windsor`.  For that reason, (at least with these packages) it was not necessary to downgrade UnicodePlots, the current version would have been used appropriately in both packages.

**Comment by oxinabox** [comment]
this is a problem with Gnuplot.jl and UnicodePlots.jl specifying compat too tightly, they would probably apprecitate a PR to relax their compat bounds.

I don't think we want to live in a world where Pkg is made smart enough to reason about breaking changes by looking at the code that changed between versions and looking at  the functions that a package uses.

**Comment by JeffreySarnoff** [comment]
Are you suggesting we dumb down Pkg?  Its internal security may not allow that.

**Comment by KristofferC** [comment]
I don't really have any idea what this issue is about. In general it is good to be as specific as possible in issues. If this is something about automatically detecting what parts of a package another package uses, it is really out of scope for Pkg.

**Comment by JeffreySarnoff** [comment]
Yes .. it is about that. I am closing this.
