### ISSUE TITLE
registry containing a space cannot be removed

### ISSUE THREAD

**Issue by feanor12** [JuliaLang/Pkg.jl#1838]
I added a localregistry with LocalRegistry.jl.
I named it "My Registry" and I cannot remove it via the REPL

```
(@v1.4) pkg> registry remove "My Registry"
ERROR: `My Registry` cannot be parsed as a registry

(@v1.4) pkg> registry remove My Registry
registry `My` not found.
registry `Registry` not found.

(@v1.4) pkg> registry remove My\ Registry
ERROR: `My\` cannot be parsed as a registry

(@v1.4) pkg> registry status
Registry Status
 [23338594] General (https://github.com/JuliaRegistries/General.git)
 [97f9683e] My Registry (https://domain.com/gerrit/jl_registry)
```

Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)

**Comment by StefanKarpinski** [comment]
You can go into `~/.julia/registries` and delete it manually.

**Comment by feanor12** [comment]
I did that and it worked.
Still it should be possible to use the registry remove command provided by the REPL.

**Comment by StefanKarpinski** [comment]
How did you add it in the first place? This would require support for quoting registry names in REPL commands. Not sure that complication is worth it. You can’t have spaces in URLs either...

**Comment by KristofferC** [comment]
> This would require support for quoting registry names in REPL commands

Support for quoting REPL arguments is already there, see the error for

```
(@v1.4) pkg> registry remove "My Registry"
ERROR: `My Registry` cannot be parsed as a registry
```

The reason it  errors is just that we validate the registry name which I guess right now uses the same naming rule as a package?

**Comment by feanor12** [comment]
To create the registry I used https://github.com/GunnarFarneback/LocalRegistry.jl .
```julia
create_registry("My Registry","https://username@domain.com/gerrit/jl_registry")  
```

I then pushed it to the server, so I can add it by registry add "https://username@domain.com/gerrit/jl_registry"

**Comment by KristofferC** [comment]
I think using quotes here is fine. It mirrors very much how `rm` works in a terminal.
