### ISSUE TITLE
Problem with ZMQ and MbedTLS while installing IJulia - artifacts download?

### ISSUE THREAD

**Issue by Dareczin** [JuliaLang/Pkg.jl#1847]
Hi! I tried on profile of ZMQ and they told me to write here.

Hi!

I tried to google my problem and try couple of solutions to make IJulia works on windows 7. One of the problem is being unable to install ZMQ with this error massage. Same is for MbedTLS:

Exception setting "SecurityProtocol": "Cannot convert null to type "System.Net.
SecurityProtocolType" due to invalid enumeration values. Specify one of the fol
lowing enumeration values and try again. The possible enumeration values are "S
sl3, Tls"."
At line:1 char:35

[System.Net.ServicePointManager]:: <<<< SecurityProtocol =
CategoryInfo : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : PropertyAssignmentException
Exception calling "DownloadFile" with "2" argument(s): "Połączenie podstawowe z
ostało zakończone: Wystąpił nieoczekiwany błąd przy wysyłaniu."
At line:7 char:24

$webclient.DownloadFile <<<< ("https://github.com/JuliaBinaryWrappers/ZeroMQ_
jll.jl/releases/download/ZeroMQ-v4.3.2+3/ZeroMQ.v4.3.2.x86_64-w64-mingw32-cxx11
.tar.gz", "C:\Users\Amber\AppData\Local\Temp\jl_XRAl3wKibf-download.gz")
CategoryInfo : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : DotNetMethodException
ERROR: Unable to automatically install 'ZeroMQ' from 'C:\Users\Amber.julia\pack
ages\ZeroMQ_jll\uERLA\Artifacts.toml'
Stacktrace:
[1] error(::String) at .\error.jl:33
[2] ensure_artifact_installed(::String, ::Dict{String,Any}, ::String; platform:
:Pkg.BinaryPlatforms.Platform, verbose::Bool, quiet_download::Bool) at D:\buildb
ot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Artifacts.jl:8
94
[3] ensure_all_artifacts_installed(::String; platform::Pkg.BinaryPlatforms.Plat
form, pkg_uuid::Nothing, include_lazy::Bool, verbose::Bool, quiet_download::Bool
) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src
Artifacts.jl:958
[4] download_artifacts(::Pkg.Types.Context, ::Array{String,1}; platform::Pkg.Bi
naryPlatforms.Windows, verbose::Bool) at D:\buildbot\worker\package_win64\build
usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:616
[5] download_artifacts(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; p
latform::Pkg.BinaryPlatforms.Windows, verbose::Bool) at D:\buildbot\worker\packa
ge_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:595
[6] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}, ::Array{Base.UUI
D,1}; preserve::Pkg.Types.PreserveLevel, platform::Pkg.BinaryPlatforms.Windows)
at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Op
erations.jl:1091
[7] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; preserve::Pkg.Ty
pes.PreserveLevel, platform::Pkg.BinaryPlatforms.Windows, kwargs::Base.Iterators
.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at D:\buildbot\worker\pa
ckage_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\API.jl:159
[8] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at D:\buildbot\w
orker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\API.jl:112
[9] #add#27 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1
.4\Pkg\src\API.jl:109 [inlined]
[10] add(::Array{Pkg.Types.PackageSpec,1}) at D:\buildbot\worker\package_win64
build\usr\share\julia\stdlib\v1.4\Pkg\src\API.jl:109
[11] do_cmd!(::Pkg.REPLMode.Command, ::REPL.LineEditREPL) at D:\buildbot\worker
\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\REPLMode\REPLMode.jl:40
2
[12] do_cmd(::REPL.LineEditREPL, ::String; do_rethrow::Bool) at D:\buildbot\wor
ker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\REPLMode\REPLMode.jl
:380
[13] do_cmd at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1
.4\Pkg\src\REPLMode\REPLMode.jl:375 [inlined]
[14] (::Pkg.REPLMode.var"#24#27"{REPL.LineEditREPL,REPL.LineEdit.Prompt})(::REP
L.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at D:\buildb
ot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\REPLMode\REPLM
ode.jl:541
[15] #invokelatest#1 at .\essentials.jl:712 [inlined]
[16] invokelatest at .\essentials.jl:711 [inlined]
[17] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterfac
e, ::REPL.LineEdit.MIState) at D:\buildbot\worker\package_win64\build\usr\share
julia\stdlib\v1.4\REPL\src\LineEdit.jl:2354
[18] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at D:\buildbot\wo
rker\package_win64\build\usr\share\julia\stdlib\v1.4\REPL\src\REPL.jl:1055
[19] run_repl(::REPL.AbstractREPL, ::Any) at D:\buildbot\worker\package_win64\b
uild\usr\share\julia\stdlib\v1.4\REPL\src\REPL.jl:206
[20] (::Base.var"#764#766"{Bool,Bool,Bool,Bool})(::Module) at .\client.jl:383
[21] #invokelatest#1 at .\essentials.jl:712 [inlined]
[22] invokelatest at .\essentials.jl:711 [inlined]
[23] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at .\client.jl:367
[24] exec_options(::Base.JLOptions) at .\client.jl:305
[25] _start() at .\client.jl:484

My firewalls are down and its not helping. Also no antivirus is working. 

Trying to install normally or those pakages separatly is not working.

If anyone have and idea please share

**Comment by StefanKarpinski** [comment]
I'm getting a 403 forbidden on the URL that it's trying to download:

https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.2+3/ZeroMQ.v4.3.2.x86_64-w64-mingw32-cxx11.tar.gz

What command are you running when this happens?

**Comment by Dareczin** [comment]
Whole thing originally looks like that

julia> using Pkg

 

julia> Pkg.add("IJulia")

   Updating registry at `C:\Users\Amber\.julia\registries\General`

   Updating git-repo `https://github.com/JuliaRegistries/General.git`

  Resolving package versions...

Downloading artifact: MbedTLS

Exception setting "SecurityProtocol": "Cannot convert null to type "System.Net.

SecurityProtocolType" due to invalid enumeration values. Specify one of the fol

lowing enumeration values and try again. The possible enumeration values are "S

sl3, Tls"."

At line:1 char:35

+ [System.Net.ServicePointManager]:: <<<< SecurityProtocol =

    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException

    + FullyQualifiedErrorId : PropertyAssignmentException

 

Exception calling "DownloadFile" with "2" argument(s): "Połączenie podstawowe z

ostało zakończone: Wystąpił nieoczekiwany błąd przy wysyłaniu."

At line:7 char:24

+ $webclient.DownloadFile <<<< ("https://github.com/JuliaBinaryWrappers/MbedTLS

_jll.jl/releases/download/MbedTLS-v2.16.0+1/MbedTLS.v2.16.0.x86_64-w64-mingw32.

tar.gz", "C:\Users\Amber\AppData\Local\Temp\jl_6tKGq4nYtu-download.gz")

    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException

    + FullyQualifiedErrorId : DotNetMethodException

ERROR: Unable to automatically install 'MbedTLS' from 'C:\Users\Amber\.julia\pac

kages\MbedTLS_jll\hP8le\Artifacts.toml'

Stacktrace:

 [1] error(::String) at .\error.jl:33

 [2] ensure_artifact_installed(::String, ::Dict{String,Any}, ::String; platform:

:Pkg.BinaryPlatforms.Platform, verbose::Bool, quiet_download::Bool) at D:\buildb

ot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Artifacts.jl:8

94

 [3] ensure_all_artifacts_installed(::String; platform::Pkg.BinaryPlatforms.Plat

form, pkg_uuid::Nothing, include_lazy::Bool, verbose::Bool, quiet_download::Bool

) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\

Artifacts.jl:958

 [4] download_artifacts(::Pkg.Types.Context, ::Array{String,1}; platform::Pkg.Bi

naryPlatforms.Windows, verbose::Bool) at D:\buildbot\worker\package_win64\build\

usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:616

 [5] download_artifacts(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; p

latform::Pkg.BinaryPlatforms.Windows, verbose::Bool) at D:\buildbot\worker\packa

ge_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:595

 [6] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}, ::Array{Base.UUI

D,1}; preserve::Pkg.Types.PreserveLevel, platform::Pkg.BinaryPlatforms.Windows)

at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Op

erations.jl:1091

 [7] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; preserve::Pkg.Ty

pes.PreserveLevel, platform::Pkg.BinaryPlatforms.Windows, kwargs::Base.Iterators

.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at D:\buildbot\worker\pa

ckage_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\API.jl:159

 [8] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at D:\buildbot\w

orker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\API.jl:112

 [9] #add#27 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1

.4\Pkg\src\API.jl:109 [inlined]

 [10] add at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\

Pkg\src\API.jl:109 [inlined]

 [11] #add#24 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v

1.4\Pkg\src\API.jl:107 [inlined]

 [12] add at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\

Pkg\src\API.jl:107 [inlined]

 [13] add(::String; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTu

ple{(),Tuple{}}}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdl

ib\v1.4\Pkg\src\API.jl:106

 [14] add(::String) at D:\buildbot\worker\package_win64\build\usr\share\julia\st

dlib\v1.4\Pkg\src\API.jl:106

 [15] top-level scope at REPL[2]:1

 

julia>

And I cannot pass this, reinstalling everything always give the same result.

**Comment by StefanKarpinski** [comment]
There seems to be an issue where some download agents can download [this file](https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.0+1/MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz) while others can't. For example, `wget` can download it just fine whereas when I try using `curl -IL` I get a 403. @staticfloat, any idea why this would be different across different user agents?

**Comment by Dareczin** [comment]
Pkg > activate "an_empty_directory"
Pkg > add IJulia

is not working 

just downloading packages separatly? wgt is for linux only?

**Comment by fonsp** [comment]
This also happens when installing `HTTP` on Windows 7 with Julia v1.2:

([tested by zenon, originally posted here](https://github.com/fonsp/Pluto.jl/issues/147))

```
C:\test>mkdir xx

C:\test>cd xx

C:\test\xx>..\j.cmd
(v1.2) pkg> activate "."
Activating new environment at `C:\test\xx\Project.toml`

(xx) pkg> status
    Status `C:\test\xx\Project.toml`
  (empty environment)

(xx) pkg> add HTTP
  Updating registry at `C:\Users\zenon\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
┌ Warning: Some registries failed to update:
│     — C:\Users\zenon\.julia\registries\General — failed to fetch from repo
└ @ Pkg.Types C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\Types.jl:1171
 Resolving package versions...
  Updating `C:\test\xx\Project.toml`
  [cd3eb016] + HTTP v0.8.15
  Updating `C:\test\xx\Manifest.toml`
  [b99e7846] + BinaryProvider v0.5.10
  [cd3eb016] + HTTP v0.8.15
  [83e8ac13] + IniFile v0.5.0
  [739be429] + MbedTLS v0.7.0
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8ba89e20] + Distributed
  [b77e0a4c] + InteractiveUtils
  [8f399da3] + Libdl
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [de0858da] + Printf
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [8dfed614] + Test
  [4ec0a83e] + Unicode

(xx) pkg> build MbedTLS
  Building MbedTLS → `C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\build.log`
┌ Error: Error building `MbedTLS`:
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ [ Info: Downloading https://github.com/JuliaWeb/MbedTLSBuilder/releases/download/v0.17.0/MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz to C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\usr\downloads\Mb
edTLS.v2.16.0.x86_64-w64-mingw32.tar.gz...
│ ERROR: LoadError: Could not download https://github.com/JuliaWeb/MbedTLSBuilder/releases/download/v0.17.0/MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz to C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps
\usr\downloads\MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz:
│ ErrorException("")
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] #download#100(::Bool, ::typeof(BinaryProvider.download), ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\PlatformEngines.jl:619
│  [3] #download at .\none:0 [inlined]
│  [4] #download_verify#101(::Bool, ::Bool, ::Bool, ::typeof(download_verify), ::String, ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\PlatformEngines.jl:688
│  [5] #download_verify at .\tuple.jl:0 [inlined]
│  [6] #install#141(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::typeof(install), ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\Prefix.jl:314
│  [7] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\tuple.jl:0
│  [8] top-level scope at C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\build.jl:48
│  [9] include at .\boot.jl:328 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1094
│  [11] include(::Module, ::String) at .\Base.jl:31
│  [12] include(::String) at .\client.jl:431
│  [13] top-level scope at none:5
│ in expression starting at C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\build.jl:44
│ caused by [exception 1]
│
│ Stacktrace:
│  [1] error() at .\error.jl:42
│  [2] #download#100(::Bool, ::typeof(BinaryProvider.download), ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\PlatformEngines.jl:613
│  [3] #download at .\none:0 [inlined]
│  [4] #download_verify#101(::Bool, ::Bool, ::Bool, ::typeof(download_verify), ::String, ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\PlatformEngines.jl:688
│  [5] #download_verify at .\tuple.jl:0 [inlined]
│  [6] #install#141(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::typeof(install), ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\Prefix.jl:314
│  [7] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\tuple.jl:0
│  [8] top-level scope at C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\build.jl:48
│  [9] include at .\boot.jl:328 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1094
│  [11] include(::Module, ::String) at .\Base.jl:31
│  [12] include(::String) at .\client.jl:431
│  [13] top-level scope at none:5
│ Ausnahme beim Festlegen von "SecurityProtocol": "NULL kann aufgrund von ung�ltigen Enumerationswerten nicht in den Typ "System.Net.SecurityProtocolType" konvertiert werden. Geben Sie einen der folgenden
E
│ numerationswerte an, und versuchen Sie es erneut. M�gliche Enumerationswerte sind "Ssl3, Tls"."
│ Bei Zeile:1 Zeichen:35
│ + [System.Net.ServicePointManager]:: <<<< SecurityProtocol =
│     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
│     + FullyQualifiedErrorId : PropertyAssignmentException
│
│ Ausnahme beim Aufrufen von "DownloadFile" mit 2 Argument(en):  "Die Verbindung mit dem Remoteserver kann nicht hergestellt werden."
│ Bei Zeile:7 Zeichen:24
│ + $webclient.DownloadFile <<<< ("https://github.com/JuliaWeb/MbedTLSBuilder/releases/download/v0.17.0/MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz", "C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\usr
\
│ downloads\MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz")
│     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
│     + FullyQualifiedErrorId : DotNetMethodException
│
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\backwards_compatible_isolation.jl:647

```

**Comment by staticfloat** [comment]
@fonsp your issue is that you need to install some more software; read the Windows 7 instructions here: https://julialang.org/downloads/platform/#windows_7_windows_server_2012_installation_notes
