### ISSUE TITLE
Coverage miss on macros that work on functions

### ISSUE THREAD

**Issue by aminya** [JuliaLang/Pkg.jl#1866]
Coverage misses the first line of this function definition
```jl
# Union with Nothing
@transform function findcontent(::Type{UN{T}}, name::String, node::Node, argAmlType::Type{allsubtypes(AbsDocOrNode)}) where {T}
    return findcontent(T, name, node, argAmlType)
end
```
https://codecov.io/gh/aminya/AcuteML.jl/src/master/src/xmlutils/findcontent.jl#L45

Note: I am not sure if this is related to Pkg. https://github.com/JuliaCI/Coverage.jl/issues/275

**Comment by KristofferC** [comment]
The only thing Pkg does is to tell julia to run with coverage, it is Julia itself that generates all the coverage files. So this issue would be better for the Julia repo.

Also, as always, it is best if possible to try give a self contained example without references to packages.

**Comment by aminya** [comment]
Thanks. I created an issue here https://github.com/JuliaLang/julia/issues/36283
