### ISSUE TITLE
option to set `quiet_download=true`

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/Pkg.jl#1870]
It would be useful if there was a way to set `quiet_download=true` (e.g. via an environment variable). When used on slurm it generates very long output, e.g. https://gist.githubusercontent.com/climabot/5325d3dcfbf1ff1c1e0a92570a97944f/raw/42a018ce57b6cc2299349572f6d9aa8fdf206673/out_10011931

**Comment by simonbyrne** [comment]
It seems to be cause by `curl`: we've worked around it for now by using `.curlrc` file:
```
export CURL_HOME="$(pwd)"
printf -- "--silent\n--show-error\n" > "$CURL_HOME/.curlrc"
```

**Comment by KristofferC** [comment]
Perhaps we should only print it if it is to a TTY?

**Comment by simonbyrne** [comment]
That should work, since when I try running the script
```
#!/usr/bin/env bash
module load julia/1.4.2
julia -e '@show stdout stderr'
```
under `sbatch` it reports 
```
stdout = IOStream(<fd 10>)
stderr = IOStream(<fd 11>)
```

**Comment by KristofferC** [comment]
Actually we already did the `TTY` thing. We just failed to propagate it: https://github.com/JuliaLang/Pkg.jl/pull/2000.
