### ISSUE TITLE
[BUG] setting JULIA_PKG_SERVER as empty string in Julia 1.4

### ISSUE THREAD

**Issue by johnnychen94** [JuliaLang/Pkg.jl#1875]
This is only an issue for Julia 1.4, for Julia >= 1.5 unset it to `""` works normally because it checks `isempty` instead of `isnothing`:

https://github.com/JuliaLang/Pkg.jl/blob/3e3f9d7a3baf3a96c860d2b1bc895d5fd2d40d35/src/Pkg.jl#L24

Perhaps there's no need to fix this since the pkg server feature is opt-in in Julia 1.4, but still, I'd like to open this issue in case you're not aware of this.

```
julia> ENV["JULIA_PKG_SERVER"] = ""

(@v1.4) pkg> add ReferenceTests
    Cloning default registries into `tmp`
┌ Warning: malformed Pkg server value
│   server = "https:"
└ @ Pkg.PlatformEngines /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Pkg/src/PlatformEngines.jl:605
┌ Warning: malformed Pkg server value
```

**Comment by StefanKarpinski** [comment]
I agree that this should be considered a bug in 1.4 and fixed if there are any more 1.4 releases (there may not be).

**Comment by StefanKarpinski** [comment]
I would distinguish between `JULIA_PKG_SERVER` being set to the empty string and being unset. This works fine if you do `unset JULIA_PKG_SERVER` in the shell or `delete!(ENV, "JULIA_PKG_SERVER")`; it's only setting it to the empty string that's a problem.

**Comment by KristofferC** [comment]
Solution now is use 1.5.
