### ISSUE TITLE
Better printing of the Pkg LEGAL NOTICE 

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/Pkg.jl#1889]
Currently, the LEGAL NOTICE is printed as an Info message, and it is not formatted nicely on the screen. It would be nice to format it to be easier to read.

![screen_shot_2020-06-27_at_4 43 51_pm](https://user-images.githubusercontent.com/744411/85951339-86d69500-b930-11ea-98e1-24b8ea19036b.png)

**Comment by StefanKarpinski** [comment]
I’m not terribly adept at formatted output and mainly focused on satisfying the legal obligation of the GDPR and CCPA as advised by legal counsel for NumFocus, so if someone else wants to take a crack at making this message print out prettier, they’d be welcome to do so. Maybe using Markdown? Although it’s not a great reason to make Pkg depend on Markdown.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/Pkg.jl/blob/531861f6677f434f6d594212d1085ac5bc309328/Project.toml#L13

**Comment by StefanKarpinski** [comment]
Ah, we already depend on it. Cool, cool, cool. Not sure whether glad...

**Comment by Keno** [comment]
@eschnett points out on Twitter (https://twitter.com/eschnett/status/1279114578035605510) that the notice is easy to mistake for for log output. I agree. I think nicely formatted markdown with additional spaces and a centered title would go a long way to making it more obvious. Maybe we should even wait for a key stroke in interactive mode (maybe only in the repl mode, but not via `Pkg.`, such that scripts pasted into the REPL don't break). Once we have the REPL opt out (#1895), ideally also include that info at the end of the notice.

**Comment by Keno** [comment]
Also, maybe it should say "Privacy Notice" rather than "Legal Notice"?

**Comment by c42f** [comment]
> I think nicely formatted markdown with additional spaces and a centered title would go a long way to making it more obvious.

Like this output from TerminalLoggers.jl?

![terminal_logger](https://user-images.githubusercontent.com/601473/86499908-f76a2f80-bdd0-11ea-9fd4-6ecee0966c0d.png)

(TerminalLoggers.jl uses markdown processing for message strings; it seems to work pretty well so I've been considering putting it into the stdlib.)

**Comment by KristofferC** [comment]
Functionality removed.
