### ISSUE TITLE
Legal notice should have opt-out information

### ISSUE THREAD

**Issue by alhirzel** [JuliaLang/Pkg.jl#1898]
https://github.com/JuliaLang/Pkg.jl/blob/20f9b9e14ab59d81991b5984a2f9eb87d38b6230/src/PlatformEngines.jl#L855

The legal notice should be changed to include opt-out information in its text, rather than referencing a website which includes opt-out information. The opt-out process is not complicated enough to justify a hop to a website (especially after #1895). Additionally, if this process changes over time (i.e. between Pkg.jl versions), it may well be very much less painful to maintain this procedure as part of the Pkg.jl source code rather than the julialang.org website.

**Comment by KristofferC** [comment]
Not applicable anymore (functionality has been removed).
