### ISSUE TITLE
Storing Pkg telemetry ID on a machine that is isolated from the IP address of the submitting machine

### ISSUE THREAD

**Issue by dlakelan** [JuliaLang/Pkg.jl#1903]
When collecting Pkg telemetry, the machine storing the data should be placed behind a proxy, and should only receive the info about the Pkg NOT any information about the IP address of the submitting machine. This prevents the Julia project from having a database which could track individual users as they move from network to network, which could reveal sensitive location information. Particularly in the case where a breach of security occurs and a third party gets ahold of the database, there would be no way for them to identify locations or ip addresses associated with Pkg actions.

**Comment by fredrikekre** [comment]
https://github.com/JuliaPackaging/PkgServer.jl
