### ISSUE TITLE
"Downloading" artifact is not aligned

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#1910]
![bild](https://user-images.githubusercontent.com/1282691/86842948-3684d300-c0a6-11ea-8b01-106b8729cfd2.png)

:scream:

**Comment by DilumAluthge** [comment]
Also Building is not aligned with Installed

**Comment by fredrikekre** [comment]
I don't understand, the verbs are supposed to right align: https://github.com/JuliaLang/Pkg.jl/blob/20f9b9e14ab59d81991b5984a2f9eb87d38b6230/src/Types.jl#L1356-L1358

**Comment by DilumAluthge** [comment]
The first text after the verb is aligned. That is, the white text is aligned.

**Comment by KristofferC** [comment]
Actually this is correct.....
