### ISSUE TITLE
ArgumentError when import the HelloWorld Pkg

### ISSUE THREAD

**Issue by likanzhan** [JuliaLang/Pkg.jl#1911]
I tried to follow the Pkg [manual(https://github.com/JuliaLang/Pkg.jl/blob/master/docs/src/creating-packages.md) to create a simple Pkg.

When I imported the Pkg with the following function:

`julia> import HelloWorld`

I got the following error:

```
ERROR: ArgumentError: Package HelloWorld not found in current path:
- Run `import Pkg; Pkg.add("HelloWorld")` to install the HelloWorld package.
```

Any suggestions?

**Comment by johnnychen94** [comment]
You need to follow what the instructions say and run 

```julia
(@v1.5) pkg> generate HelloWorld
 Generating  project HelloWorld:
    HelloWorld/Project.toml
    HelloWorld/src/HelloWorld.jl

julia> cd("HelloWorld/")

(@v1.5) pkg> activate .
 Activating environment at `~/HelloWorld/Project.toml`

julia> import HelloWorld
[ Info: Precompiling HelloWorld [d2dbcb7b-1e4d-4a74-9d51-bccbfb1785af]
```

**Comment by likanzhan** [comment]
I see. Thanks. 
It seems that I forgot the  period mark `.` when activating the package.
