### ISSUE TITLE
Artifact macro not working with variable in Julia 1.3

### ISSUE THREAD

**Issue by racinmat** [JuliaLang/Pkg.jl#1912]
Following code is broken in Julia 1.3, works with Julia 1.4.
```julia
using Pkg.Artifacts
version = "1996l" # can be other, e.g.g 2020a
@artifact_str "tzdata_$version"
```
in Julia 1.3, it complains that version variable is not known.
I use this sometimes when I have lots of artifacts and they are meant to be accessible through variable, e.g. in https://github.com/JuliaTime/TimeZones.jl which I'm migrating to artifacts.

**Comment by fredrikekre** [comment]
1.3 is EOL so nothing to do here really except upgrading to 1.4.
