### ISSUE TITLE
Hard to see terminal font color

### ISSUE THREAD

**Issue by pauljurczak** [JuliaLang/Pkg.jl#1915]
I use a light theme for my terminals. `pkg> status` lists package names in a very bright color, which is almost invisible (see bottom of screen capture below). `pkg> add` uses perfectly readable color for package names (see top of the picture). 

![julia1](https://user-images.githubusercontent.com/4933032/86984499-fd06a300-c14b-11ea-88e6-98f93fc17c54.png)

Can you use that color for `pkg> status` too?

**Comment by dpo** [comment]
I also have this issue. I switch between a light and a dark theme. With the light theme, the package names are not readable. And with the dark theme, the sha between brackets is not readable.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/2521 should fix the light theme.
