### ISSUE TITLE
Can we have docstring for Pkg.generate()?

### ISSUE THREAD

**Issue by anandijain** [JuliaLang/Pkg.jl#1917]
I think it'd be nice to have a docstring for `Pkg.generate()`

I don't know the standards for writing docstrings (why I submitted issue not PR), but something like:

```julia
Pkg.generate(...)

Creates a new project with the following files (visualized with the external tree command):

shell> tree .
.
├── YourPkg
│   ├── Project.toml
│   └── src
│       └── YourPkg.jl

1 directory, 2 files
```

**Comment by KristofferC** [comment]
Might be better off just using https://github.com/invenia/PkgTemplates.jl.

**Comment by StefanKarpinski** [comment]
I think we should deprecate it or delete it.

**Comment by DilumAluthge** [comment]
> I think we should deprecate it or delete it.

Correct.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/1496

I don't remember now why I closed it.

**Comment by anandijain** [comment]
Thanks, `PkgTemplates` seems to have a lot of functionality!

I agree with [this comment in #1496](https://github.com/JuliaLang/Pkg.jl/pull/1496#issuecomment-584560730), that it would be nice to still have REPL functionality. 

Any way to have best of both worlds?

**Comment by DilumAluthge** [comment]
PkgTemplates has an interactive wizard.

If someone wants additional REPL functionality beyond what is available in PkgTemplates, I'm sure that Chris would be happy to accept pull requests to enhance PkgTemplates. Alternatively, someone could make a new package that implemented the REPL functionality.

The ReplMaker package may be helpful for building REPL functionality.

Anyway, I don't think this functionality needs to live in Pkg.

@StefanKarpinski I'll make a new PR to deprecate `Pkg.generate`.
