### ISSUE TITLE
Create and export Version module

### ISSUE THREAD

**Issue by mattBrzezinski** [JuliaLang/Pkg.jl#1919]
I've ran across this problem a few times now where I needed to create a workaround for one of my dependencies in my package. There are times where I am unable to update to a newer version of the dependency, so instead I leave a comment in my code and log a Git issue. However, as time goes on I might be forgetful and not remember to properly fix the issue.

I recently started to dig around `Pkg.jl` and found a nice way to handle this by creating a test which will fail when 

```julia
using Pkg
using Pkg.Types: intersect, semver_spec, VersionSpec
using Test

@testset "Broken Package" begin
    # Link to Git Issue #123

    broken_version = VersionSpec("0.1")
    toml = Pkg.TOML.parsefile(joinpath(@__DIR__, "..", "Project.toml"))

    pkg_versions = toml["compat"]["Package"]
    pkg_versions = semver_spec(pkg_versions)  # Calculate the range of available versions

    @test_broken isempty(intersect(broken_version, pkg_versions))
end
```

This way, when I finally get around to update and dropping this version of a package. I can be reminded to go back and update the work-around code. However, this feels "hacky" in a sense since I'm gaining access to these functions via the `Types` which is `including("versions.jl")`.

Would it be possible to create a `module Versions` and `export` it to make this more "official"?

**Comment by KristofferC** [comment]
There is now a `module Versions` (will be in Julia 1.7) but I don't want to export it because we need the freedom to tweak things in possibly backwards incompatible ways.
