### ISSUE TITLE
less subtlety when downgrading a package

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/Pkg.jl#1927]
I did `Pkg.add(Winston)` and was surprised when `Compat` stopped containing functionality I'd expected there. Looking back very closely, I noticed:
```
  [34da2185] ↓ Compat v3.13.0 ⇒ v2.2.0
```

But that's quite subtle! Can we print a warning message at the bottom in bold:

```
Downgraded 4 packages while installing to satisfy version bounds.
```

**Comment by KristofferC** [comment]
It shows downgraded packages in a different color:

![bild](https://user-images.githubusercontent.com/1282691/87443258-89561180-c5f5-11ea-91a0-47a9448f2612.png)

**Comment by KristofferC** [comment]
The red stuff feels non-subtle enough.

**Comment by vtjnash** [comment]
Red means "no change" though?

**Comment by fredrikekre** [comment]
No the red is deleted, purple is downgrade.

**Comment by ptoche** [comment]
In the Julia REPL, where I set my Profiles to "Ocean Default",  I get these colours, which make it a lot easier to spot downgrades. However, it would still be nice to have a warning or maybe even an interactive `yes/no` request with "are you sure you want to proceed?". 

<img width="623" alt="a" src="https://user-images.githubusercontent.com/6339274/119744980-0d963980-be42-11eb-869d-6554f6a20473.png">

**Comment by xgdgsc** [comment]
Is it possible to make it stop if there are packages need to downgrade, unless a `-f/--force` flag is added to make it more clear?
