### ISSUE TITLE
Feature Request: support String interpolation for `@artifact_str`

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/Pkg.jl#1929]
I find `@artifact_str` does not support string interpolation, which is quite inconvenient when the artifact name is related to a version, e.g the Julia version, so I cannot directly use `artifact"name-$VERSION"` to download the lazy artifact and get its path. So it would be nice if we could support this.

**Comment by fredrikekre** [comment]
Why not just use `@artifact_str("name-$VERSION")`?

**Comment by staticfloat** [comment]
This isn't a problem with Pkg; this is a basic language limitation; string interpolation does not happen within string macros:

```
julia> macro foo_str(ex)
       return ex
       end
@foo_str (macro with 1 method)

julia> foo"a $b"
"a \$b"
```

**Comment by fredrikekre** [comment]
> This isn't a problem with Pkg; this is a basic language limitation; string interpolation does not happen within string macros:

Right, but some string macros implement it, but I don't think it is needed here.
