### ISSUE TITLE
Strange error message from Pkg.add

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/Pkg.jl#1935]
I tried to add a package via an http url, and I received the error message below:

```Julia
(@v1.5) pkg> add https://kristofferc.github.io/JuAFEM.jl
ERROR: Unable to parse `hub.io/JuAFEM.jl` as a package.
```

This error message is strange. It seems that something cuts the name `github` into two. Maybe there is a regex that looks for `.git` which misfires here?

This is Julia 1.5.0-rc2.

Don't mind the actual url; it's wrong, the package lives elsewhere. But the error message should have been different. I expect to see something like "no git repo lives there".

**Comment by barucden** [comment]
That is perhaps due to the regex for URLs:

https://github.com/JuliaLang/Pkg.jl/blob/4270a54130d70a3b93419d4ce6908f0d999bec59/src/REPLMode/argument_parsers.jl#L27

It might help to add `$` to the regex leading to 
```
((git|ssh|http(s)?)|(git@[\w\-\.]+))(:(//)?)([\w\.@\:/\-~]+)(\.git$)(/)?
                                                          [here]--^
```
. What do you think?

**Comment by fredrikekre** [comment]
Looks reasonable. Do you want to make a PR?

**Comment by barucden** [comment]
@fredrikekre done
