### ISSUE TITLE
Add a way to check for updates

### ISSUE THREAD

**Issue by Vexatos** [JuliaLang/Pkg.jl#1937]
On some systems, particularly on Windows, updating packages can take a long time (up to multiple hours), especially with larger applications that have large dependencies (ours has over a gigabyte of dependencies in total). In many situations, it is a good idea to check for updates first before applying them, just to see what needs to be done, allowing one to plan for the update and allocate time for it. In early versions of Julia, we used to take git hashes and compare them to hashes of the public repo to see whether an update was available, but this was unreliable and only worked until Julia stopped cloning entire git repos in favour of only the latest trees. Since then, we used to run and parse the output of `Pkg.update(; preview=true)`, but that was removed in #1367. It would be nice to have a stable and fast way to check which packages need updates without actually applying them / downloading anything.

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/Pkg.jl/issues/1945

**Comment by Vexatos** [comment]
I do not believe it is a duplicate. #1945 is requesting a preview of `Pkg.add` that asks the user for confirmation before applying a change, while in this issue I suggest a pure preview, without any need for user input. Our update system is automated and cannot interact with the user, which is why such a confirmation prompt wouldn't work. Ideally, it could even be supplied as an easily parseable list or dict of packages which require updating.

**Comment by KristofferC** [comment]
They are small tweaks of each other so they can be tracked via the same issue. Perhaps you can add your comment to that issue?
