### ISSUE TITLE
Pkg.instantiate calls update_registries even if update_registry=false

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/Pkg.jl#1939]
here:
https://github.com/JuliaLang/Pkg.jl/blob/20f9b9e14ab59d81991b5984a2f9eb87d38b6230/src/API.jl#L833

cc: @StefanKarpinski

**Comment by KristofferC** [comment]
Seems like this option was added here https://github.com/JuliaLang/Pkg.jl/commit/10b161a0d55a43259de68a987b6a7c9eb425612f#diff-47db2d66769667be0982a7b56891b4a8R460.

I don't really understand the point of it though...

**Comment by StefanKarpinski** [comment]
cc @00vareladavid: can you comment on if that was intentional or accidental?
