### ISSUE TITLE
Malformed UUID aborts julia

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaLang/Pkg.jl#1946]
I had made a mistake by moving a dependency from `[deps]` to `[extras]` and the last character of the UUID was missing.

Upon activating the environment I got an error with
```
ArgumentError: Malformed UUID string: "77ba4419-2d1f-58cd-9bb1-8ffee604a2e"
```
And then julia quit. It would be nice, if it kept the session running and just refused to activate the environment.

**Comment by StefanKarpinski** [comment]
It definitely should straight quit Julia.

**Comment by KristofferC** [comment]
*shouldn't

**Comment by StefanKarpinski** [comment]
😂 yes, I fat fingered that one: shouldn't. (Edited above)

**Comment by fredrikekre** [comment]
I can't reproduce the crashing.

> It would be nice, if it kept the session running and just refused to activate the environment.

This is what happens for me.

**Comment by KristofferC** [comment]
Yeah, I don't see how julia aborting would happen. It's not like we call exit anywhere.
