### ISSUE TITLE
better API for generating artifact from tarball URL

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/Pkg.jl#1950]
It would be nice to have a function like
```julia
add_artifact!(artifact_toml::String, name::String, tarball_url::String; platform=nothing, lazy=false)
```
in Pkg.Artifacts, which would automatically download a tarball from `url`, generate all the needed hashes, and add an artifact with the given `name` to `artifact_toml`, optionally specifying a specific platform and whether the artifact should be lazy. BinaryBuilder already does all this, but I think it would be a pretty nice QOL improvement for shipping artifacts independent of BinaryBuilder.

**Comment by KristofferC** [comment]
https://github.com/simeonschaub/ArtifactUtils.jl solves this imo.
