### ISSUE TITLE
Pkg operations for dev producing _git2_axxxx files

### ISSUE THREAD

**Issue by musm** [JuliaLang/Pkg.jl#1964]
There's a lot of random `_git2_a10552` and similar files when I dev packages or clone them from github living in the repo directory. It looks like some operations are not gracefully cleaning up  intermediate files. This appears on Windows.

**Comment by fredrikekre** [comment]
Looks to be fixed in libgit2 v1: julia> f.(eachcol(x_traj))
3-element Array{Array{Int64,1},1}:
 [3, 1]
 [7, 1]
 [11, 1]
