### ISSUE TITLE
command spellings

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/Pkg.jl#200]
I kind of threw in a bunch of different spellings of commands for kicks, including some symbols (`+`, `-`, `/`, `?`), but we should decide on which ones we actually want. Do we want to keep one short and one long for each command? Keep the symbols or ditch them?

**Comment by KristofferC** [comment]
`?` for help seems ok but `+` and `-` are perhaps excessive since the commands themselves are short

**Comment by StefanKarpinski** [comment]
Agree. There's still the issue of aliases like `rm` and `remove` which are fine most of the time but become needless clutter when tab completing for example. It seems silly when someone types `r<tab>` to list both `rm` and `remove` when they do the same thing.

**Comment by pfitzseb** [comment]
Imho there's no real need for the short forms when autocomplete works.

**Comment by StefanKarpinski** [comment]
I strongly prefer the shorter forms. If anything, I'd be more in favor of _only_ having the short forms.

**Comment by KristofferC** [comment]
```
    "help"      => CMD_HELP,
    "?"         => CMD_HELP,
    "st"        => CMD_STATUS,
    "add"       => CMD_ADD,
    "rm"        => CMD_RM,
    "up"        => CMD_UP,
    "test"      => CMD_TEST,
    "gc"        => CMD_GC,
    "preview"   => CMD_PREVIEW,
    "init"      => CMD_INIT,
    "build"     => CMD_BUILD,
    "pin"       => CMD_PIN,
    "free"      => CMD_FREE,
    "develop"   => CMD_DEVELOP,
    "generate"  => CMD_GENERATE,
```
?

**Comment by StefanKarpinski** [comment]
Yes, but `dev` and `gen` instead as well 😬

**Comment by StefanKarpinski** [comment]
The only one that's a bit _too_ short is `st` for `status` but I use that alias all the time for git so it's hard to imagine having to type `status` all the time.

**Comment by pfitzseb** [comment]
You *could* just write `s\tab` though :)

**Comment by KristofferC** [comment]
> Yes, but `dev` and `gen` instead as well 

plzno

**Comment by StefanKarpinski** [comment]
The only reason to have the short versions is for people who prefer typing a short name to tab completion (which e.g. I strongly do) and the main issue is double listing in the tab completion UI. Perhaps the solution is to only list long names when doing tab completion unless the only viable completions are abbreviations.
