### ISSUE TITLE
Could not parse compatibility version for dependency, invalid version specifier

### ISSUE THREAD

**Issue by mohamed-barakat** [JuliaLang/Pkg.jl#2004]
I get the following error
```
ERROR: Could not parse compatibility version for dependency `Singular`
...
invalid version specifier: 0.4-0
```
while [building the documentation with Github actions](https://github.com/homalg-project/HomalgProject.jl/runs/1069374496). However, the range in the [Project.toml](https://github.com/homalg-project/HomalgProject.jl/blob/v0.5.0/Project.toml#L17)  is valid [https://julialang.github.io/Pkg.jl/v1/compatibility/#Version-specifier-format-1] and passes the [test](https://github.com/homalg-project/HomalgProject.jl/actions/runs/238467725).

**Comment by fredrikekre** [comment]
You need Julia >= 1.4 for that syntax.

**Comment by mohamed-barakat** [comment]
Thank you very much
