### ISSUE TITLE
Pkg server does not reflect newly added packages in GitHub Actions?

### ISSUE THREAD

**Issue by tkf** [JuliaLang/Pkg.jl#2011]
Trying to install Aqua v0.4.7 in GitHub Actions currently fails with

> ```
> ERROR: Unsatisfiable requirements detected for package Aqua [4c88cf16]:
>  Aqua [4c88cf16] log:
>  ├─possible versions are: [0.1.0, 0.2.0, 0.3.0, 0.4.0-0.4.6] or uninstalled
>  └─restricted to versions 0.4.7-0.4 by an explicit requirement — no versions left
> ```
> 
> --- https://github.com/JuliaFolds/BangBang.jl/runs/1083743216#step:5:7

even though Aqua v0.4.7 is registered 4 hours ago (as of writing) https://github.com/JuliaRegistries/General/pull/21018

For now, I'm working around this by setting `JULIA_PKG_SERVER=""` but it'd be nice if the packages can be accessed through Pkg server soon after it is registered.  Strangely, I cannot reproduce this in `docker run -i -t --rm julia:1.5` (i.e., `]add Aqua` installs Aqua 0.4.7).

**Comment by DilumAluthge** [comment]
Yeah this is an ongoing issue.

@staticfloat @StefanKarpinski Any updates on the registry latency?

**Comment by DilumAluthge** [comment]
Related discussions:
1. https://github.com/JuliaRegistries/General/issues/16777
2. https://github.com/JuliaPackaging/PkgServer.jl/issues/60

**Comment by DilumAluthge** [comment]
It's pretty common for people to report delays on the order of four hours.

**Comment by tkf** [comment]
Thanks for the pointers! I didn't think of searching elsewhere. Please feel free to close this one if it's better to track in other repos.

**Comment by StefanKarpinski** [comment]
The storage server delay is already much better than it was but occasionally it gets slammed with some large commit. I'm not sure what all we can do aside from make the storage server processing faster, which there are plans for but they haven't been implemented yet. Perhaps GitHub Actions should always directly clone the general registry? That way it will always be looking at the latest versions of everything. If the pkg server can't serve them, they will be cloned directly from GitHub (or wherever).

**Comment by tkf** [comment]
> Perhaps GitHub Actions should always directly clone the general registry?

Ah, so I guess it's better than `JULIA_PKG_SERVER=""` because Pkg.jl first tries to connect to the package server and it can send the request metadata (when it's done by default)?

**Comment by tkf** [comment]
What is the best way to do this? Something like this?

`JULIA_PKG_SERVER="" julia -e 'using Pkg; VERSION >= v"1.5-" && !isdir(joinpath(DEPOT_PATH[1], "registries", "General")) && Pkg.Registry.add("General")'`

**Comment by StefanKarpinski** [comment]
That seems like it would work, yes.

**Comment by tkf** [comment]
Thanks!  I implemented the idea in https://github.com/julia-actions/julia-runtest/pull/17

---

Just as a record, the package information was not reflected to the Pkg server accessed from GitHub Actions at least 9 hours after registration:

```
2020-09-08T07:10:43.3719258Z ┌ Error: Pkg.Resolve.ResolverError("Unsatisfiable requirements detected for package Aqua [4c88cf16]:\n Aqua [4c88cf16] log:\n ├─possible versions are: [0.1.0, 0.2.0, 0.3.0, 0.4.0-0.4.6] or uninstalled\n └─restricted to versions 0.4.7-0.4 by an explicit requirement — no versions left", nothing)
2020-09-08T07:10:43.3719838Z └ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:1427
2020-09-08T07:10:44.6040181Z ERROR: Unsatisfiable requirements detected for package Aqua [4c88cf16]:
2020-09-08T07:10:44.6040816Z  Aqua [4c88cf16] log:
2020-09-08T07:10:44.6041847Z  ├─possible versions are: [0.1.0, 0.2.0, 0.3.0, 0.4.0-0.4.6] or uninstalled
2020-09-08T07:10:44.6042649Z  └─restricted to versions 0.4.7-0.4 by an explicit requirement — no versions left
```

https://github.com/JuliaFolds/BangBang.jl/pull/201/checks?check_run_id=1084577964#step:5:7

while Aqua 0.4.7 is registered at 2020-09-07T21:58 https://github.com/JuliaRegistries/General/pull/21018#event-3738451058

Also, GitHub Actions is using us-east.pkg.julialang.org (https://github.com/JuliaFolds/BangBang.jl/runs/1087912291#step:3:7). I couldn't get the same behavior probably because my laptop uses us-west.pkg.julialang.org.

**Comment by fredrikekre** [comment]
`us-east` seem to be the least reliable so that's unfortunate.
