### ISSUE TITLE
Feature request: `registry update` does not fix a broken registry

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/Pkg.jl#2017]
One of our students had a broken registry: the folder `~/.julia/registries/General` was missing the `A` through `F` subfolders (not sure why), but running `registry update` did not fix it. 

The solution was to delete the folder manually, but would it be possible for `registry update` to do an integrity check? ~Or could we add a new method to reset a registry?~

**Comment by fonsp** [comment]
Sorry I just realised that `registry remove General` will reset it :)

**Comment by fredrikekre** [comment]
Windows presumably?

**Comment by ThirdEyeSqueegee** [comment]
> 
> 
> Windows presumably?

Yes!

**Comment by KristofferC** [comment]
>  unless the user is sustaining a non-tarball registry

This should only be the case if one is using git.

So I think this can be closed.
