### ISSUE TITLE
Migrate from Travis-CI.org to Travis-CI.com

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/Pkg.jl#2030]
Currently, Pkg.jl uses Travis-CI.org.

Travis-CI.org will be shut down on December 31, 2020: https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=%5BUNIQID%5D

Therefore, before then, we need to migrate from Travis-CI.org to Travis-CI.com.

The migration needs to be performed by a user that is an `owner` of the relevant GitHub organization, which in this case is JuliaLang.

Instructions for migration are available here: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by DilumAluthge** [comment]
cc: @StefanKarpinski @ViralBShah

**Comment by ViralBShah** [comment]
cc @KristofferC

**Comment by ViralBShah** [comment]
@DilumAluthge Also invited you as JuliaLang owner, if you could address this.

**Comment by fredrikekre** [comment]
Done.
