### ISSUE TITLE
Package Pkg not found in current path AppVeyor julia Nightly

### ISSUE THREAD

**Issue by saersamani** [JuliaLang/Pkg.jl#2032]
Hi, 

When I test my code with CI systems such as AppVeyor, I get the below error for julia nightly. The error is independent from the operative system. Please note that I do not get this error with julia 1.

Thanks. 
Saer

**Code:**

"@testset "Dependency Check" begin

    using Pkg

    if in("MS_Import",keys(Pkg.installed()))
        @eval using MS_Import
    else
        @warn("MS_Import is being installed")
        Pkg.add(PackageSpec(url="https://bitbucket.org/SSamanipour/ms_import.jl/src/master/"))
        using MS_Import
    end

    path=""
    filenames=["test_chrom.mzXML"]
    mz_thresh=[0,600]

    chrom=import_files(path,filenames,mz_thresh)
    @test size(chrom["MS1"]["Rt"],1) == 43
end"

**Error:** 
 
Testing Running tests...
Checking Depenedencies: Error During Test at C:\projects\compcreate-jl\test\runtests.jl:15
  Got exception outside of a @test
  ArgumentError: Package Pkg not found in current path:
  - Run `import Pkg; Pkg.add("Pkg")` to install the Pkg package.
  
  Stacktrace:
   [1] require(into::Module, mod::Symbol)
     @ Base .\loading.jl:803
   [2] top-level scope
     @ C:\projects\compcreate-jl\test\runtests.jl:18
   [3] top-level scope
     @ D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Test\src\Test.jl:1113
   [4] top-level scope
     @ C:\projects\compcreate-jl\test\runtests.jl:18
   [5] include(fname::String)
     @ Base.MainInclude .\client.jl:444
   [6] top-level scope
     @ none:6
   [7] eval(m::Module, e::Any)
     @ Core .\boot.jl:360
   [8] exec_options(opts::Base.JLOptions)
     @ Base .\client.jl:261
   [9] _start()
     @ Base .\client.jl:485
Test Summary:          | Error  Total
Checking Depenedencies |     1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
in expression starting at C:\projects\compcreate-jl\test\runtests.jl:15
ERROR: Package CompCreate errored during testing
Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Types.jl:52
 [2] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing)
   @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Operations.jl:1580
 [3] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, test_fn::Nothing, julia_args::Cmd, test_args::Cmd, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Pkg.API D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:327
 [4] #test#62
   @ D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:67 [inlined]
 [5] test(; name::Nothing, uuid::Nothing, version::Nothing, url::Nothing, rev::Nothing, path::Nothing, mode::Pkg.Types.PackageMode, subdir::Nothing, kwargs::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:coverage,), Tuple{Bool}}})
   @ Pkg.API D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:80
 [6] top-level scope
   @ none:1

**Comment by fredrikekre** [comment]
You need to add Pkg as a (test) dependency if you want to use it.
As a sidenote; you generally shouldn't run Pkg operations from inside the testscript.

**Comment by saersamani** [comment]
I changed the code as following. However, I still get the same error. 

**code** 

using CompCreate
using Test
using JLD
using CSV
using DataFrames
using HDF5
using Pkg


if in("MS_Import",keys(Pkg.installed()))
    @eval using MS_Import
else
    @warn("MS_Import is being installed")
    Pkg.add(PackageSpec(url="https://bitbucket.org/SSamanipour/ms_import.jl/src/master/"))
    using MS_Import
end





@testset "Checking Depenedencies" begin
    #using Base


    path=""
    filenames=["test_chrom.mzXML"]
    mz_thresh=[0,600]

    chrom=import_files(path,filenames,mz_thresh)

    d=load("test_chrom.jld")
    d1=load("AUX_data.jld","AUX_data")
    #println(pwd())
    feature_list = CSV.File("test_chrom_report.csv") |> DataFrame!



    @test chrom["MS1"]["Rt"][1] == 0.02
    @test size(d1["Iso"]["ru_m"],1) == 6
    @test feature_list[!,"Nr"][1] == 1

end



**config**
Build started
git clone -q --branch=master https://bitbucket.org/SSamanipour/compcreate.jl.git C:\projects\compcreate-jl
git checkout -qf 0224c917419218406528e1238ebc44bb5fa442a8
Running Install scripts
iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))
Installing Julia...
Julia Version 1.6.0-DEV.1001
Commit 46cf572773* (2020-09-22 12:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)
Environment:
  JULIA_PROJECT = @.
  JULIA_VERSION = nightly
echo "%JL_BUILD_SCRIPT%"
"using Pkg; Pkg.build()"
C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"
 Installing known registries into `C:\Users\appveyor\.julia`
      Added registry `General` to `C:\Users\appveyor\.julia\registries\General`
  Installed Glob ──────────────────────── v1.3.0
  Installed ProgressBars ──────────────── v0.7.1
  Installed Showoff ───────────────────── v0.3.1
.
.
.

  Testing Running tests...
ERROR: LoadError: ArgumentError: Package Pkg not found in current path:
- Run `import Pkg; Pkg.add("Pkg")` to install the Pkg package.
Stacktrace:
 [1] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:803
 [2] include(fname::String)
   @ Base.MainInclude .\client.jl:444
 [3] top-level scope
   @ none:6
in expression starting at C:\projects\compcreate-jl\test\runtests.jl:9
ERROR: Package CompCreate errored during testing
Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Types.jl:52
 [2] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing)
   @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Operations.jl:1580
 [3] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, test_fn::Nothing, julia_args::Cmd, test_args::Cmd, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Pkg.API D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:327
 [4] #test#62
   @ D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:67 [inlined]
 [5] test(; name::Nothing, uuid::Nothing, version::Nothing, url::Nothing, rev::Nothing, path::Nothing, mode::Pkg.Types.PackageMode, subdir::Nothing, kwargs::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:coverage,), Tuple{Bool}}})
   @ Pkg.API D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:80
 [6] top-level scope
   @ none:1

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
