### ISSUE TITLE
[FR] Quiet environment setup

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/Pkg.jl#2036]
I wonder if it would make sense to have an option for quiet environment setup in projects. Currently, whenever we activate, instantiate, precompile an environment in the beginning of a script, we get information messages sent to stdout. It is fine when you only have one worker process, but when the script is being executed on a computer cluster with say 100 processes, it is a lot as each worker prints the same information.

I am considering using Supressor.jl to deal with this verbose printing, but would like to ask here if it makes sense to make this a feature of the package manager, something like an option `Pkg.setup(verbose=false)`.

**Comment by fredrikekre** [comment]
You can pass `io=devnull` to Pkg operations.

**Comment by juliohm** [comment]
Can't see this option in Julia v1.5.1.

In particular, `Pkg.activate` and `Pkg.precompile` don't have options regarding verbosity. Can you please clarify?

**Comment by juliohm** [comment]
This is my preamble in a script run with 100 processes:

```Julia
using Distributed

# instantiate environment in all processes
@everywhere begin
  using Pkg; Pkg.activate(@__DIR__)
  Pkg.instantiate(); Pkg.precompile()
end
```

**Comment by fredrikekre** [comment]
`Pkg.instantiate(io=devnull)` for example.

**Comment by juliohm** [comment]
How about the other commands that actually do the printing? `Pkg.instantiate` is quiet by default.

**Comment by fredrikekre** [comment]
That is logging output so just wrap in a devnulllogger or something. But why are you instantiating and precompiling on multiple processes? Do they not have a shared filesystem?

**Comment by juliohm** [comment]
I think you closed the issue prematurely? Why shouldn't these commands allow for a quiet activation and precompilation? I am  using processes that are spread in multiple machines in a computer cluster. So I need to instantiate everywhere and the precompilation also helps spot issues sooner if the host machine doesn't have GPU or something.

**Comment by juliohm** [comment]
If I submit a PR to add options for verbosity, do you think there is time to add it to the Julia v1.6 release?

**Comment by juliohm** [comment]
I guess this means no :/

**Comment by StefanKarpinski** [comment]
No, it would still be possible.

**Comment by juliohm** [comment]
Ok I will try to submit a PR in the following days.

**Comment by ianshmean** [comment]
#2091 adds an `io` kwarg to `Pkg.precompile`, so `up=devnull` will work there

**Comment by juliohm** [comment]
Thanks @iamed2 does it also fix the `activate` command?

**Comment by iamed2** [comment]
@juliohm you tagged the wrong person there, I think you meant to tag @ianshmean
