### ISSUE TITLE
Proposal: move all CI to GitHub Actions CI

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/Pkg.jl#2066]
Currently the Linux and Mac tests run on Travis, and the Windows tests run on AppVeyor.

Would it more convenient to have all of CI on a single provider?

Options include:
1. ~~Put everything in Travis CI~~ not an option, as Travis on Windows is too slow
2. Put everything in GitHub Actions CI

**Comment by DilumAluthge** [comment]
Option 1 is implemented in #2067

**Comment by KristofferC** [comment]
We did this before and Travis windows was very slow (https://github.com/JuliaLang/Pkg.jl/pull/1316).

**Comment by DilumAluthge** [comment]
Nope, looks like Travis Windows is still slow (#2607)

**Comment by DilumAluthge** [comment]
I think GH Actions CI will be the best approach here.

**Comment by ianshmean** [comment]
Attempts to try github actions over in https://github.com/JuliaLang/Pkg.jl/pull/2166

**Comment by KristofferC** [comment]
With Travis changing this seems like a good plan forward.
