### ISSUE TITLE
Install the Codecov GitHub app on this repo?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/Pkg.jl#2085]
Would it be a good idea to install the Codecov GitHub app on the Pkg.jl repo? This would result in Codecov posting a status on each pull request.

This might make it easier to detect e.g. if someone commented out all of the tests and forgot to un-comment them before committing and pushing. Such a scenario would result in an ❌ (failing) Codecov status on the pull request because the coverage would have significantly dropped.

We already submit coverage to Codecov:
https://github.com/JuliaLang/Pkg.jl/blob/f0cacf64d1a5fa767098cab43ba5c1c2c5f21e37/.travis.yml#L49-L51

So this would just be a matter of installing the Codecov GitHub app.

**Comment by DilumAluthge** [comment]
See also: https://github.com/JuliaLang/Pkg.jl/pull/2086

**Comment by fredrikekre** [comment]
I can install the app if we don't do #2086 :)

**Comment by fredrikekre** [comment]
It looks like it is already enabled on this repo...

**Comment by DilumAluthge** [comment]
That's strange... it should be posting statuses.

I wonder if Codecov is getting confused because we submit to coverage from Travis but not AppVeyor. So it detects the AppVeyor builds (by polling the GitHub API), but it never gets coverage from AppVeyor, so it keeps waiting.

For completeness we should submit coverage from all platforms anyway.

**Comment by DilumAluthge** [comment]
Even when we submit coverage from AppVeyor, the CodeCov status doesn't show up: https://github.com/JuliaLang/Pkg.jl/pull/2088

**Comment by DilumAluthge** [comment]
It'll probably be easiest to just do https://github.com/JuliaLang/Pkg.jl/pull/2086

**Comment by DilumAluthge** [comment]
@fredrikekre Can you try uninstalling and reinstalling the Codecov app? Codecov should be posting statuses on both PRs and branches. I'm not sure why it's not doing that.

**Comment by fredrikekre** [comment]
I nuked the install and re-authorized it.

**Comment by DilumAluthge** [comment]
@fredrikekre I think you've cured it! See this PR, which has the Codecov statuses: https://github.com/JuliaLang/Pkg.jl/pull/2089

**Comment by fredrikekre** [comment]
Perhaps it was confused about the travis org -> com move?

**Comment by DilumAluthge** [comment]
> Perhaps it was confused about the travis org -> com move?

Probably. I've heard of other people having various parts of their workflow broken by the migration.
