### ISSUE TITLE
Enable precompiling after Pkg operations by default

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#2093]
It would be good to enable this by default so it gets properly tested in the 1.6 alpha and RCs.

@tkf you mentioned you wanted to use preferences for this, how would that look in practice?

cc @ianshmean

**Comment by tkf** [comment]
> @tkf you mentioned you wanted to use preferences for this, how would that look in practice?

I think this is difficult now that Preferences.jl is an external package. I guess an environment variable is a practical choice for now.
