### ISSUE TITLE
 malformed Pkg server value

### ISSUE THREAD

**Issue by ardsatcg** [JuliaLang/Pkg.jl#2100]
(@v1.5) pkg> add Flux
   Updating registry at `C:\Users\LENOVO\.julia\registries\General`
┌ Warning: malformed Pkg server value
│   server = "https://C:\\Users\\LENOVO\\.julia\\packages"
└ @ Pkg.PlatformEngines D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\PlatformEngines.jl:605
┌ Warning: malformed Pkg server value
│   server = "https://C:\\Users\\LENOVO\\.julia\\packages"
└ @ Pkg.PlatformEngines D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\PlatformEngines.jl:605

I get this warning and Pkg can't loaded ( lag ), should i delete all Pkg and reinstalling?
#2098

**Comment by johnnychen94** [comment]
Would you mind showing your `versioninfo()` result to help with further investigation?

**Comment by ardsatcg** [comment]
> Would you mind showing your `versioninfo()` result to help with further investigation?
> 
> My best guess is that you have wrongly set the environment variable `JULIA_PKG_SERVER`

julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Celeron(R) CPU 4205U @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_FFTW_PROVIDER = FFTW
  JULIA_PKG_SERVER = C:\Users\LENOVO\.julia\packages
  JULIA_PROJECT = @.

**Comment by johnnychen94** [comment]
Here `JULIA_PKG_SERVER` should be unset or set to `https://pkg.julialang.org`.

Please search the internet on how environment variables are set for the windows system.

**Comment by ardsatcg** [comment]
> Here `JULIA_PKG_SERVER` should be unset or set to `https://pkg.julialang.org`.
> 
> Please search the internet on how environment variables are set for the windows system.

👍👍
