### ISSUE TITLE
Automatic precompilation in testing

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg.jl#2110]
I did not investigate this fully but there seems to be two potential issues here:
```
$ pkg st
Status `/tmp/tmp.PatNYm6KXK/Project.toml`
  [50fe2c2e] Bar v0.1.0 `Bar`
  [7876af07] Example v0.5.3

$ pkg test Example
Precompiling project... (tip: to disable auto-precompilation set ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0)
  ✗ Bar
0 dependencies successfully precompiled, 1 errored (1 already precompiled)

PkgError: The following direct dependencies failed to precompile:
  Bar [50fe2c2e-f4b2-4264-9eb4-931c784c76dc]
```

1. Why are we precompiling an env with `Bar` in it? That should not happen since `Bar` is not a dependency of `Example`.
2. We probably should disable the call to `precompile` in testing?

**Comment by KristofferC** [comment]
> We probably should disable the call to precompile in testing?

Why? We are going to load the packages so might as well precompile them?

**Comment by fredrikekre** [comment]
Is it not a hard error?

**Comment by KristofferC** [comment]
I meant, we can precompile the temporary project that the tests will run in.

**Comment by fredrikekre** [comment]
Right, but does it not error for e.g. OS specific packages then?

**Comment by KristofferC** [comment]
Hm, but I thought those were made non-hard error for this reason. I can't recall. cc @ianshmean

**Comment by fredrikekre** [comment]
IIRC it was a non-hard error for indirect deps, but for testing we put everything as direct deps.

**Comment by KristofferC** [comment]
I see, good point. Hm.

**Comment by ianshmean** [comment]
> Why are we precompiling an env with Bar in it? That should not happen since Bar is not a dependency of Example.

The precompile call is always global to the environment. Which could be a little confusing when it happens after `pkg> add`


> We probably should disable the call to precompile in testing?

Precompile shouldn't be called during `pkg> test`. It's only these

https://github.com/JuliaLang/Pkg.jl/blob/d6e6c81f7fde5eb2eb94dd32a78188d54608730e/src/API.jl#L71

and `pkg> instantiate`

I can't see how it's happening.

**Comment by KristofferC** [comment]
We also call `instantiate`.

**Comment by KristofferC** [comment]
> IIRC we call `Pkg.develop` internally when adding the package itself to the test environment.

Isn't that with an explicit `ctx`? I thought it didn't auto precompile in that case.
