### ISSUE TITLE
opt-in precompilation after Pkg.update when laptop is on battery

### ISSUE THREAD

**Issue by johnnychen94** [JuliaLang/Pkg.jl#2114]
It's not very nice if your laptop is on battery and you happen to do a `up`, which I regularly do a lot. To keep the battery last longer, some of the precompilation can be done lazily until you actually need that.

Probably there should be a nice way to make this opt-in when the laptop is on battery.

**Comment by ianshmean** [comment]
A single `Ctrl-C` will gracefully exit auto precompilation after a short wait (I've just added a message to reassure that it is exiting in #2113)

Otherwise, I'm not sure julia can know if the system is running on battery?

**Comment by Keno** [comment]
> Otherwise, I'm not sure julia can know if the system is running on battery?

All the OSes have APIs for this

**Comment by johnnychen94** [comment]
Precompilation does not always happen in an interactive mode, for example, it can be background cronjob that updates packages in the root project.

Yeah, I'm aware of the JULIA_PKG_PRECOMPILE_AUTO mode, and I have regularly switched between two modes because I both like the new precompilation feature and want to make my laptop working a bit longer when it's on battery. I don't have an expectation of what should be the best option here. Probably this is not a Julia Pkg thing and probably the best option is just to set a watchdog daemon to automate the switches.

**Comment by ianshmean** [comment]
@johnnychen94 I knocked together https://github.com/ianshmean/PowerMonitor.jl which provides the following that can be added to `.julia/config/startup.jl` to disable auto-precomp when on battery.

```julia
import PowerMonitor
PowerMonitor.autopreomp_notbattery()
```

I've only tested it on MacOS, but linux _should_ be supported.
I'm sure the code and function names could be nicer. PR's welcome!

**Comment by johnnychen94** [comment]
This looks really nice and clean! Sounds like a better place than Pkg to give it an implementation so I'll close it here.

Thanks again for all the parallel precompilation work!

**Comment by ianshmean** [comment]
Through the wonders of JLLs, this is now fully cross-platform https://github.com/ianshmean/PowerMonitor.jl
