### ISSUE TITLE
(@v1.6) pkg> up      ugly default behaviour:   precompilation overblows my linux installation with workload

### ISSUE THREAD

**Issue by Mirage10** [JuliaLang/Pkg.jl#2121]
when updating my packages (c.a 3800 installed, stresstest) my computer gets not interactive anymore. It is because the precompilation is active now and gets 3800 packages precompiled. This - unfortunately - is now the standard behaviour.

I apply the following workaround:
1) ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0 
2) (@v1.6) pkg> up 
then everything fine

In julia 1.5 the precompilation was turned off in default. everything fine

My wish: let up without precompliation in default. If the user wants precompilation then
(@v1.6) pkg> up precompile

by the way: the precompilation in 1.6 is too aggressive. Maybe in default there schould be a limit in the initiated threads. With the current solution my laptop becomes non-responsive at a certain point in time during the updating procedure.

have a gr8 day!

**Comment by KristofferC** [comment]
> It is because the precompilation is active now and gets 3800 packages precompiled.

This is a very non-standard usage so it makes sense to me to have to then opt-out to the default precompile. What's the issue with doing that?

**Comment by ianshmean** [comment]
You can also set `JULIA_NUM_PRECOMPILE_TASKS` which overrides `Sys.CPU_THREADS` if you wanted to keep auto precomp, but spawn fewer processes.

**Comment by Mirage10** [comment]
@ianshmean : I have limit JULIA_NUM_PRECOMPILE_TASKS with 3. Works pretty well. In my opinion a certain limit should be applied in the default. Wouldnt this be a reasonable approach?

**Comment by ianshmean** [comment]
I haven't seen my macbook pro slow down during the process of testing this, so from my experience the default seems reasonable. But if we continue to hear of people's systems getting bogged down, then we could revisit a lower default
