### ISSUE TITLE
Pkg.precompile significantly slower than triggering from using

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg.jl#2126]
Initially I thought this was a hang (killed after 7 minutes) but that is only happening when using `jlpkg` so I guess I have to investigate that.

Anyway, with this branch starting from a fully precompiled project: https://github.com/fredrikekre/Plots.jl/tree/fe/precompile-hang I see this:
```
$ rm -rf ~/.julia/compiled/v1.6/PlotThemes

$ time julia -e 'using PlotThemes'                                 

real    0m4.749s
user    0m4.758s
sys     0m0.412s

$ rm -rf ~/.julia/compiled/v1.6/PlotThemes

$ time julia -e 'using Pkg; Pkg.precompile()'                      
Precompiling project...
2 dependencies successfully precompiled (60 already precompiled)

real    0m28.193s
user    0m27.796s
sys     0m0.813s
```

Julia commit https://github.com/JuliaLang/julia/commit/9d6da9c4d664b832379bd2d0fa97cefecabb0e7e

**Comment by fredrikekre** [comment]
Re jlpkg, I guess this is because that runs with `--compile=min` and `--optimize=0`, but IIRC that was not a problem before. Is it new that those flags are propagated to the precompile processes?

**Comment by KristofferC** [comment]
> I wonder what is special with PlotThemes.

Maybe it does a lot of stuff in `__init__`.

**Comment by fredrikekre** [comment]
It seems slow on 1.5 too so probably not the new system at fault. I should just do https://github.com/fredrikekre/jlpkg/blob/c15ff4b7e1d408416e85151b6fe288d97ccd8893/src/cli.jl#L165-174 for precompile too.

**Comment by KristofferC** [comment]
Close? :P

**Comment by fredrikekre** [comment]
28.193s vs 4.749s though?

**Comment by KristofferC** [comment]
Ah, missed that.

**Comment by KristofferC** [comment]
What does profiling say?

**Comment by ianshmean** [comment]
I presume this is happening because you also have `Plots` in the env, which depends on `PlotThemes`. So gets precompiled again after `PlotThemes`

Note the `2 dependencies successfully precompiled` in your original post

```
shell> rm -rf /Users/ian/.julia/compiled/v1.6/PlotThemes

julia> @time Pkg.precompile()
Precompiling project...
  Progress [========================================>]  2/2
2 dependencies successfully precompiled (344 already precompiled)
 33.357093 seconds (3.36 M allocations: 212.191 MiB, 0.22% gc time)

(@v1.6) pkg> rm Plots
Updating `~/.julia/environments/v1.6/Project.toml`
  [91a5bcdd] - Plots v1.6.12
Updating `~/.julia/environments/v1.6/Manifest.toml`
  [28b8d3ca] - GR v0.52.0
  [4d00f742] - GeometryTypes v0.8.3
  [442fdcdd] - Measures v0.3.1
  [ccf2f8ad] - PlotThemes v2.0.0
  [91a5bcdd] - Plots v1.6.12
  [01d81517] - RecipesPipeline v0.1.13

shell> rm -rf /Users/ian/.julia/compiled/v1.6/PlotThemes

julia> @time Pkg.precompile()
Precompiling project...
  Progress [========================================>]  1/1
1 dependency successfully precompiled (340 already precompiled)
  5.174837 seconds (3.30 M allocations: 208.705 MiB, 2.42% gc time)
```

Perhaps there's an argument that both `PlotThemes` .ji files should be identical, except for creation datetime.. so recompiling `Plots` is unnecessary?

**Comment by ianshmean** [comment]
I guess `rm`-ing a package from `compiled` isn't _normal_ behavior, so this kind of unnecessary re-precompilation of dependents won't happen in the wild much

**Comment by fredrikekre** [comment]
> Note the 2 dependencies successfully precompiled in your original post

Thanks, I missed that. Why is the `using` path able to understand that `Plots` does not have to precompile again though?

**Comment by ianshmean** [comment]
It isn't
```
julia> using PlotThemes
[ Info: Precompiling PlotThemes [ccf2f8ad-2431-5c83-bf29-c5338b663b6a]

julia> using Plots
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]

shell> rm -rf /Users/ian/.julia/compiled/v1.6/PlotThemes

julia> exit()

...

julia> @time using PlotThemes
[ Info: Precompiling PlotThemes [ccf2f8ad-2431-5c83-bf29-c5338b663b6a]
  5.172320 seconds (2.76 M allocations: 199.864 MiB, 1.96% gc time, 2.36% compilation time)

julia> @time using Plots
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
 30.060308 seconds (3.35 M allocations: 243.350 MiB, 0.29% gc time, 1.47% compilation time)
```
