### ISSUE TITLE
Package stuck at updating 

### ISSUE THREAD

**Issue by ardsatcg** [JuliaLang/Pkg.jl#2174]
I,ve been waiting for decade, and did'nt generate anything
![image](https://user-images.githubusercontent.com/71117550/97520494-55e99800-19d6-11eb-9dd5-ea06ffda5b78.png)

**Comment by StefanKarpinski** [comment]
Probably https://github.com/JuliaLang/Pkg.jl/issues/2014.

**Comment by ardsatcg** [comment]
> Probably https://github.com/JuliaLang/Pkg.jl/issues/2014.

Nice try

**Comment by ardsatcg** [comment]
> Probably #2014.
What's next?

![image](https://user-images.githubusercontent.com/71117550/97676958-7136cf00-1acc-11eb-8c06-55ca740e3b84.png)

**Comment by KristofferC** [comment]
I don't think it is that issue. I've noticed in various places people complaining that their downloads from Pkg server just freeze which seems more similar to the issue here.

**Comment by ardsatcg** [comment]
> I don't think it is that issue. I've noticed in various places people complaining that their downloads from Pkg server just freeze which seems more similar to the issue here.

ok, i'm gonna close this
