### ISSUE TITLE
gen_project.jl does not work

### ISSUE THREAD

**Issue by ohmsweetohm1** [JuliaLang/Pkg.jl#2178]
The [help](https://julialang.github.io/Pkg.jl/v1/creating-packages/) instructs one to use the [`gen_project.jl`](https://github.com/JuliaLang/Pkg.jl/blob/934f8b71eb436da6d2bdb30ccfc80e5e11891c5b/bin/gen_project.jl) script in order to update an old packages that still has a `REQUIRE` file.
However, the script seems outdated and does not work on Julia 1.5.
I suggest removing this from the documentation of `Pkg.jl` or fixing the script.

**Comment by fredrikekre** [comment]
The script works but you need an old version of Julia, but yea, at this point we can probably just delete it from the manual.

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/1887
