### ISSUE TITLE
Auto-precompilation after Pkg.dev fails when re-build is needed

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/Pkg.jl#2195]
`Pkg.dev()` doesn't re-build the package being dev-ed, so the auto-precomp step can fail if build was needed.

I see three options:
1) `dev` should build
2) `dev` shouldn't auto-precomp
3) leave as-is and developers can handle when errors occur

**Comment by fredrikekre** [comment]
I think 2 is fine.

**Comment by IanButterworth** [comment]
I'm not sure why this was reopened. #2197 disabled auto-precompilation after `Pkg.develop`, which seems to be ok in the wild
