### ISSUE TITLE
Precomp deadlocks if a dep is missing a src/Module.jl file

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/Pkg.jl#2199]
If a package is missing a source file, precomp will deadlock without explaining why.

Perhaps a check should be made and strip any packages from the queue before they enter the parallel phase

**Comment by KristofferC** [comment]
Is this still true?

**Comment by IanButterworth** [comment]
Fixed in https://github.com/JuliaLang/Pkg.jl/pull/2332
