### ISSUE TITLE
Generating a Project.toml file for an existing package

### ISSUE THREAD

**Issue by dmbates** [JuliaLang/Pkg.jl#223]
Adding a package with `Pkg3` currently produces a warning
```
Warning: packages will require to have a [Julia]Project.toml file in the future
```
(Gramatical aside - shouldn't that be "will be required to have a ..." or just "will require a ..."?)

I can see that `Pkg3.generate` and its REPL equivalent produce such a file and that the `Compat` package has this file but it wasn't clear to me how it is to be generated (and updated?) for an existing package.

**Comment by KristofferC** [comment]
Yes, should be added.

**Comment by StefanKarpinski** [comment]
We're going to make PRs for all registered packages at some point, generating UUIDs based on the current registered names – that's how we've been doing it in the Uncurated registry. After that, going forward, new packages will generate random UUIDs instead.

**Comment by StefanKarpinski** [comment]
Yes, you can count on it: since the current METADATA is a shared global namespace, we're going to assign UUIDs to all packages in METADATA based on their registered names. I don't mind answering questions – my current work is writing docs and answering questions, so knowing what people are wondering about is quite helpful 😃

**Comment by jgoldfar** [comment]
Doc request for generating Project.toml file for an existing package seconded; are there any early adopter examples (packages outside the stdlib) using Pkg/Pkg3?

**Comment by KristofferC** [comment]
Compat.jl.

**Comment by jgoldfar** [comment]
In case anyone else happens upon this issue/request, MPI.jl after https://github.com/JuliaParallel/MPI.jl/pull/210 is a good example for how the new Pkg interacts with CI

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/Pkg.jl/blob/master/bin/gen_project.jl

**Comment by astadmistry** [comment]
Generating a Project.toml and Manifest.toml for an existing package: (Tested on Julia 1.5)
https://discourse.julialang.org/t/convert-require-to-project-toml-and-manifest-toml/17775/14

REF:
https://discourse.julialang.org/t/convert-require-to-project-toml-and-manifest-toml/17775/3
https://github.com/JuliaLang/Pkg.jl/commit/34ec22f5405ffc7f8f25a4b4f7178e887f718051
https://github.com/JuliaLang/Pkg.jl/blob/34ec22f5405ffc7f8f25a4b4f7178e887f718051/src/Types.jl
https://github.com/JuliaLang/Pkg.jl/search?p=1&q=gen_project.jl&type=Issues
