### ISSUE TITLE
missing CompilerSupportLibraries_jll

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/Pkg.jl#2264]
I've just begun to see CI failures on nightly with the message:
```
LoadError: ArgumentError: Package CompilerSupportLibraries_jll [e66e0078-7015-5450-92f7-15fbd957f2ae] is required but does not seem to be installed:
```
even though the earlier log seems to indicate it was installed: [full log](https://gist.github.com/stevengj/a7a3999dda80fd9d34c9150231dfefa7).

This was in https://github.com/JuliaMath/SpecialFunctions.jl/pull/278

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/38654
