### ISSUE TITLE
NEWS.md

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/Pkg.jl#2279]
We need a NEWS.md for Pkg.
I know we used to have one, and people kept not using it or something.
But in retrosect the problem would better have been handled by not merging PRs that don't update it.

Having looks at the major changes to julia since 1.0.
A ton of very signficiant once have been to Pkg.
(Ironically though that might mean that we are close to done with Pkg, so the need lessens. But I suspect we still have things to do that will be news worthy)

Most importantly, I have often needed to find out when one happened.
For example when what the tiered resolved introduced?
When did it become possible to have the same package in multiple registries with different versions?

Possibly an alternative, is to label PRs with the version of julia they are merged into.
That might be easier than a NEWS.md, and get the same outcomes.
But it would be inconsistent with what we do for julia, but maybe that is ok.

When the Pkg version is updated in Julia the things should probably be copied over to julia's NEWS.md

**Comment by DilumAluthge** [comment]
> Possibly an alternative, is to label PRs with the version of julia they are merged into.

This is actually already available, although perhaps not in the most intuitive way. If you know the PR number, you can figure out which version of Julia it first appears in, as follows:
1. Go to the PR's URL. For example, if we want to figure out the version of Julia that the tiered resolver (#1330) first appears in, we go to [`https://github.com/JuliaLang/Pkg.jl/pull/1330`](https://github.com/JuliaLang/Pkg.jl/pull/1330)
2. Control-F (or Command-F) and search for the text `merged commit`
3. Look for the line that looks something like `<someone> merge commit <commit short hash> into  JuliaLang:master on <data>`. In this example, the sentence is `bors [bot] merged commit 08daeb3 into JuliaLang:master on Sep 10, 2019`.
4. Click on the commit short hash. In this example, click on `08daeb3`.
5. The top of the page looks like this:
<img width="1034" alt="Screen Shot 2020-12-08 at 16 02 32" src="https://user-images.githubusercontent.com/5619885/101541106-d4a00080-3998-11eb-8018-9e72925be941.png">


6. Click on the ellipse (`...`). Now the top of the page looks like this:
<img width="1034" alt="Screen Shot 2020-12-08 at 16 02 44" src="https://user-images.githubusercontent.com/5619885/101541112-d8338780-3998-11eb-989f-8263b4ee6c66.png">


This lists all the tags in the Pkg.jl repository that include this commit. So we can see that this PR is first available in the v1.4.0 tag.

**Comment by KristofferC** [comment]
There is a CHANGELOG.md file now.
