### ISSUE TITLE
Sum function changes behavior for some arrays when run during Pkg.test()

### ISSUE THREAD

**Issue by maetshju** [JuliaLang/Pkg.jl#2298]
When a `runtests.jl` file is run through `Pkg.test()`, calling `sum` on certain arrays seems to force a naive summation instead of the pairwise summation routine that is normally used with the `sum` function. So far, I have been able to replicate this error on two separate "kinds" of arrays. The first is a 1D array that was generated by calling `sum` with a `dims` argument on a 2D array. The second is a 1D array that had values manually entered. However, when the code is executed by just running the script, the `sum` function seems to use the pairwise sum routine, or at least the result does not match left-to-right evaluation.

As an example of the first kind of array:

```julia
using Random
Random.seed!(0)
c = rand(100, 500)
c = sum(c, dims=2)
s = sum(c); println("statistics sum:\t$s")
f = foldl(+, c); println("foldl sum:\t$f")
```
yields values of  24988.7468834317 for `s` and 24988.746883431704 for `f` when the script is run using a command like `julia runtests.jl`. Whereas, it yields a value of 24988.746883431704 (the naive summation value) for both `s` and `f` when the code is executed using a command like `julia -e "using Pkg; Pkg.activate(); Pkg.test()"`. The `Random.seed!(0)` can be removed and the problem persists, so I don't think it is isolated to just this specific array. There may well be more cases where this happens, but I have not been able to find them.

Similarly, as an example of the second kind of array,

```julia
a = [79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454467, 79.97860557454469, 79.97860557454467, 79.97860557454469, 79.97860557454467, 79.97860557454467, 79.97860557454467, 79.97860557454467, 79.97860557454467, 79.97860557454469, 79.97860557454469, 79.97860557454467, 79.97860557454467, 79.97860557454467, 79.97860557454467, 79.97860557454467, 79.97860557454467, 79.97860557454469, 79.97860557454467, 79.97860557454469, 79.97860557454469, 79.97860557454467, 79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454467, 79.97860557454467, 79.97860557454467, 79.97860557454469, 79.97860557454467, 79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454469, 79.97860557454469]
s1 = sum(a); println("statistics sum:\t$s1")
s2 = foldl(+, a); println("foldl sum:\t$s2")
```

yields 3998.9302787272372 for `s1` and 3998.930278727238 for `s2` when run with `julia runtests.jl`. Whereas, a value of 3998.930278727238 (the naive summation value) is given for both `s1` and `s2` when run with `julia -e "using Pkg; Pkg.activate(); Pkg.test()"`.

I have a [repo with a simple package](https://github.com/maetshju/testmeansumpackagejl) containing these tests. [The Travis build](https://travis-ci.com/maetshju/testmeansumpackagejl) replicates the issue on Linux, Windows, and Mac for Julia 1.5. Some of the exact numbers come out slightly differently, but the pattern is the same.

**Comment by fredrikekre** [comment]
Tests run with `--check-bounds=yes`.

**Comment by KristofferC** [comment]
(which can inhibit SIMD and thus change the result).

**Comment by maetshju** [comment]
> Tests run with `--check-bounds=yes`.

This causes both values to come out the same for me, producing the naive summation values, which is not what I would expect and causes both tests to fail. As well, if the fix were to use this flag when testing, it suggests that, by default, the execution of some functions is subtly different when testing as compared to regular execution. Perhaps that is intentional, but it seems like a bug to me.

**Comment by maetshju** [comment]
Okay, I get it now. I thought you were saying that the tests I had provided ran correctly with the `--check-bounds=yes` flag. I understand now that you're saying that tests in general run with that flag on. Sorry for the misunderstanding!
