### ISSUE TITLE
ERROR: could not find project file in package at `/root/.julia/registries/General` maybe `subdir` needs to be specified

### ISSUE THREAD

**Issue by junedwx** [JuliaLang/Pkg.jl#2300]
The following error message is displayed when you install the General in offline mode:
Prerequisites: Ubuntu 18.04 and julia 1.5 are used, and Git Repo can be connected.
Coordinates: China.

(@v1.5) pkg> add /root/.julia/registries/General/
   Updating git-repo `/root/.julia/registries/General`
ERROR: could not find project file in package at `/root/.julia/registries/General` maybe `subdir` needs to be specified

(@v1.5) pkg> st
Status `~/.julia/environments/v1.5/Project.toml` (empty project)

**Comment by fredrikekre** [comment]
`pkg> add ...` - > `pkg> registry add ...`?
