### ISSUE TITLE
Consider develop to default to --local 

### ISSUE THREAD

**Issue by musm** [JuliaLang/Pkg.jl#2305]
I find the `dev` default  shared mode a bit odd since to activate the shared `dev` environment you must:
```julia
pkg>activate --shared dev  # must specify --shared  (good default)
```

However `dev`'ing  a package defaults to use the shared `dev` environment 
```julia
pkg>dev Foo  
```

I'd have thought that `--local` would be a  more sensible default for `dev`

**Comment by oxinabox** [comment]
I think (like #2252) this would be too disruptive to do, (though like that one  silently deprecating it might be a thing).
but that we should strongly consider it for 2.0

**Comment by musm** [comment]
I don't think this is very disruptive and does not compare to https://github.com/JuliaLang/Pkg.jl/issues/2252 in the magnitude of its deprecation impact. I mean this only affects a local `dev` and could be easy to deprecate with a one-time notification when users first use `dev`

**Comment by KristofferC** [comment]
In hindisght, I also think the `--local` by default is correct. I also think that this is orders of magnitude less disruptive than #2252 since it in most cases would require no changes from users.

**Comment by oxinabox** [comment]
>  I also think that this is orders of magnitude less disruptive than #2252 since it in most cases would require no changes from users.

this would require way more change from users.
#2252 has literally no effect until Julia 2.0, or if they have deprecation warnings turned on would be a warning that they can igore.
Where as people who currently use `] dev` would have things show up in a totally different directory to what they expect.
There is no way to ignore that.

Unless you are saying everyone already does `dev --local`?
I mean, I always do `dev --local` and everyone I teach how to use the package manager i tell to use `dev --local`,
but it is hard to imagine it is everyone.

**Comment by fredrikekre** [comment]
Personally I have never used `--local` and would be very annoyed to have multiple git repos of the same package all over the place.

**Comment by StefanKarpinski** [comment]
Agree: I never do `dev --local`. I get that it makes sense for some people's workflows but it's not clearly preferable and this would certainly be a change.

**Comment by musm** [comment]
Ok, closing this as it's does seem like there's disagreement that is an objectively better default. I'm fine with that. 

OTOH, I'm not sure if it's feasible but it does seem sensible that `dev`  would default to `--shared`, but it would be an exception, which opens up another can of worms.
