### ISSUE TITLE
More helpful error messages

### ISSUE THREAD

**Issue by baggepinnen** [JuliaLang/Pkg.jl#2308]
I have somehow found myself in this situation
```
(@v1.6) pkg> resolve
ERROR: Dependency `Test` in target `test` not listed in `deps` or `extras` section.
```
This error message would benefit from containing information about which exact file the error appears in. The file `~/.julia/environments/v1.6/Project.toml` which I would think the error arose in does not contain any `target test` so it must have happened in another file.

**Comment by KristofferC** [comment]
Pretty much a dup of https://github.com/JuliaLang/Pkg.jl/issues/1853
