### ISSUE TITLE
Pkg.test(): how to stop printing Status of project.toml and manifest.toml

### ISSUE THREAD

**Issue by t-pollington** [JuliaLang/Pkg.jl#2315]
`Pkg.test()` prints many lines of **Status** output of the packages in project and manifest files (which isn't relevant to most) before getting to the test results. Can this be turned off by default and the former enabled through an additional argument?

**Comment by KristofferC** [comment]
It shows the exact version of all the dependencies use which I think is a quite valuable context to the test results. An option to turn it off could of course be added, but is it really that annoying?

**Comment by t-pollington** [comment]
Hi @KristofferC, I admit, yes it's valuable. It's just that on _Juno IDE_ I find that I'm regularly `Ctrl+L` clearing the REPL screen as vertical scrolling gets cumbersome. This is kind of related to me having RSI so I'm trying to limit mouse use :) 🖱️

**Comment by 00vareladavid** [comment]
I think this can be closed by #2452. You can set `io=devnull` to completely silent Pkg feedback.

Example:
```
julia> Pkg.test("JSON";io=devnull)
Test Summary: | Pass  Total
Parser        |   86     86
Test Summary: | Pass  Total
Serializer    |   49     49
Test Summary: | Pass  Total
Integration   |  108    108
Test Summary: | Pass  Total
Regression    |    8      8
```

**Comment by t-pollington** [comment]
Hi @00vareladavid unfortunately that doesn't work for me as `Pkg.test("DataFrames";io=devnull)` still gives the Project and Manifest preamble. I'm using Julia 1.6.0.

**Comment by 00vareladavid** [comment]
Yes, #2452 was just merged today. So it won't show up until 1.6.1 or 1.6.2.
