### ISSUE TITLE
I found a problem about local network issue in Pkg mode

### ISSUE THREAD

**Issue by nesteiner** [JuliaLang/Pkg.jl#2326]
today I found that when  I start a repl from the terminate, and the terminate has been set the proxy environment, in this case,  some operation in pkg mode, like `add`, `registry up` and so on will fail, it would tell you that 
![2021-01-11 19-30-09 的屏幕截图](https://user-images.githubusercontent.com/46296608/104178424-40b4cf00-5445-11eb-9cfd-862e19b4dc8b.png)

then I try deleting the proxy variable in terminate and restart the repl again, and I found that I successed:
![2021-01-11 19-42-57 的屏幕截图](https://user-images.githubusercontent.com/46296608/104178441-4ad6cd80-5445-11eb-960b-dc5798d7b0cd.png)

**Comment by johnnychen94** [comment]
This seems to be a network issue in your side, would you mind providing more information about your network settings, for example, are you behind a firewall that has a limited network connection?

Assuming that `HTTP_PROXY=http://127.0.0.1:7890 curl -SsfL https://kr.pkg.julialang.org/registries` works, the fastest way to diagnose this might be checking if `curl -SsfL https://kr.pkg.julialang.org/registries` return the same result.

**Comment by nesteiner** [comment]
你还是说中文吧，我看不懂

**Comment by johnnychen94** [comment]
我的意思是说，这应该是你那边网络或者代理设置的问题，和 Julia 或者 Pkg 无关.

只要你的命令行能够正常 curl -SsfL https://kr.pkg.julialang.org/registries 拿到结果那么就可以了.

**Comment by nesteiner** [comment]
```bash
➜  HelloWorld curl -SsfL https://kr.pkg.julialang.org/registries
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:7890 
```
终究还是错付了啊
看来是我这边的问题

**Comment by johnnychen94** [comment]
嗯，既然不是Pkg的问题，可以麻烦你关闭这个 issue 么？

**Comment by nesteiner** [comment]
不是你们操作的吗，我不知道怎么关 :yum:
