### ISSUE TITLE
`write_env_usage()` can self-clobber

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/Pkg.jl#2346]
When cleaning up the Yggdrasil CI bots, I found that the `manifest_usage.toml` and `artifact_usage.toml` files were clobbered rather often due to multiple Julia processes writing out at once.

I believe this may be due to `TOML.print(io, ::Dict)` partially printing then yielding.  It would probably be better to have this construct the string first, then append it in one `write()` call.

https://github.com/JuliaLang/Pkg.jl/blob/94d3c45f1b7c6c7a1e887d97f4e87e3662801d0f/src/Types.jl#L415

**Comment by fredrikekre** [comment]
Yep, that is what we do for the project and manifest (https://github.com/JuliaLang/Pkg.jl/pull/1203)

**Comment by fredrikekre** [comment]
But the print to file is done in one chunk already?

**Comment by staticfloat** [comment]
Hmmm, you're right.  That must not be the issue then.

**Comment by fredrikekre** [comment]
Same with Scratch.jl: https://github.com/JuliaPackaging/Scratch.jl/blob/2b527ef57d94f10240ac45a2992e2cbffe69c210/src/Scratch.jl#L156

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/Pkg.jl/blob/94d3c45f1b7c6c7a1e887d97f4e87e3662801d0f/src/API.jl#L518-L520 maybe
