### ISSUE TITLE
Detecting a precompile failure

### ISSUE THREAD

**Issue by omus** [JuliaLang/Pkg.jl#2358]
As part of a Docker build we're using `Pkg.API.precompile()`. We've noticed that if a failure occurs with this function no exception or return is provided to indicate that a failure has taken place. This is problematic as it's hard to provide Docker with a non-zero return codes to indicate the `RUN` instruction has failed. With newer versions of Docker the flag `--progress=auto` is the default which automatically hides the output generated during successful `RUN` commands making pre-compilation failures practically invisible.

Could we update `Pkg.API.precompile()` with an option to throw and exception or return success/failure?

**Comment by ianshmean** [comment]
When you call `precompile` directly, it will throw for any errors from direct dependencies. i.e. deps in the Project.toml

Indirect dependencies may fail but won't throw, unless they are actually called by direct dependencies during their own precompilation.

During autoprecomp, direct deps will report failure in the log but won't throw

**Comment by omus** [comment]
Interesting. In this particular case the failure occurred during the `__init__` of an indirect dependency.

**Comment by ianshmean** [comment]
If your direct deps don't fail, then maybe that indirect dep isn't actually used my your direct deps in your config? Being in a Project.toml doesn't mean the dep with definitely be used. 

Or if it's guarded behind Requires.jl you might want to add the erroring dep to your Project.toml

**Comment by omus** [comment]
The private package is definitely being used as an indirect dep. I think what I want is an option to to `precompile` which will throw an exception when any failure occurs. That way Julia will produce a non-zero return code causing Docker to report the failure.

**Comment by omus** [comment]
As a work around I'm validating that the `.ji` file exists for my package:
```julia
using Pkg
Pkg.API.precompile()

# Validate precompile succeeded
pkg_uuid = Base.UUID(Pkg.TOML.parsefile(joinpath(PKG_PATH, "Project.toml"))["uuid"])
pkg_id = Base.PkgId(pkg_uuid, PKG_NAME)
isfile(Base.compilecache_path(pkg_id)) || error("precompile failed")
```
Note: I can't use the module to create the `PkgId` as that involve loading the package which triggers another precompile

**Comment by ianshmean** [comment]
How does this look? https://github.com/JuliaLang/Pkg.jl/pull/2362
