### ISSUE TITLE
Latests packages can differ between computers

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/Pkg.jl#2395]
Julia 1.5.3.

I have been hitting this issue:
1. Create empty repository
1. `Pkg.activate("."); Pkg.add("Plots")` to create the Project Manifest files, with the very latest versions of deps
2. Commit Project+Manifest, and run the repo with mybinder.org
3. The binder fails to build, with an error like:
```
Pkg updating registry...
Instantiating Manifest...
RecipesBase 0.5.1 not found, available versions [0.1 - 0.5.0]
```

Checking `RecipesBase`, it had just released `0.5.1` 4 hours ago.

---

The binder build logs show that it updates its registry, which is _after_ I created the Manifest.toml. Perhaps the build machine is hitting a different pkgserver, which is outdated?

**Comment by fredrikekre** [comment]
https://github.com/JuliaRegistries/General/issues/16777
