### ISSUE TITLE
Disable AppVeyor?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/Pkg.jl#2396]
Now that GitHub Actions is passing on Windows, perhaps we can disable AppVeyor?

**Comment by IanButterworth** [comment]
There may be benefit to keeping it.. it runs with elevated permissions, so might be catching weird windows edge cases. 

Also, AV finishes in about 24 mins, whereas GHA takes >35 mins. Not sure why.

**Comment by DilumAluthge** [comment]
Let's leave AV for now, since we want to make sure to test all these weird Windows permissions situations.

**Comment by DilumAluthge** [comment]
I'm going to re-open this.

AV limits us to a single concurrent job. In contrast, GHA gives us 20 concurrent jobs across the JuliaLang organization. This means that, in practice, the GHA jobs finish much earlier than the AV job.

If I understand correctly, the main benefit to keeping AV is that it runs with elevated permissions. Could we just emulate that by adding a job to the GHA matrix that runs the Pkg.jl tests as root?

**Comment by KristofferC** [comment]
I don't have permission to disable AV. Not sure who does.

**Comment by DilumAluthge** [comment]
You can go to the repo settings and delete the AV webhooks, I think.

**Comment by KristofferC** [comment]
Thanks, I think it should be done now.
