### ISSUE TITLE
Bug: The "STDLIBS_BY_VERSION up-to-date" test is currently broken

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/Pkg.jl#2410]
See also:
- https://github.com/JuliaLang/Pkg.jl/pull/2409

**Comment by IanButterworth** [comment]
I fixed this in https://github.com/JuliaLang/Pkg.jl/pull/2402 but can remove it if it needs its own PR

**Comment by DilumAluthge** [comment]
> I fixed this in #2402 but can remove it if it needs its own PR

Yeah, if you already have a fix for this, can you pull it out and make a separate PR with it?

**Comment by DilumAluthge** [comment]
Also, when you make that PR, can you also change the `@test_broken` back to `@test`?

(I changed the `@test` to `@test_broken` in https://github.com/JuliaLang/Pkg.jl/pull/2409.)

**Comment by DilumAluthge** [comment]
Actually, never mind. #2402 LGTM, so let's just merge that.

**Comment by DilumAluthge** [comment]
I don't think #2402 was sufficient to fix this.

**Comment by DilumAluthge** [comment]
The list of stdlibs needs to have libblastrampoline_jll in it.

But when I add it to the list, everything breaks. See e.g. https://github.com/JuliaLang/Pkg.jl/pull/2411
