### ISSUE TITLE
CI on gitlab with private registry

### ISSUE THREAD

**Issue by baggepinnen** [JuliaLang/Pkg.jl#2422]
I'm trying to setup CI on a private gitlab server and am facing some problems with the way the package manager accesses packages registered in a private registry. For the gitlab CI-runner to be able to access other repos stored on the same gitlab server, one must preface the url with [a `CI_JOB_TOKEN` environment variabe](https://docs.gitlab.com/ee/user/project/new_ci_build_permissions_model.html#dependent-repositories). This allows me to succesfully add the local registry in the CI-script. When the package manager tries to install the required dependencies that are registered in the local registry, it fails due to it not using the `CI_JOB_TOKEN`. I could potentially write a julia program that runs before the package tests that goes through the local registry and modifies all urls to include the token, but maybe there is a better approach that I can't see?

The way I used to use the gitlab token to add the registry was to add the following to my CI-script
```julia
Pkg.Registry.add("General");
Pkg.Registry.add(RegistrySpec(url = "https://gitlab-ci-token:$(ENV["CI_JOB_TOKEN"])@gitlab/path/to/local/registry/"));
```

**Comment by baggepinnen** [comment]
It seems `git` has a feature that is useful here, as discussed in the following discourse thread
https://discourse.julialang.org/t/use-private-registry-in-gitlab-ci-job/36179/16

**Comment by fredrikekre** [comment]
Configure it to use ssh instead?

**Comment by baggepinnen** [comment]
Using ssh does not solve the problem, but using the `insteadOf` of git works well. The thread https://discourse.julialang.org/t/use-private-registry-in-gitlab-ci-job/36179/16 can thus be seen as the solution to this issue.
