### ISSUE TITLE
Documentation how to push a package to github is missing

### ISSUE THREAD

**Issue by ufechner7** [JuliaLang/Pkg.jl#2427]
While there is some documentation how to create a package locally, it is nowhere explained how to push a locally created package to github. In particular the fact that the local package folder and the repository must have a different name (locally without any suffix, in github with the suffix .jl) is nowhere explained.

If someone can suggest where to add this documentation I might be able to create a pull request.

**Comment by DilumAluthge** [comment]
I've transferred this issue to the Pkg.jl repo.

**Comment by KristofferC** [comment]
>  it is nowhere explained how to push a locally created package to github.

It is a bit out of scope for the Pkg docs to explain how to push repos to different git hosting systems.

> In particular the fact that the local package folder and the repository must have a different name (locally without any suffix, in github with the suffix .jl) is nowhere explained.

This is not true. Your local folder can be called whatever you want it to.

```
(@v1.6) pkg> generate Foo
  Generating  project Foo:
    Foo/Project.toml
    Foo/src/Foo.jl

shell> mv Foo Whatever.jljljl

(@v1.6) pkg> dev Whatever.jljljl/
Path `Whatever.jljljl/` exists and looks like the correct package. Using existing path.
   Resolving package versions...
    Updating `~/.julia/environments/v1.6/Project.toml`
  [19b08507] + Foo v0.1.0 `../../../juliamaster/Whatever.jljljl`
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [19b08507] + Foo v0.1.0 `../../../juliamaster/Whatever.jljljl`
```

**Comment by DilumAluthge** [comment]
Instead of adding this to the Pkg.jl docs, perhaps we could find a place to add it in the PkgTemplates.jl docs.

**Comment by ufechner7** [comment]
Very bad and stupid to close this issue. You do not understand the needs of Julia users and package developers.

**Comment by ufechner7** [comment]
What you are doing is to convince people NOT to develop Julia packages. The correct way how to push a package to githup is very confusing and needs good documentation. First I asked to add this documentation to Julia, I was told to add it to Pkg.jl. Now you say I shall not add it to Pkg.jl, but to PkgTemplates.jl. In the end you want me to add documentation to a location where nobody can find it. This is contra-productive.
