### ISSUE TITLE
Automatically add `compat` entries according to current installed versions

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/Pkg.jl#2463]
`compat` entries should automatically be added according to the current minor version of the relevant package whenever that package is `Pkg.add`ed to an environment.

**Comment by ufechner7** [comment]
This cannot be so difficult... What is missing? Do we want that this works in the way described by dpsanders? 
I think that would be very useful for beginners to avoid that they upgrade packages and brake their code because they added a package.

**Comment by ufechner7** [comment]
Is this a duplicate, or what is different: https://github.com/JuliaLang/Pkg.jl/issues/776 ?
