### ISSUE TITLE
Pkg.build() broken

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg.jl#2470]
GH actions CI is broken on nightly now https://github.com/JuliaLang/Pkg.jl/pull/2443#issuecomment-810113013

**Comment by DilumAluthge** [comment]
Should we add a regression test to the Pkg test suite?

**Comment by KristofferC** [comment]
We have a bunch of tests for `Pkg.build` so the task is to figure out what exactly isn't covered yet.

**Comment by IanButterworth** [comment]
Fixed by https://github.com/JuliaLang/Pkg.jl/pull/2471
