### ISSUE TITLE
Bad error message "already exists as a direct dependency"

### ISSUE THREAD

**Issue by Keno** [JuliaLang/Pkg.jl#2476]
```
(@v1.7) pkg> dev https://github.com/JuliaComputing/NgSpice.jl
     Cloning git-repo `https://github.com/JuliaComputing/NgSpice.jl`
Path `/home/keno/.julia/dev/NgSpice` exists and looks like the correct repo. Using existing path.
ERROR: refusing to add package `NgSpice [1a64e563]`: package `NgSpice = "1a64e563-3ad9-44a2-8713-a1728bea8a90"` already exists as a direct dependency
```

The issue here is that the package was renamed and I already had it with the old (uncapitalized) name in my Project.toml. It would be nice for it to have told me that the package was already there with the old name and then told me how to get rid of it.

**Comment by DilumAluthge** [comment]
I wonder if this is specifically because the old name is equal (modulo case changes) to the new name.

Or does it happen any time you have the old package's UUID in your `Project.toml` file?

**Comment by 00vareladavid** [comment]
@DilumAluthge we do a direct comparison to check the name, but there was a typo in the error message which makes it seem like we just check modulo case
