### ISSUE TITLE
Last package updated missing from console display

### ISSUE THREAD

**Issue by lbilli** [JuliaLang/Pkg.jl#2499]
In Julia v1.6, when updating **more then one** package, the list of packages displayed in the console gets trimmed by one once the process is completed.

To better illustrate the issue, here are two screenshots: the first is taken during precompilation and the second after the update is done.
In this case `Adapt` and `Compat` are being updated, but the line referring to `Compat` is missing in the second screenshot.

![ss1](https://user-images.githubusercontent.com/12815378/114174950-613adb00-9907-11eb-9361-9535f4d808b5.png)

![ss2](https://user-images.githubusercontent.com/12815378/114174967-6730bc00-9907-11eb-8548-a201c4a470a4.png)

**Comment by fredrikekre** [comment]
Probably duplicate of https://github.com/JuliaLang/Pkg.jl/issues/2306 or https://github.com/JuliaLang/Pkg.jl/issues/2141

**Comment by IanButterworth** [comment]
Fixed by https://github.com/JuliaLang/Pkg.jl/pull/2457 which will be in 1.6.1

**Comment by IanButterworth** [comment]
I'm also not sure it's the same issue as those other two, given this is specifically due to the way the precompilation report overprinted rows before printing

**Comment by lbilli** [comment]
Indeed, fixed in 1.6.1.
