### ISSUE TITLE
Add metadata to manifest

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/Pkg.jl#2508]
It seems a fair few issues with upgrading to 1.6 have been around using old manifests that fail in unclear/unpleasant ways (because of changes to stdlibs for one), and the advice is "manifests aren't guaranteed to work across julia versions, delete the manifest and try again".

For 1.7 given there's no guarantee of cross-version manifest compatibility, I was wondering if a clean break could be made and change the structure of the manifest & Manifest.toml to something a bit more flexible than a `Dict{UUID,PackageEntry}` so that metadata can be added, like julia version and a hash of the Project.toml so that Pkg can be sure that the manifest is a valid resolve of the current project.

A heuristic could be added to 1.6.1 to `read_manifest` to detect if the manifest is of the new format, to warn/instruct the user to delete the manifest to proceed.

The new manifests would break if users tried to use them with older julia versions. But perhaps that's part of the _no guarantee_?

I had a search and couldn't find another issue to track this

**Comment by DilumAluthge** [comment]
Related to https://github.com/JuliaLang/Pkg.jl/issues/1458?

**Comment by IanButterworth** [comment]
Indeed! I'll post in that issue instead.
