### ISSUE TITLE
Feature request: make `pkg.status()` reveal the current & latest version of the package

### ISSUE THREAD

**Issue by azev77** [JuliaLang/Pkg.jl#2526]
Users (esp beginners) often don't realize that they don't have the latest versions. 
Would it be possible for `pkg.status()` to reveal the current & [latest version](https://discourse.julialang.org/t/how-to-get-latest-version-number-of-a-package/27262) of the package:
(w different colors if current version ≠ latest version)
```julia
(@v1.6) pkg> status
      Status `C:\Users\azevelev\.julia\environments\v1.6\Project.toml`
              Package    Current   Latest
  [f6006082] `EvoTrees   v0.5.3    v0.7.0`
  [9bbee03b]  NaiveBayes v0.5.0    v0.5.0
  [add582a8] `MLJ        v0.15.2   v0.16.0`
  [d491faf4] `MLJModels  v0.13.3   v0.14.1` 
```

**Comment by KristofferC** [comment]
Let's keep this type of discussion in https://github.com/JuliaLang/Pkg.jl/issues/2526 to not spread it out too much.

**Comment by azev77** [comment]
Sorry, the issue you linked #2526, is the current issue. 
Which issue did you have in mind?

**Comment by KristofferC** [comment]
I always do this... https://github.com/JuliaLang/Pkg.jl/issues/1655.
