### ISSUE TITLE
Error message for missing project file could be improved

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/Pkg.jl#2528]
I am trying to do: 

```Julia
(@v1.6) pkg> add https://github.com/danielsuo/Crypto.jl
    Updating git-repo `https://github.com/danielsuo/Crypto.jl`
ERROR: could not find project file in package at `https://github.com/danielsuo/Crypto.jl` maybe `subdir` needs to be specified
```
and it fails. I tried a git clone locally and it worked without issue. My guess is that the project structure is causing the issues?

**Comment by logankilpatrick** [comment]
It looks like per here: https://discourse.julialang.org/t/error-could-not-find-project-file-in-package-at-https-github-com/44059 you can't add a package without a Project file, perhaps the error message wording could be improved?

**Comment by logankilpatrick** [comment]
Ehh, maybe that error message is fine, I still have not had coffee yet so will let it sink in and revisit

**Comment by DilumAluthge** [comment]
We could change `project file` to `Project.toml file`, if that helps?

**Comment by logankilpatrick** [comment]
Yeah, that will do the trick

**Comment by KristofferC** [comment]
It could be called `JuliaProject.toml` as well which I guess maybe is why it is just called `project file`. On the other hand, no one uses that so perhaps it is fine to just hard code `Project.toml`.
