### ISSUE TITLE
after upgrade to 1.6.1: lost Pkg prompt on Pkg.update() and Pkg.add("...")

### ISSUE THREAD

**Issue by walra356** [JuliaLang/Pkg.jl#2542]
After upgrading from 1.6.0 to 1.6.1 I lost the Pkg prompt on Pkg.update() and Pkg.add("...") in my Jupyter notebook. 

Is this intentional or an issue? 

The code runs fast and I believe correct (thanks!) but lacks the prompt reporting updates. So, I can do my work but wanted to report my issue... I searched for a key to switch the prompt on but could not find it.

**Comment by fredrikekre** [comment]
Must be https://github.com/JuliaLang/Pkg.jl/pull/2391

**Comment by IanButterworth** [comment]
Indeed. Note that these are executed cells

<img width="385" alt="Screen Shot 2021-04-30 at 10 17 48 AM" src="https://user-images.githubusercontent.com/1694067/116708076-58d13f80-a99d-11eb-9610-26aad3d7678d.png">

**Comment by walra356** [comment]
Yes, thanks, this is what I reproduce.  After restarting the kernel I get:

using Pkg
Pkg.update()
Fetching: [========================================>]  100.0 %

Pkg.add("FixedPoint Numbers")

Note: no output was returned, i.e., i got no message that Pkg.add was successful (same for update). In previous versions Julia returned output about the presence or absence of changes in the Project and Manifest tomls. I found that helpful. Now I understand that this has abandoned, which I respect but regret.

**Comment by IanButterworth** [comment]
As a quick fix before 1.6.2 comes out, you can work around in 1.6.1 it by setting
```
import Pkg
Pkg.DEFAULT_IO[] = stdout
```

**Comment by walra356** [comment]
Thank you for chewing this out for me... Great support!
