### ISSUE TITLE
Packages downgraded after `Pkg.update()`?

### ISSUE THREAD

**Issue by ptoche** [JuliaLang/Pkg.jl#2550]
Unless I'm mistaken, packages were downgraded without a prior warning (and without an explanation):

I just called 

    import Pkg
    Pkg.update()

The tail-end of the console shows:

        Updating `~/Julia/workspace/Project.toml`
      [b4f34e82] ↑ Distances v0.10.2 ⇒ v0.10.3
      [91a5bcdd] ~ Plots v1.13.2 `https://github.com/JuliaPlots/Plots.jl.git#master` ⇒ v1.13.2 `https://github.com/JuliaPlots/Plots.jl.git#master`
      [92933f4c] ↑ ProgressMeter v1.5.0 ⇒ v1.6.0
        Updating `~/Julia/workspace/Manifest.toml`
      [4fba245c] ↑ ArrayInterface v3.1.9 ⇒ v3.1.10
      [324d7699] ↑ CategoricalArrays v0.9.6 ⇒ v0.9.7
      [d360d2e6] ↑ ChainRulesCore v0.9.40 ⇒ v0.9.41
      [b630d9fa] - CheapThreads v0.2.3
      [34da2185] ↑ Compat v3.27.0 ⇒ v3.28.0
      [bcd4f6db] ↑ DelayDiffEq v5.29.3 ⇒ v5.30.0
      [2b5f629d] ↑ DiffEqBase v6.60.0 ⇒ v6.60.1
      [b4f34e82] ↑ Distances v0.10.2 ⇒ v0.10.3
      [7a1cc6ca] ↑ FFTW v1.4.0 ⇒ v1.4.1
      [5789e2e9] ↑ FileIO v1.8.1 ⇒ v1.8.2
      [82e4d734] ↑ ImageIO v0.5.3 ⇒ v0.5.4
      [5ab0869b] ↑ KernelDensity v0.6.2 ⇒ v0.6.3
      [bdcacae8] ↓ LoopVectorization v0.12.12 ⇒ v0.11.2
      [7269a6da] ↑ MeshIO v0.4.6 ⇒ v0.4.7
      [1dea7af3] ↑ OrdinaryDiffEq v5.52.7 ⇒ v5.53.0
      [a03496cd] ↑ PlotlyBase v0.5.2 ⇒ v0.5.3
      [91a5bcdd] ~ Plots v1.13.2 `https://github.com/JuliaPlots/Plots.jl.git#master` ⇒ v1.13.2 `https://github.com/JuliaPlots/Plots.jl.git#master`
      [92933f4c] ↑ ProgressMeter v1.5.0 ⇒ v1.6.0
      [476501e8] ↓ SLEEFPirates v0.6.15 ⇒ v0.6.10
      [2913bbd2] ↑ StatsBase v0.33.6 ⇒ v0.33.8
      [789caeaf] ↑ StochasticDiffEq v6.33.1 ⇒ v6.33.2
      [7792a7ef] - StrideArraysCore v0.1.5
      [c3572dad] ↑ Sundials v4.4.1 ⇒ v4.4.3
      [0c5d862f] ↑ Symbolics v0.1.24 ⇒ v0.1.25
      [8290d209] ↓ ThreadingUtilities v0.4.1 ⇒ v0.2.5
      [f269a46b] ↑ TimeZones v1.5.3 ⇒ v1.5.4
      [3d5dd08c] ↓ VectorizationBase v0.19.32 ⇒ v0.18.14

There is no warning and unless I missed it there wasn't any information about it in the [docs](https://docs.julialang.org/en/v1/stdlib/Pkg/).

Just a few days ago I noticed I was using a version of `Plots`  from 3 or 4 years ago because some obscure package I had installed and forgotten about was holding it back. Now that I've carefully cleaned things up, I'm surprised to see several downgrades. Particularly as I do not know the reasons. For instance, `ThreadingUtilities v0.4.1 ⇒ v0.2.5` suggests an important downgrade. Maybe it's not a big deal, the console message doesn't state anything about it. Should I worry at all?

**Comment by KristofferC** [comment]
> Unless I'm mistaken, packages were downgraded without a prior warning (and without an explanation):

Pkg tries to give you the latest version of packages within the constraint that all those versions have to be compatible with each other. Sometimes upgrading one package makes it incompatible with other packages.

> Should I worry at all?

It depends, do you need ThreadingUtilities to be on v0.4? In that case, you should add

```
[compact]
ThreadingUtilities = 0.4
```

to your Project file.

**Comment by ptoche** [comment]
Thanks Kristoffer. Is there a way to run `Pkg.update()` while forcing `no-downgrades`? I'm not too bothered if there are minor downgrades, but I was surprised to find `Plots` being stuck at a version of several years back because it was being held back by some package I'd forgotten about, despite regularly running `Pkg.update()`. Packages like `ThreadingUtilities` are installed by other packages and it's not easy to know if I should force a more recent version or not. Is there a better way of managing my packages? Thanks.

**Comment by StefanKarpinski** [comment]
> Is there a way to run `Pkg.update()` while forcing `no-downgrades`?

Since the resolver prefers not to downgrade anything unless it's forced to, if there was a "no downgrades" option, you would instead get an error that there is no way to satisfy your version requirements, which is not any better. The only things that can really be improved here is making it clearer what the core conflict is that's causing a downgrade and potentially allowing you to choose which downgrades you'd prefer until those conflicts are resolved either by new releases of by fixing compat bounds.

**Comment by ptoche** [comment]
Thanks for your explanations Stefan. 

> making it clearer what the core conflict is that's causing a downgrade and potentially allowing you to choose which downgrades

Yes, that would be very useful indeed. Perhaps it would be too verbose for other users' taste and could be made available as an option. It's true that now that I'm aware of this issue, I won't be running `Pkg.update()` so often and ifever I do in the future, I'll be carefully reading the information printed to screen.

> you can make that choice is by putting your own version requirements into your project file.

Thanks for the suggestion. **Would that particular version requirement override all other requirements stated elsewhere?** Let me give an example. Suppose I want to have as recent a version of the `Plots` package as is reasonable, but I also use another package for some small calculation somewhere in a part of my package that is not called all that often. The package in question has the following line (literally copied):

    [[Plots]]
    deps = ["Base64", "Contour", "Dates", "FFMPEG", "FixedPointNumbers", "GR", "GeometryTypes", "JSON", "LinearAlgebra", "Measures", "NaNMath", "Pkg", "PlotThemes", "PlotUtils", "Printf", "REPL", "Random", "RecipesBase", "Reexport", "Requires",     "Showoff", "SparseArrays", "Statistics", "StatsBase", "UUIDs"]
    git-tree-sha1 = "0d7cf139b508defb467ac4fd655f4bd4d92f30cf"
    uuid = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
    version = "0.27.0"

Say I am not using the plotting capabilities of that package. **Would putting the version number of `Plots` in my project file override the version number requested by that other package?** 

Of course there are workarounds when you know what you want. I could contact the package maintainer (but perhaps that package really needs version "0.27.0" for certain things). Or I could clone the package and change the relevant lines myself.  Or I could go to the source code and copy-paste the relevant parts of that package that I need.

P.S. By "project file", you mean the `Manifest.toml` file, right? The `Project.toml` file has obscure entries like `Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"`, while the `Manifest.toml` gives version numbers.

**Comment by StefanKarpinski** [comment]
There is no overriding of requirements and specific versions aren't requested: there are compatibility bounds, often lower but sometimes upper; all requirements must be satisfied, including yours. When there's some conflict, there is more than one Pareto-optimal solution to the version selection problem. The resolver chooses one of these solutions, which uses a less recent version of some dependency, but it could have used a less recent version of some other dependency. If there was no conflict, it could just use the most recent version of all dependencies, but there is and it can't. You can guide it to choose a different solution by requiring that the dependency that it chose the older version of be installed at a higher version (if that's possible). The core problem here is that these problems are very complex and it's and open problem how to figure out and clearly present what the "core conflict" even is. If we knew how to do that, we would. Even computing what all the options are is hard and not something we can currently do.

**Comment by ptoche** [comment]
I see! In this case, an option to approve/reject downgrades one by one as they present themselves to the console sounds like maybe the only reasonable solution. Pushing responsibility to the user.

**Comment by ptoche** [comment]
Today I installed `Flux.jl` for the first time and noticed a significant downgrade of `StaticArrays` as a result:

    StaticArrays v1.1.2 ⇒ v0.12.5

It was the only downgrade. Everything else was upgraded. I'm posting here because you've been great at listening. I hope it's not too much noise for you.

I checked the `Manifest.toml`, but the version listed there was `1.1.1`. I tried to track the problem elsewhere. In the `Flux` manifest and project files, `StaticArrays` was listed as a dependency in two places: `ForwardDiff` and `DiffResults`, but both have a compat of `1.0`. So that couldn't be the cause. Does it mean it's necessarily a "nested" compatibility? e.g. `Flux` requires package `X` which in turns requires package `Y`, and package `Y` has a compact of `0.12.5`. Could it be that? And how can I track the problem down? 

I tried to delete `StaticArrays` from my `Manifest.toml` and `Project.toml`, but that caused Julia to crash, because `StaticArrays` is listed for some other package I have that is unrelated to `Flux` and dependencies. I had to undo the changes. It seems likely that I could upgrade `StaticArrays` significantly without causing problems elsewhere. It seems likely that the downgrade is caused by an unintended version dependency. But how to track it down? Last time (a few paragraphs above), I removed my environment and started from scratch, is there a better option?

Follow-up on the general topic of downgraded packages. In the last week, I have opened an issue to point out that their package was forcing a significant downgrade to some other package, and they very kindly updated their manifest. Is there a way for package maintainers to automate this?

**Comment by ptoche** [comment]
> > It depends, do you need ThreadingUtilities to be on v0.4? In that case, you should add
> 
> ```
> [compact]
> ThreadingUtilities = 0.4
> ```
> 
> to your Project file.

How does that work? I'm trying to force-upgrade `StaticArrays`. This is in my `Manifest.toml`:

    [[StaticArrays]]
    deps = ["LinearAlgebra", "Random", "Statistics"]
    git-tree-sha1 = "da4cf579416c81994afd6322365d00916c79b8ae"
    uuid = "90137ffa-7385-5640-81b9-e52037218182"
    version = "0.12.5"

If I change the last line to `version = "1.1.2"` Julia crashes. Do I remove the `deps`, `git-tree`, `uuid` lines as well? Thanks for your suggestion! 

Oh doing that at least helps me find incompatibilities. So one way to detect problems is to attempt to force a particular version in my `Manifest.toml` and investigate the error messages?

    ERROR: Unsatisfiable requirements detected for package StaticPolynomials [62e018b1]:
     StaticPolynomials [62e018b1] log:
     ├─possible versions are: 0.2.2-1.3.3 or uninstalled
     ├─restricted by compatibility requirements with StaticArrays [90137ffa] to versions: uninstalled
     │ └─StaticArrays [90137ffa] log:
     │   ├─possible versions are: 0.8.0-1.2.0 or uninstalled
     │   └─restricted to versions 1.1.2 by an explicit requirement, leaving only versions 1.1.2
     └─restricted by compatibility requirements with ImplicitPlots [55ecb840] to versions: 1.3.3 — no versions left
       └─ImplicitPlots [55ecb840] log:
         ├─possible versions are: 0.1.0-0.2.1 or uninstalled
         ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.2.1
         └─restricted by compatibility requirements with StaticArrays [90137ffa] to versions: 0.2.1 or uninstalled, leaving only versions: 0.2.1
           └─StaticArrays [90137ffa] log: see above

**Comment by ptoche** [comment]
I put the following in my `Project.toml` file and hopefully that will prevent `StaticArrays` from being downgraded in the future. 

    [deps]
    StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

    [compat]
    StaticArrays = "1.2.0"

I'd like to test to see if installing `ImplicitPlots` would downgrade `StaticArrays` again (1. the package author has updated the dependency. 2. I have the [compat] line above, so it shouldn't). Is there something equivalent to the `ask=TRUE` option in `R`? If you don't like what the package manager proposes to do (upgrades/downgrades), you can decline interactively:

    update.packages(ask = TRUE)

**Comment by ptoche** [comment]
Is it ever possible that packages will be downgraded when installing a package with no dependencies?

This just happened to me. 

<img width="467" alt="a" src="https://user-images.githubusercontent.com/6339274/119916816-16f2d500-bf1a-11eb-9342-e2af02f5deaf.png">


The `Project.toml` contains:

    [deps]

    [compat]
    julia = "1"

    [extras]
    Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

    [targets]
    test = ["Test"]
