### ISSUE TITLE
Feature Request: hooks for setting package preference prompt

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/Pkg.jl#2573]
I find for various packages, there are settings that users can configure, either via Preferences or other ways, in my own case, I provide options of choosing building a system image for the CLI package or not.

However the current package installation will supress everything come out of build scripts or package precompile, so there will be no way of asking user to choose how they want to install the package (e.g with a system image built during installation or not), I think the same thing applied for things like Flux, where user may want to choose not use CUDA at installation. Outside Julia's ecosystem, when installing a software, we usually have the freedom to select certain feature enabled or not via a prompt asking yes or no.

So I'm hoping Pkg to provide a mechanism or hooks for package developers to provide preferences selection and maybe Pkg can decide whether or when to bump the prompt. 

On the other hand, this feature could also be application specific which relates #1962

**Comment by fonsp** [comment]
As a user, I think the no-configuration install of Pkg is actually a nice feature (or limitation): it means that I can install anything I like without having to answer prompts about packages that I am not yet familiar with. 

I think this is especially important when sharing your work: any configurations should be included in my source code. When someone runs my project on their computer, there should be no prompts.

If it requires input, then perhaps your build script is more suited as a function that users call manually _after_ installing the package?

**Comment by fonsp** [comment]
Having a prompt would also require an alternative when Pkg is used outside of a terminal-based environment or on an automated system, such as github actions and https://github.com/fonsp/Pluto.jl/pull/844

**Comment by Roger-luo** [comment]
> As a user, I think the no-configuration installs of Pkg is actually a nice feature (or limitation): it means that I can install anything I like without having to answer prompts about packages that I am not yet familiar with.

Good point, I agree that install anything without having to answer prompts is nice, which I guess also means the package developers will take the job to try as hard as they can to figure out something working by default.

---

After some thinking on this, I think what I actually want is about generating the perference file for a user's environment (which is the `LocalPreference`) interactively, so that the user can share their preference directly, the current way of using Preference seems to be more developer oriented (e.g it requires macros to setup things). Ideally, I was hoping a terminal menu can be prompted by Pkg when user wants to change their preference.

I guess this can persumably implemented in an external package however, so I'll close this.
