### ISSUE TITLE
Package server is >18 hours behind

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/Pkg.jl#2574]
Version `0.14.7` was added to General 18 hours ago: https://github.com/JuliaRegistries/General/pull/37565

But I still cannot install it:
```
(jl_OBNnp1) pkg> registry update
    Updating registry at `~/.julia/registries/General`
    Updating registry at `~/.julia/registries/PackageNursery`
    Updating git-repo `https://github.com/j-fu/PackageNursery.jl.git`

(jl_OBNnp1) pkg> add Pluto@0.14.7
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Pluto [c3e4b0f8]:
 Pluto [c3e4b0f8] log:
 ├─possible versions are: 0.2.0-0.14.6 or uninstalled
 └─restricted to versions 0.14.7 by an explicit requirement — no versions left
```

I made a system to tag releases as "Recommended" (by typing "Recommended update" in the description: https://github.com/fonsp/Pluto.jl/releases), and users will be told to upgrade to 0.14.7 when they open an older version of Pluto. Because the package server is behind, they can't update.

**Comment by fredrikekre** [comment]
https://github.com/JuliaRegistries/General/issues/16777
