### ISSUE TITLE
[docs] `Pkg.develop` after `Pkg.activate`

### ISSUE THREAD

**Issue by ptoche** [JuliaLang/Pkg.jl#2578]
Just tried `Pkg.develop` for the first time and followed instructions in the [docs](https://pkgdocs.julialang.org/v1.6/api/#Pkg.develop). Unless I'm mistaken, one must not try to  `Pkg.develop` after `Pkg.activate`. If my understanding is correct, the user should be alerted under the `Pkg.develop` section, which is right above `Pkg.activate`. As I'm very new to the package and still don't understand much of it, I'm not offering a PR, with apologies to the busy developers. 

This is what happens:

    dir = expanduser("~/path/to/myPackage/")
    push!(LOAD_PATH, dir)
    using Pkg
    Pkg.activate(dir)
    Base.active_project()  # just to check that the package is activated
    Pkg.develop(PackageSpec(path=dir)) # fails if currently activated
    
    Path `/path/to/myPackage/` exists and looks like the correct package. Using existing path.
    ERROR: package `myPackage [89a7d78b]` has the same name or UUID as the active project

    Stacktrace:
     [1] pkgerror(msg::String)
       @ Pkg.Types /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:55
     [2] develop(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; shared::Bool, preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Iterators.Pairs{Symbol, Base.TTY, Tuple{Symbol}, NamedTuple{(:io,), Tuple{Base.TTY}}})
       @ Pkg.API /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:141
     [3] develop(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
       @ Pkg.API /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:79
     [4] develop(pkgs::Vector{Pkg.Types.PackageSpec})
       @ Pkg.API /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:77
     [5] #develop#14
       @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:74 [inlined]
     [6] develop(pkg::Pkg.Types.PackageSpec)
       @ Pkg.API /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:74
     [7] top-level scope
       @ REPL[6]:1

**Comment by KristofferC** [comment]
You just cannot `add` or `develop` a package that has the same UUID as the active project. If you think about it, it is kinda nonsense to do it because that package is already available so it doesn't make sense to try add it as a dependency.

**Comment by ptoche** [comment]
I see. Well the docs could just say that" "You cannot develop an active package". 

My first thought was that I needed to activate the package before developing it. Perhaps I don't really understand the meaning of "activate" and "develop"...
