### ISSUE TITLE
Check if updates are available without updating

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/Pkg.jl#2582]
For https://github.com/fonsp/Pluto.jl/pull/844, I would like to check whether updates are available and conditionally show an "update" button to the user.

Currently, my ideas for implementing this are:
1. Use the registry to find the latest version of direct dependencies, and compare to installed versions.
2. Make a temporary copy of the environment folder, and call `Pkg.update` on it.

Both have shortcomings: 1. does not respect compatibility bounds between direct dependencies: updating to the latest version might not be possible. 2. can take a long time, downloading code and jll binaries.

Any suggestions? My suggestion would be a "dry run" option to API calls like `update` that just update a manifest without downloading source or binaries. This would enable 2.

**Comment by fonsp** [comment]
Similarly, I would like to tell a user which version of `Example` will be installed, if it were added to the current environment. I currently use 1. from above to achieve this, but 2. would be better, with the same shortcoming and proposed solution.

**Comment by KristofferC** [comment]
We had a dry run command https://github.com/JuliaLang/Pkg.jl/pull/1367.

It was a bit tricky to define "dry" though because, for example, if you have packages that are added via git you need to update the git repository of those packages to know what the end result will be.

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/Pkg.jl/issues/1937
