### ISSUE TITLE
Compatibility debugging

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/Pkg.jl#2583]
In addition to https://github.com/JuliaLang/Pkg.jl/issues/2582, @staticfloat also proposed adding "compatibility debugging" features to IDEs ([like Pluto.jl](https://github.com/fonsp/Pluto.jl/pull/844)): if a package has a more recent version but it _cannot_ be installed, show the user _why_ not (i.e. which other direct dep is holding it back). 

I think that this is also valuable directly in the Pkg REPL. For example:

```julia
pkg> add Revise
... Revise 2 added! ...

pkg> # hmmm I heard that Revise 3 is available, let's try update!

pkg> update Revise
... No changes to Manifest ...
... Revise 3 is available but Example restricts it to 2 ...
```

Currently, I can achieve this by copying my environment to a temporary directory, and calling `add Revise@3.2.1` (if `3.2.1` is latest according to the registry). The resulting error message will be the debugging information I need. However, like in https://github.com/JuliaLang/Pkg.jl/issues/2582, a "dry run" option to `Pkg.add` would be very useful, allowing me to quickly call `Pkg.add` without downloading source or binaries.

In the future, perhaps this behaviour can be implemented into Pkg itself?

**Comment by KristofferC** [comment]
I did some WIP here https://github.com/JuliaLang/Pkg.jl/pull/2284. Might be able to take something from there.

**Comment by KristofferC** [comment]
Cosed by #2284

**Comment by KristofferC** [comment]
You can probably use the `status_compat_info` as an API and then display the result of that.
