### ISSUE TITLE
Add option to instantiate to delete Manifest.toml

### ISSUE THREAD

**Issue by ufechner7** [JuliaLang/Pkg.jl#2585]
Pkg.instantiate fails when new packages have been added to Project.toml and an old Manifest.toml exist.

This should never happen. Instead, instantiate should delete Manifest.toml in that case and try again.

**Comment by DilumAluthge** [comment]
This should do what you describe (i.e. ignore the `Manifest.toml` file even if it exists):

```julia
julia> Pkg.instantiate(; manifest = false)
```

**Comment by DilumAluthge** [comment]
We should probably document the `manifest` kwarg in the docstring for the `Pkg.instantiate` function.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaLang/Pkg.jl/issues/2586

**Comment by ufechner7** [comment]
Question:
If I execute Pkg.instantiate(; manifest = false), is the manifest updated?
