### ISSUE TITLE
Helpful message for `Pkg.add(url=...#forked_branch)`

### ISSUE THREAD

**Issue by anandijain** [JuliaLang/Pkg.jl#2588]
Basically, I'd like a way to check that `Pkg.add(url="https://github.com/LCSB-BioCore/SBML.jl#paulflang:pl/mk-species-units")` doesn't actually resolve to the intended branch (as it does not exist). 

`Pkg.add(url="https://github.com/LCSB-BioCore/SBML.jl#paulflang:pl/mk-species-units")` keeps turning into `https://github.com/LCSB-BioCore/SBML.jl#paulflang:pl/mk-species-units#master` with the `master` on the end, but fairly silently. 

I tried `Pkg.add(url="https://github.com/LCSB-BioCore/SBML.jl", rev="pl/mk-species-units")`, which gives what I'd expect `Pkg.add(url="https://github.com/LCSB-BioCore/SBML.jl#paulflang:pl/mk-species-units")`  to do, that is:
`ERROR: Did not find rev pl/mk-species-units in repository`

This scenario is quite confusing if you forget that a fork is on a different origin URL. 

I'm wondering if there is anything that can be done to make this lapse more obvious, particularly for newcomers. It bit me pretty hard for a while today

**Comment by KristofferC** [comment]
The status quo feels ok here. 

> This scenario is quite confusing if you forget that a fork is on a different origin URL.

It impossible to guard against all kind of user errors here. I think the current message should point you in enough of a direction to figure out that the `repo` entry is wrong.
