### ISSUE TITLE
KeyError: key UUID("...") not found in CI on nightly (1.7)

### ISSUE THREAD

**Issue by jagot** [JuliaLang/Pkg.jl#2602]
Possibly related to #2554

While updating compat bounds, I noticed that tests on nightly failed, due to not finding a test dependency, although that package ([RollingFunctions.jl](https://github.com/JeffreySarnoff/RollingFunctions.jl)) has been published since forever:
https://github.com/JuliaApproximation/CompactBases.jl/runs/2771496296?check_suite_focus=true#step:6:11
The tests pass without problems on Julia 1.5 and 1.6.

@simeonschaub thought it could have something to do with the new Manifest format.

**Comment by KristofferC** [comment]
It has to do with code that is conditionally enabled when CompatHelper is running:

```
[ Info: This is a Dependabot/CompatHelper job, so `force_latest_compatible_version` has been set to `true`
```

**Comment by DilumAluthge** [comment]
I should have a fix for this available soon.
