### ISSUE TITLE
API request: get installed version (from Manifest)

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/Pkg.jl#2605]
I can run `Pkg.status(;manifest=true)` to get the installed versions from all packages, but there seems to be no public API to programmatically:

> get the installed version (or `PackageSpec`) given a package name/uuid (or partial `PackageSpec`)

My implementation:
```julia
select = first ∘ Iterators.filter

function get_manifest_version(ctx, package_name)
	entry = select(e -> e.name == package_name, values(ctx.env.manifest))
    entry.version
end
```

# Use case

Show which version is installed in the GUI of https://github.com/fonsp/Pluto.jl/pull/844

<img src='https://user-images.githubusercontent.com/6933510/121338233-99699480-c91d-11eb-99a9-3ee687ae6c3b.png' height=100>

**Comment by KristofferC** [comment]
Why not use `Pkg.dependencies()`?

**Comment by fonsp** [comment]
That's what I needed, thanks!
