### ISSUE TITLE
Pkg never adds a `julia_version` entry to an upgraded manifest

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#2621]
If you upgrade a manifest, you will get a v2 manifest without a `julia_version` entry. If you then make a package operation, it will still not have a `julia_version` entry. It seems it is now impossible for an old manifest to fully transition to a properly upgraded manifest. What I expected to happen is that on the first package operation with the v2 manifest, the `julia_version` entry is set.

**Comment by IanButterworth** [comment]
Fixed in #2620
