### ISSUE TITLE
gc() on v1.6 tries to read manifests from v1.8

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/Pkg.jl#2627]
I just ran a `Pkg.gc()` on `v1.6` and I get a bunch of errors of the form:

```
┌ Error: Could not parse entry for `deps`
└ @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/manifest.jl:150
┌ Warning: Reading manifest file at /home/sabae/.julia/environments/v1.8/Manifest.toml failed with error
│   exception =
│    MethodError: no method matching get(::Pair{String, Any}, ::String, ::Nothing)
│    Closest candidates are:
│      get(::WeakKeyDict{K, V} where V, ::Any, ::Any) where K at weakkeydict.jl:140
│      get(::Test.GenericDict, ::Any, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1663
│      get(::IdDict{K, V}, ::Any, ::Any) where {K, V} at iddict.jl:86
│      ...
└ @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:504
```

This is because the usage logs are shared among all Julia versions, and so when we GC from an older version of Julia, we'll try to read manifests that are from _all_ usage.  The operation continues, but it does mean that Julia v1.6 is going to mark all v1.8-only package versions as un-installed (because it won't find any manifests which contain those package versions), which is a little scary.  Hopefully users will mostly be running `Pkg.gc()` from `v1.8` and not `v1.6`.

**Comment by IanButterworth** [comment]
This should be handled properly in 1.6.2, but yeah if people don't upgrade to that it's a problem

**Comment by KristofferC** [comment]
1.6.2 is released
