### ISSUE TITLE
Pkg install prompt should not error on ^D

### ISSUE THREAD

**Issue by Keno** [JuliaLang/Pkg.jl#2630]
When hitting ^D to abort the add prompt, this should be interpreted as `n` and return to the REPL.
At the moment it throws an ugly error: 
```
 │ Package Flux not found, but a package named Flux is available from a registry. 
 │ Install package?
 │   (Diffractor) pkg> add Flux 
 └ (y/n) [y]: ERROR: MethodError: no method matching lowercase(::Nothing)
Closest candidates are:
  lowercase(::T) where T<:AbstractChar at strings/unicode.jl:249
  lowercase(::AbstractString) at strings/unicode.jl:540
Stacktrace:
  [1] try_prompt_pkg_add(pkgs::Vector{Symbol})
    @ Pkg.REPLMode ~/julia/usr/share/julia/stdlib/v1.8/Pkg/src/REPLMode/REPLMode.jl:691
```

**Comment by DilumAluthge** [comment]
Probably the same for other interrupts? E.g. Control-C?

**Comment by DilumAluthge** [comment]
Here's one possible wrinkle:

@StefanKarpinski suggested on Slack that if someone presses enter without typing `y` or `n`, we should interpret that as `y`. I agree.

So what we want is:
1. `y` => yes
2. `n` => no
3. Press enter without entering any characters => yes
4. Control-D => no
5. Control-C => no

Can we actually distinguish between number 3 and number 4?

**Comment by IanButterworth** [comment]
Yep, that's possible and what #2631 does
