### ISSUE TITLE
Versioned stdlibs are broken on `Pkg#master`

### ISSUE THREAD

**Issue by antimon2** [JuliaLang/Pkg.jl#2638]
I built and tried Julia-1.7.0-beta1, and Pkg went wrong.
When I run `up`, it's explicitly added the version number `1.6.0` to Pkg in Manifest.toml, and then `resolve` shows an error.

````julia
(@v1.7) pkg> resolve
ERROR: Unsatisfiable requirements detected for package Pkg [44cfe95a]:
 Pkg [44cfe95a] log:
 ├─possible versions are: 1.7.0 or uninstalled
 └─restricted to versions 1.6.0 by an explicit requirement — no versions left
````

I tried to set the version number to `1.7.0` by directly editing Manifest.toml, but it reverts to `1.6.0` when I run `resolve` or `up` again.

What's wrong?

versioninfo():

```julia
Julia Version 1.7.0-beta1
Commit a15fbbc809 (2021-06-17 16:39 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.0 (ORCJIT, skylake)
```

Is there any other information I should show?

**Comment by KristofferC** [comment]
I guess this is fixed.
