### ISSUE TITLE
Show package version and whether it's the latest after `] add` command

### ISSUE THREAD

**Issue by Wikunia** [JuliaLang/Pkg.jl#2682]
Currently the output of `add OrdinaryDiffEq` looks roughly like:
```
(tmp.4uUytIOkzt) pkg> add OrdinaryDiffEq
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
   Installed PreallocationTools ─ v0.1.0
   Installed SLEEFPirates ─────── v0.6.25
   Installed Tables ───────────── v1.5.0
   Installed SparseDiffTools ──── v1.16.1
   Installed DiffEqBase ───────── v6.71.0
   Installed Setfield ─────────── v0.7.1
   Installed StaticArrays ─────── v1.2.10
   Installed OrdinaryDiffEq ───── v5.60.2
   Installed NLSolversBase ────── v7.8.1
   Installed Polyester ────────── v0.3.8
   Installed VectorizationBase ── v0.20.29
   Installed LoopVectorization ── v0.12.61
```
and then shows the important info:
```
[1dea7af3] + OrdinaryDiffEq v5.60.2
``` 
for a few milliseconds
and creating tenth of lines about which versions of packages are added to the Manifest file.

at the very end it shows:
```
Precompiling project...
  26 dependencies successfully precompiled in 99 seconds (60 already precompiled)
```

I think the most important information the user wants is missing here:
- Which version is installed (this is actually printed but isn't prominent in the list of stuff that most people probably don't understand)
- Is the installed version the newest version available?

The second question is important when one has multiple packages in the environment and they aren't compatible with each other. Currently this can result in installing an ancient version of a package without notifying the user. That user will probably checked the latest version of the docs though and is frustrated that something doesn't work and either moves away from the package or creates an issue where they still might not realize that it is an old version.

I suggest therefore to end the `] add command` with something like:

`Package v0.5 was added as the newest version v0.7 isn't compatible`
or `The latest version of Package (v0.7) was successfully installed`

Maybe the upper one in orange and the lower one in green. 

I'm happy to work on a PR for this. If you have any pointers of where I should start I would be very grateful.

**Comment by IanButterworth** [comment]
There's a lot of support for this, and an issue already https://github.com/JuliaLang/Pkg.jl/issues/1655 but perhaps part of this issue is just raising the prominence of which package was installed in the output? Perhaps that's unique, so worth keeping this issue open for?

**Comment by Wikunia** [comment]
I feel it's distinct as that one is written for `up` and I think knowing in either case which version is installed even if it is the newest is useful

**Comment by KristofferC** [comment]
I think it is ok if this is now shown in the output for `add` but only when you do `status`. I'm updating https://github.com/JuliaLang/Pkg.jl/pull/2284 now and you can see how you like that when it's done.

**Comment by Wikunia** [comment]
I don't think that this is enough. New users want to know whether the docs they check are matching the version they installed. They can double check that with your PR but they can't just assume it.

I don't assume that the PR will reduce the number of issues created on packages where something didn't fit the documentation simply because an older version was installed unknowingly.

**Comment by robsmith11** [comment]
I really think `add` should ask the user to confirm whether he really wants to install a given version if it's not the latest possible version.

So often I assume it installed latest version only to realize later that it ended up installing an old version because of some random conflict.

**Comment by KristofferC** [comment]
If you have requirements for what version you need, the way to most easily handle that is to add that to the `[compat]` section of your Project.toml file. So if you need version `2.x` of package `Foo` you add:

```
[compat]
Foo = "2.x"
```

to the Project file.

**Comment by KristofferC** [comment]
Done in https://github.com/JuliaLang/Pkg.jl/pull/2906
