### ISSUE TITLE
Provide entry point for color customization

### ISSUE THREAD

**Issue by Arkoniak** [JuliaLang/Pkg.jl#2683]
Pkg.jl uses hardcoded colors for generating output and unfortunately color choice is not always suitable for all users for various reasons.

I propose to use the following approach instead of colors hardcoding:

```julia
# define somewhere at the beginning

const COLOR = Ref((; foo = :red, bar = :green))

# and later in the code, when color is needed
printstyled("what you need to print", COLOR[].foo)
```

This simple change does not provide full-fledged color theme switching by itself (this probably should be implemented JuliaLang/julia#41435), but it provides an entry point for all future color theme related stuff. I.e. all user level convenience functions would just modify this variable one way or another. And anyway this proposal allows color customization right here and now (maybe slightly cumbersome) unlike the current situation.

Implementing this feature looks like a good beginner PR, doesn't require large modifications of the code base and it solves color issues.

**Comment by KristofferC** [comment]
See https://github.com/JuliaLang/julia/issues/41435

**Comment by Arkoniak** [comment]
Yes, I've made reference to this issue in the topic itself. Since I do not want to duplicate answers, here is a link to a comment in different issue: https://github.com/JuliaLang/julia/issues/41791#issuecomment-893285058

I've made issue in Pkg.jl, since it looks like a different package and can be adjusted separately from main julia code base. If it's not the case, then I can close this issue.

**Comment by KristofferC** [comment]
Sorry for not reading carefully. I think it is better that a proper interface is developed in julia base, and then we can adopt that.
