### ISSUE TITLE
Allow `precompile` to take packages as argument

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#2713]
```jl
(@v1.6) pkg> precompile Plots
ERROR: Wrong number of arguments
```

would be nice to be able to do. What do you think @IanButterworth?

**Comment by IanButterworth** [comment]
Yeah. It's not trivial to implement I think, but definitely doable.

**Comment by KristofferC** [comment]
Isn't it "just" to tweak:

https://github.com/JuliaLang/Pkg.jl/blob/7a35bbe98197d49c867f93cc421f1ebea869d814/src/API.jl#L1035-L1038

?
