### ISSUE TITLE
Feature: Install package prompt; option to choose default environment

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/Pkg.jl#2721]
The prompt to install a package that's in the registry but not already in the default or package environment is great. One slight pain point is that if you're working in a package, sometimes you'd rather add a new package into the default environment (e.g. BenchmarkTools).

Currently, you'd have to do this:
```julia
julia> using BenchmarkTools
 │ Package BenchmarkTools not found, but a package named BenchmarkTools is available from a registry. 
 │ Install package?
 │   (MyPackage) pkg> add BenchmarkTools
 └ (y/n) [y]: n
]activate
]add BenchmarkTools
]activate .
using BenchmarkTools
```

Suggestion: Add an option to the prompt ("d"?) to install the package to the default environment, if not already in the default environment.

**Comment by DilumAluthge** [comment]
Just out of curiosity, is this functionality implemented in Pkg or in Base Julia? I thought it lived in Base.

@IanButterworth

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/2669

**Comment by IanButterworth** [comment]
> Just out of curiosity, is this functionality implemented in Pkg or in Base Julia?

The code to make a list of packages that are missing and the hook is in Base. The package search and prompt is in Pkg.
