### ISSUE TITLE
Pkg can not create Manifest.toml as “nt authority\system” user account on Windows

### ISSUE THREAD

**Issue by A1-Mathematik** [JuliaLang/Pkg.jl#2735]
Hi all :)

I will just link to my discourse post

https://discourse.julialang.org/t/pkg-can-not-create-manifest-toml-as-nt-authority-system-user-account-on-windows/68452

**Comment by KristofferC** [comment]
I don't know the details of permissions on Windows but you get a `Permission denied` error so that user is not allowed to write that file it seems. You probably get the same if you do `julia> touch(joinpath("my_project, Project.toml"))`

**Comment by A1-Mathematik** [comment]
The file was on a network drive and I had no permission to touch it. Thank you
