### ISSUE TITLE
Registry updates significantly slower on 1.7

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg.jl#2745]
Are precompile-statements optimized for the old system?

Almost 5x slowdown:
```
$ time julia16 --project=. -e 'using Pkg; Pkg.update()' 2> /dev/null
real    0m0.773s
user    0m0.678s
sys     0m0.182s

$ time julia17 --project=. -e 'using Pkg; Pkg.update()' 2> /dev/null
real    0m3.651s
user    0m3.591s
sys     0m0.193s
```

Interpreted mode almost 35x slowdown:
```
$ time julia16 --project=. --compile=min --optimize=0 -e 'using Pkg; Pkg.update()' 2> /dev/null
real    0m0.328s
user    0m0.285s
sys     0m0.129s

$ time julia17 --project=. --compile=min --optimize=0 -e 'using Pkg; Pkg.update()' 2> /dev/null
real    0m11.389s
user    0m11.351s
sys     0m0.180s
```

**Comment by KristofferC** [comment]
I don't think we ever precompiled a registry update. But it looks like there is significantly more compilation now, indeed. 

1.7:

```
julia> @time Pkg.update()
...
  1.902799 seconds (3.37 M allocations: 195.200 MiB, 2.13% gc time)

julia> empty!(Pkg.Registry.REGISTRY_CACHE)


julia> @time Pkg.update()
...
  0.231274 seconds (1.17 M allocations: 78.057 MiB, 6.74% gc time)
```

**Comment by fredrikekre** [comment]
My timings were for the "no op" case though, where the tree-hash is the same. That shouldn't read the tarball?

**Comment by KristofferC** [comment]
Mine too. Why would it not read the tarball?

**Comment by fredrikekre** [comment]
The tree hash is stored in a separate file, no?

**Comment by KristofferC** [comment]
Yes but first, you are not calling  `Pkg.Registry.update` but the normal update which uses the resolver etc. And even for `Pkg.Registry.update` we call `reachable_registies`:

https://github.com/JuliaLang/Pkg.jl/blob/13b7861518dcfceebfc01566c329a2b2faa62623/src/Registry/Registry.jl#L343

which "materializes" the registry.

**Comment by fredrikekre** [comment]
Huge slowdowns for e.g. `Pkg.status` too (3x and 8x):
```
$ time julia16 -e 'using Pkg; Pkg.status()' > /dev/null        
real    0m0.517s
user    0m0.569s
sys     0m0.144s

$ time julia17 -e 'using Pkg; Pkg.status()' > /dev/null        
real    0m1.479s
user    0m1.567s
sys     0m0.189s

$ time julia16 --compile=min --optimize=0 -e 'using Pkg; Pkg.st
atus()' > /dev/null
real    0m0.165s
user    0m0.172s
sys     0m0.091s

$ time julia17 --compile=min --optimize=0 -e 'using Pkg; Pkg.st
atus()' > /dev/null                                                                            
real    0m11.148s
user    0m11.168s
sys     0m0.173s
```

**Comment by KristofferC** [comment]
That also uncompresses the registry because it eagerly collects the registries. Should probably be changed to only do that when using it...

**Comment by KristofferC** [comment]
I think this can be closed now.
