### ISSUE TITLE
`ensure_artifacts_installed` does not use pkg server

### ISSUE THREAD

**Issue by melonedo** [JuliaLang/Pkg.jl#2751]
On 1.6.3, downloading artifacts that are specified by standalone toml file by `ensure_artifact_installed` only downloads from the specified source, can we make it use pkg server for faster downloading?

**Comment by KristofferC** [comment]
I don't see why that would be the case. From a cursory glance:

https://github.com/JuliaLang/Pkg.jl/blob/964e9eecd2b5095b9c536ffb1a4eb371d78214fa/src/Artifacts.jl#L418-L424

it seems it should use Pkg server.

**Comment by melonedo** [comment]
Thanks! I checked further, this is because the pkg server did not have the requested artifact.
