### ISSUE TITLE
Document offline mode and the `Pkg.offline` function in the manual?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/Pkg.jl#2822]
I can't seem to find offline mode (or the `Pkg.offline` function) in the manual.

Is offline mode part of the public API of Pkg? If so, can we add it to the manual?

**Comment by fredrikekre** [comment]
https://pkgdocs.julialang.org/dev/api/#Pkg.offline

**Comment by DilumAluthge** [comment]
Oh that's my bad, I was checking `https://pkgdocs.julialang.org/`, which redirects to `https://pkgdocs.julialang.org/v1/`.

**Comment by KristofferC** [comment]
Might as well backport it though?
