### ISSUE TITLE
couldn't load a branch of package with bugfix

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/Pkg.jl#2852]
Most likely this my own a misuse of `Pkg`, but in case it is an actual bug, I thought I would report it.  I am fixing a bug (https://github.com/JuliaCollections/DataStructures.jl/issues/773) in DataStructures.jl; the branch with fix is called `fix_sortedmultidict_bug` on github.  But I wasn't able to load this branch (Julia 1.6.3) and I'm not sure why.
```
julia> Pkg.add(url="https://github.com/StephenVavasis/DataStructures.jl#fix_sortedmultidict_bug")
     Cloning git-repo `https://github.com/StephenVavasis/DataStructures.jl#fix_sortedmultidict_bug`
    Updating git-repo `https://github.com/StephenVavasis/DataStructures.jl#fix_sortedmultidict_bug`
ERROR: could not find project file in package at `https://github.com/StephenVavasis/DataStructures.jl#fix_sortedmultidict_bug` maybe `subdir` needs to be specified
```

User oxinabox suggested that I should bypass Pkg and instead clone my branch with the `git` command, and then start Julia with the `--project="."` flag.  This worked.

**Comment by fredrikekre** [comment]
https://pkgdocs.julialang.org/stable/api/#Package-API-Reference-1
