### ISSUE TITLE
artifacts from stdlibs will always be deleted (with --all / after 7 days)

### ISSUE THREAD

**Issue by benlorenz** [JuliaLang/Pkg.jl#2874]
I have a package which relies on the headers of GMP_jll and MPFR_jll at runtime, so we ensure those are downloaded during precompilation with some code adapted from this: https://github.com/JuliaLang/julia/pull/38797#issuecomment-741953480

But the usage of these artifacts does not seem to be tracked and they will always be deleted by `] gc` after the cleanup timeout (or immediately when using `--all`):

```julia
(mpfr) pkg> st 
      Status `/tmp/mpfr/Project.toml`
  [3a97d323] MPFR_jll

julia> using MPFR_jll; full_artifact_dir(MPFR_jll)
"/home/lorenz/.julia/artifacts/5f30672c17afb8ec61558a3b8fbeba51c9a00945"

(mpfr) pkg> gc --all --verbose
[.......]
     Deleted `~/.julia/artifacts/5f30672c17afb8ec61558a3b8fbeba51c9a00945` (2.754 MiB)
     Deleted 1 artifact installation (2.754 MiB)
```

Is there a way to avoid this? (which should also cover the case that `gc` is triggered from a different julia installation with a different stdlib version)

PS: Code installing the artifacts:
```julia
using Pkg.Artifacts

function full_artifact_dir(m::Module)
   artifacts_toml = joinpath(dirname(dirname(Base.pathof(m))), "StdlibArtifacts.toml")

   # If this file exists, it's a stdlib JLL and we must download the artifact ourselves
   if isfile(artifacts_toml)
      # we need to remove the _jll for the artifact name
      meta = artifact_meta(string(m)[1:end-4], artifacts_toml)
      hash = Base.SHA1(meta["git-tree-sha1"])
      if !artifact_exists(hash)
         dl_info = first(meta["download"])
         download_artifact(hash, dl_info["url"], dl_info["sha256"])
      end
      return artifact_path(hash)
   else
      # Otherwise, we can just use the artifact directory given to us by the module
      return m.artifact_dir
   end
end
```

**Comment by staticfloat** [comment]
Invoking `download_artifact()` directly like that is not enough to tell Pkg that the artifact denoted by `hash` belongs to the file pointed to by `artifacts_toml`.
If you're installing things in this manner, you'll need to manually call `Pkg.Types.write_env_usage(artifacts_toml, "artifact_usage.toml")`, to tell Pkg to not remove any artifacts that are listed in `artifacts_toml` as long as that TOML file exists on disk.

**Comment by benlorenz** [comment]
Thanks a lot for the explanation, we will add this to our code!
