### ISSUE TITLE
https://pkgdocs.julialang.org/stable/ gives the docs for Julia 1.1.2

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/Pkg.jl#2913]
https://pkgdocs.julialang.org/stable/ gives the docs for Julia 1.1.2

I would say that we should either:
1. Fix it so that `/stable` automatically updates to point to the latest stable release of Julia whenever a new release is made.
2. Delete `/stable/*` and just tell people to use https://pkgdocs.julialang.org/ or https://pkgdocs.julialang.org/v1/

I would probably recommend that we do option 2, but I don't feel too strongly either way.

**Comment by DilumAluthge** [comment]
@KristofferC @fredrikekre Is it okay I just delete `/stable` and call it a day?

**Comment by KristofferC** [comment]
I would say so, yes.

**Comment by fredrikekre** [comment]
I will run the outdated warning snippet and fix it

**Comment by DilumAluthge** [comment]
Thanks Fredrik!
