### ISSUE TITLE
CUDA_compat artifact has different git-tree-sha on different systems

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/Pkg.jl#2929]
This `CUDA_compat` artifact is giving different git tree sha values on different systems
https://github.com/JuliaGPU/CUDA.jl/blob/273781b1dabf856dc1d17ef244f8049f22c80628/Artifacts.toml#L375

On my system both git and julia 1.6.5 and master agrees with the expected 
```
~/Downloads/d9b5623143a996f924e7a5eee9d06354cb650d73$ git log --pretty=format:'%T %s'
d9b5623143a996f924e7a5eee9d06354cb650d73 init commit
```
```
julia> bytes2hex(Pkg.GitTools.tree_hash("/home/ian/.julia/artifacts/d9b5623143a996f924e7a5eee9d06354cb650d73"))
"d9b5623143a996f924e7a5eee9d06354cb650d73"
```

i.e. no complaints when
```
pkg> activate --temp
pkg> add CUDA
julia> using CUDA
julia> CUDA.versioninfo()
```

However...

On a particular ubuntu github runner with a typical file system it hits
```
 Downloading artifact: CUDA_compat
┌ Error: Tree Hash Mismatch!
│   Expected git-tree-sha1:   d9b5623143a996f924e7a5eee9d06354cb650d73
│   Calculated git-tree-sha1: b618eadab05abb3bef21da981a51b6f4f0183b27
└ @ Pkg.Artifacts /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Artifacts.jl:368
```

and on @giordano's system both julia and git give that other sha
```
CUDA_compat.v11.5.50.x86_64-linux-gnu% git log --pretty=format:'%T %s'
b618eadab05abb3bef21da981a51b6f4f0183b27 first commit
```
```
% for j in julia-13 julia-14 julia-15 julia-16 julia julia-master; do ${j} -E 'print(VERSION, " "); using Pkg; bytes2hex(Pkg.GitTools.tree_hash("/tmp/mozilla_mose0/CUDA_compat.v11.5.50.x86_64-linux-gnu"))'; done
1.3.1 "b618eadab05abb3bef21da981a51b6f4f0183b27"
1.4.2 "b618eadab05abb3bef21da981a51b6f4f0183b27"
1.5.4 "b618eadab05abb3bef21da981a51b6f4f0183b27"
1.6.4 "b618eadab05abb3bef21da981a51b6f4f0183b27"
1.7.1 "b618eadab05abb3bef21da981a51b6f4f0183b27"
1.8.0-DEV.1138 "b618eadab05abb3bef21da981a51b6f4f0183b27"
```

@staticfloat any idea??

**Comment by giordano** [comment]
Note that the same artifact is also in [`CUDA_compat_jll`](https://github.com/JuliaBinaryWrappers/CUDA_compat_jll.jl): https://github.com/JuliaBinaryWrappers/CUDA_compat_jll.jl/blob/bd512f429381c57f88183fbd97a7f4d10fd5df03/Artifacts.toml#L3.  Here the git-tree-sha1 (computed on amdci7) is `b618eadab05abb3bef21da981a51b6f4f0183b27`, the same as what I get locally.

To summarise: julia and git agree, but the git-tree-sha1 is consistently inconsistent on different machines.

**Comment by IanButterworth** [comment]
This turns out to be confusion due to a bad `Artifacts.toml` and some systems being on the pkgserver and the others not, rather than a hashing bug.

The confusion between @giordano and I was that we were looking at two different tarballs, with two different git tree hashes, stemming from the fact CUDA.jl has a messed up Artifacts.toml file (mismatch between url/sha256 sum and git tree hash).

And I was puzzled by not being able to reproduce the issue (mismatched tree hash) on different machines because only one was using the PkgServer, which was directly fetching the tarball with the expected tree hash (and the sha256 check is skipped), while on the other machine not using the PkgServer it's fetching the tarball by url (thus running into the mismatch).

Big thanks to @staticfloat and @giordano for doing most of the figuring out here.

Actions:
- Fix the bad Artifacts.toml file at CUDA.jl cc. @maleadt  https://github.com/JuliaGPU/CUDA.jl/issues/1309
- For debugging make it so that `Pkg.Artifacts.download_artifact` prints out the URL it’s downloading from when `verbose=true`
- Perhaps also add a standard pkg/pkgserver setup header to `julia-runtests` to highlight system differences
