### ISSUE TITLE
Pkg Crashes with update

### ISSUE THREAD

**Issue by kzapfe** [JuliaLang/Pkg.jl#2955]
Hello.
I did a full system update on an Arch Linux machine.
My Julia is on purpose frozen at 1.4.1 version. 
After the update the IJulia kernel in Jupyter keeps dying.
So I went to the Julia Prompt in a terminal and entered Pkg Mode.
If I try to update the next messages appear and then it crashes:
```
Updating registry at `~/.julia/registries/General`
Updating git-repo `https:://github.com/JuliaRegistries/General.git`
Bus error (`core` generated)
```
I have absolutely no idea what is going on.

**Comment by KristofferC** [comment]
How did you install Julia? Is it an official julia download from https://julialang.org/downloads/oldreleases/#v142_may_23_2020?

**Comment by kzapfe** [comment]
I installed Julia through Arch package manager, pacman, circa may 2020, that, as it is advertised, is just a front end that grabs the official repository. I never had problems using arch or gentoo package managers for such kind of repos.

**Comment by KristofferC** [comment]
Try with the official build and see if it works?
