### ISSUE TITLE
Project.toml bot?

### ISSUE THREAD

**Issue by rofinn** [JuliaLang/Pkg.jl#299]
It'd be nice if there was a bot that made PRs to repos to add the Project.toml file. We could also include links to the latest documentation and where they should file issues (it wasn't clear if I should be reporting issues against Pkg3.jl, Pkg.jl or base julia).

**Comment by KristofferC** [comment]
Pkg3.jl is redirected here and here is a good place. Yes such a bot is highly desirable and definitely planned. The plan right now is to finish up https://github.com/JuliaLang/Pkg.jl/pull/234 and then make a function to add project files to existing packages. Then a bot would be a "wrapper" over that function.
