### ISSUE TITLE
Incomprehensible message for dependency error

### ISSUE THREAD

**Issue by getzze** [JuliaLang/Pkg.jl#2994]
```julia
(@v1.7) pkg> dev StatsPlots
     Cloning git-repo `https://github.com/JuliaPlots/StatsPlots.jl.git`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package AbstractOperators [d9c5613a]:
 AbstractOperators [d9c5613a] log:
 ├─possible versions are: 0.1.0-0.2.2 or uninstalled
 ├─restricted by compatibility requirements with StructuredOptimization [46cd3e9d] to versions: 0.1.0-0.2.2
 │ └─StructuredOptimization [46cd3e9d] log:
 │   ├─possible versions are: 0.0.1-0.3.0 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions 0.0.1-0.3.0
 └─restricted by compatibility requirements with AbstractFFTs [621f4979] to versions: uninstalled — no versions left
   └─AbstractFFTs [621f4979] log:
     ├─possible versions are: 0.3.0-1.1.0 or uninstalled
     └─restricted to versions 1.1.0-1 by StatsPlots [f3b207a7], leaving only versions 1.1.0
       └─StatsPlots [f3b207a7] log:
         ├─possible versions are: 0.14.33 or uninstalled
         └─StatsPlots [f3b207a7] is fixed to version 0.14.33
```

`StructuredOptimization` depends on `AbstractOperators`, so the line "restricted by compatibility requirements with StructuredOptimization" makes sense to me (but it doesn't seem to be the issue according to the message).
But `AbstractFFTs` doesn't depend on `AbstractOperators`, actually the opposite is true... At least the message should be different in both cases.
Then nothing is explaining why 'AbstractFFTs` is restricting this poor `AbstractOperators` to be uninstalled. I mean 'AbstractFFTs` is pretty harmless.
One information that is missing is also the current versions of the packages (`AbstractFFTs`, `AbstractOperators`, ...) so I can start looking if the problem comes with outdated packages first. After digging for 10min I realized that `AbstractFFTs` is stuck to v0.5 instead of 1.1 for example. (but again it doesn't seem to be the problem as `AbstractOperators` requires `AbstractFFTs` >= v0.4.1)

Solution:

```julia
(@v1.7) pkg> rm StructuredOptimization
```
`AbstractOperators` got removed and `AbstractFFTs` got bumped ot v1.1 as a bonus.
And I can install the dev version of `StatsModels`.

I'm really lost with these compatibilty messages...

**Comment by KristofferC** [comment]
```
 └─AbstractFFTs [621f4979] log:
     ├─possible versions are: 0.3.0-1.1.0 or uninstalled
     └─restricted to versions 1.1.0-1 by StatsPlots [f3b207a7], leaving only versions 1.1.0
```

So AbstractFFTs are required to be at 1.1.0 since that is the only version that is compatible with StatsPlots. 

But looking at https://github.com/JuliaRegistries/General/blob/d47497008bcc970203b872edbf715430d63952ca/A/AbstractOperators/Compat.toml AbstractOperators prevents AbstractFFTs from being at version 1.1.0.

This is a contradiction and therefore there is no solution. You can see it simpler via

```

(jl_D9S3Ln) pkg> add AbstractOperators AbstractFFTs@1.1.0
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package AbstractFFTs [621f4979]:
 AbstractFFTs [621f4979] log:
 ├─possible versions are: 0.3.0-1.1.0 or uninstalled
 ├─restricted to versions 1.1.0 by an explicit requirement, leaving only versions 1.1.0
 └─restricted by compatibility requirements with AbstractOperators [d9c5613a] to versions: 0.3.0-0.5.0 — no versions left
   └─AbstractOperators [d9c5613a] log:
     ├─possible versions are: 0.1.0-0.2.2 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.2.2
```

The error message seems to be perfectly correct here so I will close this issue. But I can agree that it requires some experience to interpret it.
