### ISSUE TITLE
Undefined variable in `Pkg.Registry.uncompress`

### ISSUE THREAD

**Issue by giordano** [JuliaLang/Pkg.jl#3003]
https://github.com/JuliaLang/Pkg.jl/blob/3aa150553cbbdcef54770142544704afcdd02f6c/src/Registry/registry_instance.jl#L86
`path` is undefined

**Comment by DilumAluthge** [comment]
Duplicate of https://github.com/JuliaLang/Pkg.jl/issues/2899
