### ISSUE TITLE
LocalPreferences.toml are added upon `pkg> up`

### ISSUE THREAD

**Issue by charleskawczynski** [JuliaLang/Pkg.jl#3014]
LocalPreferences.toml are added upon `pkg> up`, and they shouldn't.

I'm not sure about the best or most compact / reproducible way to report this is. But, until I (intentionally or accidentally) delete `ck/pkg_issue`, this can be reproduced with:

```
git clone https://github.com/CliMA/TurbulenceConvection.jl
cd TurbulenceConvection.jl
git checkout ck/pkg_issue
julia --project
] up
```

`LocalPreferences.toml` now exists in `TurbulenceConvection.jl/`.

**Comment by staticfloat** [comment]
The issue is that `CPUSummary` recently added a thing that unconditionally sets a preference: https://github.com/JuliaSIMD/CPUSummary.jl/blob/main/src/CPUSummary.jl#L19

**Comment by DilumAluthge** [comment]
Even so, that preference is being set when `Pkg.test` is run, right? That's why `LocalPreferences.toml` is being created at `test/LocalPreferences.toml`.

So it still seems to me that the `LocalPreferences.toml` file should be created in a temporary directory.

**Comment by KristofferC** [comment]
Yeah, I don't see why

**Comment by staticfloat** [comment]
It happens at precompile time; that's a top-level statement that is calling `set_preferences!()`, so it's not happening at test time, it's happening during the precompilation phase, probably while we're instantiating.  Do we instantiate the test environment in a temporary directory, or do we only run the tests in a temporary directory?

**Comment by DilumAluthge** [comment]
I was under the impression that we resolve the test environment in the temporary directory.

**Comment by charleskawczynski** [comment]
I don't know if it's related, but I'm often also seeing the Project.toml getting modified upon `pkg> up`, the order of the compat and deps are switched, and this entry often pops up:

```toml
[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
```

**Comment by goerz** [comment]
Is this something that can be fixed within `Pkg`, or is this a bug that should be reported to `CPUSummary`?

I hope this can be fixed soon. It's pretty irritating to have my `test/Project.toml` rewritten every time I run the tests.

**Comment by chriselrod** [comment]
CPUSummary depends on Preferences.jl.

It tries to check if `using Hwloc; Hwloc.gettopology()` works and doesn't segfault Julia:
https://github.com/JuliaSIMD/CPUSummary.jl/blob/91846c77aed015cf2ba2fe738197e5b6aa64eb04/src/CPUSummary.jl#L14-L20
The problem is, this check always returns `false`, even though it works when I try it in the REPL.
There was a recent PR that tried to fix/improve things, but it did not work:
https://github.com/JuliaSIMD/CPUSummary.jl/pull/7

Perhaps the best solution moving forward is to give up on Hwloc.

**Comment by DilumAluthge** [comment]
I don't think that this is an issue with CPUSummary.

I think the issue here is that Pkg should be instantiating in a temporary directory.

**Comment by KristofferC** [comment]
I don't think Pkg does anything bad here.
