### ISSUE TITLE
Pkg depends on `stdin` being open

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/Pkg.jl#3062]
https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2022-04/15/AAindex.primary.log

We could possibly substitute `devnull` here transparently when the stream was previously exhausted and therefore now closed, but I don't know if that is ideal. In general though, passing `stdin` to a concurrent process is a terrible idea. Either you might want `RawFD(0)`, or just don't.

**Comment by IanButterworth** [comment]
The goal of https://github.com/JuliaLang/Pkg.jl/pull/2933 where the stdin forwarding was added, was to try to increase the chances of the child process being interrupted. It appears to work well in regular usage.

I'm afraid I don't quite understand your suggestion.

**Comment by vtjnash** [comment]
This needs to be fixed ASAP since it is breaking CI. I tried to revert automatically, but github couldn't do it

**Comment by IanButterworth** [comment]
I don't think a full revert of #2933 is needed. Just the stdin forwarding needs removing
https://github.com/JuliaLang/Pkg.jl/blob/7676431149332ae400a805632082b12263c20269/src/Operations.jl#L1747
