### ISSUE TITLE
Windows formatting terminal characters error

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/Pkg.jl#3068]
This just started happening, but it's only on one computer so I'm not sure the ultimate cause. Also causes the precompile progress display to use up many lines instead of update in-place.

![image](https://user-images.githubusercontent.com/1438610/164861340-0285f1cd-94d0-4608-b1a4-5be620fb275d.png)

It might be related to the custom registry? I'm guessing some special character isn't getting a closing for some reason. If I remove the custom registry, it seems to be okay again. Mostly observed with the `up` command.

This is on Julia 1.8.0-beta3, on Windows 11 22H2 22598.200, with Windows Terminal 1.12.10983.0

**Comment by DanBerge** [comment]
I am having the same issue with a custom registry.  At first I thought it might have something to do with the banner on the SSH session, but I am getting the same issue with a local only registry also.

![image](https://user-images.githubusercontent.com/36931035/166253377-a3c7e76c-f967-4b7e-8c36-8cf64e4d9afc.png)


This is on Julia 1.7.1., Windows 10 Version 21H1 19044.1645

**Comment by BioTurboNick** [comment]
@DanBerge what's your Windows Terminal version, if that's what you're using?

**Comment by KristofferC** [comment]
It would be helpful if you could try with different terminals / different settings as much as possible to try narrow it down.

**Comment by DanBerge** [comment]
I forgot Windows Terminal is not the Command Prompt, so I'm not sure if it has a version or how to find it.  I also get the same issue in PowerShell and VSCode using PowerShell.

![image](https://user-images.githubusercontent.com/36931035/166264341-6973053a-ae6c-4e30-8c5b-f6a5e8f3b789.png)

**Comment by DanBerge** [comment]
I've tracked it down more, and maybe @BioTurboNick is doing the same.  In order to get the SSH private keys working I had to set `ENV["JULIA_PKG_USE_CLI_GIT"]=true` so that it would find the SSH key set with ENV["SSH_KEY"PATH".  I don't remember where I saw to use the CLI GIT.

**Comment by BioTurboNick** [comment]
I haven't had a chance to do more, but I also had to set the CLI env variable; I believe because it wasn't properly finding the key and/or using the ssh-agent?

However, I'm on a system at the moment where that first env variable is set and it doesn't have the issue. I didn't set the other variable you refer to though.

**Comment by KristofferC** [comment]
I remember an issue where if you used git CLI in a julia session it would mess up your color printing in the terminal. It was either in this repo or the julia repo. I'll try find it...

**Comment by BioTurboNick** [comment]
I found this: https://github.com/JuliaLang/julia/issues/43273 but it related to loss of any color. Whatever is happening here seems to be restricted to the precompilation steps, somehow?

**Comment by BioTurboNick** [comment]
Confirmed that on the machine where this is happening, switching between `ENV["JULIA_PKG_USE_CLI_GIT"]` states switches the behavior. However, it fails to update from the custom registry as a result.

**Comment by BioTurboNick** [comment]
Possibly a hint? https://stackoverflow.com/questions/66000833/what-could-disable-terminal-ansi-color-code

**Comment by KristofferC** [comment]
This is what I was thinking about https://github.com/JuliaLang/julia/issues/26894. It wasn't git specifically, it was any external command.

What happens if you manually run `git` from Julia. Does it also disable ansi colors?

**Comment by BioTurboNick** [comment]
Well, I just verified it happens in 1.6.6 too. And again, only if CLI git is in use.

Actually, the terminal cursor also becomes invisible here. Weird.

I tried running a few git commands, at the shell prompt and with `run`, but no issue there. I didn't see git's normal colors but no control codes either.

**Comment by BioTurboNick** [comment]
Maybe this is instructive. When running `test Pkg`, the trouble starts just after the `add: input checking` test set, and it affects the display of the test results. All the way up until the `resolve` test set, where it resumes normality. Then it breaks again after `all` and is restored again after `cycles`.

Then it breaks again after `not collecting multiple package instances #1570` and restores after `adding and upgrading different versions`.

Then breaks again after `invalid repo url` and restores again after `Suggest `Pkg.develop` instead of `Pkg.add``

Then breaks again after `tab completion`, then restores again after `unit test for REPLMode.promptf`

Then breaks again after `issue #2587, PR #2589: `Pkg.PackageSpec` accepts `Union{UUID, AbstractString, Nothing}` for `uuid`` and restores after `Artifact archival`

**Comment by IanButterworth** [comment]
Still happening? I haven't seen new reports?

**Comment by BioTurboNick** [comment]
I can't recall the last time I saw this.

**Comment by IanButterworth** [comment]
Nice.
