### ISSUE TITLE
Feature request: install package to temp environment through REPL menu

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/Pkg.jl#3126]
Currently, on v1.8,
```julia
julia> using ArrayLayouts
 │ Package ArrayLayouts not found, but a package named ArrayLayouts is available from a registry. 
 │ Install package?
 │   (@v1.8) pkg> add ArrayLayouts 
 └ (y/n/o) [y]: 
``` 
selecting `o` I obtain
```julia
julia> using ArrayLayouts
 │ Package ArrayLayouts not found, but a package named ArrayLayouts is available from a registry. 
 │ Install package?
 │   (@v1.8) pkg> add ArrayLayouts 
 └ Select environment:
 > 1: `~/.julia/environments/v1.8/Project.toml` (@v#.#)
```
However, in my workflow, I just want to experiment with the package, and want to add it to a temporary environment. Currently, I need to activate a temp environment and install it there, for which I need to switch to the pkg mode (or run `using Pkg; Pkg.activate(temp=true)`). In either case, I must exit the menu. It would be convenient if a temp environment option was provided in the menu.

**Comment by IanButterworth** [comment]
This was discussed and rejected as a feature here, but an alternative approach to achieve this is given https://github.com/JuliaLang/Pkg.jl/pull/2669#issuecomment-884502870

**Comment by jishnub** [comment]
Thanks, this certainly works. I'll close this.
