### ISSUE TITLE
`Pkg.activate()` doesn't seem to activate the home package

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/Pkg.jl#3127]
In a project directory at
```console
abcd/ $ pwd
/home/jishnu/Dropbox/JuliaPackages/abcd
```
I launch julia using
```console
abcd/ $ julia-1.8 --project=.
```
In julia
```julia
julia> LOAD_PATH
4-element Vector{String}:
 "@"
 "/tmp/jl_ztlVMr"
 "@v#.#"
 "@stdlib"

julia> Base.active_project()
"/home/jishnu/Dropbox/JuliaPackages/abcd/Project.toml"

julia> using OffsetArrays
 │ Package OffsetArrays not found, but a package named OffsetArrays is available from a registry. 
 │ Install package?
 │   (abcd) pkg> add OffsetArrays 
 └ Select environment:
   1: `~/Dropbox/JuliaPackages/abcd/Project.toml` (@)
 > 2: `/tmp/jl_ztlVMr` (/tmp/jl_ztlVMr)
   3: `~/.julia/environments/v1.8/Project.toml` (@v#.#)
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `/tmp/jl_ztlVMr/Project.toml`
  [6fe1bfb0] + OffsetArrays v1.12.7
    Updating `/tmp/jl_ztlVMr/Manifest.toml`
  [79e6a3ab] + Adapt v3.3.3
  [6fe1bfb0] + OffsetArrays v1.12.7
  [56f22d72] + Artifacts
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [e66e0078] + CompilerSupportLibraries_jll v0.5.2+0
  [4536629a] + OpenBLAS_jll v0.3.20+0
  [8e850b90] + libblastrampoline_jll v5.1.0+0

julia> Base.active_project()
"/home/jishnu/Dropbox/JuliaPackages/abcd/Project.toml"

julia> Base.current_project()
"/home/jishnu/Dropbox/JuliaPackages/abcd/Project.toml"

julia> using Pkg; Pkg.activate()
  Activating project at `/tmp/jl_ztlVMr`

julia> Base.active_project()
"/tmp/jl_ztlVMr/Project.toml"

julia> versioninfo()
Julia Version 1.8.0-rc1
Commit 6368fdc656 (2022-05-27 18:33 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, tigerlake)
  Threads: 1 on 8 virtual cores
Environment:
  LD_LIBRARY_PATH = :/usr/lib/x86_64-linux-gnu/gtk-3.0/modules
  JULIA_EDITOR = vim
```
The docstring says "If no argument is given to activate, then activate the home project. The home project is specified by either the --project command line option to the julia executable, or the `JULIA_PROJECT` environment variable.". In this case, the specified `--project` flag is not being activated anymore, and `JULIA_PROJECT` is not set. In this case, `Pkg.activate()` should not change the path at all, as the home project is already activated.

**Comment by danielwe** [comment]
Here's another and perhaps simpler MWE:

```bash
user@host:~/myenv$ julia --project=.
```

```julia
julia> using Pkg

julia> Pkg.status()
Status `~/myenv/Project.toml` (empty project)

julia> Pkg.activate(; temp=true)
  Activating new project at `/tmp/jl_gmivnG`

julia> Pkg.status()
Status `/tmp/jl_gmivnG/Project.toml` (empty project)

julia> Pkg.activate()
  Activating project at `~/.julia/environments/v1.8`

julia> Pkg.status()
Status `~/.julia/environments/v1.8/Project.toml`
  [...]
```

Clearly `Pkg.activate()` activates the default environment `@v#.#`, not the environment specified on the command line as claimed in the docs.

**Comment by kleinschmidt** [comment]
It looks like in this case, we're calling into `Base.activate_project()`, so I think this may actually be a base issue 

https://github.com/JuliaLang/Pkg.jl/blob/daf02a458ae6daa402a5dd6683c40d6910325c4e/src/API.jl#L1820

**Comment by kleinschmidt** [comment]
Okay, the relevant bits in base AFAICT are:
- `active_project(search_load_path=true)` will go through the LOAD_PATH and return the first project it finds: https://github.com/JuliaLang/julia/blob/c6fc12c9eee6aa4fb1f584840e5a0f988009d82f/base/initdefs.jl#L304-L311
- `@` is skipped in this search
- `@` in load path corresopnds to the "home project" according to https://github.com/JuliaLang/julia/blob/c6fc12c9eee6aa4fb1f584840e5a0f988009d82f/base/initdefs.jl#L143C1-L145
- there's a comment in the source for `expand_load_path` that suggests that `@` should be expanded early, but I still see the literal `@` in my load path even after starting with `JULIA_PROJECT` set:

```
julia> LOAD_PATH
3-element Vector{String}:
 "@"
 "@v#.#"
 "@stdlib"

julia> ENV["JULIA_PROJECT"]
"/Users/dkleinschmidt/.julia/dev/Example"
```

- `expand_load_path` calls back into `active_project` for `@`, with `search_load_path=false` (I guess to avoid infinite loop?)

So what this all comes down to is that `active_project` ends up completely ignoring `@`, which corresponds to the "home project"
