### ISSUE TITLE
]add "url#branch" behavior

### ISSUE THREAD

**Issue by thofma** [JuliaLang/Pkg.jl#3133]
Hm, I just stumbled upon the fact that
```
]add "https://github.com/blub/bla.jl#branchname"
```
just installs the master branch of the repo. In `]st` it then shows up as
```
  [e1435946] + blabla `https://github.com/blub/bla.jl#branchname#master`
```
Is this a bug or a feature? I know that the right thing is
```
add https://github.com/blub/bla.jl#branchname
```
but it took me a few minutes to find the problem. I would have expected an error.

**Comment by fredrikekre** [comment]
Since you are quoting the whole URL you basically tell Pkg *not* to split it up into pieces.
