### ISSUE TITLE
Platform specific requirement don't work ?

### ISSUE THREAD

**Issue by jonathanBieler** [JuliaLang/Pkg.jl#317]
I'm trying to build Cairo on OS X but it's trying to build WinRPM even though it should only be build on windows:

https://github.com/JuliaGraphics/Cairo.jl/blob/master/REQUIRE

Is this supported or it's a bug ?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/Pkg.jl/issues/165

Will happen.

**Comment by jonathanBieler** [comment]
My bad I should have searched better. That said if would be nice to have this fixed, since it's blocking working on downstream packages.

**Comment by KristofferC** [comment]
WinRPM will fail to build but you should still be able to work on it? What is the exact problem?
