### ISSUE TITLE
Detect modification of packages that are supposed to be immutable

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#32]
If a user accidentally modifies a package (for example by using `@edit`), the package could easily break and I don't think there is a way to detect it.

Perhaps there should be some option of doing an integrity check that checks that the tree hashes in the saved packages actually are what they are supposed to be?

**Comment by KristofferC** [comment]
Stefan had a thought about making the files read only.

**Comment by mauro3** [comment]
+1 to both read-only and a check (preferably run at each update).  I just got bitten by a corrupted file and it took me some time to figure out what is going on.

**Comment by KristofferC** [comment]
Would probably need something like https://github.com/simonbyrne/GitX.jl/commit/886bbddfb9d2508b04c6722718967fe558486349 to verify the tree hash.

Would just setting `-w` on all files work well on all OS?
