### ISSUE TITLE
Artifact hash errors on nightly 64-bit

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#3212]
https://github.com/JuliaLang/Pkg.jl/actions/runs/3157873266/jobs/5139255214

```
Artifacts.toml Utilities: Test Failed at /home/runner/work/Pkg.jl/Pkg.jl/test/artifacts.jl:237
  Expression: artifact_hash("foo_txt", artifacts_toml) == hash2
   Evaluated: SHA1("5679c650921bf0f891224295dd95572a5e9db8da") == SHA1("09795a47b3e5d3bcc4b44beace0072e1c3eb8aab")
```

Not sure what changed.

**Comment by KristofferC** [comment]
Also fails on https://github.com/JuliaLang/Pkg.jl/pull/3178 which I just updated.

**Comment by DilumAluthge** [comment]
Interesting. They're still passing on Buildkite... what's different between Buildkite and GitHub Actions? The hardware, maybe?

**Comment by KristofferC** [comment]
Tests passed on https://github.com/JuliaLang/Pkg.jl/pull/3205 now... Something intermittent with GitHub serving bad stuff maybe..?

**Comment by vtjnash** [comment]
We got a SHA failure in rr https://buildkite.com/julialang/julia-master/builds/17283#0183faf8-d50b-41b7-bffb-10f237f7b6c0. Not sure how useful it is though

**Comment by gbaraldi** [comment]
I'm able to reproduce this locally on x86 linux. I believe we might have a data race in this test.
```julia
using Pkg.Artifacts
using Test
using TOML
using Pkg
path = mktempdir()
function torture()
    while true
        hash = create_artifact() do path
        open(joinpath(path, "foo.txt"), "w") do io
            print(io, "hello, world!")
        end
    end
    artifacts_toml = joinpath(path, "Artifacts.toml")
    bind_artifact!(artifacts_toml, "foo_txt", hash;  force=true)
    hash2 = create_artifact() do path
        open(joinpath(path, "foo.txt"), "w") do io
            print(io, "goodbye, world!")
        end
    end
    @test_throws ErrorException bind_artifact!(artifacts_toml, "foo_txt", hash2)
    # sleep(0.1)
    @test artifact_hash("foo_txt", artifacts_toml) == hash
    # sleep(0.1)
    bind_artifact!(artifacts_toml, "foo_txt", hash2; force=true)
    @test artifact_hash("foo_txt", artifacts_toml) == hash2
end
end

torture()
```
Works for me, those sleeps make if fail less often and incresing them enough makes it pass.
