### ISSUE TITLE
https://discourse.julialang.org/t/package-is-not-updating-but-why/88338/4

### ISSUE THREAD

**Issue by kafisatz** [JuliaLang/Pkg.jl#3218]
I wanted to share an example where
`Pkg.status(; outdated=true)`

does not provide any reasons why the package (`DataFrames`) does not update.
Also, the marker for DataFrames is is green, i.e. `^` , but Pkg.up() does not update the package. Neither does it report a reason why.

As shown here, forcing the version to be the most recent (`]add DataFrames@1.4`), does eventually give the reason.
https://discourse.julialang.org/t/package-is-not-updating-but-why/88338/4

Not sure if this is intended behavior (feel free to close this if yes) or indeed an issue.

**Comment by KristofferC** [comment]
I think https://discourse.julialang.org/t/package-is-not-updating-but-why/88338/5?u=kristoffer.carlsson explains it.
