### ISSUE TITLE
Surfacing warnings during precompilation

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/Pkg.jl#3224]
We're trying to troubleshoot an issue that only occurs during precompilation on GitHub CI, but the precompilation process seems to hide such output. Is there a way to show that information during CI? And/or to force display of a warning?

It's currently producing an error, which shows up in the testing pass but not in the build pass. We'd like to change it to a warning because it's a survivable issue and it shouldn't hold up release, but we'd like to be able to track it.

**Comment by IanButterworth** [comment]
Calling `Pkg.precompile()` explicitly prints all errors verbosely. The automatic precompilation doesn't.

**Comment by BioTurboNick** [comment]
The first precompilation is happening automatically after `Pkg.build(verbose = true)` is called. Maybe when `verbose = true`, that should use the verbose version of `Pkg.precompile()`?

**Comment by KristofferC** [comment]
You can disable the automatic precompilation and then call it explicitly perhaps.

**Comment by t-bltg** [comment]
Debug messages from [loading `GR_jll`](https://github.com/jheinen/GR.jl/blob/744fa7c759e1f20b2d61eeb11895df3eec996e11/src/preferences.jl#L6) are also hidden making debugging harder.

As seen trying to help debug `Plots` precompilation in  https://discourse.julialang.org/t/cannot-precompile-plots-jl-due-to-gr/88230/9 or in https://discourse.julialang.org/t/julia-fails-to-precompile-plots/88411/20.

**Comment by vtjnash** [comment]
Oof, that GR_jll code seems like a bad idea. It seems like that is supposed to be a configuration option (https://github.com/jheinen/GR.jl/blob/744fa7c759e1f20b2d61eeb11895df3eec996e11/src/preferences.jl#L38), but it is not hooked up correctly (and is ignoring the whole existing Artifacts system design for customizations)

**Comment by IanButterworth** [comment]
Implemented in https://github.com/JuliaLang/Pkg.jl/pull/3319
