### ISSUE TITLE
Pkg.instantiate() doesn't download packages inside dockerfile

### ISSUE THREAD

**Issue by egonik-unlp** [JuliaLang/Pkg.jl#3228]
I'm trying to make a very simple julia project containerized. I'm using [this](https://gist.github.com/egonik-unlp/72c69e7238a8ee9977ac1042724eaef1) Dockerfile and [this](https://gist.github.com/egonik-unlp/22b4c428292f04d35f81f4cf26d2edcf) docker-compose.yml file. All instructions I believe are needed for installing packages are needed, yet when i run the image, i get "so and so package is not installed" (so and so being the first package needed in my code). when I get a terminal running inside my container I get this output:

```julia
(goodvibes) pkg> status
  Installing known registries into `~/.julia`
Status `~/Project.toml`
→ [336ed68f] CSV v0.10.4
→ [a93c6f00] DataFrames v1.4.1
→ [194296ae] LibPQ v1.14.1
→ [9c8b4983] LightXML v0.9.0
→ [d96e819e] Parameters v0.12.3
→ [748b5efa] PostgresORM v0.5.3
→ [f269a46b] TimeZones v1.9.0
  [8ba89e20] Distributed
Info Packages marked with → are not downloaded, use `instantiate` to download
```

versioninfo() output: 
```julia
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 4 virtual cores
Environment:
  JULIA_GPG = 3673DF529D9049477F76B37566E3C7DC03D6E495
  JULIA_VERSION = 1.8.2
  JULIA_PATH = /usr/local/julia
```

[Manifest and Project files](https://gist.github.com/egonik-unlp/6347cb2c6fa2e1e3dc679a804567cda1)

**Comment by fredrikekre** [comment]
I can not reproduce this.
