### ISSUE TITLE
Pkg docs stuck at 1.7.1

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/Pkg.jl#3231]
https://pkgdocs.julialang.org/v1/

**Comment by fredrikekre** [comment]
Just pushed tags and made releases for 1.7.2, 1.7.3, 1.8.0, 1.8.1, 1.8.2.

**Comment by fredrikekre** [comment]
Not sure why they didn't trigger CI though?

**Comment by DilumAluthge** [comment]
Did you create lightweight tags or annotated tags?

I just did the following:
1. Deleted your 1.8.2 release
2. Deleted your `v1.8.2` tag
3. Created a new annotated `v1.8.2` tag locally (pointing to the exact same commit that your now-deleted `v1.8.2` tag pointed to).
4. Pushed my annotated `v1.8.2` tag to GitHub.
5. Created a new 1.8.2 release that points to my `v1.8.2` tag.

And CI was triggered correctly: https://github.com/JuliaLang/Pkg.jl/actions?query=event%3Apush+branch%3Av1.8.2

**Comment by DilumAluthge** [comment]
That is strange. How did you push the tags? It shouldn't make a difference, but I used SSH public key auth.

**Comment by DilumAluthge** [comment]
Can you try deleting one of the releases/tags and then re-tagging and pushing? Maybe there was a brief GitHub outage when you pushed, and that's why the jobs didn't start?

I can't really think of what would have been different when you did it versus when I did it.

**Comment by IanButterworth** [comment]
Thanks!

**Comment by KristofferC** [comment]
Good catch!

**Comment by fredrikekre** [comment]
>  used SSH public key auth.

Same.

Some people have reported TagBot not triggering builds either, even when using SSH keys. I wonder if it is related. But there are not such things as different permissions for keys I don't think? And if the key was outdated or something, then it shouldn't be able to even push the tags. Very strange.

**Comment by DilumAluthge** [comment]
Yeah, I'm very confused.

**Comment by IanButterworth** [comment]
They just announced this but I assume unrelated https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/
