### ISSUE TITLE
update downgrades specific package for no reason

### ISSUE THREAD

**Issue by tom-plaa** [JuliaLang/Pkg.jl#3232]
(Issue has been edited by Kristoffer)

Creating a project file with the content:

```
[deps]
AlphaStableDistributions = "f20549b4-2d50-407f-863c-cdd202ba59a3"
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
``` 

and running `resolve` gives a package of the dependency MAT as:

```
⌃ [23992714] + MAT v0.8.1
```

However, just explicitly upgrading `MAT`: 

```
pkg> up MAT
  No Changes to `~/JuliaTests/downgrade/Project.toml`
    Updating `~/JuliaTests/downgrade/Manifest.toml`
  [a74b3585] - Blosc v0.7.3
  [f67ccb44] ↑ HDF5 v0.13.6 ⇒ v0.16.12
  [23992714] ↑ MAT v0.8.1 ⇒ v0.10.3
  [0b7ba130] - Blosc_jll v1.21.1+0
  [5ced341a] - Lz4_jll v1.9.3+0
  [3161d3a3] - Zstd_jll v1.5.2+0
```

gives an improved resolution with no packages downgraded. An `up` with no arguments downgrades the package:

```
pkg> up
  No Changes to `~/JuliaTests/downgrade/Project.toml`
    Updating `~/JuliaTests/downgrade/Manifest.toml`
  [a74b3585] + Blosc v0.7.3
⌅ [f67ccb44] ↓ HDF5 v0.16.12 ⇒ v0.13.6
⌃ [23992714] ↓ MAT v0.10.3 ⇒ v0.8.1
  [0b7ba130] + Blosc_jll v1.21.1+0
  [5ced341a] + Lz4_jll v1.9.3+0
  [3161d3a3] + Zstd_jll v1.5.2+0
```

Adding `MAT` to the project seems to fix it:

```
(downgrade) pkg> add MAT
   Resolving package versions...
    Updating `~/JuliaTests/downgrade/Project.toml`
⌃ [23992714] + MAT v0.8.1
  No Changes to `~/JuliaTests/downgrade/Manifest.toml`

(downgrade) pkg> up
    Updating `~/JuliaTests/downgrade/Project.toml`
  [23992714] ↑ MAT v0.8.1 ⇒ v0.10.3
    Updating `~/JuliaTests/downgrade/Manifest.toml`
  [a74b3585] - Blosc v0.7.3
  [f67ccb44] ↑ HDF5 v0.13.6 ⇒ v0.16.12
  [23992714] ↑ MAT v0.8.1 ⇒ v0.10.3
  [0b7ba130] - Blosc_jll v1.21.1+0
  [5ced341a] - Lz4_jll v1.9.3+0
  [3161d3a3] - Zstd_jll v1.5.2+0
```

This is on Julia 1.8.

Check the thread at [Package manager always downgrades specific package for no reason](https://discourse.julialang.org/t/package-manager-always-downgrades-specific-package-for-no-reason/89018/10) for a lengthier discussion.

**Comment by tom-plaa** [comment]
thanks for editing the issue description, @KristofferC

**Comment by carlobaldassi** [comment]
I'll take a look as soon as I can

**Comment by carlobaldassi** [comment]
So, I've been investigating this, and I have found a reduced test case that reproduces the problem. The bad news is that I did not find any bugs, it looks like parts of the dependency graphs are very intricate and the solver finds a local optimum. In tries to improve it, but it hits some intermediate versions of HDF5 which would require to downgrade Compat (previous versions don't require it; later versions are compatible with the version that needs to be installed to satisfy the other packages).

The only solution that I can think about at the moment is the following: if the solver finds a feasible solution, it could just throw away all the package versions below the ones in the solution (which hopefully should be most of them), simplify the graph (again, hopefully by a significant amount), and restart from scratch; this would be iterated until a fixed point is reached. I have reasons to believe that this would work, at least in this case, but I haven't tried yet.

**Comment by tom-plaa** [comment]
If you start iterating with the initial state being the local optimum, won't it just be stuck in place?
From the linked merge request, I see that this doesn't appear to be the case, so that's pretty good.

**Comment by carlobaldassi** [comment]
The reason why it does not necessarily get stuck is that the solver is heuristic (which is why it may get trapped in a local optimum in the first place), and simplifying the graph (by forbidding versions and propagating the consequences of doing that) can help considerably.

As for improving the solving algorithm: one may argue that the change in #3258 does exactly that, and it is the best I could come up with so far. It still does not offer guarantees of optimality, but it should get closer. The resolve problem in general is NP-C, meaning that the main issue is how to avoid an exponential running time at least for practically relevant scenarios (in full generality it's impossible). So for example I could not think of a better way to escape local optima such as the one in this issue, at least within the current solving scheme.

**Comment by tom-plaa** [comment]
Got it. Thanks for looking into this!
