### ISSUE TITLE
Nonexisting depot creates toml files in wrong place

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/Pkg.jl#325]
Nonexisting depot:
```
/tmp/julia-22590d529d/bin$ rm -rf /tmp/foo; JULIA_DEPOT_PATH=/tmp/foo ./julia -e 'using Pkg; pkg"add Compat"'
   Cloning default registries into /tmp/foo/registries
   Cloning registry Uncurated from "https://github.com/JuliaRegistries/Uncurated.git"
  Updating registry at `/tmp/foo/registries/Uncurated`
  Updating git-repo `https://github.com/JuliaRegistries/Uncurated.git`
 Resolving package versions...
Downloaded Compat ─ v0.66.0
  Updating `/tmp/julia-22590d529d/share/julia/stdlib/v0.7/Project.toml`
  [34da2185] + Compat v0.66.0
  Updating `/tmp/julia-22590d529d/share/julia/stdlib/v0.7/Manifest.toml`
  [34da2185] + Compat v0.66.0
  ...
```

Existing, but empty depot:
```
/tmp/julia-22590d529d/bin$ rm -rf /tmp/bar; mkdir /tmp/bar; JULIA_DEPOT_PATH=/tmp/bar ./julia -e 'using Pkg; pkg"add Compat"'
   Cloning default registries into /tmp/bar/registries
   Cloning registry Uncurated from "https://github.com/JuliaRegistries/Uncurated.git"
  Updating registry at `/tmp/bar/registries/Uncurated`
  Updating git-repo `https://github.com/JuliaRegistries/Uncurated.git`
 Resolving package versions...
Downloaded Compat ─ v0.66.0
  Updating `/tmp/bar/environments/v0.7/Project.toml`
  [34da2185] + Compat v0.66.0
  Updating `/tmp/bar/environments/v0.7/Manifest.toml`
  [34da2185] + Compat v0.66.0
  ...
```

Note differences in `Updating` paths.

Broke my set-up on one occasion, making it impossible to import `Pkg` itself.

**Comment by maleadt** [comment]
> Broke my set-up on one occasion, making it impossible to import `Pkg` itself.

This is exactly like what I got on CI: https://github.com/JuliaLang/julia/pull/27145#issuecomment-390567366, but maybe @fredrikekre found another reason for that error.

**Comment by KristofferC** [comment]
@StefanKarpinski you wrote the logic here:

https://github.com/JuliaLang/Pkg.jl/blob/5dfe2810614024bf7433f34c819c88844b87dc3d/src/Types.jl#L474-L483

What happens is that the stdlib is last in LOAD_PATH and since `find_env` doesn't find anything if `DEPOT_PATH` is empty we will hit the case where we just use the last LOAD_PATH as our project path:

```
➜  rm -rf /tmp/foo; JULIA_DEPOT_PATH=/tmp/foo ./julia -e 'using Pkg; @show Pkg.Types.EnvCache().project_file'

((Pkg.Types).EnvCache()).project_file = "/Users/kristoffer/julia/usr/share/julia/stdlib/v0.7/Project.toml"
```

**Comment by barche** [comment]
I think I am affected by this too. I built Julia master from source, and after that my `LOAD_PATH` is:

```
julia> LOAD_PATH
2-element Array{Any,1}:
 Any[]           
 "/usr/lib/julia"
```

When trying to add packages, I get a permission error on `/usr/lib/julia/Project.toml`

**Comment by barche** [comment]
OK, so stupidly I had the `JULIA_LOAD_PATH` environment variable set to `/usr/lib/julia`, so that is why it broke for me.

**Comment by KristofferC** [comment]
Bump.
