### ISSUE TITLE
Warning: duplicate UUID in Manifest

### ISSUE THREAD

**Issue by mbesancon** [JuliaLang/Pkg.jl#329]
During all package operations, getting the warning:
```julia
  Updating `~/.julia/environments/v0.7/Manifest.toml`
┌ Warning: Duplicate UUID in manifest: 44cfe95a-1eb2-52ea-b672-e2afdf69b78f
└ @ Pkg.Display Display.jl:192
┌ Warning: Duplicate UUID in manifest: 44cfe95a-1eb2-52ea-b672-e2afdf69b78f
```

~/.julia/environments/v0.7/Manifest.toml
```
[[Pkg]]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Pkg3]]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
```

**Comment by KristofferC** [comment]
Yes, Pkg3 was renamed to Pkg so perhaps you have an old Manifest with Pkg3 in it. You should be able to remove [[Pkg3]] and rename all the deps entries in the Manifest that has Pkg3 in it to Pkg.
