### ISSUE TITLE
Are we able to create our own registries yet?

### ISSUE THREAD

**Issue by BenJWard** [JuliaLang/Pkg.jl#331]
If so how? I'd love to get a BioJulia registry going. I don't see much about developing and releasing packages in the docs for Pkg yet, mostly stuff about Projects (which is awesome btw).

**Comment by StefanKarpinski** [comment]
It is possible but I think it's too early at this point. I recommend waiting a bit.

**Comment by KristofferC** [comment]
Can be done now.
