### ISSUE TITLE
Allow `add localpath`

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/Pkg.jl#334]
It didn't occur to me that to add a local package to a project, I should do `dev localpath`; in my mind, the `dev` command is more about checking out master of a project so I can make changes & upstream. I almost exclusively use it w/ existing packages that have already been "added" to a project. Hence, I think it makes sense to have `add localpath` command, for adding a local package to a project.

**Comment by KristofferC** [comment]
> In my mind, the dev command is more about checking out master of a project so I can make changes & upstream

This is a failure of the documentation then. `dev` is about putting a `path` entry in your manifest, i.e. loading packages which files are considered mutable. `add localpath` already has a meaning which is to track the git repository at `localpath` (in exactly the same way as `add giturl` does).

**Comment by quinnj** [comment]
Ah, so the problem I ran into was the fact that my individual packages themselves weren't git repos, but I had all 3 in a single git repo (i.e. each package's parent directory was the git repo). That makes sense now. But my package directories _did_ have Project.toml & Manifest.toml files; couldn't that be enough to be considered "a package"? Why the strong requirement on the package directory itself being a git repository?

**Comment by KristofferC** [comment]
The idea I had for the distinction between `add` and `dev` is that if you just use `add` you will never introduce mutable state into your Project. The state is identified by the tree hash and when you use your project again 2 months later everything is the same. With dev we just put a path in the manifest but who knows what happens to those files the next time we use the project.

**Comment by KristofferC** [comment]
Marking as doc because `add localpath` exists and has a meaning.

**Comment by KristofferC** [comment]
Think this can be closed with the new docs.
