### ISSUE TITLE
Test environment doesn't inherit number of interactive threads

### ISSUE THREAD

**Issue by carstenbauer** [JuliaLang/Pkg.jl#3395]
Only the number of threads in the default thread pool seems to propagate to the test environment but not the number of interactive threads (irrespective of whether set via `-t N,M` or `JULIA_NUM_THREADS=N,M`). AFAICS, this makes it impossible to test package features related to interactive threads.

**MWE:**
```julia
# test/runtests.jl
using Base.Threads: nthreads
@show nthreads(:default)
@show nthreads(:interactive)
```

`julia --project -t 3,4` followed by `] test` gives
```
nthreads(:default) = 3
nthreads(:interactive) = 0
```
both on 1.9 as well as on nightly.

**Comment by kpamnany** [comment]
We ran into this too. [Here](https://github.com/JuliaLang/Pkg.jl/blob/master/src/Operations.jl#L1682) is the offfending code. Will post a PR to fix shortly.

**Comment by KristofferC** [comment]
FWIW, I think it is better to pass stuff like this explicitly via the `julia_args` argument to `Pkg.test`.

**Comment by kpamnany** [comment]
Agree, but this should work.
