### ISSUE TITLE
instantiate does not trigger precompilation if only Project.toml existsed

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/Pkg.jl#3407]
I have an environment that only contains a Project.toml file, but no Manifest.toml file. (I used https://github.com/fonsp/repro3403/blob/main/env2/Project.toml ) When you run `instantiate`, it will instantiate but not precompile. You need to explicitly call `precompile`. 

I was surprised by this behaviour, and it can cause users to lose the benefit of parallel precompilation.

**Comment by KristofferC** [comment]
Should probably add a precompile call at https://github.com/JuliaLang/Pkg.jl/blob/dbd5663838019820373472483790150dcdb70a78/src/API.jl#L1665.

**Comment by fonsp** [comment]
@KristofferC I noticed that `dev` also does not trigger precomp, is that intentional?

```
(@v1.9) pkg> dev /Users/fons/Documents/PlutoSliderServer.jl/
   Resolving package versions...
    Updating `~/.julia/environments/v1.9/Project.toml`
  [2fc8631c] + PlutoSliderServer v0.3.20 `~/Documents/PlutoSliderServer.jl`
    Updating `~/.julia/environments/v1.9/Manifest.toml`
  [6e696c72] + AbstractPlutoDingetjes v1.1.4
  [1520ce14] + AbstractTrees v0.4.4
  [c9fd44ac] + BetterFileWatching v0.1.5
  [ff7dd447] + FromFile v0.1.5
  [d7ba0133] + Git v1.3.0
  [6b79fd1a] + GitHubActions v0.1.4
  [c27321d9] + Glob v1.3.0
  [1d6d02ad] + LeftChildRightSiblingTrees v0.2.0
  [2fc8631c] + PlutoSliderServer v0.3.20 `~/Documents/PlutoSliderServer.jl`
  [33c8b6b6] + ProgressLogging v0.1.4
  [5d786b92] + TerminalLoggers v0.1.6
  [04572ae6] + Deno_jll v1.28.1+0
  [2e619515] + Expat_jll v2.4.8+0
  [f8c6e375] + Git_jll v2.36.1+2
  [94ce4f54] + Libiconv_jll v1.16.1+2
  [efcefdf7] + PCRE2_jll v10.42.0+0

julia> import PlutoSliderServer
[ Info: Precompiling PlutoSliderServer [2fc8631c-6f24-4c5b-bca7-cbb509c42db4]

```

**Comment by fonsp** [comment]
@KristofferC should I open a new issue for that?

**Comment by KristofferC** [comment]
Sure, I don't recall if that was intentional or not.

**Comment by IanButterworth** [comment]
Intentional because dev doesn't call build, so it's up to the developer when to do both

**Comment by fonsp** [comment]
Got it, thanks!
