### ISSUE TITLE
Installing from repos doesn't handle subdir?

### ISSUE THREAD

**Issue by JoaoAparicio** [JuliaLang/Pkg.jl#3423]
Hi. I don't know how to present a minimal working example, as the issue requires setting up a registry etc. But the issue is, I believe, that `subdir` doesn't work together with installing from repos. Correct me if I'm wrong.

Let me give you some context. We have a registry internally. All our packages have the same structure: the repo root contains `src/` which contains `MyPackageName.jl`. This works well. Now we were trying to mirror external repos internally so we can apply our own commits internally while we wait for them to be upstreamed.

Specifically consider the public repo:
https://github.com/apache/arrow-julia
On its root there's `src/` inside which `Arrow.jl` lives. But in addition, inside `src/` there's also a folder named `ArrowTypes` which is the root of the ArrowTypes package: inside this folder there's another `src/` and inside that there's `ArrowTypes.jl`. So the root of ArrowTypes is the subdir `src/ArrowTypes` relative to the repo root.

Now if we look at the public registry
https://github.com/JuliaRegistries/General/blob/master/A/ArrowTypes/Package.toml
we see that this Package defines a non-empty `subdir = "src/ArrowTypes"` which is consistent with the setup described above. It would appear that Pkg.jl somehow uses this information to install ArrowTypes. However, this is not the case, I believe.

This is the Pkg.jl function that downloads code:
https://github.com/JuliaLang/Pkg.jl/blob/908f84e0df6a76983c5df254403d5714e9c650cd/src/Operations.jl#L791
To it we pass a `Context` object which contains an `EnvCache` object, which contains a `Manifest` object, which contains a dictionary of `PackageEntry`s. But PackageEntry doesn't contain any information about `subdir`:
https://github.com/JuliaLang/Pkg.jl/blob/908f84e0df6a76983c5df254403d5714e9c650cd/src/Types.jl#L265-L277
So how is it possible that `add ArrowTypes` actually does the right thing?

The way it works is that inside `download_source` we have this code path
https://github.com/JuliaLang/Pkg.jl/blob/908f84e0df6a76983c5df254403d5714e9c650cd/src/Operations.jl#L852
which downloads tarballs. If you bother to find the ArrowTypes tarballs and extract them you'll see that their root is already `src/ArrowTypes`, so `download_source` installs them as normal without having to use `subdir`.

However, in our internal setup we don't package tarballs, we expected Pkg.jl to actually grab source from git.
When `download_source` fails to download tarballs it falls back to the `install_git` function, here:
https://github.com/JuliaLang/Pkg.jl/blob/908f84e0df6a76983c5df254403d5714e9c650cd/src/Operations.jl#L900-L914
However this function also isn't passed `subdir` and so it puts the repo root into the folder where inner package root should installed. This operation terminates without throwing an error, but trying to use the inner package fails (I forgot the exact error, but it read something like "package is installed but couldn't find the code").

Is this correct or am I missing something?

1.
```
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 48 × Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake-avx512)
  Threads: 8 on 48 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 8
```

2. Installed julia by going to julialang.org and downloading from there.

**Comment by JoaoAparicio** [comment]
I have a partial fix for this here
https://github.com/JoaoAparicio/Pkg.jl/tree/subdir
I put it on top of tag v1.8.2 as that's the latest release. However it appears I'm not allowed to open a PR to merge into v1.8.2 but only into master, is that right? If so and if there's interest in this I might have time tomorrow to resolve the conflicts.

**Comment by KristofferC** [comment]
Regarding `PackageEntry` those are used as the entries parsed from the manifest and the git repo + the tree hash in the manifest is enough to download a package, even if it is in a subdir.

The inputs to Pkg are of type `PackageSpec`.

**Comment by JoaoAparicio** [comment]
Hi Kristoffer, thanks for responding.

I didn't understand whether you're agreeing or disagreeing with my claims.
For example, do you agree with the claim that if I don't put my packages into tarballs, then `download_source` will go into this
https://github.com/JuliaLang/Pkg.jl/blob/908f84e0df6a76983c5df254403d5714e9c650cd/src/Operations.jl#L900-L914
code path and call `install_git`?

If you agree with that, then presumably what you're saying is that passing `pkg.tree_hash` into `install_git` is enough for it to know which subdir to use as package root, is that the case? If that's the case, would you kindly point out which specific line inside `install_git` uses this tree_hash to download a specific subdir. Presumably it has to be this:
https://github.com/JuliaLang/Pkg.jl/blob/908f84e0df6a76983c5df254403d5714e9c650cd/src/Operations.jl#L699
Is this correct?

If that's what you're saying, I suppose it's possible that I made a mistake calling RegistryTools, leading it to pass the wrong tree_hash to the registry.

**Comment by JoaoAparicio** [comment]
Hi Kristoffer,

I just went thru this again, and you were right. The mistake I was making was that I was passing `RegistryTools.register` the tree-hash of the root. I still think it's awkward that you need _both_ the subdir tree hash and the subdir path to be registered just because one or the other will be used depending on the packaging. Anyway it's working now, thank you! :-)

Closing.
