### ISSUE TITLE
Pkg removes user comments in the TOML file

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/Pkg.jl#3426]
The actual reason for this is that TOML is implemented on a dictionary rather than an actual serializer, but this is causing the behavior of Pkg not to act as expected, e.g if you have a comment in the TOML file, it will get removed after adding a new dependency (whatever triggers the Pkg to update `Project.toml`) See also https://github.com/JuliaTesting/Aqua.jl/issues/100

Also, I think we should preserve the user's TOML file order instead of re-sort it.

This is probably something not fixable until we have a rewrite of the TOML parser, but just want to leave this issue here. I'm also not sure where to submit issues for the TOML parser now, should be under JuliaLang/julia?

**Comment by fredrikekre** [comment]
Duplicate of #42697

**Comment by Roger-luo** [comment]
Oh thanks, didn't find that issue
