### ISSUE TITLE
Error cloning package that depends on previously cloned package.

### ISSUE THREAD

**Issue by sjorn3** [JuliaLang/Pkg.jl#343]
I have two packages, WebAssembly and Charlotte, but I'm not sure how to get them working with the new package manager. I can add WebAssembly quite easily, but Charlotte fails (and depends on WebAssembly).

Adding WebAssembly:
```
 pkg> add https://github.com/MikeInnes/WebAssembly.jl
  Updating git-repo `https://github.com/MikeInnes/WebAssembly.jl`
┌ Warning: packages will require to have a [Julia]Project.toml file in the future
└ @ Pkg.Types Types.jl:817
[ Info: Assigning UUID 1f861900-6989-11e8-0620-f17e63e90237 to WebAssembly
  Updating registry at `~/.julia/registries/Uncurated`
  Updating git-repo `https://github.com/JuliaRegistries/Uncurated.git`
 Resolving package versions...
  Updating `Project.toml`
  [1f861900] + WebAssembly v0.0.0 # [https://github.com/MikeInnes/WebAssembly.jl]
  Updating `Manifest.toml`
  [b99e7846] + BinaryProvider v0.3.0
  ... more deps ...
  [4ec0a83e] + Unicode 
  Building WebAssembly → `~/.julia/packages/WebAssembly/LQ4H/deps/build.log`
```

Adding Charlotte:
```
 pkg> add https://github.com/MikeInnes/Charlotte.jl
  Updating git-repo `https://github.com/MikeInnes/Charlotte.jl`
┌ Warning: packages will require to have a [Julia]Project.toml file in the future
└ @ Pkg.Types Types.jl:817
[ Info: Assigning UUID 3bfb4fe4-6989-11e8-1835-39afc9127c2d to Charlotte
  Updating registry at `~/.julia/registries/Uncurated`
  Updating git-repo `https://github.com/JuliaRegistries/Uncurated.git`
 Resolving package versions...
ERROR: The following package names could not be resolved:
 * WebAssembly (1f861900-6989-11e8-0620-f17e63e90237 in manifest but not in project)
Please specify by known `name=uuid`.
```
Thanks.

**Comment by MikeInnes** [comment]
FYI, I just registered WebAssembly so this repro will probably work now. Would still be nice to support dependencies on unregistered packages though.

**Comment by StefanKarpinski** [comment]
It will work fine once we're past the transition phase, but until we add project files, it's tough. We're working on getting to that as fast as we can.

**Comment by KristofferC** [comment]
Supporting unregistered dependencies is kinda hard though, at least with how information are stored now. We don't know where to download them for example since we get that from the registry.

**Comment by MikeInnes** [comment]
I'm only imagining this working when you've already done `dev X` to install the unregistered package (the same workflow you'd have on Pkg2 now).

**Comment by StefanKarpinski** [comment]
If someone gives a URL to an unregistered package, we can certainly support that fine. The main issue is if it in turn depends on something unregistered then it's unclear how the package manager can know where to find that package. We may be able to do some kind of lightweight registry which includes a UUID map only, skipping the version info.

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/Pkg.jl/pull/372
