### ISSUE TITLE
build.log file disappears? 

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#347]
Moved from https://github.com/JuliaLang/julia/issues/27463

In the process of updating packages for 0.7, I notice that building packages doesn't seem to leave the promised `build.log` file:
```jl
(v0.7) pkg> build ZMQ
  Building ZMQ → `~/.julia/dev/ZMQ/deps/build.log`
 Resolving package versions...

julia> isfile(homedir() * "/.julia/dev/ZMQ/deps/build.log")
false
```
By watching the directory in anothe terminal window, I see that an empty `build.log` exists while the build is occurring, but it never seems to contain anything, and it is apparently deleted when the build completes.  This doesn't seem very useful?

**Comment by KristofferC** [comment]
The build log is deleted when the package is successfully built. It is kept when it failed. Comments for improved workflow is appreciated.

**Comment by stevengj** [comment]
Is there a downside to just leaving the `build.log` file in all cases, only overwriting it on the next build?  It is nice to go back and see what happened even on a successful build sometimes.

**Comment by KristofferC** [comment]
I'm ok with that. @StefanKarpinski? We should add `deps/build.log` to generated `.gitignore` then (when `generate` actually starts to generate more stuff).

**Comment by StefanKarpinski** [comment]
No, seems fine to me. This is just what we did in the old package manager too.

**Comment by KristofferC** [comment]
We had build log files in the old package manager?

**Comment by stevengj** [comment]
In the old package manager the log was to stdio.
