### ISSUE TITLE
Pkg fails to print all output from subprocesses

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/Pkg.jl#3488]
It seems there is some mistake in Pkg IO handling that results in it truncating the output from subprocesses. A possible reason is the mistaken use of IOBuffer, when that is supposed to be forbidden to use for stdout. One example is at https://github.com/JuliaLang/Pkg.jl/blob/c3b9d3ee16a7e75aa0470dfba8f95931338a0cd0/test/utils.jl#L303

I have been too busy and forgot to implement the error when I added automatic conversion functionality (for stdin and BufferStream), but this may lead to problems with corrupt output. I think the upstream issue for this is
 https://github.com/JuliaLang/julia/issues/46768#issuecomment-1247233447

**Comment by IanButterworth** [comment]
> when that is supposed to be forbidden to use for stdout

AFAICT the _documentation_ of this is that it's explicitly not in the list in the note here https://docs.julialang.org/en/v1.10-dev/base/io-network/#Base.redirect_stdout

Would it be possible to improve the docs. Perhaps a short section on buffering best practices linked to in all relevant buffer types and redirect functions?

**Comment by vtjnash** [comment]
A second mistake is that someone called `closed(iob)`, which prematurely truncates the stream and creates many problems.

**Comment by IanButterworth** [comment]
Fixed by https://github.com/JuliaLang/Pkg.jl/pull/3573
