### ISSUE TITLE
Make is_stdlib(uuid::UUID) part of the public API

### ISSUE THREAD

**Issue by SamuraiAku** [JuliaLang/Pkg.jl#3514]
I use `is_stdlib()` in my package PkgToSoftwareBOM.jl .  Other developers roll their own version of this functionality, so there's clearly some demand. So why not give everyone a standard way to do this?

**Comment by KristofferC** [comment]
You really shouldn't have to depend on a whole package manager for this small feature.

**Comment by SamuraiAku** [comment]
But all known solutions involve digging into the bowels of the package manager anyways. So why not present a standardized solution and save developers from reinventing the wheel?

**Comment by KristofferC** [comment]
Just saying that the package manager is probably not the right place to put a standardized solution. Probably better in Julia itself.

**Comment by SamuraiAku** [comment]
I'm not sure that it is possible to put the function `is_stdlib(uuid::UUID)` inside of Base. Does Base have any awareness of package UUIDs?

**Comment by KristofferC** [comment]
Yes. It knows the UUID of every loaded package and could easily gather the UUIDs and names for the stdlibs during build time.

**Comment by SamuraiAku** [comment]
That sounds like a not-trivial amount of work vs. publishing the already existing function.  Also consider that `is_stdlib()` will be maintained since Pkg code depends on it.  A function in Base with minimal active use could become neglected. You'd want to update Pkg to use this new function as well, which adds to the workload.

**Comment by KristofferC** [comment]
> That sounds like a not-trivial amount of work vs. publishing the already existing function.

As I said, you shouldn't have to depend on a package manager to ask if something is a standard library. And I don't think it is much work, basically just move the code from here to Base. 

> Also consider that is_stdlib() will be maintained since Pkg code depends on it. A function in Base with minimal active use could become neglected.

It would be tested and Pkg could swap over to use that function instead.

**Comment by SamuraiAku** [comment]
Then how do you recommend to proceed? Open a parallel issue in the Julia repository?

**Comment by KristofferC** [comment]
Yes, open an issue on the Julia repo.
