### ISSUE TITLE
rename Uncurated to General ?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/Pkg.jl#353]
At first the thought was that we'd have a highly curated registry called `Curated` and free-for-all registry called `Uncurated` but it seems more likely at this point that different organizations (GitHub orgs and/or companies) will do the curation instead. Thinking along those lines, perhaps the `Uncurated` registry should have a less "judgemental" name like `General`.

**Comment by KristofferC** [comment]
Agree.

**Comment by StefanKarpinski** [comment]
Then the question is how to go about doing this. GitHub rename tracking will allow people on older Julias to continue cloning with the old name. If we assume people will only upgrade pre-release Julia versions, we could have Pkg check for the existence of `~/.julia/registries/Uncurated` and just move it to `~/.julia/registries/General` before doing any registry operations.

**Comment by fredrikekre** [comment]
done.
