### ISSUE TITLE
Provide a mechanism to mark a release as broken

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg.jl#355]
`cargo` has the option to "yank" a  release (https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-yank) effectively marking it as broken. I think we need this for our package manager too. Translated to julia; yanking a release would mean that the broken version would not be considered an option for the resolver, but if you have a yanked release in a `Manifest.toml` you can still `instantiate` it to install the broken version that way. With the new version specification it is a bit harder to upper bound in case of broken releases (and if package maintainers follow SemVer you should never have to upper bound). Yanking a release would be a way to enforce SemVer on a higher level, since that would presumably be up to the registry maintainer to do. So instead of

> PackageA v1.2 is broken, so I upperbounded PackageB to PackageA v1.1

we should have 

> PackageA v1.2 is broken, so that release was "yanked"

which seems a lot better.

In practice I think this would need an entry in the registry which marks a release as yanked, and then the resolver filters out those when collecting possible versions to install.

**Comment by StefanKarpinski** [comment]
100%, we should also have a way to deprecate old releases. The main actionable thing seems to be no longer considering certain versions when doing version resolution. We could also print warnings when yanked or deprecated versions are installed and/or used.

**Comment by KristofferC** [comment]
Should be easy. Just have an entry in the registry for each version and look at that when doing resolution.

**Comment by StefanKarpinski** [comment]
Is there a difference between "yanked" and "deprecated"?

**Comment by KristofferC** [comment]
Yanked is effectively deleted while still "instantiable" from manifests. Not sure what deprecated should be. You can install it but you get warned if it is a top-level dependency in your project, or something?

**Comment by StefanKarpinski** [comment]
It seems like deprecated should mean the same: resolver doesn't consider it but if it's in a manifest it can still get installed and used. It does seem like there could be room for something stronger where even if a version is in a manifest, it's so broken (e.g. contains malicious code) that we want to either not use it or warn the user about it before they use it.

**Comment by KristofferC** [comment]
> It seems like deprecated should mean the same: resolver doesn't consider it but if it's in a manifest it can still get installed and used.

Ok, so then they are the same then?

**Comment by StefanKarpinski** [comment]
Seems like it. Just clarifying. So I assume we'll want to use the more standard term "deprecated" rather than "yanked".

**Comment by fredrikekre** [comment]
I don't think they are the same. "yanking" is done for a specific release, and simply hides that from beeing installed. I think deprecated packages should still be installable, but yield a warning, just like deprecated functions does. What does it mean to deprecate a package? Presumably there are still version that will work just fine, and those should still be installable IMO.
