### ISSUE TITLE
[Feature request] Add shortcut for `activate`

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/Pkg.jl#3563]
This is perhaps the most used command in the package manager, it is very long to type...

Can we have a shortcut for it like we do for `status`? I ❤️ `st`

**Comment by IanButterworth** [comment]
Duplicate of #3266

**Comment by juliohm** [comment]
How is that a duplicate of #3266? Can you clarify @IanButterworth ?

**Comment by juliohm** [comment]
You probably meant https://github.com/JuliaLang/Pkg.jl/issues/3256
