### ISSUE TITLE
incorrectly warning uses of warnings

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/Pkg.jl#3566]
The output text says "had warnings", but this text is not a warning, just informational advice, and it is harmful to users for Pkg to claim this is a warning:
```
julia> using Test1
Precompiling Test1
  Progress [>                                        ]  0/1
  ◑ Test1 Waiting for background task / IO / timer. Interrupt to inspect
 Interrupted: Exiting precompilation...

  1 dependency had warnings during precompilation:
┌ Test1 [ddca8587-cad1-46e2-86b4-b726afea1d60]
│  [pid 7156] waiting for IO to finish:
│   TYPE[FD/PID]       @UV_HANDLE_T->DATA
│   timer              @00000228c312eca0->00000228bf815db0
```
observed at https://github.com/JuliaPy/PyPlot.jl/issues/572

**Comment by IanButterworth** [comment]
I proposed “warning” to dissuade packages from using output during precompilation for anything other than warnings. It seems like something we don’t want to promote?

**Comment by IanButterworth** [comment]
@vtjnash let me know if you disagree, otherwise perhaps we can close this?

**Comment by vtjnash** [comment]
I think Pkg should avoid editorializing, although I agree it is not generally advisable, some messages just won't be warnings

**Comment by IanButterworth** [comment]
Ok so `warnings` -> `output` ?

**Comment by vtjnash** [comment]
Yes, or something like "wrote text"
