### ISSUE TITLE
Can't run without Pkg

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/Pkg.jl#3570]
I'm looking into a smaller sysimage, and it depends on Pkg.

You can run Julia non-interactively (i.e. without the REPL and its pkg> mode). You can still use Pkg, if you so choose, but often you don't and I would like that supported without it slowing down startup.

First, to be clear, that should be possible: E.g. using and import (when they find the package) do not use Pkg, right?

I may need guidance on how to make this happen (in case others do not make this happen). This package depend on a lot e.g. Downloads, that I plan to disable anyway, and can instruct sysimg.jl to ignore already, but I believe Pkg overrides that because of the dependencies. Can all the dependencies og Pkg be loaded lazily like other packages can, or is that not ðpossible for a stdlib?

At least for now, I would be ok with not having Pkg even in the REPL. Such a fork of Julia/sysimage seems valuable.

**Comment by KristofferC** [comment]
See https://github.com/JuliaLang/julia/pull/49135
