### ISSUE TITLE
Error loading CompatLinearAlgebraExt of Compat: __precompile__(false) is not allowed in files that are being precompiled

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/Pkg.jl#3571]
Please see this discussion on slack: https://julialang.slack.com/archives/C7E3LFG82/p1691080604527259.

i saw this weird error when doing `]instantiate` on our codebase (RAICode) after i first upgraded to 1.9.2:
```julia
  ✓ RAICode
  276 dependencies successfully precompiled in 156 seconds. 2 already precompiled.
  3 dependencies had warnings during precompilation:
┌ FilePathsBase [48062228-2e41-5def-b9a4-89aafe57970f]
│  ┌ Warning: The call to compilecache failed to create a usable precompiled cache file for CompatLinearAlgebraExt [dbe5ba0b-aecc-598a-a867-79051b540f49]
│  │   exception = ArgumentError: Invalid checksum in cache file /Users/nathandaly/.julia/compiled/v1.9/CompatLinearAlgebraExt/Zxpzq_129SD.dylib.
│  └ @ Base loading.jl:1818
│  ┌ Error: Error during loading of extension CompatLinearAlgebraExt of Compat, use `Base.retry_load_extensions()` to retry.
│  │   exception =
│  │    1-element ExceptionStack:
│  │    Declaring __precompile__(false) is not allowed in files that are being precompiled.
│  │    Stacktrace:
│  │      [1] _require(pkg::Base.PkgId, env::Nothing)
│  │        @ Base /nix/store/s6rilz6g0292x8mkk8g3qk4mdzh8mf29-julia-1.9.2-patched/lib/julia/sys.dylib:-1
│  │      [2] _require_prelocked(uuidkey::Base.PkgId, env::Nothing)
│  │        @ Base /nix/store/s6rilz6g0292x8mkk8g3qk4mdzh8mf29-julia-1.9.2-patched/lib/julia/sys.dylib:-1
```
...
I don't actually see a `__precompile__(false)` anywhere in [CompatLinearAlgebraExt.jl](https://github.com/JuliaLang/Compat.jl/blob/master/ext/CompatLinearAlgebraExt.jl)... It seems like it was fine to ignore; everything is working dandily, but I want to check in about it.

From @IanButterworth:
> Can you open an issue in Pkg? I suspect it might be a bug in how we line up extensions for the parallel precomp scheduling due to the only dep of CompatLinearAlgebraExt being a _sysimage_ pkgimage stdlib. It might be that multiple packages are trying to precompile the ext at the same time.

**Comment by NHDaly** [comment]
CC: @kpamnany / @nickrobinson251

**Comment by IanButterworth** [comment]
I think this is because LinearAlgebra is in the sysimage and we weren't checking for that #3572 

Alternatively it could be a stacked environment issue.. Do you have LinearAlgebra in your default environment?

**Comment by IanButterworth** [comment]
Yeah, that extension is activated even if LinearAlgebra isn't in the project, but is in the sysimage
```
(@v1.11) pkg> st --extensions
Status `~/.julia/environments/v1.11/Project.toml`
  [34da2185] Compat v4.9.0
              └─ CompatLinearAlgebraExt [LinearAlgebra]
```
