### ISSUE TITLE
Add docs for test-specific dependencies.

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#359]
Implemented but no docs yet-

**Comment by tpapp** [comment]
Isn't this resolved by the [section in the manual](https://julialang.org/Pkg.jl/latest/#Test-specific-dependencies-1), or is there more to come?

Incidentally, is there a way to use `add` to add to `[target.test.deps]`?

**Comment by KristofferC** [comment]
> Incidentally, is there a way to use add to add to [target.test.deps]?

Currently, no.

But yes, this is resolved.
