### ISSUE TITLE
parallel test

### ISSUE THREAD

**Issue by xgdgsc** [JuliaLang/Pkg.jl#3601]
How to do parallel test can be hard to find as https://discourse.julialang.org/t/run-pkg-test-with-several-processors/6917 shows. Is it easy to make it built in to Pkg? Now I use ReTest.jl.

**Comment by KristofferC** [comment]
This issue has little to do with the package manager. The test framework most people use is the "Test" stdlib. As you mention there are other test frameworks that perhaps makes it easier to test in parallel. The package manager however only invokes the `runtests.jl` file so there is little it can do about the implementation of how the testing is done.

**Comment by xgdgsc** [comment]
Thanks. Found the issue in julia repo.
