### ISSUE TITLE
Progress meter glitch in Julia 1.10.0-beta2

### ISSUE THREAD

**Issue by mkoculak** [JuliaLang/Pkg.jl#3617]
Hi,
just switched to Julia 1.10.0-beta2 and during updating and precompiling packages, progress meter was glitching when one of the packages was waiting on some other process:

![Screenshot 2023-09-12 000823](https://github.com/JuliaLang/Pkg.jl/assets/16628635/a0c300ff-2747-41dd-a740-9fc8e15225a8)

The output of `versioninfo()`:
```julia
Julia Version 1.10.0-beta2
Commit a468aa198d (2023-08-17 06:27 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 32 × AMD Ryzen 9 5950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
  Threads: 5 on 32 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

Julia installed with juliaup.

**Comment by jishnub** [comment]
I think this should be fixed by https://github.com/JuliaLang/Pkg.jl/pull/3561, which is scheduled to be backported. This seems to be the same issue as https://github.com/JuliaLang/Pkg.jl/issues/3614
