### ISSUE TITLE
Readme widget links to 1.0 docs

### ISSUE THREAD

**Issue by ShalokShalom** [JuliaLang/Pkg.jl#3621]
Hi there :)

I was about to send you a PR, that fixes this, but the widgets are confusing to me, so its an issue: 

The v1 badge still links to 1.0, I would update that to 1.9:

![Screenshot_20230913_162917](https://github.com/JuliaLang/Pkg.jl/assets/6344099/32022250-62fc-4fd0-8707-ee5d7d258fc7)

**Comment by KristofferC** [comment]
It links to v1 which points to v1.9, no?

**Comment by ShalokShalom** [comment]
Sorry, I did try it, and I swear, I landed on 1.0
