### ISSUE TITLE
Change semantics of `respect_sysimage_versions`

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/Pkg.jl#3627]
I think `]dev Tar` should continue to "just work".
```julia
(@v1.6) pkg> dev Tar
   Resolving package versions...
    Updating `~/.julia/environments/v1.6/Project.toml`
  [a4e569a6] + Tar `~/.julia/dev/Tar`
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [a4e569a6] ~ Tar ⇒ `~/.julia/dev/Tar`

(@v1.11) pkg> dev Tar
     Cloning git-repo `https://github.com/JuliaIO/Tar.jl.git`
ERROR: Tried to develop or add by URL package Tar [a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e] which is already in the sysimage, use `Pkg.respect_sysimage_versions(false)` to disable this check.
```
I propose to change the semantics to either 
A (preferred)
false => no change (syimg versions are still irrelevant)
true => force using sysimg versions for anything that is not explicitly set in Project.toml.

or B (less breaking, but this fixes a regression so idk if that's really an issue)
false => no change (syimg versions are still irrelevant)
:auto => use force using sysimg versions for anything that is not explicitly set in Project.toml.
true => no change (force use sysimg versions everywhere)

See also: JuliaLang/julia#51374, https://github.com/JuliaLang/Pkg.jl/pull/3002, cc @KristofferC

**Comment by KristofferC** [comment]
The point here is that you cannot load any other Tar than the one in the sysimage so doing a `dev` doesn't really make sense, or?

**Comment by LilithHafner** [comment]
Right. So not a regression because in 1.6 this seemed to work at first, but didn't actually work
```julia
(@v1.6) pkg> dev Tar
  Resolving package versions...
     Updating `~/.julia/environments/v1.6/Project.toml`
  [a4e569a6] + Tar `~/.julia/dev/Tar`
  No Changes to `~/.julia/environments/v1.6/Manifest.toml`

julia> using Tar

julia> @which Tar.read_data(stdout, stdout)
read_data(tar::IO, file::IO; size, buf, tee) in Tar at /Users/x/.julia/juliaup/julia-1.6.7+0.x64.apple.darwin14/share/julia/stdlib/v1.6/Tar/src/extract.jl:642
```

To make this feature request reasonable, we would need a way of loading a version of Tar other than the one in the syimg. (something like, but ideally more pretty than the UUID hack we currently recommend for `]dev`ing stdlibs)

**Comment by KristofferC** [comment]
> To make this feature request reasonable, we would need a way of loading a version of Tar other than the one in the syimg. 

The solution in my opinion is to move out stdlibs from the sysimage which is very much an active work in progress.

**Comment by KristofferC** [comment]
Most stdlibs are now out of the sysimage so `dev` should work quite well now.
