### ISSUE TITLE
Opt-out of `Could not use exact versions of packages in manifest, re-resolving`

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/Pkg.jl#3635]
In a CI context, it's sometimes frustrating to find spurious failures due to upgraded packages when a new version of Julia is used on CI, and the current `Manifest.toml` can no longer be directly used.   While this is technically a failure of the package author having lax compat bounds, it would be nice to discover these more proactively by giving an option to disable the auto-re-resolution, and then perhaps automatically setting that in our CI scripts.  In terms of API, either kwargs to `instantiate()` or an environment variable works for me.

**Comment by DilumAluthge** [comment]
[`Pkg.test(; allow_reresolve=false)`](https://pkgdocs.julialang.org/dev/api/#Pkg.test)

**Comment by DilumAluthge** [comment]
(The `Could not use exact versions of packages in manifest, re-resolving` message is printed from within `Pkg.test`, not from inside `Pkg.instantiate`.)

**Comment by staticfloat** [comment]
Ah, that's wonderful.
