### ISSUE TITLE
Pkg.precompile only aware of extensions that should be loaded due to current Manifest

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/Pkg.jl#3637]
Pkg.precompile isn't aware of extensions that should be available due to other environments in the load stack which was enabled by https://github.com/JuliaLang/julia/pull/49701

Note `extdep_uuid in keys(ctx.env.manifest.deps)` here
https://github.com/JuliaLang/Pkg.jl/blob/3960c692bd4dd2b2eafc7699e8d0744f90756812/src/API.jl#L1127-L1130

@vtjnash I think this might be why, or at least a reason why Pkg.precompile tasks are hitting internal compilecache pidlocks

I'm trying to figure out what the right check to replace that with should be.

**Comment by KristofferC** [comment]
I am not sure this is an issue actually? Maybe can be closed? @IanButterworth

**Comment by IanButterworth** [comment]
Yeah I think this was a misunderstanding on my part
