### ISSUE TITLE
Loading Pkg with --compiled-modules=no changes active project

### ISSUE THREAD

**Issue by pfitzseb** [JuliaLang/Pkg.jl#3691]
Starting Julia (nightly) with `--compiled-modules=no` and then loading Pkg changes the currently active environment:
```
$ julia --compiled-modules=no --project=. -e 'println(Base.active_project()); using Pkg; println(Base.active_project())'
/home/pfitzseb/Documents/Git/julia-vscode/scripts/packages/SymbolServer/Project.toml
/tmp/jl_Cs4MSb/TestPkg.jl/Project.toml

$ julia -e 'using InteractiveUtils; versioninfo()'
Julia Version 1.11.0-DEV.874
Commit 137783f166 (2023-11-09 04:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
```

@fredrikekre pointed out that [this](https://github.com/JuliaLang/Pkg.jl/blob/2d59169bffdf29a4ed7bafd8b35c391ede612dde/src/precompile.jl#L116-L118) is most likely to blame.

cc @mkitti

**Comment by vchuravy** [comment]
Julia is `define-by-run` so with `compiled-modules=no` we need to execute the module definition.
`pkg_precompile()` is not guarded by a `if Base.generating_output()` (see https://github.com/JuliaLang/julia/blob/29d78fae2121eda08d03ebf1abeb4626859ef62b/stdlib/REPL/src/REPL.jl#L1626)

**Comment by KristofferC** [comment]
In my memory the whole precompile file include was guarded with that but that is apparently not in alignment with reality...

**Comment by mkitti** [comment]
Is that the solution then? At the end of Pkg.jl we just change it the following?

```julia
if Base.generating_output()
    include("precompile.jl")
end
```

**Comment by mkitti** [comment]
... or would it be better to do the following at the end of precompile.jl?

```julia
if Base.generating_output()
    pkg_precompile()
end
```

**Comment by pfitzseb** [comment]
The former, I think. There's no need to do any of the work in precompile.jl unless we're precompiling, right?

**Comment by KristofferC** [comment]
Don't think it matters in practice but I guess it is sliiiiiiiiiightly odd to have a different set of functions defined depending on if you run with precompiled or not.

**Comment by pfitzseb** [comment]
Fair point. I've typically put the `include` into the if statement, but also typically only have one function defined in there. I don't think it matters much either way tbh
