### ISSUE TITLE
unbounded version in resolve errors are not printed well

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#371]
```
`0.0.0-4294967295.4294967295.4294967294` ..
```

should probably tweak the printing.

**Comment by StefanKarpinski** [comment]
The minus 1 for the last number is kind of funny. I think it's because version ranges are inclusive here whereas in the old system the end-point was open so `[0, typemax(VersionNumber))` becomes `[0, typemax(VersionNumber)-1]` if you see what I mean.

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/Pkg.jl/pull/440
