### ISSUE TITLE
Garbage collector should remove unreachable clones as well

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#374]

**Comment by StefanKarpinski** [comment]
Or maybe all clones? Since they're not usually needed.

**Comment by 00vareladavid** [comment]
Exactly what I was thinking. It hardly seems worth the effort if it is just a cache. It would be a step forward at least.

**Comment by KristofferC** [comment]
Seems like a step backward for me heh. Trading some disk space for having to redownload a bunch of things you are likely currently using.

**Comment by StefanKarpinski** [comment]
But we don't usually need to clone anything to install packages. What would the criteria for keeping a clone be? We could also do `git gc --aggresive` in each git repo.

**Comment by fredrikekre** [comment]
In my experience `git gc --aggressive` often takes much more time compared to cloning the repo, so in that case it seems better to just remove the repo.

**Comment by StefanKarpinski** [comment]
Wait do we have both `~/.julia/clones` and `~/.julia/.clones` now?

**Comment by KristofferC** [comment]
We never had `.clones`, I wrote it wrong.
