### ISSUE TITLE
Adding an already-installed General registry via pkgserver shows no output, where clones do

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/Pkg.jl#3747]
This does update General, as a progress meter shows up but it disappears and doesn't let you know it already exists like a clone does.

It's quite confusing on CI because this is all you see.

```
$ julia -e 'using Pkg; Pkg.Registry.add([RegistrySpec(name="General"), RegistrySpec(url="https://github.com/HolyLab/HolyLabRegistry")]);'
     Cloning registry from "https://github.com/HolyLab/HolyLabRegistry"
Registry `HolyLabRegistry` already exists in `~/.julia/registries/HolyLabRegistry`.
```

**Comment by omus** [comment]
Something else that's weird about this is that it appears we clone the entire registry first before we check if it's already present. Seems like we could see a performance improvement if we checked for the registries existence first and if it exists refresh it?
