### ISSUE TITLE
`Exception: RequestError`

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaLang/Pkg.jl#3752]
a student freshly installed Julia on Windows, then got this `RequestError` when trying to install his first package. what can we do?

![image](https://github.com/JuliaLang/Pkg.jl/assets/30643894/cf03a2eb-a88c-4c8f-afc2-946c2f0e197a)

**Comment by omus** [comment]
As work around you can launch Julia with `JULIA_PKG_SERVER="" julia`

**Comment by SimonEnsemble** [comment]
thanks! seems after restarting his computer, the normal way of launching Julia + `add Pluto` works. odd.
