### ISSUE TITLE
Packages can load stdlibs when building or testing without declaring a dependency

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#379]
This means that moving packages out of the stdlib is breaking.

We would have to remove the stdlib path from the `JULIA_LOAD_PATH` to prevent this.

**Comment by StefanKarpinski** [comment]
I think we should do this and see what happens.

**Comment by staticfloat** [comment]
> We would have to remove the stdlib path from the JULIA_LOAD_PATH to prevent this.

Doesn't that mean that interactive use would not be able to load the `stdlib` as well?

**Comment by KristofferC** [comment]
This is only for when Pkg is building or testing.

**Comment by staticfloat** [comment]
Ah, that makes sense then.  Yes, I would like to get as hardline on the "put it in the project.toml to be able to load it" as we can, so that there is as little "magic" as possible.

**Comment by fredrikekre** [comment]
fixed by #535
