### ISSUE TITLE
Pkg always trying to install below a package's allowed version

### ISSUE THREAD

**Issue by tom-plaa** [JuliaLang/Pkg.jl#3805]
After just upgrading to Julia 1.10(.1)
` [7ad07ef1] CoupledFields v0.2.0` is a dependency of one of my installed packages and it is supposed to allow StatsBase.jl up to v0.34 inclusive:
https://github.com/Mattriks/CoupledFields.jl/blob/master/Project.toml

However, Pkg is only letting me install StatsBase up to v0.33 and this is breaking some other packages I have:
```
(@v1.10) pkg> status --outdated
Status `~/.julia/environments/v1.10/Project.toml`
⌅ [2913bbd2] StatsBase v0.33.21 (<v0.34.2): CoupledFields
```

version info:
```
julia> versioninfo()
Julia Version 1.10.1
Commit 7790d6f0641 (2024-02-13 20:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
Threads: 8 default, 0 interactive, 4 GC (on 8 virtual cores)
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by IanButterworth** [comment]
https://github.com/Mattriks/CoupledFields.jl needs to make a release. You're looking at unreleased master

**Comment by tom-plaa** [comment]
Oops...
Thanks, I'm going to ask there.
