### ISSUE TITLE
[extensions] is ignored in JuliaProject.toml

### ISSUE THREAD

**Issue by xitology** [JuliaLang/Pkg.jl#3815]
When the project file is called `JuliaProject.toml` (as opposed to `Project.toml`), its `[extensions]` section is ignored by Pkg.jl. It must be caused to the hard-coded filename in https://github.com/JuliaLang/Pkg.jl/blob/master/src/Operations.jl#L168.

This could be reproduced with a package from Pkg.jl tests:
```
cd test/test_packages/ExtensionExamples/HasExtensions.jl
# Verify that it works
julia --project=@hasext-good -e 'using Pkg; Pkg.add("OffsetArrays"); Pkg.add("IndirectArrays"); Pkg.develop(path="."); include("test/runtests.jl")'
# Rename *.toml files
mv Project.toml JuliaProject.toml
mv Manifest.toml JuliaManifest.toml
# Verify that it no longer works
julia --project=@hasext-bad -e 'using Pkg; Pkg.add("OffsetArrays"); Pkg.add("IndirectArrays"); Pkg.develop(path="."); include("test/runtests.jl")'
```

**Comment by KristofferC** [comment]
Yep, seems like a straight up bug. Happy for a PR.
