### ISSUE TITLE
Always develop the local package in `test/Project.toml`, `docs/Project.toml`

### ISSUE THREAD

**Issue by olynch** [JuliaLang/Pkg.jl#3816]
One thing that constantly trips me up over and over again is that I have to remember to run `julia --project=test -e 'import Pkg; Pkg.develop(".")' ` and `julia --project=docs -e 'import Pkg; Pkg.develop(".")' ` before I run any tests or edit the docs. My understanding is that it's not best practice to check in Manifest.toml, which would be one way to resolve this. Would it be possible to add a field to the `Project.toml` in `docs` and `test` to always be based on the local version?

**Comment by KristofferC** [comment]
I would say that this is kind of fixed by either using a workspace, or by adding a `[sources]` entry to the Project file pointing to the package.
