### ISSUE TITLE
Add test for target deps for dependencies

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#383]
Right now we are only testing when the current project is what is being tested, not a dependency.

**Comment by 00vareladavid** [comment]
Is this something that will be resolved by #1427?

**Comment by KristofferC** [comment]
Probably :P. I don't remember exactly what this issue was about...

**Comment by 00vareladavid** [comment]
ok. In any case, I'll try to add a few more tests to #1427

**Comment by 00vareladavid** [comment]
I'm assuming you were talking about something like
```
Pkg.develop("Example")
Pkg.test("Example")
```
as compared to
```
Pkg.develop("Example")
Pkg.test()
```

#1427 includes tests for both cases
