### ISSUE TITLE
Investigate Travis log from BinaryProvider 

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#384]
https://travis-ci.org/JuliaPackaging/BinaryProvider.jl/jobs/391963313

Why are different Compat installed when building and testing?

**Comment by staticfloat** [comment]
We figured out this was happening because I had checked in a `Manifest.toml`.  I removed that and [things made much more sense](https://travis-ci.org/JuliaPackaging/BinaryProvider.jl/jobs/391985668)

**Comment by KristofferC** [comment]
I still think there is something bad here because different versions of Compat got installed. Although I think it is a dup of https://github.com/JuliaLang/Pkg.jl/issues/361
