### ISSUE TITLE
add package#user/branch

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/Pkg.jl#386]
Maybe this is supported, I just could not figure out the right syntax for [using a specific PR](https://github.com/timholy/Revise.jl/pull/101/), even though I could use a hash:
```julia
(v0.7) pkg> add Revise#teh/lln
   Cloning git-repo `https://github.com/timholy/Revise.jl.git`
  Updating git-repo `https://github.com/timholy/Revise.jl.git`
ERROR: git object teh/lln could not be found

(v0.7) pkg> add Revise#7b1dfcea07cf60d9da333dc78b575d29465f005f
  Updating git-repo `https://github.com/timholy/Revise.jl.git`
┌ Warning: packages will require to have a [Julia]Project.toml file in the future
└ @ Pkg.Types Types.jl:588
  Updating registry at `~/.julia/registries/Uncurated`
  Updating git-repo `https://github.com/JuliaRegistries/Uncurated.git`
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
  [295af30f] ↑ Revise v0.4.1 ⇒ v0.4.1+ #7b1dfce [https://github.com/timholy/Revise.jl.git]
  Updating `~/.julia/environments/v0.7/Manifest.toml`
  [295af30f] ↑ Revise v0.4.1 ⇒ v0.4.1+ #7b1dfce [https://github.com/timholy/Revise.jl.git]
```

**Comment by fredrikekre** [comment]
But this is because the branch is removed, no?

**Comment by tpapp** [comment]
No, the output above is from when the branch was still there.

*(In retrospect, I do realize that providing an example from a repo whose maintainer is known to be very fast was a mistake, I can make an MWE repo if that helps).*

**Comment by fredrikekre** [comment]
Are you sure? Try e.g.
```
pkg> add Literate#fe/invokelatest
```

**Comment by tpapp** [comment]
Now it works — perhaps the branch was deleted in the few seconds I checked but before I typed the `pkg>` commands.

Still, could the manual include an example for `#user/branch`?

**Comment by fredrikekre** [comment]
What do you mean with `user/branch`, it is just a branch name like any other.

**Comment by tpapp** [comment]
Confusion on my part, sorry. Closing the issue.
