### ISSUE TITLE
Naming a package extension "REPLExt" breaks loading 

### ISSUE THREAD

**Issue by tecosaur** [JuliaLang/Pkg.jl#3906]
So, I've been working on decreasing TTFX in a package of mine, and thought in the process I'd split the REPL functionality up into a package extension ... called `REPLExt`.

Turns out this causes issues though, do package extension names need to be globally unique? That would be weird, but it kinda seems like it from this MWE.

[pkg_ext_name_repro.zip](https://github.com/JuliaLang/Pkg.jl/files/15447693/pkg_ext_name_repro.zip)

This is just the results of `]generate pkg_ext_name_repo` + a minimal `REPL`-based package extension.

Reproduction instructions:
- Extract (and instantiate?) `pkg_ext_name_repo`
- Run `julia +1.11 --startup-file=no --project=pkg_ext_name_repo`
- Try `using Pkg`
- Observe the below error message

```
julia> using Pkg
[ Info: Precompiling REPLExt [e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b] (cache misses: wrong dep version loaded (2), wrong source (2), invalid header (8), mismatched flags (2))
ERROR: LoadError: ArgumentError: Package REPLExt does not have pkg_ext_name_repro in its dependencies:
- Note that the following manifests in the load path were resolved with a different
  julia version, which may be the cause of the error:
    /home/tec/pkg_ext_name_repro/Manifest.toml (vnothing)
- You may have a partially installed environment. Try `Pkg.instantiate()`
  to ensure all packages in the environment are installed.
- Or, if you have REPLExt checked out for development and have
  added pkg_ext_name_repro as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with REPLExt
Stacktrace:
 [1] macro expansion
   @ ./loading.jl:2133 [inlined]
 [2] macro expansion
   @ ./lock.jl:273 [inlined]
 [3] __require(into::Module, mod::Symbol)
   @ Base ./loading.jl:2105
 [4] #invoke_in_world#3
   @ ./essentials.jl:1064 [inlined]
 [5] invoke_in_world
   @ ./essentials.jl:1061 [inlined]
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:2098
 [7] include
   @ ./Base.jl:558 [inlined]
 [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base ./loading.jl:2721
 [9] top-level scope
   @ stdin:4
in expression starting at /home/tec/pkg_ext_name_repro/ext/REPLExt.jl:1
in expression starting at stdin:4
┌ Error: Error during loading of extension REPLExt of Pkg, use `Base.retry_load_extensions()` to retry.
│   exception =
│    1-element ExceptionStack:
│    Failed to precompile REPLExt [e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b] to "/home/tec/.julia/compiled/v1.11/REPLExt/jl_f6PsaY".
│    Stacktrace:
│      [1] error(s::String)
│        @ Base ./error.jl:35
│     ...
│     [41] _start()
│        @ Base ./client.jl:536
└ @ Base loading.jl:1437
```

**Comment by IanButterworth** [comment]
What if the name isn't REPLExt but the same name as a non stdlib ext?

**Comment by KristofferC** [comment]
Probably some interaction with `require_stdlib`

**Comment by IanButterworth** [comment]
Is your manifest up to date? The error message mentions it.

**Comment by KristofferC** [comment]
> I think I'm hitting the same issue with two packages that both define PkgExt, is that also part of a stdlib?

No. Hm, I don't think the loading code should ever identify a package only by name and they should get different UUIDs because their parent is different. But if course, might be a bug somewhere. But I'm pretty sure there are many exte sions in the ecosystem with the same name so I would have thought that would have already showed up if it was an issue.

**Comment by KristofferC** [comment]
That's possible. Should be fixed in 1.11 I think it is.

**Comment by tecosaur** [comment]
Some more info/responses:

- I'm using Julia 1.11-beta2
- My manifest(s) are up to date, as best I know

In my global environment, here's where one `PkgExt` is defined:

```
(@v1.11) pkg> st --extensions
Status `~/.julia/environments/v1.11/Project.toml`
  [1e701ad1] Setup v0.1.0 `~/.julia/config/Setup`
              ├─ PkgExt [Pkg]
              ...
```

and then when the error appears, it's when I'm developing `DataToolkitCommon` which also has a `PkgExt = "Pkg"` extension.

**Comment by disberd** [comment]
I have also faced this in the last days dealing with multiple packages defining an extension for PlotlyBase (so definitely not a stdlib) called PlotlyBaseExt. Problems seems to be fixed if I changed the name of either of the two extensions called PlotlyBaseExt.

I didn't manage to narrow down an MWE but I'll post it if I manage to

**Comment by KristofferC** [comment]
I can repro this so I should be able to understand what is going on.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/54658 should fix this.

**Comment by tecosaur** [comment]
Thanks Kristoffer!
