### ISSUE TITLE
New HistoricalStdlibVersions version is breaking the Pkg tests

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/Pkg.jl#3929]
I'm confused; I tagged a v2.0 breaking version of HistoricalStdlibVersions, but it appears that new version is [breaking existing Pkg tests](https://buildkite.com/julialang/julia-master/builds/37467#01902945-bb30-47fa-ab51-7abc5e6a94c0/835-1765).  Is [this compat entry](https://github.com/JuliaLang/Pkg.jl/blob/master/test/Project.toml#L18) insufficient?

**Comment by KristofferC** [comment]
It seems Pkg adds HistoricalStdlibVersions.jl during testing in a temp env:

https://github.com/JuliaLang/Pkg.jl/blob/db8ce8919c3f4a51d3e9307fa56a83932bf9d2c1/test/runtests.jl#L43

Which will not have that compat entry in it.
