### ISSUE TITLE
The redirection to the build.log files doesn't preserve chronological order of the output to stderr and stdout

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#394]
Makes it annoying to read the log file since everything is mixed up.

**Comment by staticfloat** [comment]
This is partly what `OutputCollector` in `BinaryProvider` is used for; it preserves chronological order on a line-by-line basis.

**Comment by KristofferC** [comment]
Yeah, it would be nice to see that directly but  not sure what the beat way to do that is. I had some deadlock problems with it on Windows does when using it with multiple async tasks but might be fixed, or is a Base issue.

**Comment by staticfloat** [comment]
For now, I say just beg/borrow/steal whatever you need from it to get something working.  Post 1.0, we can revisit this and see if we want to make a little "runner" package that gets used by both BinaryProvider and Pkg3.  Or who knows, maybe Pkg3 will just swallow BP.

**Comment by KristofferC** [comment]
I think this is fixed now.
