### ISSUE TITLE
Hide unnecessary internal Pkg stack traces in test logs

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/Pkg.jl#3944]
This entire stacktrace seems superfluous to the user.
However, I think this might be a `julia-runtest` issue. Opening here for better visibility for any discussion.

![Screenshot 2024-07-08 at 3 57 01 PM](https://github.com/JuliaLang/Pkg.jl/assets/1694067/e1338535-9267-40fb-bf52-1210ee3210d4)

**Comment by KristofferC** [comment]
Might make sense to fix this on the Pkg side? Also annoying for local testing etc.

**Comment by IanButterworth** [comment]
I thought about that but it might be breaking to change the way that Pkg.test throws when a package fails?
