### ISSUE TITLE
Weird syntax highlighting in docstrings

### ISSUE THREAD

**Issue by fatteneder** [JuliaLang/Pkg.jl#3954]
Happens on `julia +nightly`. Issue is likely that the stdout output is included in a codeblock (cc @fredrikekre).

![image](https://github.com/user-attachments/assets/b5496a7c-7b9b-4619-811d-0922ce605e30)

**Comment by fredrikekre** [comment]
I think in earlier Julia versions if the language was empty it was assuming plaintext, but now it assumes julia code. Snippets like https://github.com/JuliaLang/Pkg.jl/blob/d801e4545f548ab9061a018bf19db1944c711607/src/Pkg.jl#L521 need an explicit `plaintext` now I think.

**Comment by fatteneder** [comment]
Using either `plain` or `plaintext` squeezes everything into one line:
![image](https://github.com/user-attachments/assets/cfc6f71b-cc72-4685-b59e-31ed9cecd907)

Currently trying to understand what's going on in `Markdown.jl`.

**Comment by fatteneder** [comment]
Nevermind, I forgot to close a code block. Using `plaintext` works just fine.
