### ISSUE TITLE
Add `projectdir` function to Pkg.jl?

### ISSUE THREAD

**Issue by Datseris** [JuliaLang/Pkg.jl#3985]
The `projectdir` function of DrWatson is one of the most popular features of the package. It just returns the path of the Project.toml file of the currently active project.

The function itself has a trivial source code: 

https://github.com/JuliaDynamics/DrWatson.jl/blob/ce2016156260713b2291b4fe7f0536a17322e929/src/project_setup.jl#L8-L34

essentially being just `dirname(Base.active_project())` with some warning decorators. 

Yet, this function really enhances productivity and reproducibility of a self-contained scientific project because people don't have to care where there scripts are, as long as they are within the project's root folder.

Given the utility of this function, can we add it to Pkg.jl directly? Will a PR adding this be accepted?

Having this to Pkg.jl directly will also improve other aspects of user experience, such as hopefully allowing VSCode to recognize code loaded via `include(projectdir(....))`.

**Comment by KristofferC** [comment]
It seems kind of crazy that you have to depend on a package manager for this. Why wouldn't making `Base.active_project` public be the solution to this?

**Comment by Datseris** [comment]
I never understood why `Base.active_project` was not public in he first place, since its creation. But yes, making this function public would be a solution. `dirname` is a commonly used function already.

**Comment by Datseris** [comment]
Hm, actually while `active_project` would be a technical solution, it won't be a practical one. Compare
```
joinpath(dirname(active_project()), "src", "foo.jl")
```
to 
```
projectdir("src", "foo.jl")
```
which is definitely better in terms of more readable and ergonomic.

So this new function is useful to have. Currently it is in DrWatson. While there can be accessibility advantages having it in Pkg instead of DrWatson, the function also isn't a Pkg-related functionality, at least not in an obvious way. It is not clear to me whether there would be reasons to port it here. If you think so, happy to do so. Otherwise we can close this.

---

Unfortunately I've also realized that having this in Pkg would not improve much the problem that originally prompted me to open this. (although, it could motivate VSCode devs to take this more seriously).
