### ISSUE TITLE
Tree Hash Mismatch installing BLPData on Windows with Julia v1.10

### ISSUE THREAD

**Issue by felipenoris** [JuliaLang/Pkg.jl#4010]
[BLPData.jl](https://github.com/felipenoris/BLPData.jl) run tests on windows using appveyor.

See https://ci.appveyor.com/project/felipenoris/blpdata-jl/builds/50512855.

It gets `Tree Hash Mismatch` error on Julia v.10 and latest. The CI also tests on previous Julia versions, with no errors.

```
Julia Version 1.10.5
Commit 6f3fdf7b36 (2024-0[8](https://ci.appveyor.com/project/felipenoris/blpdata-jl/builds/50512855/job/dty5slxidqxachdr#L8)-27 14:19 UTC)
...
C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"
  Installing known registries into `C:\Users\appveyor\.julia`
       Added `General` registry to C:\Users\appveyor\.julia\registries
    Updating registry at `C:\Users\appveyor\.julia\registries\General.toml`
ERROR: Unable to automatically download/install artifact 'blpapi' from sources listed in 'C:\projects\blpdata-jl\Artifacts.toml'.
Sources attempted:
- https://pkg.julialang.org/artifact/5c366[26](https://ci.appveyor.com/project/felipenoris/blpdata-jl/builds/50512855/job/dty5slxidqxachdr#L26)8f16c55e522bad96ae446ba619b904c0c
    Error: RequestError: HTTP/1.1 404 Not Found while requesting https://pkg.julialang.org/artifact/5c366268f16c55e522bad96ae446ba619b904c0c
- https://github.com/felipenoris/BLPData.jl/releases/download/blpapi-3.12.3.1/blpapi_cpp_3.12.3.1-windows-x64.tar.gz
    Error: Tree Hash Mismatch!
  Expected git-tree-sha1:   5c366268f16c55e522bad96ae446ba619b904c0c
  Calculated git-tree-sha1: 57b7ceb6bdb7d7df12f208fbd71d5be13afa2f4e
```

This looks the same as https://github.com/JuliaLang/Pkg.jl/issues/3643.

See also https://github.com/felipenoris/BLPData.jl/issues/22.

**Comment by nhz2** [comment]
You need to update your Artifacts.toml to use the hash "57b7ceb6bdb7d7df12f208fbd71d5be13afa2f4e"
Previous versions of Julia just ignored the tree hash on Windows, so that was why it was working. #3643 was caused by Windows artifacts containing symlinks, but in your case, your artifact is just a single executable file.

"5c366268f16c55e522bad96ae446ba619b904c0c" would be the tree hash if the file was not executable.
