### ISSUE TITLE
Deprecated/aliased commands should have help messages

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/Pkg.jl#404]
Since you can `checkout Foo`, you should be able to `help checkout`.  I think it would help (heh) a lot if the user can `help` anything they enter into the REPL, even if it's just a simple message saying "`checkout` is deprecated use `develop` instead", then prints out the help message for `develop`.   This is especially true as we aren't getting any deprecation notices when you `checkout` within the `pkg>` repl for some reason.

**Comment by KristofferC** [comment]
FWIW ` checkout` repl command is deleted now.
