### ISSUE TITLE
Improving accessibility of the new 1.12 progress bar

### ISSUE THREAD

**Issue by christiangnrd** [JuliaLang/Pkg.jl#4046]
As raised by @davidanthoff on slack, while the new progress bars look great, they can be harder to see due to the differentiation between both sides being mostly colour. This problem is exacerbated when Julia is launched with no colour output.

Current progress bar in VSCode (examples 1/2):
![Image](https://github.com/user-attachments/assets/9b99640e-6fe5-4360-9add-5582fb8ff0a6)

![Image](https://github.com/user-attachments/assets/a3288323-997e-42b8-9154-9fd067bed7ba)

I looked at how PIP deals with no colour since this design was inspired off theirs, they replace the unfilled side with white space to ensure good contrast.

Example 3:
![Image](https://github.com/user-attachments/assets/d25057a6-8922-4621-bd34-ff97879dccf2)

Another idea I had would be to keep using the heavy character variant on the left, but use the light variant on the right. That would add even more differentiation while still looking similar to the new style.

Examples 4/5:
![Image](https://github.com/user-attachments/assets/659c3875-a41b-4290-b219-c0af038bcee7)
![Image](https://github.com/user-attachments/assets/e0e52f12-970a-4072-91ec-b63ed85e4024)

Personally, I think the no colour option should use whitespace on the right (example 3), while for a colour terminal, I don't know if I prefer the current status bar or my suggestion (1 or 4).

**Comment by christiangnrd** [comment]
At the moment I only have access to my macbook, but it would also be worth getting opinions and screenshots for how they look on lower-DPI displays.

**Comment by IanButterworth** [comment]
It'd be helpful to add examples in a dark terminal. Personally I'm completely unfamiliar with julia in light terminals..

**Comment by christiangnrd** [comment]
> It'd be helpful to add examples in a dark terminal. Personally I'm completely unfamiliar with julia in light terminals..

Good point. Here they are.

Dark examples 1/2:
![Image](https://github.com/user-attachments/assets/7e847649-709f-44a5-b79c-11bf288c1466)
![Image](https://github.com/user-attachments/assets/f8a785d8-5bef-4adc-bfff-5bfe9a4cb6c5)


Dark example 3:
![Image](https://github.com/user-attachments/assets/9e6ffe85-c5a8-45df-a759-9b84be168789)


Dark examples 4/5:
![Image](https://github.com/user-attachments/assets/1be7a2ad-4df4-46e8-a863-338945fae9de)
![Image](https://github.com/user-attachments/assets/e6917b83-0651-4202-9bef-5341a0dccc25)

**Comment by IanButterworth** [comment]
I quite like 4/5. Could be enough?

**Comment by christiangnrd** [comment]
I tried it on a lower-res external monitor and there's not a huge visual difference between the heavy and light characters, so 5 might not be sufficient for black/white terminals. My favourites are now 3/4.

**Comment by tecosaur** [comment]
Is 1 for color terminals, 3 for no-color an accessible way of presenting progress?
