### ISSUE TITLE
Pkg3 complains of missing module

### ISSUE THREAD

**Issue by 00vareladavid** [JuliaLang/Pkg.jl#405]
I started on discourse, but now I am fairly confident the issue lies within Pkg3: https://discourse.julialang.org/t/how-to-install-sqlite-package-with-julia-0-7/11771/5

I get a “Module Compat not found in current path” during the build phase, but issuing a `using Compat` in a REPL will not result in any errors. I'm guessing Pkg3 creates some sort of "environment" but isn't populating it according to the REQUIRE file? 

System:
OS: Arch Linux systemd-nspawn container
Arch: x86_64
Julia Version: 0.7.0-alpha

**Comment by 00vareladavid** [comment]
So the `REQUIRE` file is no longer supported on 0.7? I had just assumed it was, since many of packages I have seen seem to still be using it and not `Project.toml`. If this is the case, then feel free to close the issue.

Thanks!

**Comment by staticfloat** [comment]
Yep, that's correct.  `REQUIRE` files will be a thing of the past.
