### ISSUE TITLE
Crash when updating packages

### ISSUE THREAD

**Issue by diffbar** [JuliaLang/Pkg.jl#4083]
Hey,

I just tried to update my packages, but instead the julia process crashed.

    (@v1.11) pkg> up
        Updating registry at `~/.julia/registries/General.toml`
    No Changes to `~/.julia/environments/v1.11/Project.toml`
    No Changes to `~/.julia/environments/v1.11/Manifest.toml`
    ┌ Warning: attempting to remove probably stale pidfile
    │   path = "/home/jan/.julia/compiled/v1.11/MLStyle/v4qmW_aAiQW.ji.pidfile"
    └ @ FileWatching.Pidfile /usr/share/julia/stdlib/v1.11/FileWatching/src/pidfile.jl:249
    Precompiling ┌ Warning: attempting to remove probably stale pidfile
    │   path = "/home/jan/.julia/compiled/v1.11/ArrayLayouts/QloHc_aAiQW.ji.pidfile"
    └ @ FileWatching.Pidfile /usr/share/julia/stdlib/v1.11/FileWatching/src/pidfile.jl:249
    project...
    ┌ Warning: attempting to remove probably stale pidfile  0/56
    │   path = "/home/jan/.julia/compiled/v1.11/LoopVectorization/4TogI_aAiQW.ji.pidfile"
    └ @ FileWatching.Pidfile /usr/share/julia/stdlib/v1.11/FileWatching/src/pidfile.jl:249
    ┌ Error: curl_multi_assign: 1                        ]  0/38
    └ @ Downloads.Curl /usr/share/julia/stdlib/v1.11/Downloads/src/Curl/utils.jl:57
    ┌ Error: curl_multi_assign: 1
    └ @ Downloads.Curl /usr/share/julia/stdlib/v1.11/Downloads/src/Curl/utils.jl:57
    ┌ Error: curl_multi_assign: 1
    └ @ Downloads.Curl /usr/share/julia/stdlib/v1.11/Downloads/src/Curl/utils.jl:57

    [30295] signal 6 (-6): Aborted
    in expression starting at none:0
    unknown function (ip: 0x71c3586113f4)
    gsignal at /usr/bin/../lib/libc.so.6 (unknown line)
    abort at /usr/bin/../lib/libc.so.6 (unknown line)
    unknown function (ip: 0x71c357c23f1f)
    unknown function (ip: 0x71c357d3fa7d)
    uv_run at /usr/bin/../lib/julia/libjulia-internal.so.1.11 (unknown line)
    ijl_task_get_next at /usr/bin/../lib/julia/libjulia-internal.so.1.11 (unknown line)
    unknown function (ip: 0x71c33fd01f82)
    unknown function (ip: 0x71c33eedb772)
    unknown function (ip: 0x71c33ea8bbbf)
    wait at ./condition.jl:125 [inlined]
    _wait at /build/julia/src/julia-1.11.1/usr/share/julia/stdlib/v1.11/FileWatching/src/FileWatching.jl:572
    wait at /build/julia/src/julia-1.11.1/usr/share/julia/stdlib/v1.11/FileWatching/src/FileWatching.jl:600
    #58 at /build/julia/src/julia-1.11.1/usr/share/julia/stdlib/v1.11/Downloads/src/Curl/Multi.jl:188
    unknown function (ip: 0x71c33e470d13)
    unknown function (ip: 0x71c357c6683e)
    Allocations: 15306348 (Pool: 15303246; Big: 3102); GC: 13
    Aborted (core dumped)

Same happens when I try to intstall a new package.

**Comment by KristofferC** [comment]
How did you install julia?

**Comment by diffbar** [comment]
I run Arch Linux and installed julia via the official repositories.
To be sure, I did a full system update, but the problem still occurs.

**Comment by KristofferC** [comment]
See https://julialang.org/downloads/#please_do_not_use_the_version_of_julia_shipped_by_unix_package_managers.

Can you reproduce this with an official julia version?

**Comment by diffbar** [comment]
Thank you! :)
Using the official julia binary everything works.
