### ISSUE TITLE
If `Pkg.dir()` is deprecated, what is its replacement?

### ISSUE THREAD

**Issue by tkluck** [JuliaLang/Pkg.jl#417]
The function `Pkg.dir()` gives the following warning:

    Warning: Pkg.dir is only kept for legacy CI script reasons

which I think means that it is deprecated. I currently use it to pass the right library environment to a non-julia subprocess ([source][usecase]). What's the best way to get the same result?

[usecase]: https://github.com/tkluck/StatProfilerHTML.jl/blob/99015aaf09a949af7e4cf43bb78205f5911c6a76/src/StatProfilerHTML.jl#L21

I'll be happy to submit a pull request to document the alternative, hopefully in the warning itself.

**Comment by tkluck** [comment]
Thanks @KristofferC! I just pushed https://github.com/tkluck/StatProfilerHTML.jl/commit/6eb9335da621a92d4697c239c4d80ddefa82730e by your recommendation.

> `Pkg.dir` is definitely the wrong thing to use because it assumed that the package is installed in `.julia/v0.x` which might not be true at all. 

Is that a necessary limitation for this function? Couldn't `Pkg.dir` theoretically use the same resolution logic as what `using` and `import` use? (Looking at [the source](https://github.com/JuliaLang/Pkg.jl/blob/1ed4feaa5a297ec8b63647ef1585a45decfec2d9/src/API.jl#L439), I can't really decide whether that isn't what it does.)

**Comment by KristofferC** [comment]
It was a limitation with the old function, but it could indeed support showing the actual location (and that is actually what the deprecation sneakily uses).

https://github.com/JuliaLang/julia/issues/27592 should be relevant.

**Comment by tpapp** [comment]
Another use case I had for `Pkg.dir` is
```julia
cd(Pkg.dir("somepkg", "test"))
```
so that I could step through a `runtest.jl` with `include`s interactively.

Is there a suggested replacement for this?

**Comment by KristofferC** [comment]
Until JuliaLang/julia#27592 is fixed you can use something like

```
julia> pkgdir(pkg::String) = abspath(joinpath(dirname(Base.find_package(pkg)), ".."))
pkgdir (generic function with 1 method)

julia> pkgdir("Example")
"/Users/kristoffer/.julia/packages/Example/kH44/"
```

But what package julia will load is completely independent of the package manager which is why I feel this should maybe be a Base API.

**Comment by fredrikekre** [comment]
For most uses I recommend trying to rewrite the code to use `@__DIR__`, but we now also have `Base.pathof(::Module)` if need be.

**Comment by tpapp** [comment]
Not opening another issue, but I am not sure how to determine where the coverage files ended up after a
```julia
Pkg.test("SomePkg"; coverage = true)
```
using the official API. `Base.pathof` would assume that I loaded the module, right?

**Comment by fredrikekre** [comment]
For Coverage submission on CI? Youd don't need the `cd` call there anyway, we are already in the root of the package.

**Comment by tpapp** [comment]
No, for [LocalCoverage.jl](https://github.com/tpapp/LocalCoverage.jl/blob/2c70b42673fb5bbc7a1d871582e0dd58238209ea/src/LocalCoverage.jl#L59). I want to know where the files are so I can run `genhtml` etc on them.

I think this is a reasonable use case. Coverage may be run outside CI, and one may want to know where the output is for processing.

**Comment by tpapp** [comment]
Also, if there is no immediate fix, please reopen the issue or let me know if I should create another one.

**Comment by fredrikekre** [comment]
Why can't you load it? You can also use `Base.find_package`

**Comment by fredrikekre** [comment]
Another option is to change your API, and make it `generate_coverate(::Module)` instead. That is what we have done with `DocumenterTools`.

**Comment by tpapp** [comment]
> Why can't you load it?

My understanding is that it would be a global side-effect, which I would want to avoid in a function.

> You can also use `Base.find_package`

A [comment](https://github.com/JuliaLang/Pkg.jl/issues/417#issuecomment-399387040) above suggests that it may not be the right solution, did that change?

In any case, I think my issue boils down to the following: `Pkg.test(...; coverage = true)` generates files as an intended side effect, but it is not possible to find out where they are via the official API.

**Comment by KristofferC** [comment]
That is pretty much https://github.com/JuliaLang/Pkg.jl/issues/624. We could have something like `activate --target=...` that generates the new files and keeps you in that environment (so you can do e.g. `include("test/runtests.jl")`.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/issues/29030

**Comment by tpapp** [comment]
Thanks. Is there a way to query if the result of `Base.active_project()` is something I can run `pkg"test"` on?

**Comment by KristofferC** [comment]
If it has a `name = ...` in the TOML file and if `test/runtests.jl` exists.

Could probably do it like

```
function can_run_test()
    p = Base.active_project()
    try Pkg.Types.read_package(p)
    catch
        return false
    end
    return isfile(joinpath(dirname(p), "test", "runtests.jl")
end
```
