### ISSUE TITLE
Tagging packages with category Keywords / ID numbers

### ISSUE THREAD

**Issue by chakravala** [JuliaLang/Pkg.jl#43]
As discussed in https://discourse.julialang.org/t/package-naming-guidelines/7140/48

Having a keyword tagging system for packages would really help with discoverability of packages and being able to sort them, to be able to find all the similar packages that belong into the same category.

> Another idea is to have keyword ID numbers, that package developers could include in their REQUIRE file.
> 
> Then to each number you can associate a keyword category, such as “metaprogramming” or “numerical methods”. The advantage of having a numbering system is that the names of the categories can easily be modified, updated, and changed, without requiring the package developers to change their REQUIRE files.
> 
> So basically, the ID numbers will be invariant, but you can still easily change the names of the categories then, so that as the community evolves it is easier to also make the discovery and categorization evolve in time.
> 
> With thousands of packages avaialbale, it doesn’t make sense to have a single huge list of packages, it needs to be filterable and browsable using kewyord categories, and using ID numbers to specify them gives the extra flexibility of allowing the category names to be updated as things evolve.
> 
> Otherwise, instead of having the ID numbers in the REQUIRE file, they could be required as part of a Pull-Request to METADATA, so that they keyword category ID’s can be approved and agreed by the community.

> you could use tags and keywords to group and organize packages, instead of forcing related packages to be grouped into a single package. Then you can immediately tell which domain a package belongs to and that helps more than anything with understanding its relevance to a user browsing for packages.
> 
> Having a tagging keyword system is more flexible than grouping packages into a single package, because the package you want to re-group might actually be relevant to multiple keyword domains, and organizing it as part of a single meta package will be less clear than having it organized into multiple keyword categories.
> 
> So I’d advocate for having keyword tags, then any package related to that can add a tag ID to it’s listing on the Julia package listing. This is more flexible and allows evolving changes in future

*This is a feature I'd like to create a pull-request for in the future; however, I will post it as an issue for now since during the next few weeks I am going to be very busy studying for examinations in pure math and writing some papers.* If somebody else has time for implementing this for 0.7 or 1.0, please go ahead, otherwise I will eventually look into trying this out on my own branch when I actually have time for something like this, but it's not my main priority right now.

**Please let me know your comments if this is a good idea, or why it's not a good idea.**

**Comment by StefanKarpinski** [comment]
We can certainly have a `keywords` section in the project metadata in the `Project.toml` file. That's already in all of the mockup examples. We then need the ability to search keywords and descriptions.

**Comment by chakravala** [comment]
Greetings, what is the state of the keywords feature for Pkg3? Is it still only a mock up in the `project.toml` file currently, or is it already a part of the system now? I'd like to help out with it.

**Comment by StefanKarpinski** [comment]
`keywords` can be put into the project file already but there's no tooling that does that for you or does anything based on it. The indirection of ID numbers seems unnecessary to me for this – if you want to rename a keyword in a registry, just replace all instances of it. What kind of functionality would you imagine to be connected to keywords? Search seems like the most basic one. If you want to implement a name, description and keyword search feature, that would be a first step. This would take a pattern and match it against package names, their descriptions and their keywords and list the ones that match.

**Comment by chakravala** [comment]
The ID numbers vs text values would reduce the size of the downloaded data, if one had an entire database of thousands of packages for example. This might make a difference for github repositories, since Registry and METADATA repositories can grow very large in size right?

That's another feature that would come with the ID numbers (in addition to the ease of renaming the text labels of different categories without making a commit on the registry repository), but that's up to you I suppose, these are only the advantages I thought of.

As for the use and application of it, some kind of built in search feature in the `pkg>` prompt would probably be very convenient. The registry data could be downloaded and then searched for keywords for example, and other metadata fields that are included or otherwise available.

**Comment by StefanKarpinski** [comment]
> The ID numbers vs text values would reduce the size of the downloaded data, if one had an entire database of thousands of packages for example. This might make a difference for github repositories, since Registry and METADATA repositories can grow very large in size right?

This is what generic compression schemes are for – git pack files are already compressed and if we don't want to use git for transfer, we'll use compressed tarballs. So the remaining concern would be size on disk, which I doubt will be a problem – 10k packages with five 20-character keywords each is still only 1 MB. If it does become a problem, we can leave registries compressed on disk as well.

> As for the use and application of it, some kind of built in search feature in the `pkg>` prompt would probably be very convenient. The registry data could be downloaded and then searched for keywords for example, and other metadata fields that are included or otherwise available.

Anyone using the package manager already has the registry data.

**Comment by chakravala** [comment]
Alright then. Yes, I'm aware it already has the registry data, I'm only being descriptive.

How about the idea of generating a keywords lookup table though? When the registry data is updated from git, you can check which files were changed, and use that information to determine how to update the search index table stored in a file, so that when julia is restarted all of the metadata files don't have to be parsed to search for the results. Does that sound like a reasonable approach?

**Comment by chakravala** [comment]
Ah no, better yet, when a package is added to the registry, it needs to add its name to a file that lists what packages exist under each keyword. Then the list does not need to be generated, it already exists as a convenient searchable lookup table then.

**Comment by KristofferC** [comment]
Parsing all files in the registry now takes about a second and we have barely tried to optimize it (just the lowest hanging fruits). Just letting each package define their keywords seem simple enough.

**Comment by chakravala** [comment]
If it's really that fast, then that's fine

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/Pkg3.jl/pull/116#issue-167638105

**Comment by KristofferC** [comment]
If you have julia 0.7 built you can go to `julia/stdlib/Pkg3` edit the file `Project.toml` in that directory and remove the `UUID` field. Start julia, when you run `import Pkg3` you will load a new version of Pkg3 and any edits you do in `julia/stdlib/Pkg3` will be reflected in that loaded package. The reason you have to remove the UUID field is so it wont be "the same package" as the one already in the sysimg.

**Comment by chakravala** [comment]
The way the search function in my post above works, all of the key **values** are searched recursively, but not the key name itself. So the nested TOML data from Deps.toml will also be searched, but only the sha1 data is matched for the search term. So you can also do something like
```Julia
julia> pkgsearch("1234")
6-element Array{String,1}:
 "BIGUQ"       
 "COBRA"       
 "Elliptic"    
 "GLFW"        
 "LibCURL"     
 "MathProgBase"
```
And find that. But the `pkgsearch` function can easily be modified for specific search options though, and the Deps.toml file can also be excluded. It depends on how the data should be searched.

**Comment by chakravala** [comment]
Will be making a pull-request for this feature soon.

If you've had a specific search scenario in mind, please list it here so that I can make sure to handle the type of search situation that you had in mind for your purposes. I'd like to turn this into a fully functional feature for the julia language.

**Comment by chakravala** [comment]
So the `toml` files in `.julia/registries/Uncurated` are not how they will appear when Pkg3 is released? Instead, the `Project.toml` file in the Pkg3 directory is the exact format `toml` file format that will be used? What are all of the different `toml` files that are going to be around?

**Comment by chakravala** [comment]
@KristofferC could you explain how the new package manager generates new packages?

I'd like to start creating some v0.7 packages using the package generator to experiment the search.

**Comment by KristofferC** [comment]
@chakravala The only difference between https://github.com/wildart/TOML.jl and the one here should be performance.

I started some package generation stuff here https://github.com/JuliaLang/Pkg3.jl/pull/169 but still a WIP.

**Comment by chakravala** [comment]
Yes, the `TOML` performance improvements interest me, since I'd like to build a database, so working on the `Pkg3` thing is kind of like practice for something bigger I want to do, in terms of search and data.

Then I will stick to 0.7 and use the `Pkg3.TOML` package for now, since the upstream does not have the performance improvement yet. When 1.0 is released, will `Pkg3.TOML` still exist in the same way it is now or will it be downloaded from the wildart repository?

**Comment by 00vareladavid** [comment]
Closing in favor of #1070
