### ISSUE TITLE
Command to add registry

### ISSUE THREAD

**Issue by adamslc** [JuliaLang/Pkg.jl#453]
It would be nice if there was a way to add registries from the `Pkg` REPL mode. As it is now, I have to clone the registry into `.julia/registries`. Perhaps the following syntax would work
```julia
(v0.7) pkg> add registry <path/repo here>
```

I took a look at the `Pkg` code, but unfortunately adding this sort of feature is way over my head.

**Comment by KristofferC** [comment]
Yep, should be added.

**Comment by StefanKarpinski** [comment]
I think there should be a `registry` command with various sub commands including `add`, `rm`, `list` and `up`.

**Comment by davidanthoff** [comment]
Any chance that this might make it into the first release? We have a bunch of plans where this would be really key.

**Comment by fredrikekre** [comment]
Shouldn't be too hard to implement (I think), just have a look at the other commands if you wanna give it a shot.

**Comment by davidanthoff** [comment]
I won't have the time to contribute code to this, I'm afraid...

**Comment by fredrikekre** [comment]
Very WIP, but here I add a this registry https://github.com/fredrikekre/Registry where I have registered `ImportMacros` (which is not in `General`):
```
(Pkg) pkg> registry add https://github.com/fredrikekre/Registry.git
   Cloning registry from "https://github.com/fredrikekre/Registry.git"

(Pkg) pkg> add ImportMacros
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating registry at `~/.julia/registries/Registry`
  Updating git-repo `https://github.com/fredrikekre/Registry.git`
 Resolving package versions...
  Updating `Project.toml`
 [no changes]
  Updating `Manifest.toml`
 [no changes]
```

**Comment by fredrikekre** [comment]
More progress: Now supports multiple registries with the same name, distinguished by uuid, and removal of registries:
```
(Pkg) pkg> registry add https://github.com/fredrikekre/Registry.git
   Cloning registry from "https://github.com/fredrikekre/Registry.git"
     Added registry `Registry` to `~/.julia/registries/Registry`

(Pkg) pkg> registry rm Registry
ERROR: multiple registries with name Registry, please specify with uuid.

(Pkg) pkg> registry rm Registry=ae0cb698-197b-42ec-a0a0-4f871aea6013
  Removing registry `Registry` from ~/.julia/registries/Registry/xhgIZ
```

**Comment by davidanthoff** [comment]
Great! If that could make it into the release, it would be awesome!

**Comment by BenJWard** [comment]
@fredrikekre How can I test this out myself? Do I just build julia from master or do I have to do something else?

**Comment by fredrikekre** [comment]
By hand.
