### ISSUE TITLE
Explain the meaning of colors in `update`

### ISSUE THREAD

**Issue by timholy** [JuliaLang/Pkg.jl#459]
I get a lovely rainbow of colors when I update:
![image](https://user-images.githubusercontent.com/1525481/42215104-146af590-7e83-11e8-9f19-4fbd87c251d2.png)

I may have missed it, but I don't see any documentation about what the different colors mean.

**Comment by KristofferC** [comment]
Firstly, the testing diff output is not very good right now, because it shows the diff vs your current project vs the one we generate for the package getting tested. We should just show the "absolute state", i.e. not a diff when testing.

Regarding docs, indeed!

**Comment by KristofferC** [comment]
I kind of feel this doesn't really need explicit docs. Some of them are quite obvious (red = remove, green = add), and they all have a textual representation to show what happened. You will learn it quite quickly by usage.
