### ISSUE TITLE
Pkg.dev installs old dependencies?

### ISSUE THREAD

**Issue by timholy** [JuliaLang/Pkg.jl#465]
This is *definitely* a corner case, and I'm not even sure it's a bug. Executive summary: the combination of a package that:

1. switches from one package dependency to another
2. installs a dev copy of itself as part of its tests
3. spins up some additional worker processes after installing the dev copy

seems to have problems because the workers end up installing the old dependencies whereas the main process uses the new dependencies.

More detail:
I'm trying to wean Revise off of DataStructures and using a more minimal package [OrderedCollections](https://github.com/JuliaCollections/OrderedCollections.jl). My PR is https://github.com/timholy/Revise.jl/pull/108. There is no hint of DataStructures anywhere in Revise's repo:
```sh
tim@diva:~/.julia/dev/Revise$ grep -r DataStructures *
tim@diva:~/.julia/dev/Revise$ 
```
Yet when I run on Travis, I still get an installation of DataStructures: https://travis-ci.org/timholy/Revise.jl/jobs/400095353
Moreover, the travis run fails whereas it passes locally, and the failure is specifically in the Distributed tests which launch additional workers.

The final ingredient seems to happen on account of the fact that Revise checks out a development copy of itself: https://github.com/timholy/Revise.jl/blob/9a27925ff2f9a28609e99d9e692f74441b0707a4/test/runtests.jl#L671-L677. (It does this because Revise can leverage git directly now; checking out the dev copy is more complicated than it should be because of #422.) It's when checking out the dev copy that it seems to install DataStructures. The final commit in that PR just moved the distributed tests to a point prior to checking out that dev copy, and then [tests pass](https://travis-ci.org/timholy/Revise.jl/jobs/400100443) even though it still ends up installing DataStructures (just, too late to corrupt the worker processes).

This happens even though I explicitly tried calling `Pkg.resolve()` in the .travis script.

**Comment by KristofferC** [comment]
I think this is https://github.com/JuliaLang/Pkg.jl/issues/406 which is fixed here, but haven't been propagated to master. The PR to follow is https://github.com/JuliaLang/julia/pull/27824 which had some CI problems but should hopefully go in tomorrow.

**Comment by KristofferC** [comment]
I think this still happens

**Comment by KristofferC** [comment]
```
shell> rm -rf ~/.julia/dev/Cassette/

(Pkg) pkg> dev https://github.com/jrevels/Cassette.jl

shell> cat ~/.julia/dev/Cassette/REQUIRE
julia 0.7.0-DEV.5059
```

```
➜  ~ git clone  https://github.com/jrevels/Cassette.jl

➜  ~ cat Cassette.jl/REQUIRE
julia 0.7-beta2
```
