### ISSUE TITLE
add --project/-p flag to add

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg.jl#467]
For packages, that only have `Project.toml` I think it would be useful to have something like
```
(MyPackage) pkg> add --project JSON
```
that will only add `JSON` with appropriate `uuid` to `Project.toml` without doing any version resolution etc.

**Comment by StefanKarpinski** [comment]
Shouldn't those still have a `Manifest.toml` file but just not track it in version control? I.e. do `echo /Manifest.toml >> .gitignore` instead.

**Comment by fredrikekre** [comment]
Sure, but then you still have to run the resolver etc for no reason.

**Comment by KristofferC** [comment]
You could `add A B C D` if you want to not run resolve a bunch of time. But without the manifest you can't load anything. So is this just when you build up your project? What if you do

```
add --project A
add --project B
```

and `A` and `B`  are mutually exclusive?
