### ISSUE TITLE
Generate in non-empty folder?

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/Pkg.jl#477]
Would it be possible to add support for generate in a nonempty folder? It seems like the only real issue arises if there is already a Project.toml, but in interactive mode it could be a prompt to override it?

**Comment by ellisvalentiner** [comment]
I'm also interested in this.

@IainNZ I could see this working a few different ways and I'm curious what you (and others) are thinking.

1. Pkg doesn't export functions for manually generating the Project and Manifest files, but obviously already has the ability to do so (see https://github.com/JuliaLang/Pkg.jl/blob/master/src/generate.jl#L26). Pkg could export these functions and allow the user to use them directly when the directory is nonempty. This might be the least amount of work and doesn't change the behavior of `generate`.
2. Alternatively `generate` could prompt the user when the directory is nonempty and/or contains the Project or Manifest files.

I also suppose these aren't mutually exclusive options and that both could be implemented.

**Comment by 00vareladavid** [comment]
Same reason for closing as #889. When it comes to `generate`, https://github.com/invenia/PkgTemplates.jl is a lot more feature rich
