### ISSUE TITLE
dev relative/path should put relative/path in Manifest.toml

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg.jl#485]
Currently we have that
```
pkg> dev dir/Foo
```
puts `dir/Foo` in `Manifest.toml`, but 
```
pkg> dev ../Foo
```
puts the absolute path of `Foo` in `Manifest.toml`. I think it would be useful if whatever path you `dev` is put in `Manifets.toml`, and if you want an absolute path you have to dev an absolute path, e.g. 
```
pkg> dev /absolute/path/Foo
```

This would be useful for a structure like
```
Foo
├── Project.toml
├── docs
│   ├── Manifest.toml
│   └── Project.toml
└── src
    └── Foo.jl
```
where I want to be able to 
```
(docs) pkg> dev ../
```
to add `Foo` to `docs/Project.toml`.

**Comment by StefanKarpinski** [comment]
That seems reasonable to me.
