### ISSUE TITLE
Pkg asks for github credentials for private repos

### ISSUE THREAD

**Issue by rened** [JuliaLang/Pkg.jl#493]
With #430, the package manager on `up` asks for my github username / password for all private github `git@github.com/...` repos.

`up` works for me again after `setprotocol!(nothing)`, which seems to restore the previous behaviour, i.e. use the SSH keys set up with github to perform the authentication.

May I suggest `nothing` as the default, and / or a more elaborate form along the lines of `mapprotocol = Dict("http" => "https", "git" => "git")` which allows per-protocol control?

**Comment by rened** [comment]
Neither the old package manager (0.4-0.6) nor Pkg3 until #430 asked for the credentials.

**Comment by rened** [comment]
The issue comes (I believe) from the fact that all protocals are replaced to use `https` (the curernt default value). Using `nothing` lets the package manager decide (as stated in docs), so it just uses the protocols stated in Manifest.toml - git for git, http for http and https for https.

**Comment by KristofferC** [comment]
The old package manager had:

https://github.com/JuliaLang/julia/blob/f3ad0678b3c7b1b4bfdc66a093bd37907faa40dc/stdlib/OldPkg/src/cache.jl#L9

which seems like it would rewrite it to `https` by default.

Anyway, no one really complained about the old behavior we had here, so I'll swap back the default.

**Comment by rened** [comment]
@KristofferC get we get this merged into base before the beta2 tag? I would expect a lot of people to hit this.

**Comment by KristofferC** [comment]
Done
