### ISSUE TITLE
ERROR: LoadError: LoadError: UndefVarError: Dir not defined

### ISSUE THREAD

**Issue by scls19fr** [JuliaLang/Pkg.jl#510]
Hello,

I'm trying to use with Julia 0.7 a library which was written for Julia 0.6 

When doing

    using ThisLibrary

I'm getting the following error:

    ERROR: LoadError: LoadError: UndefVarError: Dir not defined

Maybe we should have a depreciation warning instead.

Kind regards

**Comment by KristofferC** [comment]
`Pkg.Dir` was never part of the  `Pkg` API, `Pkg.dir` was and it has a deprecation warning. Also, `Pkg.dir` should seldom be used inside packages.

**Comment by KristofferC** [comment]
The call the package is acutally doing is `Pkg.Dir._pkgroot()` though.

**Comment by scls19fr** [comment]
With Julia 0.6

    julia> Pkg.Dir._pkgroot()
    "/Users/scls/.julia"

How can it be replaced for Julia 0.7?

**Comment by KristofferC** [comment]
The package manager system used right now is very different so there is no direct translation that would work the same way.

**Comment by StefanKarpinski** [comment]
I don’t think there’s anything actionable here. This package was using an internal private function of the ackage manager which does not exist anymore.
