### ISSUE TITLE
Context kwargs should just be a single kwarg in API functions instead of API just passing kwargs... to it

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#515]
Bad error messages otherwise and there is currently no documentation about it so for now it is just an implementaion.

**Comment by 00vareladavid** [comment]
I've been thinking about this. What about something like this?

- `Pkg.develop([:preview => true], "Example"; devdir=true)` : for callers who don't care about `Context` and just want to preview
- `Pkg.develop(ctx, "Example"; devdir=true)` : for callers who already have a `Context` object (they should just modify it themselves)
- `Pkg.develop("Example"; devdir=true)` : this one will just create a `Context` object with default values

All context options will go in their own explicit argument. Arguments specific to the API function will be keyword arguments.

**Comment by KristofferC** [comment]
2 years later, `Context` shouldn't exist at all.
