### ISSUE TITLE
Only suggest installable packages for current julia version on tab completion in add  + dev

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#520]
Aint no one wanna install REPLCompletions.

**Comment by StefanKarpinski** [comment]
So would this be special-cased in the tab completion code or controlled by some property in the project file? I.e. does this only apply to a few stdlibs or is it a more general thing?

**Comment by KristofferC** [comment]
Special cased in completion, look it up in `Versions.toml` for all completion candidates in the registry.
