### ISSUE TITLE
Use user-agent in Webclient for download

### ISSUE THREAD

**Issue by phlavenk** [JuliaLang/Pkg.jl#537]
As discussed on [discourse](https://discourse.julialang.org/t/julia-0-7-package-development-workflow-where-are-git-repositories-of-packages/12455/8?u=phlavenk), with empty user-agent, download on windows (using PowerShell) from GitHub fails and pkg defaults for libgit cloning - slowing the install process and polluting disk space with .git's files. Would be nice to get it fixed into 1.0.

**Comment by KristofferC** [comment]
Yes, this is fixed here already and I am preparing a PR to julia to incorporate those changes.

**Comment by phlavenk** [comment]
Thank you Kristoffer, I should have looked into Pkg source code and not into Julia's one.
