### ISSUE TITLE
relation to wildart/TOML.jl, just using the TOML functionality

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/Pkg.jl#545]
AFAICT this package contains an improved fork of [wildart/TOML.jl](https://github.com/wildart/TOML.jl), which is the only TOML implementation that works on v0.7 ATM.

I need a TOML parser/writer for general purposes, and I wonder if I can just rely on
```julia
using Pkg.TOML
```
in the future, or whether this is a temporary thing and changes will be integrated back and the fork deleted at some point.

FWIW, if a fork is maintained, since the functionality is already there it would be great to "officially" expose it, ie have a TOML parser supported in STDLIB.

**Comment by KristofferC** [comment]
This is for now considered an inplementation detail and usage of it light break in the future. At some point we want to move it out though.
