### ISSUE TITLE
test with no argument should test the active project

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/Pkg.jl#546]
If the active project has tests, `pkg> test` seems like it should run them.

**Comment by KristofferC** [comment]
It doesn't?

**Comment by quinnj** [comment]
This worked in my travis run from today: https://github.com/JuliaData/Parsers.jl/blob/master/.travis.yml

**Comment by KristofferC** [comment]
FWIW, in that script, you don't have to `cd(Pkg.dir("Parsers"))` for covverage since we are already in that folder. So it can just be removed.

**Comment by KristofferC** [comment]
Closing since this works.
