### ISSUE TITLE
search all of a project's dependencies

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/Pkg.jl#557]
Suppose you know that some dependency is calling `listen` and opening a port on all interfaces. You want to know which dependency might be calling `listen` but your dependencies are spread out in various places on your file system. It would be really nice if you could do `pkg> grep listen` and get all the places in all of your dependencies where the word `listen` occurs.

**Comment by KristofferC** [comment]
Adding a full grep interface could be done in a separate package. It doesn't feel like we will add all that to Pkg.
