### ISSUE TITLE
dependency of test dependency not resolved

### ISSUE THREAD

**Issue by garrison** [JuliaLang/Pkg.jl#567]
I have three unregistered packages, each of which has a `Project.toml` file.  Package2 depends on Package1.  Package3's *tests* depends on Package2, as described in its `Project.toml` following the method [here](https://docs.julialang.org/en/latest/stdlib/Pkg/#Test-specific-dependencies-1).  When I run `Pkg.test("Package3")` on julia-0.7-rc2, I get the following error:

```
   Testing Package3
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Package1 [a63ae028]:
 Package1 [a63ae028] log:
 ├─Package1 [a63ae028] has no known versions!
 └─restricted to versions * by Package2 [975f4ea6] — no versions left
   └─Package2 [975f4ea6] log:
     ├─possible versions are: 0.0.0 or uninstalled
     └─Package2 [975f4ea6] is fixed to version 0.0.0
```

However, if I explicitly specify Package1 as a test dependency of Package3, then everything works.

If I recall correctly, everything worked on the beta, so this seems to be a recent regression.  The same error occurs on rc1.  Note that the method for specifying test dependencies has change since the beta, but I have updated all my `Project.toml` files accordingly.

**Comment by 00vareladavid** [comment]
I'll take a crack at this (fair warning: my chance of success on this is admittedly low).
If anyone else is going to try, I do have a failing test ready here: https://github.com/00vareladavid/Pkg.jl/commit/9554b047a83ab341dd05960046e3e0511f572a6f
