### ISSUE TITLE
Add "pkg> status SomePackage"

### ISSUE THREAD

**Issue by rened** [JuliaLang/Pkg.jl#575]
In large projects with dozens of packages it would be helpful to only show info related to one package e.g. only

```
pkg> st FileIO
  [5789e2e9] ~ FileIO v0.9.1+ #44b3fd8 (git@github.com:contextflow/FileIO.jl.git) ⇒ v1.0.0+ #44b3fd8 (git@github.com:contextflow/FileIO.jl.git)
```

Perhaps also show the packages with are only installed as dependecies because of that particular package (not sure about this, though).

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/Pkg.jl/issues/381I think.

**Comment by fredrikekre** [comment]
Not necessarily, that issue seems to be about showing metadata like license etc, while this is about showing status about the package as installed? (Basically just a filtered `pkg> status` call IIUC)

**Comment by jtackm** [comment]
As a further suggestion, it would be great to also allow getting information for multiple packages, with syntax similar to ```]add```:

```julia
pkg> st LightGraphs MetaGraphs SimpleWeightedGraphs
```

**Comment by cossio** [comment]
Should this be closed?
