### ISSUE TITLE
Remove `--env` stuff

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#590]
I think we have settled to use `activate`.

**Comment by 00vareladavid** [comment]
I'll get rid of it.

Is it worth keeping around any of the "meta option" machinery after this? Without `--env` it will just be taking up space. It seems unlikely that there will be an option which applies to all supported commands. 

For any (future) global configuration, it should be easy to introduce a `config` command that users can key into and wont require any special parsing.
