### ISSUE TITLE
Ability to get a REPL in a test environment

### ISSUE THREAD

**Issue by jekbradbury** [JuliaLang/Pkg.jl#593]
The Pkg docs say:
> The tests are run by generating a temporary environment with only pkg and its (recursive) dependencies (recursively) in it. If a manifest exist, the versions in that manifest is used, otherwise a feasible set of package are resolved and installed.

This means that the load path that is used to run a package's tests isn't exactly the same as the one you get by activating a package's environment; occasionally this may mean that a package will raise an error during testing that doesn't replicate in a REPL or by explicitly running `runtests.jl` in the package's environment.

Something that might be helpful for debugging in such a situation is either a command for entering a REPL in the test environment, or documentation that explains how to manually set the load path to accomplish the same thing.

cc @sbromberger

**Comment by KristofferC** [comment]
Closing as dup of #624 (even though this one was first)
