### ISSUE TITLE
Freeing a package tracking a repo doesn't collect compat from registry

### ISSUE THREAD

**Issue by omus** [JuliaLang/Pkg.jl#606]

**Comment by omus** [comment]
cc: @KristofferC

**Comment by KristofferC** [comment]
Do you remember the reproducer for this? I fail to reproduce it locally now.

**Comment by omus** [comment]
Umm, from what I can remember I was freeing a developed package and I it complained that one of it's dependencies was un-resolvable. I'll re-open this if it occurs again.
