### ISSUE TITLE
develop on non-METADATA/General packages fails

### ISSUE THREAD

**Issue by jmert** [JuliaLang/Pkg.jl#608]
I'm using some custom packages that are not registered as part of METADATA/General, and trying to `dev` any of them fails.

For example, take this simple package:
```bash
$ cd /tmp
$ julia-dev -e 'using Pkg; pkg"generate Dep"' && \
> (cd Dep && git init . && git add -A && git commit -m "Initial")
```
Then starting in a new project environment using this:
```julia
$ mkdir Project && cd Project && julia-dev
...
(v1.0) pkg> activate .
(Project) pkg> add "user@localhost:/tmp/Dep"
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Cloning git-repo `user@localhost:/tmp/Dep`
  Updating git-repo `user@localhost:/tmp/Dep`
 Resolving package versions...
  Updating `Project.toml`
  [a2037046] + Dep v0.1.0 #master (user@localhost:/tmp/Dep)
  Updating `Manifest.toml`
  [a2037046] + Dep v0.1.0 #master (user@localhost:/tmp/Dep)
```
But now, trying to `dev` on `Dep` fails (both the simple case and trying the add the full UUID as the error suggests):
```julia
(Project) pkg> dev Dep
ERROR: The following package names could not be resolved:
 * Dep (a2037046-9c09-11e8-19b0-73a67e54153c in manifest but not in project)
Please specify by known `name=uuid`.

(Project) pkg> dev Dep=a2037046-9c09-11e8-19b0-73a67e54153c
ERROR: KeyError: key UUID("a2037046-9c09-11e8-19b0-73a67e54153c") not found
Stacktrace:
 [1] getindex at ./dict.jl:478 [inlined]
 [2] registered_info(::Pkg.Types.EnvCache, ::Base.UUID, ::String) at /home/user/devel/ext/julia/build/usr/share/julia/stdlib/v1.0/Pkg/src/Types.jl:1077
 [3] set_repo_for_pkg!(::Pkg.Types.EnvCache, ::Pkg.Types.PackageSpec) at /home/user/devel/ext/julia/build/usr/share/julia/stdlib/v1.0/Pkg/src/Types.jl:744
...
```
`status` does show that the package is known, though, and including it does work:
```julia
(Project) pkg> status
    Status `Project.toml`
  [a2037046] Dep v0.1.0 #master (user@localhost:/tmp/Dep)
julia> using Dep
[ Info: Precompiling Dep [a2037046-9c09-11e8-19b0-73a67e54153c]
```

The same does work if trying to `dev` a registered package (e.g. `StaticArrays`).

**Comment by fredrikekre** [comment]
`dev` does not know what `Dep` is, or where to find it (since it is not in a registry), so just as you used the local path when `add`ing, you need to `dev` the path, something like `dev "user@localhost:/tmp/Dep"` should work.

**Comment by jmert** [comment]
OK, I think your reply has shifted my mental model enough to understand — `dev` is more like `add` which needs a full specification than it is like `update` which uses stored info in the manifest — but the error message isn't particularly helpful in understanding that.

I guess ideally I'd call this a feature request then to have `dev` work based on the path stored in the manifest if it's already installed, but at the very least it'd be clarifying to have the error message and documentation make this situation clearer. (Ultimately, I'd like to setup my own registry and bypass some of these issues, but not until the tools exist to do that.)
