### ISSUE TITLE
Building packages call `startup.jl` with every build

### ISSUE THREAD

**Issue by iht** [JuliaLang/Pkg.jl#609]
In Julia 1.0.0, every time I try to build a package, the startup script `~/.julia/config/startup.jl` is called. If that script imports any package not available in the build environment, the build fails. For instance, if I add  `using OhMyREPL` to my `startup.jl`, the build fails with this error:

```julia-repl
julia> Pkg.add("Plots")
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed Showoff ────── v0.2.0
 Installed StaticArrays ─ v0.8.3
 Installed Plots ──────── v0.18.0
 Installed PlotUtils ──── v0.5.0
 Installed PlotThemes ─── v0.3.0
 Installed Measures ───── v0.2.0
 Installed RecipesBase ── v0.4.0
 Installed Contour ────── v0.5.0
 Installed GR ─────────── v0.32.2
  Updating `~/.julia/environments/v1.0/Project.toml`
  [91a5bcdd] + Plots v0.18.0
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [d38c429a] + Contour v0.5.0
  [28b8d3ca] + GR v0.32.2
  [442fdcdd] + Measures v0.2.0
  [ccf2f8ad] + PlotThemes v0.3.0
  [995b91a9] + PlotUtils v0.5.0
  [91a5bcdd] + Plots v0.18.0
  [3cdcf5f2] + RecipesBase v0.4.0
  [992d4aef] + Showoff v0.2.0
  [90137ffa] + StaticArrays v0.8.3
  Building GR ───→ `~/.julia/packages/GR/crXzk/deps/build.log`
┌ Error: Error building `GR`:
│ ERROR: LoadError: ArgumentError: Package OhMyREPL not found in current path:
│ - Run `Pkg.add("OhMyREPL")` to install the OhMyREPL package.
....
```

I think building a package should not call the `startup.jl` at all, and it should try to build the packages in a "clean" environment.

My versioninfo:

```
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

PS: Also reported here, to try to find a way not to import `OhMyREPL` when the session is not interactive: https://github.com/KristofferC/OhMyREPL.jl/issues/68

**Comment by fredrikekre** [comment]
This is actually fixed(40d7f27f2ff08ec466df536f267129a9f5e950b4), but was lost in the port to Julia. Should be included in Julia v1.0.1. See also https://discourse.julialang.org/t/error-with-pkg-with-using-statement-in-startup-jl/13127/3?u=fredrikekre

**Comment by fredrikekre** [comment]
Also, you can start julia with `julia --startup-file=no` to workaround it for now.

**Comment by iht** [comment]
Thanks for the info and the hint.
