### ISSUE TITLE
CI sometimes stalling

### ISSUE THREAD

**Issue by omus** [JuliaLang/Pkg.jl#611]
I've noticed in a couple of cases on the CI the package manager seeming to stall and either cause the job to fail or take longer than normal. For example:

- [11 minutes for TimeZones.jl on nightly](https://travis-ci.org/JuliaTime/TimeZones.jl/builds/414395760). Typically nightly takes around 3 minutes. I took a look while it was running and it seemed to be working on a Pkg3 operation.
- [1 hour (cancelled) for LibCURL.jl on 0.7](https://ci.appveyor.com/project/shashi/libcurl-jl/build/1.0.26)

I'll keep my eye out for more examples.

**Comment by ararslan** [comment]
10m22s for NMF on 0.7: https://travis-ci.org/JuliaStats/NMF.jl/jobs/414574845

**Comment by KristofferC** [comment]
If anyone could get a backtrace by canceling the operation when this happens it would be useful.

**Comment by omus** [comment]
I may have gotten a good hit. It seems that the LibCURL Appveyor tests for 32-bit and Julia 0.7 have this issue consistently. I'm testing this out again to see if it really is consistently occuring.

**Comment by KristofferC** [comment]
Haven't head about this in a while. Closing but feel free to comment if it keeps happening.
