### ISSUE TITLE
Missing `Test` dependency works when testing from `(v1.0)`, doesn't work when testing from `(PkgName)`

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/Pkg.jl#612]
While working on `JLD2`, I noticed that running `(v1.0) pkg> test` worked, but running `(JLD2) pkg> test` doesn't work, because `Test` wasn't a dependency.  It remains a mystery to myself and Kristoffer as to why the tests running within the global environment worked.

**Comment by KristofferC** [comment]
Let's reopen if this happens again.
