### ISSUE TITLE
`pkg> git` command that just calls git?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/Pkg.jl#620]
We keep getting issues like https://github.com/JuliaLang/Pkg.jl/issues/610 and indeed, I often find myself accidentally calling `pkg> git diff` and such. You can, of course, `cd` into your active project and use `shell> git ...` to do various git operations in the active project but we perhaps we should just make `pkg> git ...` do that for you.

**Comment by KristofferC** [comment]
Hmm, how is #610 related to this?

**Comment by StefanKarpinski** [comment]
> Oh, but of course, @fredrikekre just reminded me that the copy in ~/.julia/packages isn't a full git clone. Womp womp.

If we just allowed calling `git` inside of `pkg>` then I think that kind of issue would be alleviated since it would be a full git client.

**Comment by KristofferC** [comment]
I'm still confused. #610 was about someone wanting to dev a package while being offline, which was closed because that is fundamentally impossible since we havent downloaded the git repo.

How does a git command help with that?

**Comment by StefanKarpinski** [comment]
Ok, forget the connection to #610. It's common to want to do git commands inside of the current active project. What about a `pkg> git ...` command that just call `git` in the right place?

**Comment by KristofferC** [comment]
Tbh, I rather not add the extra complexity of this when one can almost literally just pres `;` and start running `git`.
