### ISSUE TITLE
Allow activating custom project targets

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/Pkg.jl#624]
I feel that Pkg should allow activating one of the `[targets]` as an environment. It has probably come up before but I didn't find an issue for this. For the user there probably should be:

- Relevant Pkg / REPL API: `activate --target=foo <path>` ?
- A way to activate from the command line: `julia --project=<project> --project-target=foo` or maybe something like `julia --project=<project>:foo`

Although.. since `--project` can be a path, then having some sort of a separator would be tricky?

**Comment by StefanKarpinski** [comment]
I agree, although the implementation details still need to be worked out.

**Comment by KristofferC** [comment]
Yes, this is a good idea, however, you would need to do a resolve to activate it.

**Comment by StefanKarpinski** [comment]
What I'd like to do is:
1. Rewrite the resolver as a SAT solver that can resolve target dependencies correctly at the same time.
2. Record extra dependencies in the manifest as well as main dependencies, but don't necessarily install those unless requested.
4. When activating a target, you already know from the main manifest which versions to use for the extras, you just have to tell it not to ignore those marked as extra.

**Comment by mortenpi** [comment]
So the extra dependencies will also limit the versions you can install in the main environment? And the  bounds on the extra deps of a package's dependency will also be checked when installing a package? (Not saying this would be bad or anything, just curious.)

**Comment by StefanKarpinski** [comment]
Yes, that's the general idea.

**Comment by 00vareladavid** [comment]
I just read an article about SAT solvers and immediately thought of `Pkg`. I'm curious how serious this plan is? IIRC performance was a concern, how do you think it would compare to the current resolver? Do you have an existing implementation in mind?

**Comment by StefanKarpinski** [comment]
I'm planning on implementing [this paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.154.8574&rep=rep1&type=pdf) in Julia. They hacked up [MiniSAT](http://minisat.se) to evaluate their implementation but the patch isn't public or, from the sound of it, super clean. I suspect that implementing a SAT with preferences solver in Julia won't be all that hard compared to doing it in C, for example.

**Comment by 00vareladavid** [comment]
Do you know of any good test sets? I have a basic version of the minisat algorithm running in julia. Its passing for hand coded tests, but its better if I test against tests I didn't write myself. I found tests for the SAT competition, but they are quite large and AFAICT only test if the model is SAT/UNSAT (i.e. they dont provide concrete solutions). If nothing else, I will have to map some problem (e.g. Sodoku)  to provide small tests suitable for debugging/introspection.

**Comment by oxinabox** [comment]
related:
https://github.com/JuliaLang/Pkg.jl/issues/744

**Comment by o314** [comment]
> a simpler solution would be to generate additional manifest files, say Manifest.targetname.toml?

Since v1.2, a package can have multiple `Project.toml` too.
One for `src`, one for `test` optionally.
May be one for `docs` ...

That has to be taken into consideration regarding the number of manifest files.

--

Other approach : if we allow multiple projects per package, is target still useful ?

**Comment by o314** [comment]
FYI, the following package manager (at least) are driven by sat

- composer, package manager for php, license mit
  - https://github.com/composer/composer
  - [dependency resolution with a sat solver](https://www.slideshare.net/naderman/dependency-resolution-with-sat-symfony-live-2011-paris)

- zypp, package manager for opensuse/suse, license gpl
    - https://github.com/openSUSE/libzypp
    - https://doc.opensuse.org/projects/libzypp/HEAD/

- libsolv, package manager for opensuse/suse, license bsb
    - https://github.com/openSUSE/libsolv

- deps, package manager for go lang, license bsd
    - https://github.com/golang/dep/
    - https://golang.github.io/dep/docs/introduction.html
    - https://github.com/golang/dep/blob/master/docs/the-solver.md

**Comment by pdeffebach** [comment]
Has there been progress on this issue? Would be nice to have.

**Comment by oschulz** [comment]
Just wanted to vote for this (I understand it's not easy, though, from what Stefan writes). Found myself wishing for it today (https://discourse.julialang.org/t/activating-test-dependencies/48121/4) when trying to debug a package and it's tests.

**Comment by timholy** [comment]
I don't understand why it requires a whole new resolver algorithm, and I worry that this has distracted the focus from an easier solution. It seems that what you need to do is create a temporary environment that incorporates the [deps] and [extras] of the "parent" environment and then run `resolve` & `instantiate`.

**Comment by oschulz** [comment]
When I asked for this on discourse, I had assumed the mechanism was already there - after all, Pkg.test does activate the test dependencies. I guess that uses a temporary environment or so?

**Comment by timholy** [comment]
I don't know how it works, but for this case you need to have a temporary environment that persists at the REPL.

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/Pkg.jl/issues/1233 is the plan, we can probably close this issue in favor of that.

**Comment by o314** [comment]
@00vareladavid 

> I have a basic version of the minisat algorithm running in julia. Its passing for hand coded tests, but its better if I test against tests I didn't write myself. I found tests for the SAT competition, but they are quite large and AFAICT only test if the model is SAT/UNSAT (i.e. they dont provide concrete solutions). If nothing else, I will have to map some problem (e.g. Sodoku) to provide small tests suitable for debugging/introspection.

Have you already published it ? I will be glad to have a look at it ...
