### ISSUE TITLE
MonkeyPkg.jl for monkey patching Pkg?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/Pkg.jl#628]
The idea is that people would put `import MonkeyPkg` in their startup scripts and get more up-to-date monkey patching of Julia 1.0 Pkg functionality since we still need quite a lot of improvements and waiting until 1.1 could be too slow. Of course the alternative is for people to just build master where the improvements will already exist.

**Comment by fredrikekre** [comment]
I assume we will/can make a 1.0.1 release for Julia 1.0.1?

**Comment by StefanKarpinski** [comment]
Yes, but we can't add features since that's a bug fix release.

**Comment by KristofferC** [comment]
So they get the features in 1.1 just like with other stdlibs? Having a monkey patch version of all stdlibs seems unscalable.

**Comment by pfitzseb** [comment]
Wait, I thought stdlibs are supposed to be updateable without any regard to Julia version?

**Comment by KristofferC** [comment]
Sure, but that requires a system that up reading them at all is possible, which we don't have right now.

**Comment by 00vareladavid** [comment]
Is there a reason there have been no merged PRs lately? I don't think `1.1` should be an issue since this repo is not automatically mirrored upstream right?

**Comment by KristofferC** [comment]
The reason is that I have been busy with JuliaCon for the whole last week and was traveling yesterday. Things should be back to normal now though :)

**Comment by 00vareladavid** [comment]
Should be closed by JuliaLang/julia/pull/29615?

**Comment by KristofferC** [comment]
I don't think we will go this way. Maintaining a separate repo that overwrites functions and test that etc is just not sustainable.
