### ISSUE TITLE
win10 addpkg wrong

### ISSUE THREAD

**Issue by lujianok** [JuliaLang/Pkg.jl#633]
when I add Pkg "DataFrames"(which can be added successfully in Mac Julia(v1.0)) in Julia(v1.0), an error happened as follows:
"(v1.0) pkg> add DataFrames
ERROR: The following package names could not be resolved:
 * DataFrames (not found in project, manifest or registry)
Please specify by known `name=uuid`."
Is there something I forgot when configuring Julia?

**Comment by KristofferC** [comment]
Could you run:

```
rm(joinpath(homedir(), ".julia", "registries"); recursive=true)
```

and try again?

**Comment by KristofferC** [comment]
https://discourse.julialang.org/t/error-giterror-code-error-class-os-failed-to-send-request-a-connection-with-the-server-could-not-be-established/10192/9 seems like a similar problem

**Comment by lujianok** [comment]
thanks！I try again and it runs successfully, it seems an internet glitch. lucky
