### ISSUE TITLE
proxy error 407 on corporate proxy

### ISSUE THREAD

**Issue by GeraldKaeferle** [JuliaLang/Pkg.jl#647]
Hi ,

I can't install packages behind a corporate proxy. It's an authentications issue a shown in this message. This is partly in german but (407) Proxyauthentifizierung means (407) proxy authentication.

`(v1.0) pkg> add Distances
 Resolving package versions...
Exception calling "DownloadFile" with "2" argument(s): "Der Remoteserver hat
einen Fehler zurückgegeben: **(407) Proxyauthentifizierung** erforderlich."
At line:5 char:1
+ $webclient.DownloadFile("https://api.github.com/repos/JuliaStats/Dist ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException`

By reviewing the code, I found in file PlattformEngines.jl following lines for windows platforms and enhanced it for using users network (default) credentials to authenticate against proxy servers.

```
webclient_code = """
                [System.Net.ServicePointManager]::SecurityProtocol =
                    [System.Net.SecurityProtocolType]::Tls12;
                \$webclient = (New-Object System.Net.Webclient);
                \$webclient.UseDefaultCredentials = \$true;
                \$webclient.Proxy.Credentials = \$webclient.Credentials;
                \$webclient.Headers.Add("user-agent", \"Pkg.jl (https://github.com/JuliaLang/Pkg.jl)\");
                \$webclient.DownloadFile(\"$url\", \"$path\")
                """
```
I'll tried to test it but I can't find a way to rebulid Pkg. Simply using `] bulid Pkg` seems not to change anything.
```
(v1.0) pkg> build Pkg
[ Info: no packages to build
```
Thanks for giving me hint to solve this or for using this enhancment in future versions.

**Comment by KristofferC** [comment]
Thanks for looking into this.

You can test your changes using the method described in the README: https://github.com/JuliaLang/Pkg.jl#using-the-development-version-of-pkgjl.

**Comment by GeraldKaeferle** [comment]
Thanks for giving me this hint. By the way it **worked**. I installed serveral packages but I got an error on include("test/runtests.jl").

`julia> include("test/runtests.jl")
Test Summary:   | Pass  Total
semver notation |   62     62
Test Summary:     | Pass  Total
union, isjoinable |   12     12
───── Preview mode ─────
[ Info: Skipping updating registry in preview mode
   Cloning default registries into C:\Users\kaege\AppData\Local\Temp\jl_70FD.tmp
\registries
   Cloning registry General from "https://github.com/JuliaRegistries/General.git
"

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7feff305a01 -- strlen at C:\WINDOWS\s
ystem32\msvcrt.dll (unknown line)
in expression starting at C:\Users\kaege\Downloads\Pkg.jl-master\test\pkg.jl:118

strlen at C:\WINDOWS\system32\msvcrt.dll (unknown line)
git_buf_puts at C:\Users\kaege\AppData\Local\Julia-1.0.0\bin\libgit2.DLL (unknow
n line)
gitno_extract_url_parts at C:\Users\kaege\AppData\Local\Julia-1.0.0\bin\libgit2.
DLL (unknown line)
winhttp_stream_connect at C:\Users\kaege\AppData\Local\Julia-1.0.0\bin\libgit2.D
LL (unknown line)
winhttp_stream_read at C:\Users\kaege\AppData\Local\Julia-1.0.0\bin\libgit2.DLL
(unknown line)
git_smart__recv_cb at C:\Users\kaege\AppData\Local\Julia-1.0.0\bin\libgit2.DLL (
unknown line)
git_smart__store_refs at C:\Users\kaege\AppData\Local\Julia-1.0.0\bin\libgit2.DL
L (unknown line)
git_smart__connect at C:\Users\kaege\AppData\Local\Julia-1.0.0\bin\libgit2.DLL (
unknown line)
git_remote_fetch at C:\Users\kaege\AppData\Local\Julia-1.0.0\bin\libgit2.DLL (un
known line)
git_clone at C:\Users\kaege\AppData\Local\Julia-1.0.0\bin\libgit2.DLL (unknown l
ine)
macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\bu
ild\usr\share\julia\stdlib\v1.0\LibGit2\src\error.jl:99 [inlined]
clone at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\sh
are\julia\stdlib\v1.0\LibGit2\src\repository.jl:459
macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\bu
ild\usr\share\julia\stdlib\v1.0\LibGit2\src\LibGit2.jl:580 [inlined]
macro expansion at .\gcutils.jl:87 [inlined]
#clone#131 at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\u
sr\share\julia\stdlib\v1.0\LibGit2\src\LibGit2.jl:570
unknown function (ip: 000000001F8BEC88)
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/sr
c\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\
gf.c:2182 [inlined]
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:
1536 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:56

#clone at .\none:0 [inlined]
#clone#2 at C:\Users\kaege\Downloads\Pkg.jl-master\src\GitTools.jl:94
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/sr
c\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\
gf.c:2182 [inlined]
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:
1536 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:56

#50 at .\none:0
shred! at .\secretbuffer.jl:184
#registries#49 at C:\Users\kaege\Downloads\Pkg.jl-master\src\Types.jl:920
unknown function (ip: 000000001F8BB42E)
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/sr
c\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\
gf.c:2182 [inlined]
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:
1536 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:56

registries at C:\Users\kaege\Downloads\Pkg.jl-master\src\Types.jl:904 [inlined]
#find_registered!#58 at C:\Users\kaege\Downloads\Pkg.jl-master\src\Types.jl:986
unknown function (ip: 000000001F8BA4A3)
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/sr
c\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\
gf.c:2182 [inlined]
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:
1536 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:56

find_registered! at C:\Users\kaege\Downloads\Pkg.jl-master\src\Types.jl:955 [inl
ined]
registry_resolve! at C:\Users\kaege\Downloads\Pkg.jl-master\src\Types.jl:826
#add_or_develop#13 at C:\Users\kaege\Downloads\Pkg.jl-master\src\API.jl:57
unknown function (ip: 000000001F8A24A1)
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/sr
c\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\
gf.c:2182 [inlined]
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:
1536 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:56

#add_or_develop#11 at .\none:0
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/sr
c\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\
gf.c:2182 [inlined]
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:
1536 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:56

#12 at .\none:0
#3 at C:\Users\kaege\Downloads\Pkg.jl-master\test\utils.jl:23 [inlined]
mktempdir at .\file.jl:576
mktempdir at .\file.jl:574 [inlined]
#2 at C:\Users\kaege\Downloads\Pkg.jl-master\test\utils.jl:20 [inlined]
mktempdir at .\file.jl:576
mktempdir at .\file.jl:574 [inlined]
#1 at C:\Users\kaege\Downloads\Pkg.jl-master\test\utils.jl:19 [inlined]
withenv at .\env.jl:148
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/sr
c\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\
gf.c:2182 [inlined]
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:
1536 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:56

temp_pkg_dir at C:\Users\kaege\Downloads\Pkg.jl-master\test\utils.jl:18
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/sr
c\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\
gf.c:2182
do_call at /home/Administrator/buildbot/worker/package_win64/build/src\interpret
er.c:324
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src\interp
reter.c:428
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src\i
nterpreter.c:363 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src\interpr
eter.c:682
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/pack
age_win64/build/src\interpreter.c:799
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 000000000F050C8F)
unknown function (ip: 000000000000002E)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build
/src\toplevel.c:787
jl_eval_module_expr at /home/Administrator/buildbot/worker/package_win64/build/s
rc\toplevel.c:233
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build
/src\toplevel.c:616
jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win64/build/src
\ast.c:838
jl_load at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.
c:821 [inlined]
jl_load_ at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel
.c:828
include at .\boot.jl:317 [inlined]
include_relative at .\loading.jl:1038
include at .\sysimg.jl:29 [inlined]
include at C:\Users\kaege\Downloads\Pkg.jl-master\test\runtests.jl:3
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/sr
c\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\
gf.c:2182
do_call at /home/Administrator/buildbot/worker/package_win64/build/src\interpret
er.c:324
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src\interp
reter.c:428
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src\i
nterpreter.c:363 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src\interpr
eter.c:682
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/pack
age_win64/build/src\interpreter.c:799
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 00000000106CDDBF)
unknown function (ip: FFFFFFFFFFFFFFFF)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build
/src\toplevel.c:787
jl_eval_module_expr at /home/Administrator/buildbot/worker/package_win64/build/s
rc\toplevel.c:233
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build
/src\toplevel.c:616
jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win64/build/src
\ast.c:838
jl_load at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.
c:821 [inlined]
jl_load_ at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel
.c:828
include at .\boot.jl:317 [inlined]
include_relative at .\loading.jl:1038
include at .\sysimg.jl:29
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\
gf.c:2182
include at .\client.jl:388
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/sr
c\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\
gf.c:2182
do_call at /home/Administrator/buildbot/worker/package_win64/build/src\interpret
er.c:324
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src\interp
reter.c:428
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src\i
nterpreter.c:363 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src\interpr
eter.c:682
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/pack
age_win64/build/src\interpreter.c:799
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 00000000106E2D5F)
unknown function (ip: FFFFFFFFFFFFFFFF)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build
/src\toplevel.c:787
jl_toplevel_eval_in at /home/Administrator/buildbot/worker/package_win64/build/s
rc\builtins.c:622
eval at .\boot.jl:319
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\
gf.c:2182
eval_user_input at C:\cygwin\home\Administrator\buildbot\worker\package_win64\bu
ild\usr\share\julia\stdlib\v1.0\REPL\src\REPL.jl:85
macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\bu
ild\usr\share\julia\stdlib\v1.0\REPL\src\REPL.jl:117 [inlined]
#28 at .\task.jl:259
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/sr
c\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\
gf.c:2182
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:
1536 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src\task.c
:268
Allocations: 34050346 (Pool: 34041927; Big: 8419); GC: 73`

This is hard read but may be there is an issue with libgit2.DLL. I see lot of unkown functions.

**Comment by KristofferC** [comment]
Someone else had a problem on windows with LibGit2 (https://github.com/JuliaLang/Pkg.jl/issues/666). I am not the best person to debug things like that though.

Good that the proxy thing worked. Let's add it!

**Comment by GeraldKaeferle** [comment]
Shouldn't we test this in a non proxy scenario? I can do this on weekend. 

As I assumed libgit2.dll seems to be broken. I copied the dll-file from the 0.6.4.1 version and  gave `include("test/runtests.jl")` another try. The pointer errors are gone but now I got this error.


`julia> include("test/runtests.jl")
Test Summary:   | Pass  Total
semver notation |   62     62
Test Summary:     | Pass  Total
union, isjoinable |   12     12
───── Preview mode ─────
[ Info: Skipping updating registry in preview mode
   Cloning default registries into C:\Users\kaege\AppData\Local\Temp\jl_7CF4.tmp
\registries
   Cloning registry General from "https://github.com/JuliaRegistries/General.git
"
simple add and remove with preview: Error During Test at C:\Users\kaege\Download
s\Pkg.jl-master\test\pkg.jl:119
  Got exception outside of a @test
  failed to clone from https://github.com/JuliaRegistries/General.git, error: Gi
tError(Code:ERROR, Class:NoMemory, Out of memory)
  Stacktrace:
   [1] pkgerror(::String) at C:\Users\kaege\Downloads\Pkg.jl-master\src\Types.jl
:120
   [2] #clone#2(::String, ::Base.Iterators.Pairs{Symbol,LibGit2.CachedCredential
s,Tuple{Symbol},NamedTuple{(:credentials,),Tuple{LibGit2.CachedCredentials}}}, :
:Function, ::String, ::String) at C:\Users\kaege\Downloads\Pkg.jl-master\src\Git
Tools.jl:102
   [3] (::getfield(Pkg.Types, Symbol("##50#54")))(::LibGit2.CachedCredentials) a
t .\none:0
   [4] shred!(::getfield(Pkg.Types, Symbol("##50#54")), ::LibGit2.CachedCredenti
als) at .\secretbuffer.jl:184
   [5] #registries#49(::Bool, ::Function) at C:\Users\kaege\Downloads\Pkg.jl-mas
ter\src\Types.jl:920
   [6] registries at C:\Users\kaege\Downloads\Pkg.jl-master\src\Types.jl:904 [in
lined]
   [7] #find_registered!#58(::Bool, ::Function, ::Pkg.Types.EnvCache, ::Array{St
ring,1}, ::Array{Base.UUID,1}) at C:\Users\kaege\Downloads\Pkg.jl-master\src\Typ
es.jl:986
   [8] find_registered! at C:\Users\kaege\Downloads\Pkg.jl-master\src\Types.jl:9
55 [inlined]
   [9] registry_resolve!(::Pkg.Types.EnvCache, ::Array{Pkg.Types.PackageSpec,1})
 at C:\Users\kaege\Downloads\Pkg.jl-master\src\Types.jl:826
   [10] #add_or_develop#13(::Symbol, ::Bool, ::Base.Iterators.Pairs{Symbol,Bool,
Tuple{Symbol},NamedTuple{(:preview,),Tuple{Bool}}}, ::Function, ::Pkg.Types.Cont
ext, ::Array{Pkg.Types.PackageSpec,1}) at C:\Users\kaege\Downloads\Pkg.jl-master
\src\API.jl:57
   [11] #add_or_develop#11(::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol
},NamedTuple{(:mode, :preview),Tuple{Symbol,Bool}}}, ::Function, ::Array{String,
1}) at .\none:0
   [12] (::getfield(Main.PkgTests.OperationsTest, Symbol("##12#21")))(::String)
at .\none:0
   [13] #3 at C:\Users\kaege\Downloads\Pkg.jl-master\test\utils.jl:23 [inlined]
   [14] mktempdir(::getfield(Main.PkgTests.OperationsTest, Symbol("##3#6")){Stri
ng,getfield(Main.PkgTests.OperationsTest, Symbol("##12#21"))}, ::String) at .\fi
le.jl:576
   [15] mktempdir at .\file.jl:574 [inlined]
   [16] #2 at C:\Users\kaege\Downloads\Pkg.jl-master\test\utils.jl:20 [inlined]
   [17] mktempdir(::getfield(Main.PkgTests.OperationsTest, Symbol("##2#5")){getf
ield(Main.PkgTests.OperationsTest, Symbol("##12#21"))}, ::String) at .\file.jl:5
76
   [18] mktempdir at .\file.jl:574 [inlined]
   [19] #1 at C:\Users\kaege\Downloads\Pkg.jl-master\test\utils.jl:19 [inlined]
   [20] withenv(::getfield(Main.PkgTests.OperationsTest, Symbol("##1#4")){getfie
ld(Main.PkgTests.OperationsTest, Symbol("##12#21"))}, ::Pair{String,Nothing}, ::
Vararg{Pair{String,Nothing},N} where N) at .\env.jl:148
   [21] temp_pkg_dir(::getfield(Main.PkgTests.OperationsTest, Symbol("##12#21"))
) at C:\Users\kaege\Downloads\Pkg.jl-master\test\utils.jl:18
   [22] top-level scope at none:0
   [23] include at .\boot.jl:317 [inlined]
   [24] include_relative(::Module, ::String) at .\loading.jl:1038
   [25] include at .\sysimg.jl:29 [inlined]
   [26] include(::String) at C:\Users\kaege\Downloads\Pkg.jl-master\test\runtest
s.jl:3
   [27] top-level scope at none:0
   [28] include at .\boot.jl:317 [inlined]
   [29] include_relative(::Module, ::String) at .\loading.jl:1038
   [30] include(::Module, ::String) at .\sysimg.jl:29
   [31] include(::String) at .\client.jl:388
   [32] top-level scope at none:0
   [33] eval(::Module, ::Any) at .\boot.jl:319
   [34] eval_user_input(::Any, ::REPL.REPLBackend) at C:\cygwin\home\Administrat
or\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\REPL\src\REPL
.jl:85
   [35] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_
win64\build\usr\share\julia\stdlib\v1.0\REPL\src\REPL.jl:117 [inlined]
   [36] (::getfield(REPL, Symbol("##28#29")){REPL.REPLBackend})() at .\task.jl:2
59
Test Summary:                      | Error  Total
simple add and remove with preview |     1      1
ERROR: LoadError: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 erro
red, 0 broken.
in expression starting at C:\Users\kaege\Downloads\Pkg.jl-master\test\pkg.jl:118

in expression starting at C:\Users\kaege\Downloads\Pkg.jl-master\test\runtests.j
l:5`

**Comment by GeraldKaeferle** [comment]
BTW we have the same issue on BinaryProvider in PlatformEngines.jl. 

`webclient_code = """
                [System.Net.ServicePointManager]::SecurityProtocol =
                    [System.Net.SecurityProtocolType]::Tls12;
                \$webclient = (New-Object System.Net.Webclient);
                \$webclient.UseDefaultCredentials = \$true;
                \$webclient.Proxy.Credentials = \$webclient.Credentials;
                \$webclient.Headers.Add("user-agent", \"Pkg.jl (https://github.com/JuliaLang/Pkg.jl)\");
                \$webclient.DownloadFile(\"$url\", \"$path\")
                """
`

**Comment by KristofferC** [comment]
Yes, it is unfortunate that there is some code duplication here and in BinaryProvider. A long term goal is to make this a regular Julia package that can depend on other packages whereby we can just swap over to depend on BinaryProvider.

**Comment by GeraldKaeferle** [comment]
The test on a non proxy computer enviroment was successful. I think you can add the code .

` Info: activating new environment at C:\Users\geral\AppData\Local\Temp\jl_2479.tmp\Example.
Test Summary: | Pass  Total
Pkg.activate  |    7      7
Test Summary: | Pass  Total
schemes       |   48     48
Test Summary: | Pass  Total
realistic     |    2      2
Test Summary: | Pass  Total
nasty         |    4      4
Main.PkgTests`

I found an other source for changing : [BinDeps ](https://github.com/JuliaPackaging/BinDeps.jl/blob/609a5cb047fb2b8afaf3cb749965c9c99077a0bf/src/BinDeps.jl#L76)

`download_cmd = ""\$wc=(new-object net.webclient);\$wc.UseDefaultCredentials = \$true; \$wc.Proxy.Credentials = \$wc.Credentials; \$wc.DownloadFile(\"$url\", \"$filename\")"`

**Comment by GeraldKaeferle** [comment]
Hi Kristoffer!

Is there any else I can do?

**Comment by KristofferC** [comment]
No, see https://github.com/JuliaLang/Pkg.jl/pull/714.
