### ISSUE TITLE
gc collection time should be settable from the REPL mode

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#65]
Right now it only uses the default of 6 weeks.

**Comment by StefanKarpinski** [comment]
Actually, I would argue that there should not be any time limit: any environment that we know about ever being used which still exists should count. The place that a time limit should come in, IMO, is that any version that has been used within some period of time, regardless of whether it is still reachable from any environment, should be retained – in case you switch back to a state where you need it.

**Comment by vdayanand** [comment]
Can a user force gc?

**Comment by StefanKarpinski** [comment]
Currently this is the *only* way it ever happens: `pkg> gc`. At some point we may want to automatically call `gc` based on some trigger, however. We'll want to wait a while for that though to make sure it doesn't delete things people actually wanted. Of course, Pkg3 should make it easy to reinstall whatever's needed but let's err on the conservative side here.

**Comment by KristofferC** [comment]
Closed by https://github.com/JuliaLang/Pkg.jl/pull/333
