### ISSUE TITLE
[Enhancement] Provide a way to reset the General repo locally

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/Pkg.jl#650]
I was adding my first package and since i'm sometimes very impatient i soon got "nervous" when the download of the General repo felt stuck at 99.9% thus i interrupted it:
```
(v1.0) pkg> add StaticArrays
   Cloning default registries into C:\Users\necka\.julia\registries
   Cloning registry General from "https://github.com/JuliaRegistries/General.git"
ERROR: IOError: unlink: resource busy or locked (EBUSY)
Stacktrace:
 [1] uv_error at .\libuv.jl:85 [inlined]
 [2] unlink(::String) at .\file.jl:722
...
```
 Retrying though led to other errors like
```
(v1.0) pkg> add StaticArrays
ERROR: The following package names could not be resolved:
 * StaticArrays (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```

Now i was looking for a way to "redownload" General. But i didn't find one...

Enhancement: Provide a way to somehow "reset" the immutable part of the whole package manager like redownloading every registry and state of required packages

**Comment by KristofferC** [comment]
Thanks for the report.

This is fixed, will be in next bugfix release of julia.

**Comment by rapus95** [comment]
Interrupting at a later point in cloning delivers a `libuv` error.
BTW is there a reference to that fix? For that i can decide whether other errors in a similar situation are of value for you?

**Comment by fredrikekre** [comment]
And also with https://github.com/JuliaLang/Pkg.jl/pull/588 you will be able to `pkg> registry add General`.

**Comment by rapus95** [comment]
> BTW is there a reference to that fix? 
found it: https://github.com/JuliaLang/Pkg.jl/issues/633

**Comment by rapus95** [comment]
@KristofferC got another problem in a similar situation but opened a new issue for it: https://github.com/JuliaLang/Pkg.jl/issues/652
