### ISSUE TITLE
setprotocol!("git") results in `git://github.com/` URLs instead of `git@github.com:`

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/Pkg.jl#653]
Consider, in a new environment:

```julia
julia> import Pkg

julia> Pkg.setprotocol!("git")
"git"

(v1.0) pkg> dev Literate
```

Then we get (in `~/.julia/dev/Literate`)

```julia
➜  Literate git:(master) git remote -v
origin  git://github.com/fredrikekre/Literate.jl.git (fetch)
origin  git://github.com/fredrikekre/Literate.jl.git (push)
```

I was expecting `git@github.com:fredrikekre/Literate.jl.git`, which is what you get when you use the 'Clone or Download' button on the repo. I'm no expert on this and everything seems to be OK so maybe this is fine, but it was just surprising to me.

**Comment by tkoolen** [comment]
Nope, can't push.

**Comment by StefanKarpinski** [comment]
`git@github.com:` is equivalent to `ssh://git@github.com/` not `git://github.com/`

**Comment by Evizero** [comment]
```
julia> using Pkg

julia> Pkg.setprotocol!("ssh")
"ssh"

(v0.7) pkg> dev ColorTypes
   Cloning git-repo `https://github.com/JuliaGraphics/ColorTypes.jl.git`
ERROR: failed to clone from ssh://github.com/JuliaGraphics/ColorTypes.jl.git, error: GitError(Code:EAUTH, Class:None, No errors)
```

**Comment by StefanKarpinski** [comment]
Yes, you need to both change the protocol and set the user. I have no idea what the API for that is.

**Comment by Evizero** [comment]
Glancing at the code I don't think its implemented yet.

The right place to include this might be around here maybe (?):
https://github.com/JuliaLang/Pkg.jl/blob/master/src/GitTools.jl#L71-L80

I may give it a shot some time this week if no one beats me to it
