### ISSUE TITLE
Progress bar on registry download is misleading

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/Pkg.jl#654]
What happened:
Progress bar showed 100% while in the directory I could follow the Letter-folders being added one after another taking the same amount of time as downloading again (probably due to a lot of small files)

Guess:
The progress bar shows not the entire progress of getting the registry but instead it shows the progress of the download.

Suggestion:
Make the progress bar show the actual progress (100% at the end of the progress of moving) maybe even with a hint whether it's copying or downloading at the moment.

**Comment by KristofferC** [comment]
The progress bar shows the git download progress. Showing the exact progress of files being moved and integrating that into the git progress bar would be very hard and unlikely wort the effort.

**Comment by rapus95** [comment]
What about some message -> 1/2 Downloading, 2/2 Copying where copying wouldn't have it's own bar?

**Comment by fredrikekre** [comment]
Copying should be nearly instant though so seems kinda pointless?

**Comment by rapus95** [comment]
@fredrikekre for me it took around the same time again :/

**Comment by StefanKarpinski** [comment]
Are you on some kind of really slow network file system?

**Comment by StefanKarpinski** [comment]
I guess the actionable item here would be to try to download to a temporary directory that's on the same drive as the ultimate destination. Then the moving files should be instantaneous.
