### ISSUE TITLE
Should `julia --project` automatically `activate .`?

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/Pkg.jl#655]
Currently,

```bash
$ mkdir foo
$ cd foo
$ julia --quiet --project
(v0.7) pkg> status
    Status `~/.julia/environments/v0.7/Project.toml`
<...>
```

If you're juggling environments a lot, it's easy to forget to `activate .` (which is only necessary if there are no `.toml` files present yet), so that `add MyPackage` will add `MyPackage` to the root environment.

**Comment by Evizero** [comment]
FWIW I got caught off guard by this a couple times as well

**Comment by StefanKarpinski** [comment]
I'll take a look at this.

**Comment by fredrikekre** [comment]
I don't think we want this. `--project` has a clear meaning already -- it searches for a `Project.toml` file. You can use `--project=.`, which should work regardless if the file exist or not.
