### ISSUE TITLE
Each REPL command should store a short form help.

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#663]
We would use these to build up the full help for `?`. That would make it obvious what commands we have failed to document, or in fact, would make it impossible to fail to short form document a command if we require that it exists.

**Comment by 00vareladavid** [comment]
I was thinking along the same lines @KristofferC . Breaking up the [help doc](https://github.com/JuliaLang/Pkg.jl/blob/ec413a28fca07c64c466523b737ba979ccc87269/src/REPLMode.jl#L1306) and shoving the pieces in a  `description` field in `CommandSpec`.

Or did you mean something else?

**Comment by pfitzseb** [comment]
Only slightly related, but I would *love* to have a nice autocompletion frontend like this:
![image](https://user-images.githubusercontent.com/6735977/44206246-7ca2b780-a159-11e8-9eea-f057785e4d7b.png)

Interactive autocompletions should go into Base though (and I hope I'll actually find the time to work on that).

**Comment by 00vareladavid** [comment]
Fixed?

**Comment by KristofferC** [comment]
Indeed
