### ISSUE TITLE
Pkg.build is too silent for travis CI

### ISSUE THREAD

**Issue by thofma** [JuliaLang/Pkg.jl#665]
I noticed that travis was killing our build since Pkg.build is now silent and took more than 10 minutes.

I agree that dumping everying on stdout is not pretty and I really like the build.log. On the other hand, not printing anything for minutes is also bad user experience and leads to the travis problems. Not sure what the best solution is.

**Comment by fredrikekre** [comment]
Maybe we can have `pkg> build --verbose Foo` / `Pkg.build("Foo", verbose=true)`?

**Comment by thofma** [comment]
I had the same idea, but I don't know how to redirect both to stdout and base.log using `pipeline`.

**Comment by andreasnoack** [comment]
I could most likely need something similar for Elemental.jl.

**Comment by thofma** [comment]
In case you need something now, you can have a look at https://github.com/Nemocas/Nemo.jl/raw/master/.travis.yml
I could not make travis_wait work.

**Comment by rdeits** [comment]
Here's a slightly fancier workaround: https://discourse.julialang.org/t/suggestion-forcing-travis-ci-to-render-verbose-build-output/14716

**Comment by fingolfin** [comment]
It would be really nice to have a `verbose` option.
