### ISSUE TITLE
Workers should inherit environment

### ISSUE THREAD

**Issue by rened** [JuliaLang/Pkg.jl#675]
If I have a project where I installed `MyPackage` and I can say

```julia --project -e "using MyPackage"```

the following does only work when I manually activate the environment:

```jl
using Distributed
using MyPackage   # works
addprocs(3)
@everywhere
  using Pkg; Pkg.activate(".")  # required
  using MyPackage
  ...
end
```

I would suggest that workers inherit the environment that is active when they are added with `addprocs`. Should there be any calls to `Pkg.activate` after `addprocs` they have to be manually performed by the user on all workers.

**Comment by KristofferC** [comment]
Pkg doesn't control how `addprocs` work so not sure the fix can happen here.

**Comment by rened** [comment]
Wasn't sure what the right place is - shall I post this as a Julia issue instead?

**Comment by KristofferC** [comment]
Yes, this seems like a base Julia issue.

I think the long-term plan is to have all code be loaded from the master process so we don't have to send over all this state.
