### ISSUE TITLE
New registered package not in JuliaRegistries

### ISSUE THREAD

**Issue by timholy** [JuliaLang/Pkg.jl#679]
I'm sure I'm being a noob here, but I only just now noticed that Rebugger isn't in https://github.com/JuliaRegistries/General. I had the impression that registering it with attobot & in METADATA would do the same here. EDIT: we already have two versions in METADATA, e.g., https://github.com/JuliaLang/METADATA.jl/pull/17152.

What do I need to do to fix this?

**Comment by KristofferC** [comment]
Yes, this should happen automatically. I will take a look why it doesn't.

**Comment by timholy** [comment]
I think I may have royally screwed up my Project.toml files. Hopefully fixed now?

Relevant:
- https://github.com/JuliaLang/METADATA.jl/pull/17169
- https://github.com/JuliaLang/METADATA.jl/pull/17172

**Comment by timholy** [comment]
Thanks! Should I also change the uuids in the package Project.toml files (which were assigned by my machine) to match that of JuliaRegistries/General?

**Comment by KristofferC** [comment]
Yeah, do that.

**Comment by timholy** [comment]
Quite the contrary: first-class service, I'm really grateful for your help.

**Comment by timholy** [comment]
Is it best to tag another release with the new UUIDs?

And when tagging a new release, for now I should manually edit the version string in the Project.toml file to match the upcoming release version, right?

**Comment by fredrikekre** [comment]
> Is it best to tag another release with the new UUIDs?

Shouldn't be needed, the uuid here will only be used when the package is `dev`ed (I think) so should be fine if it matches on master.

> And when tagging a new release, for now I should manually edit the version string in the Project.toml file to match the upcoming release version, right?

Yea, I think the idea is to bump version in Project.toml, merge that, and then tag new release from that commit.

**Comment by KristofferC** [comment]
While METADATA.jl is used, *only* the REQUIRE files is used as input. The project file is completely ignored. It is only used when checking out the package. When we move to registering with the new registry, the project file will be used.
