### ISSUE TITLE
Pkg not detecting versions in branch dependency. 

### ISSUE THREAD

**Issue by jd-lara** [JuliaLang/Pkg.jl#681]
I have in the manifest of our package a dependency with a specific branch and version. However, when I add my package to a clean Julia installation this error happens:  

```Julia 
(v0.7) pkg> add PowerSystems#master
   Cloning git-repo `https://github.com/NREL/PowerSystems.jl.git`
  Updating git-repo `https://github.com/NREL/PowerSystems.jl.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package PowerModels [23a24fe6]:
 PowerModels [23a24fe6] log:
 ├─PowerModels [23a24fe6] has no known versions!
 └─restricted to versions * by PowerSystems [c512b964] — no versions left
   └─PowerSystems [c512b964] log:
     ├─possible versions are: 0.1.0 or uninstalled
     └─PowerSystems [c512b964] is fixed to version 0.1.0
```

Upon review of the files in the packages folder, everything looks ok as per the documentation

In the manifest file in PowerSystems the entry for PowerModels is the following: 
```Julia 
[[PowerModels]]
deps = ["Compat", "InfrastructureModels", "JSON", "JuMP", "MathOptInterface", "Memento", "Pkg"]
git-tree-sha1 = "94f9913c02857e7ee0577306be8e513feed3af4b"
repo-rev = "moi-julia-v0.7"
repo-url = "https://github.com/lanl-ansi/PowerModels.jl.git"
uuid = "23a24fe6-a169-11e8-146b-9d23c58f08d1"
version = "0.7.0"
```
This entry  was created automatically using the package manager `add` command. Moreover, in the branch `moi-julia-v0.7` the project.toml file has the following header

```Julia 
name = "PowerModels"
uuid = "23a24fe6-a169-11e8-146b-9d23c58f08d1"
version = "0.7.0"
```

However, if I add the PowerModels package first there is no error. 

```Julia 
(v0.7) pkg> add PowerModels#moi-julia-v0.7
   Cloning git-repo `https://github.com/lanl-ansi/PowerModels.jl.git`
  Updating git-repo `https://github.com/lanl-ansi/PowerModels.jl.git`
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
  [23a24fe6] + PowerModels v0.7.0 #moi-julia-v0.7 (https://github.com/lanl-ansi/PowerModels.jl.git)
  Updating `~/.julia/environments/v0.7/Manifest.toml`
  [2030c09a] + InfrastructureModels v0.0.9
  [f28f55f0] + Memento v0.9.0
  [4d1e1d77] + Nullables v0.0.7
  [23a24fe6] + PowerModels v0.7.0 #moi-julia-v0.7 (https://github.com/lanl-ansi/PowerModels.jl.git)
  [cea106d9] + Syslogs v0.2.0

(v0.7) pkg> add PowerSystems#master
  Updating git-repo `https://github.com/NREL/PowerSystems.jl.git`
 Resolving package versions...
 Installed ZipFile ─ v0.7.0
 Installed InfoZIP ─ v0.1.6
  Updating `~/.julia/environments/v0.7/Project.toml`
  [c512b964] + PowerSystems v0.1.0 #master (https://github.com/NREL/PowerSystems.jl.git)
  Updating `~/.julia/environments/v0.7/Manifest.toml`
  [336ed68f] + CSV v0.3.1
  [f4508453] + InfoZIP v0.1.6
  [7d512f48] + InternedStrings v0.7.0
  [c512b964] + PowerSystems v0.1.0 #master (https://github.com/NREL/PowerSystems.jl.git)
  [3cdcf5f2] + RecipesBase v0.5.0
  [9e3dc215] + TimeSeries v0.12.0
  [a5390f91] + ZipFile v0.7.0
  Building PowerSystems → `~/.julia/packages/PowerSystems/IoGrN/deps/build.log`
```

But at the end of the day, I can't get the master branch of PowerSystems to checkout the branch from PowerModels that I need.

**Comment by jd-lara** [comment]
So a branch from a registered package is considered as unregistered? Both `PowerSystems` and `PowerModels` are registered packages

**Comment by KristofferC** [comment]
Sorry, I misunderstood then. Will look into this in a bit.

**Comment by KristofferC** [comment]
However, just to be clear, the manifest inside `PowerSystems` is completely ignored unless it is set as the active project (whereby that manifest is activated).

**Comment by jd-lara** [comment]
This is confusing, if I have a package, `PowerSystems` in this case, with a set of dependencies reflected in the package's project and manifest files, aren't those dependencies added into the environment automatically?

**Comment by fredrikekre** [comment]
> with a set of dependencies reflected in the package's project and manifest files

The only dependencies that Pkg sees are the ones in Project.toml, when you add a package like you do here, the package Manifest.toml is ignored (i.e. where you have specified master branch of JuMP)

> then it correctly checks out the master branch of JuMP.

What do you mean? It installed `JuMP v0.18.2` and not the master branch?

**Comment by fredrikekre** [comment]
As to the original issue, it looks like a `uuid` mismatch between https://github.com/lanl-ansi/PowerModels.jl/blob/f920fcb82b64d9756a46e67558cffa584917297d/Project.toml#L2 and https://github.com/JuliaRegistries/General/blob/eaf1d71c19305e8970acdc5cc8899b8659fc9ed7/P/PowerModels/Package.toml#L2 . You should use the one from the registry.

**Comment by jd-lara** [comment]
@fredrikekre thanks about the uuid number. Is the uuid updated manually or through `Pkg`, I remember Stefan mentioning that one should never modify manually the TOML files.

**Comment by fredrikekre** [comment]
You can update it manually. Seems like everything is working as expected here then?

**Comment by 00vareladavid** [comment]
I'm curious: why was there a UUID mismatch in the first place?

**Comment by jd-lara** [comment]
@fredrikekre that resolves the error posted at the beginning, but is not clear then how to specify dependencies in the Project.TOML related to a particular branch of a package. Is it the same syntax as in the Manifest file?

**Comment by fredrikekre** [comment]
> I'm curious: why was there a UUID mismatch in the first place?

Presumably because the author just generated a random uuid.

> I'm curious: why was there a UUID mismatch in the first place?

You don't.
If you want to use the dependencies in the package `Manifest.toml`, you can `pkg> activate path/to/package` and then `pkg> instantiate`.
If you want to use this package in another environment (e.g. `v1.0`) then you need to explicitly `pkg> add JuMP#master`.

**Comment by 00vareladavid** [comment]
I think you misquoted the second time @fredrikekre
