### ISSUE TITLE
Feature request: Pkg.status for abnormal statuses only

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#686]
@jiahao commented on [Tue Dec 08 2015](https://github.com/JuliaLang/julia/issues/14320)

When debugging a package dependency problem on an installation with many packages, it can get cumbersome to wade through hundreds of package statuses to find only the packages that are dirty, checked out, pinned, or otherwise not at the most recent tagged release version.

It would be very helpful to be able to issue, say, `Pkg.status(normal=false)`, and return only the list of packages with abnormal statuses.

---

@tkelman commented on [Tue Dec 08 2015](https://github.com/JuliaLang/julia/issues/14320#issuecomment-162839760)

agreed this would be useful

---

@eschnett commented on [Tue Dec 08 2015](https://github.com/JuliaLang/julia/issues/14320#issuecomment-162962696)

If `Pkg.status()` returned an array instead of writing to stdout, then running `filter` on the result would be easy.

---

@tkelman commented on [Tue Dec 08 2015](https://github.com/JuliaLang/julia/issues/14320#issuecomment-162971208)

you can already output to an iobuffer, but maybe defining a special type for the output of status, where what we have now is the show definition, but it would be an easier data structure to do things with.

---

@jiahao commented on [Tue Dec 08 2015](https://github.com/JuliaLang/julia/issues/14320#issuecomment-162973436)

Right now I'm using `filter(x->x[2].build != (), collect(Pkg.installed()))` to get the list of packages with abnormal version numbers programmatically. Needless to say, it's rather ugly.

**Comment by KristofferC** [comment]
I think this isn't needed so much right now with multiple projects.

**Comment by 00vareladavid** [comment]
>  If Pkg.status() returned an array instead of writing to stdout, then running filter on the result would be easy.

Also, this is effectively `Pkg.dependencies()` now
