### ISSUE TITLE
Pkg.status() should indicate packages that are downgraded

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#688]
@davidanthoff commented on [Sat Jul 23 2016](https://github.com/JuliaLang/julia/issues/17571)

It would be really helpful if `Pkg.status()` would somehow visually indicate if a free (i.e. not pinned) package is downgraded currently. Not sure what the best UI is, e.g. only showing a symbol that indicates a downgrade, or maybe showing the latest available version number in addition to the installed one, or something else.

---

@tkelman commented on [Tue Sep 06 2016](https://github.com/JuliaLang/julia/issues/17571#issuecomment-245046768)

I assume you mean `Pkg.status()` here?

---

@davidanthoff commented on [Tue Sep 06 2016](https://github.com/JuliaLang/julia/issues/17571#issuecomment-245059015)

> I assume you mean `Pkg.status()` here?

Yes, thanks! I updated title and original issue text.

---

@tkelman commented on [Tue Sep 06 2016](https://github.com/JuliaLang/julia/issues/17571#issuecomment-245059520)

A note "held back, not at latest" after the version number would make sense here. Would have to check that you only consider "latest" versions that support the currently-running version of Julia though.

---

@mauro3 commented on [Wed Aug 23 2017](https://github.com/JuliaLang/julia/issues/17571#issuecomment-324262050)

Something like this maybe:
```
julia> Pkg.status()
...
 - SmoothingSplines              0.1.2              master
...               
 - SortingAlgorithms             0.1.1              held back by SomePackage; most recent v0.2.1                                                                                                
...
```

x-ref: https://discourse.julialang.org/t/diagnostics-for-pkg-update-non-latest-version/5496

**Comment by KristofferC** [comment]
Seems quite unlikely to happen and should be significantly less needed now with multiple projects.

**Comment by ssfrr** [comment]
IMO this would still be really useful. It seems like users (particularly new ones who aren't yet using small per-project environments) are running into these issues and there isn't a good path to debugging them. For example, [this recent discourse post](https://discourse.julialang.org/t/how-to-play-an-audio-in-julia/31881/3). It just feels unsatisfying to have to say "something is borked in your main environment, but we don't have a good way to tell what it is. Wipe that environment out and start a new one".

**Comment by 00vareladavid** [comment]
@ssfrr see #1330. With that change, `pkg> add FFTW@1.1.0` should resolve the correct version for `FFTW`

**Comment by KristofferC** [comment]
I have some code here (https://gist.github.com/KristofferC/7c8048e2ee9aaa465966caeb98c1446a) which does some analysis on packages upper bounding other packages to not the latest version. It might make sense to incorporate that code into Pkg and have a way to show it.
