### ISSUE TITLE
Improvements to the Pkg docs

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#689]
@mauro3 commented on [Thu May 24 2018](https://github.com/JuliaLang/julia/issues/27245)

Just reading through the new Pkg docs and I have a few suggestions:

- Title should be more descriptive, maybe as before "Packages" or "Packages (Pkg)".
- I think there should be a "Quick start" section right at the top.  Whilst the "Introduction" section is a nice long read, for someone wanting to just install a package, that is not very helpful.
- Then, whilst I understand the reason to have packages separate for each "project", for simple REPL work the old behavior of a global packages is better.  I suspect this is possible with the new Pkg, but it is not clear to me how.  I suggest to put this into the "Quick start".
- Maybe rename the "Getting started" to "Getting started with a project".

**Comment by WenjieZ** [comment]
> I think there should be a "Quick start" section right at the top. Whilst the "Introduction" section is a nice long read, for someone wanting to just install a package, that is not very helpful.

I actually finished reading the whole page :cry:

**Comment by pevnak** [comment]
I would also add a small not, how to add local non-registered package on which other non-registered package depends. Without help of discourse, I would not figured out that the preferred way is `dev --local /pat/to/package`.

Thanks a lot

**Comment by 00vareladavid** [comment]
I feel #1023 covers this
