### ISSUE TITLE
Pkg.update caches invalid credentials

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#692]
@omus commented on [Fri Aug 12 2016](https://github.com/JuliaLang/julia/issues/17990)

After purposefully entering my username and password incorrectly three times for private repo I got the expected "Package ... cannot be updated." message. What I did not expect is that running `Pkg.update()` again does not reprompt the user for credentials.

---

@StefanKarpinski commented on [Fri Aug 12 2016](https://github.com/JuliaLang/julia/issues/17990#issuecomment-239484790)

Does it just decide that you don't know them and stop asking you forever?

---

@Keno commented on [Fri Aug 12 2016](https://github.com/JuliaLang/julia/issues/17990#issuecomment-239492684)

What version was this on. I did a bit of cleanup of this code in the past two days.

---

@omus commented on [Fri Aug 12 2016](https://github.com/JuliaLang/julia/issues/17990#issuecomment-239566525)

OS X Julia v0.5.0-rc2.

---

@omus commented on [Fri Aug 12 2016](https://github.com/JuliaLang/julia/issues/17990#issuecomment-239567763)

I just tried Julia v0.5.0-rc2 on Linux and it appears to reprompt forever when given invalid credentials. Also, I forgot to mention this using HTTP.

---

@omus commented on [Mon Aug 15 2016](https://github.com/JuliaLang/julia/issues/17990#issuecomment-239938741)

As it turns out our private Git server will block access when entering invalid credentials repeatedly within a short duration of time. Once blocked, Julia will then cache the last invalid credentials and use them on subsequent `Pkg.update()` calls.

**Comment by omus** [comment]
I'm quite sure this has been addressed. I'll re-open if I encounter this again.
