### ISSUE TITLE
Pkg.installed

### ISSUE THREAD

**Issue by sherrinm** [JuliaLang/Pkg.jl#697]
This is more a question than an issue.

In Pkg(2) I found it useful when giving talks to be able to have (in the first cell of a notebook) something like:

>>>>>

# Packages used in this talk

for p in ("BenchmarkTools","UnicodePlots","PyPlot")
    Pkg.installed(p) == nothing && Pkg.add(p)
end

using "BenchmarkTools","UnicodePlots","PyPlot")

>>>>>>

I can not see how to do this using the Pkg3 API
Is this available and I've missed it, planned for the future etc.?

Malcolm

**Comment by fredrikekre** [comment]
Why do you need check if it is installed first? Won't
```
Pkg.add(["BenchmarkTools", "UnicodePlots", "PyPlot"])
```
do the job?

**Comment by 00vareladavid** [comment]
What is the use case for doing something manually that the package manager handles automatically for you?

Why is adding the following code to the top of a notebook insufficient for your use case?
```
using Pkg
packages_for_this_talk = ["BenchmarkTools","UnicodePlots","PyPlot"]
Pkg.add(packages_for_this_talk)

# BenchmarkTooks, UnicodePlots, PyPlots available here, regardless of previous configuration
```

**Comment by sherrinm** [comment]
I agree that calling *Pkg.add() *works, and has no effect if a package is
already installed - so it did in the previous version also, but that was
not my question; I feel that it is nice when giving a talk to show a level
of sophistication even if a little superficial.

In fact I did find a way using the new Pkg API to mimic the previous
version too.

The* Pkg.installed()* function returns a  Dictionary of installed packages,
as its keys, with the versions numbers as its values, so adding something
of the form . . .

*using Pkg*
*ipks = Pkg.installed();*

*pkgs =  [**"BenchmarkTools","UnicodePlots","PyPlot"];*
*for p in pkgs*
*    !haskey(ipks,p) && Pkg.add(p)*
*end*

. . . seems to do the job, currently at least.

Malcolm

**Comment by fredrikekre** [comment]
How is
```
using Pkg
ipks = Pkg.installed()
pkgs = ["BenchmarkTools","UnicodePlots","PyPlot"]
for p in pkgs
    !haskey(ipks,p) && Pkg.add(p)
end
```
nicer than
```
using Pkg
Pkg.add(["BenchmarkTools","UnicodePlots","PyPlot"])
```
?

**Comment by 00vareladavid** [comment]
In terms of imitating the previous `Pkg.installed()` with the new API, the solution you found is probably the closest there is.

**Comment by carpeliam** [comment]
`Pkg.installed` allows me to take conditional action depending on whether or not a package is installed; e.g., `Pkg.installed("SomePackage") != nothing && (using SomePackage)` won't break if `SomePackage` is not installed. Is there a way to achieve that in >0.6?

**Comment by fredrikekre** [comment]
https://github.com/MikeInnes/Requires.jl
