### ISSUE TITLE
Add . but not rm .

### ISSUE THREAD

**Issue by innerlee** [JuliaLang/Pkg.jl#701]
![image](https://user-images.githubusercontent.com/9464825/44701666-6d5d2b80-aac2-11e8-9219-386412b670ba.png)

Also, the `repo-url` record should not be `.`.

**Comment by fredrikekre** [comment]
I'm pretty sure this works as intended.

**Comment by innerlee** [comment]
While the behavior on the pkg mode is reasonable. Setting `repo-url` as `.` does not make much sense?

![image](https://user-images.githubusercontent.com/9464825/44705823-50c8ef80-aad2-11e8-91cb-1056fcc766e4.png)

**Comment by fredrikekre** [comment]
Yea, it should maybe be absolutified? Not sure.

**Comment by 00vareladavid** [comment]
This works fine now. Path is stored relative to the active project
