### ISSUE TITLE
Polluting /tmp

### ISSUE THREAD

**Issue by lbilli** [JuliaLang/Pkg.jl#704]
Starting from version 0.7/1.0, after adding/updating packages, several randomly named empty folders are left behind in `/tmp`, such as:
```
/tmp/TwOJH2Hzmugb
/tmp/ngcKCsSKTqbo
/tmp/5smw1tKbkzNt
...
```
It would be nice to have them automatically removed.

**Comment by KristofferC** [comment]
A log of leftovers: https://gist.githubusercontent.com/iblis17/5e496c9201cdcc77c29925382e144c73/raw/fd1dd35fc7e733169e131d941f682256e7b7f19f/tree.dump
