### ISSUE TITLE
JuliaProject.toml still valid?

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/Pkg.jl#705]
The [manual](https://julialang.github.io/Pkg.jl/latest/#Glossary-1) mentions it as an alternative for `Project.toml`, but my impression from reading the code is that the latter is hardcoded pretty much everywhere, and the [tests for it](https://github.com/JuliaLang/Pkg.jl/blob/d123b48e63b5a5e09cb224c6385a3f512627e4ac/test/pkg.jl#L385) are commented out.

**Comment by tpapp** [comment]
Thanks, I will just assume it is valid then and look for it as a fallback. Perhaps bringing back the tests at some point would be nice.

**Comment by 00vareladavid** [comment]
I think #706 should do it
