### ISSUE TITLE
prompt after activate depends on current directory

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/Pkg.jl#713]
I `generate`d a project named `MyProject` in `/tmp`, renamed its directory to `julia`, then ran this in a new session. Note that I only get the correct prompt if the current directory is the right one, `activate path` gets me the directory name in the prompt.
```julia
shell> pwd
/home/tamas

(v1.0) pkg> activate /tmp/julia

(julia) pkg> 

shell> cat /tmp/julia/Project.toml
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
name = "MyProject"
uuid = "292fae4c-b035-11e8-0b1f-dd334f8ab564"
version = "0.1.0"

[deps]

shell> cd /tmp/julia
/tmp/julia

(julia) pkg> activate .

(julia) pkg> activate 

(v1.0) pkg> activate .

(MyProject) pkg> 

julia> VERSION
v"1.0.1-pre.0"
```

**Comment by 00vareladavid** [comment]
I could reproduce on 1.0.0 but not on master. That's a bit weird since there was no explicit to commit to fix this. I think the best thing to do here is just to add a test in case it comes back.

(Note for future reference: it does not seem to matter what the directory name is)

**Comment by KristofferC** [comment]
Please reopen if this still happens.
