### ISSUE TITLE
pkg> status MyPackage to return status of MyPackage only

### ISSUE THREAD

**Issue by cossio** [JuliaLang/Pkg.jl#717]
In Pkg2 we could do `Pkg.status("MyPackage")` to print info (name and version) of `MyPackage` only, instead of printing the full list of installed packages. Currently `status` prints all the packages in the current environment, which could be a long list in some cases. 

Could `status MyPackage` just print status info for `MyPackage`?

**Comment by fredrikekre** [comment]
#575
