### ISSUE TITLE
StatPlots precompiles but precompilation is disabled

### ISSUE THREAD

**Issue by piever** [JuliaLang/Pkg.jl#722]
StatPlots precompiles every time it is loaded:

```julia
julia> using StatPlots
[ Info: Precompiling StatPlots [60ddc479-9b66-56df-82fc-76a74619b69c]
[ Info: Recompiling stale cache file /home/pietro/.julia/compiled/v1.0/Plots/ld3vC.ji for Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
```

But precompilation of the module is explicitly disabled, see [here](https://github.com/JuliaPlots/StatPlots.jl/blob/master/src/StatPlots.jl#L1).

**Comment by musm** [comment]
I also am seeing this

**Comment by NHDaly** [comment]
It appears that #734 was actually fixing a similar but unrelated bug: the `precompile` command suffered the same problem and also incorrectly precompiled packages that have opted out of precompilation. #734 fixes that bug, but it seems that isn't the same mechanism responsible for precompiling a package during a `using` call.

I've opened an issue on JuliaLang/julia instead:
https://github.com/JuliaLang/julia/issues/29467
