### ISSUE TITLE
Conversion script doesn't pick up Printf dependency for ExcelFiles.jl

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/Pkg.jl#728]
[ExcelFiles.jl](https://github.com/queryverse/ExcelFiles.jl) uses [printf](https://github.com/queryverse/ExcelFiles.jl/blob/f0ba1605dbe2b27bcf0c42716d26566b570d73aa/src/ExcelFiles.jl#L5), but the conversion script doesn't pick that up, see [here](https://github.com/JuliaRegistries/General/blob/7cc2e758ccb26aeaf34d2efb78c6ffd3bda96c91/E/ExcelFiles/Deps.toml). This leads to a precompile warning:
````
(v1.0) pkg> precompile
Precompiling project...
Precompiling ExcelFiles
[ Info: Recompiling stale cache file C:\Users\david\.julia\compiled\v1.0\ExcelFiles\cZRj4.ji for ExcelFiles [89b67f3b-d1aa-5f6f-9ca4-282e8d98620d]
┌ Warning: Package ExcelFiles does not have Printf in its dependencies:
│ - If you have ExcelFiles checked out for development and have
│   added Printf as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with ExcelFiles
└ Loading Printf into ExcelFiles from project dependency, future warnings for ExcelFiles are suppressed.
````
And that then affects the whole [Queryverse.jl](https://github.com/queryverse/Queryverse.jl) stack.

So, two things: a) could this be fixed in the conversion script? and b) is there some workaround in the meantime?

Thanks to @KristofferC for identifying the root issue here on Slack already.

**Comment by fredrikekre** [comment]
Its the line break that is the problem. If you remove that it's fine. So, change 
```
using ExcelReaders, IteratorInterfaceExtensions, TableTraits, DataValues,
TableTraitsUtils, FileIO, TableShowUtils, Dates, Printf
```
to
```
using ExcelReaders, IteratorInterfaceExtensions, TableTraits, DataValues
using TableTraitsUtils, FileIO, TableShowUtils, Dates, Printf
```
for example.

**Comment by davidanthoff** [comment]
Perfect, that is an easy fix :) Thanks!

**Comment by StefanKarpinski** [comment]
It's amazing that this stupid regex has worked as well as it has. I guess we could make it a bit more complex and handle this case too. Not sure if it's worth it though.
