### ISSUE TITLE
Pkg.Types.semver_spec intersects version specs wrong

### ISSUE THREAD

**Issue by Seelengrab** [JuliaLang/Pkg.jl#751]
```
julia> Pkg.Types.semver_spec(">=0.7, ^0")
VersionSpec("0.0.0-*")
```

Shouldn't this give `VersionSpec("0.7.0-0.*")`? 

EDIT: the rest was a seperate issue covered [here](https://github.com/JuliaLang/Pkg.jl/issues/750).

Ref. [this](https://discourse.julialang.org/t/specify-version-range-with-specific-versions-in-compat-on-0-7-1-0/15018) discussion on discourse and [this](https://github.com/JuliaLang/METADATA.jl/pull/18063) Issue in METADATA.jl.

**Comment by fredrikekre** [comment]
Looks correct to me since
```julia> Pkg.Types.semver_spec(">=0.7, ^0")
VersionSpec("0.0.0-*")
```
is the union of
```
julia> Pkg.Types.semver_spec(">=0.7")
VersionSpec("0.7.0-*")
```
and
```
julia> Pkg.Types.semver_spec("^0")
VersionSpec("0.0.0-0")
```
?

**Comment by StefanKarpinski** [comment]
I'm still not seeing where you're getting the expectation of intersection from:
```jl
julia> Pkg.Types.semver_spec(">=0.7")
VersionSpec("0.7.0-*")

julia> Pkg.Types.semver_spec("^1")
VersionSpec("1.0.0-1")

julia> Pkg.Types.semver_spec(">=0.7, ^1")
VersionSpec("0.7.0-*")
```
The `>=0.7` spec fully contains `^1`: if this was an intersection then the last version would be equal to `^1` if it was a union (it is) then it would be equal to `>=0.7` (it is).

**Comment by Seelengrab** [comment]
Yes, I understand that it's a union - all I'm saying is that I don't see a way to express `VersionSpec("0.7.0-1")` with the current version parsing. That the behaviour is a union instead of an intersection of version specs is what's surprising to me, not why a union gives that result.

**Comment by fredrikekre** [comment]
Since there will not be a v0.8 release of Julia you can use
```
julia> Pkg.Types.semver_spec("0.7, ^1")
VersionSpec("[0.7.0-0.7, 1.0.0-1]")
```

> Further, the doc actually says it's an intersection, not a union:

This was corrected in #773

**Comment by Seelengrab** [comment]
Well, of course I can use that for this one special case.. What I'm saying though is that, in general, it's not possible to currently provide a version spec specifying support from version x.y.z up to but not including (x+1).0.0 because of that union.

**Comment by StefanKarpinski** [comment]
Wouldn't `Pkg.Types.VersionSpec("0.7.0-1")` be the way to write it? Unless you mean something else.

This behavior of the comma does seem to be at odds with what Cargo does:

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-requirements

This is completely unspecified except for the vague sentence:

> Multiple version requirements can also be separated with a comma, e.g. `>= 1.2, < 1.5`.

Which, of course, doesn't tell you anything really—is it a union or an intersection? However, the example suggests that in Cargo it's an intersection since otherwise the example allows any version.

npm uses `||` to express a union of ranges and space separation to indicate an intersection. In any case, I think we should certainly not have a different meaning than both, so point taken.

**Comment by Seelengrab** [comment]
> Wouldn't Pkg.Types.VersionSpec("0.7.0-1") be the way to write it? Unless you mean something else.

No, that's precisely what I mean - but how can I specify that in e.g. Project.toml? I have to use the comma seperated list there, and the union prevents me from solving this easily without having to write all possibly existing future minor versions before the next major version.

**Comment by StefanKarpinski** [comment]
Why can't you can write `0.7.0-1` in `Project.toml`?

**Comment by fredrikekre** [comment]
> and the union prevents me from solving this easily without having to write all possibly existing future minor versions before the next major version.

```
julia> Pkg.Types.semver_spec("1.2.3")
VersionSpec("1.2.3-1")
```

**Comment by Seelengrab** [comment]
@StefanKarpinski Because that's an invalid version specifier.

A modified Project.toml for a newly generated Package with that specifier:
```
authors = <snip>
name = "testPkg"
uuid = "f191ba14-d2dc-11e8-1583-790a11c3e9da"
version = "0.1.0"

[compat]
julia = "0.7.0-1"

[deps]
```

which gives the following Error when trying do `dev`:

```
(v1.0) pkg> dev .
 Resolving package versions...
ERROR: invalid version specifier: 0.7.0-1
Stacktrace:
 [1] error(::String) at ./error.jl:33
<snip>
```

@fredrikekre yes, that would work for only having one major version jump - but this quickly becomes longer with multiple jumps, or in the case of `0.7.0-1` not expressable at all.

**Comment by StefanKarpinski** [comment]
There's two issues here:

1. Whether the syntax matches that of other systems like Cargo and npm.
2. Whether you need the intersection to express anything.

I'm much more concerned about 1 than 2—largely because if syntax matches Cargo and is expressive enough for Cargo, then I think it's unlikely that it's insufficiently expressive for us.

Regarding 2, however, @Seelengrab can you please describe the set of versions you want to express as an open/closed interval with fully specified point version endpoints?

**Comment by Seelengrab** [comment]
I want to specify in the particular case of IOLogging.jl the compatible version range as `[0.7.0-2)`.

How Cargo and npm handle this, I do not know. I suspect both intersection and union are needed for the general case though.

**Comment by StefanKarpinski** [comment]
> Because that's an invalid version specifier.

Ah, well. It shouldn't be. It should be a valid version specifier for the version range `[0.7.0-2.0.0)`.

**Comment by StefanKarpinski** [comment]
> I want to specify in the particular case of IOLogging.jl the compatible version range as `[0.7.0-2)`.

I asked for fully specified patch version endpoints. This is ambiguous. Do you mean `[0.7.0-2.0.0)` or something else?

**Comment by Seelengrab** [comment]
I edited my response - but I'm not sure which one is right. I basically want to support any version greater than or equal to `0.7.0`, but not support any version greater than or equal to `2.0.0`. I guess that's equivalent to `[0.7.0-2.0.0)`.

**Comment by StefanKarpinski** [comment]
Ok, I understand what you're saying now. Thanks for clarifying.

**Comment by fredrikekre** [comment]
So, as the current implementation you basically need one specifier per "breaking version" which is a minor bump pre v1 and a major bump post v1.  I think that makes sense. So for the current state of Julia releases, if you want to support Julia v0.7.X and 1.X you need (and should) use something like `"0.7, 1"`. Technically, Julia v0.8 could be breaking, and you should not claim to support that without testing it. If Julia 0.8 is release, you can test the package and add `0.8` to the list, and have something like `"0.7, 0.8, 1"`.

**Comment by StefanKarpinski** [comment]
Does no one care that our syntax is completely different from Cargo? @KristofferC, I assume that was not the intention and that this was a mistake due to the poor specification of the Cargo docs?

**Comment by StefanKarpinski** [comment]
I'm reopening this because I think it was unintentional and wrong to diverge from Cargo's behavior.

**Comment by KristofferC** [comment]
As Fredrik says, the way it is right now, you just list what potentially breaking versions you are compatible with. With no more 0 major versions being released for Julia this will in practice you would have to list `1, 2, 3` instead of `>= 1, < 4`.

**Comment by StefanKarpinski** [comment]
So it seems the divergence from Cargo _is_ intended. I have to say, it makes sense to me to just list the major and/or minor versions that you're known to be compatible with. It would be nice to support hyphen range syntax in these too so that `0.7-1` would just work.

**Comment by KristofferC** [comment]
Adding things to https://github.com/JuliaLang/Pkg.jl/blob/dfb341ae03e34ae81a5f8c2e324b7b14019bdbbe/src/versions.jl#L340-L345 should be fairly simple.

**Comment by StefanKarpinski** [comment]
Ok, I'll close this and make that a feature request issue instead.
