### ISSUE TITLE
ERROR: SystemError: realpath: No such file or directory

### ISSUE THREAD

**Issue by dpo** [JuliaLang/Pkg.jl#754]
I downloaded a fresh copy of the 0.7 binaries for Linux 64bit. The very first command I issued is `] dev .` and it resulted in:

<img width="711" alt="screen shot 2018-09-17 at 11 02 33" src="https://user-images.githubusercontent.com/38760/45631617-495d8c00-ba69-11e8-8093-8987f240498d.png">

`realpath` is indeed available under `/usr/bin`. Installing a package beforehand resolves the issue but I thought you'd want to be aware of this "corner case". I haven't checked whether this also happens with 1.0.

**Comment by KristofferC** [comment]
We now have a "safe" version of this so should be fixed on master and be in 1.0.1

https://github.com/JuliaLang/Pkg.jl/blob/e5d09f4f07739589c88af427164490a10ae53c6a/src/Types.jl#L496-L500
