### ISSUE TITLE
Update local clone before looking for git-object

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/Pkg.jl#755]
I was trying to instantiate a Manifest that was using checked-out dependencies, but my clone  wasn't updated in a while so it couldn't find the hash in the local cache. I had to do a manual fetch first.

(I didn't kept the logs sadly)

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/Pkg.jl/pull/649?

**Comment by vchuravy** [comment]
Probably!
