### ISSUE TITLE
Documentation of default `LOAD_PATH` entries

### ISSUE THREAD

**Issue by crstnbr** [JuliaLang/Pkg.jl#757]
See https://stackoverflow.com/questions/52378974/in-my-julia-1-0-0-repl-load-path-returns-unexpected-results.

As per default, the load path seems to be

```
julia> LOAD_PATH
3-element Array{String,1}:
 "@"
 "@v#.#"
 "@stdlib"
```

Except for comments in the source code itself I couldn't find any documentation of what those things actually mean. People don't really need to know I guess but, still, it should be easy to add this information to the Pkg documentation.

**Comment by crstnbr** [comment]
> Are you sure the issue belongs to Pkg.il?

I'm not.

> The named enviroments like `@.` get resolved by `Base.load_path_expand()`. I agree any piece of documentation would have helped, but perhaps we just need a good docstring for that function in Base to start with.

Actually, I think it makes sense to directly add a docstring to `LOAD_PATH`, wherever it is defined.

**Comment by KristofferC** [comment]
Documented well on Julia 1.2+
