### ISSUE TITLE
Recent change causing excessive cloning?

### ISSUE THREAD

**Issue by ma-laforge** [JuliaLang/Pkg.jl#762]
I have noticed something very strange on the Github traffic page of my package (InspectDR):

Since around September 10th, the cloning traffic has gone up significantly.

It used to be that I would have something like the following amount of clones per day:
 - 20 clones for 5 unique cloners.

However, now, I get something ***much larger***:
  - Yesterday: 154 clones for 1 unique cloner.
  - One day last week, it even peeked to 248 clones for 2 unique cloners.

I have gotten similar traffic increases for all my registered Julia packages.  I suppose a few individuals might be causing this, but ***I wonder if there might have been changes to the Pkg module that would have accidentally caused this***.

**Comment by KristofferC** [comment]
I don't really see any difference for my packages, perhaps it is CI?

**Comment by fredrikekre** [comment]
PkgEval?

**Comment by ma-laforge** [comment]
FYI: (since this is very atypical).
![image](https://user-images.githubusercontent.com/11205411/45776489-05ad8280-bc21-11e8-8383-b8e5a89641f1.png)

**Comment by ma-laforge** [comment]
>@KristofferC  [...] perhaps it is CI?

Perhaps, but that would be surprise me a bit.  You have recently updated PGFPlotsX.jl, JuAFEM.jl, StaticArrays.jl, OhMyREPL, & Tensors.jl and you say you don't see any difference in your traffic...

What I do see is that none of those packages have had a new release (no new tags).  I have noticed that you released v0.4.2 for NearestNeighbors.jl about 9 days ago... which is very close to when I started seeing issues.

I would be curious to see if there was there a spike in traffic on NearestNeighbors.jl specifically...

**Comment by ma-laforge** [comment]
> @fredrikekre: PkgEval?

Sorry. I don't know what that means.  I don't see any reference to PkgEval in the Julia docs either.

**Comment by KristofferC** [comment]
<img width="1072" alt="screen shot 2018-09-19 at 15 39 04" src="https://user-images.githubusercontent.com/1282691/45777107-ddbf1e80-bc22-11e8-89bb-396ace9f4c27.png">

**Comment by ma-laforge** [comment]
Thanks @KristofferC.

... That does not necessarily look abnormal, though.. because you have a factor 4 difference between # of clones and # of unique cloners.

But then again... it is more like a factor 10 on 09/13.

...And the general pattern is somewhat similar to my own projects:
Ramp-up in clones around Sept. 9, peaking on the 13th, dropping on the 15th, then followed by a smaller hump peaking on the 18th...

**Comment by ma-laforge** [comment]
FYI: These are brand new packages I released.  I really don't expect the user base to be this big at all (not even the number of unique cloners)

![image](https://user-images.githubusercontent.com/11205411/45777460-d6e4db80-bc23-11e8-8896-dddbb531275a.png)
![image](https://user-images.githubusercontent.com/11205411/45777558-1dd2d100-bc24-11e8-9022-611074cb26ce.png)

**Comment by KristofferC** [comment]
Someone ran something that cloned all packages or something perhaps? Something with juliabox? Don't think there is much need to stress over this, heh.

**Comment by ma-laforge** [comment]
...I really find it odd that ***all 3 packages*** got 248 clones from 2 unique cloners on Sept 13th.

...And that MDDatasets.jl & PSFWrite.jl got 202 clones from 2 unique cloners. (InspectDR got 208 clones from 5 unique clones - which is still pretty close)

**Comment by ma-laforge** [comment]
>@KristofferC: [...] Don't think there is much need to stress over this, heh.

You might be right.  It could just be some program that is doing some mining, or something.

Just wanted to raise the issue in case it was caused by the package manager itself.

**Comment by KristofferC** [comment]
Ok, well the package manager didn't change at least-
