### ISSUE TITLE
Don't allow generating packages with names that are not legal Julia identifiers

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/Pkg.jl#767]
I am teaching a computational physics course using Julia, and taught people how to use `generate` to create new packages. Sure enough, some people created packages with names such as `2018Example`. Of course this doesn't work, because this is not a valid Julia module name, and `using 2018Example` later on fails.

To be beginner friendly, I suggest to disallow package names that are not valid module names.

**Comment by Nosferican** [comment]
Tag as Good-First-Issue?

**Comment by fredrikekre** [comment]
#1083
