### ISSUE TITLE
`Pkg.generate` should create `test/runtests.jl` as well

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/Pkg.jl#768]
Since `Pkg` provides a `test` command that looks for `test/runtests.jl`, it would be quite convenient if `generate` created this file with some dummy content.

**Comment by eschnett** [comment]
Yes! Thanks for this.

...`Committing`? Does this mean that it even creates and initializes a git repository?

**Comment by KristofferC** [comment]
Yes
