### ISSUE TITLE
Add automatically compat entry when adding a package

### ISSUE THREAD

**Issue by saschatimme** [JuliaLang/Pkg.jl#776]
Assume I install StaticArrays in my current project
```julia
(v0.7) pkg> add StaticArrays
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
  [90137ffa] + StaticArrays v0.8.3
  Updating `~/.julia/environments/v0.7/Manifest.toml`
 [no changes]
```
I think that then automatically an entry to `[compat]` should be added limiting to the current (semver) major version, i.e.,
```toml
[compat]
StaticArrays = "0.8.3"
```

With this, you (as a user or package author) have to explicitly upgrade your dependencies to a new major version and do not run into the problem of an incidentally broken package or script.

**Comment by StefanKarpinski** [comment]
Yes, this is the plan for future versions.

**Comment by travigd** [comment]
Is there any reason this hasn't gained more traction/are there plans to implement this in the near future? :^)

**Comment by ufechner7** [comment]
Same question here... Any update on this issue?
