### ISSUE TITLE
`pkg> dev --activate Foo` to clone and activate in one step

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/Pkg.jl#782]
In the near and glorious future when most packages have their own `Project.toml` my understanding is that hacking on a project is intended to be done from within that package's included environment. One workflow would be:

```
# 1. go to Foo's Github
# 2. copy the repo url
shell> cd ~/.julia/dev
shell> git clone <paste>
(v1.0) pkg> activate Foo
```

Alternatively I could do
```
(v1.0) pkg> dev Foo
(v1.0) pkg> rm Foo
(v1.0) pkg> activate ~/.julia/dev/Foo
```

I think both sequences should be equivalent (not sure if you need a manual `resolve` for the first case), and end up with a self-contained dev environment ready to use, without polluting my main `1.0` environment.

Does this seem like a common-enough workflow to merit a flag to `dev`? It could be something like `dev --activate Foo` and rather than adding it to your current environment would just clone it and activate it (still respecting `--shared` or `--local` to determine where it ends up).

**Comment by StefanKarpinski** [comment]
This seems like a slippery slope.

**Comment by ssfrr** [comment]
I'm operating under the following assumptions:
1. working within a package's environment is the main intended workflow for hacking on a package (once most packages are shipping with their own `Project.toml`)
2. when hacking on a package, you want that hacking to be isolated from your main Julia environment you use for day-to-day work
3. the two workflows I listed seem kinda clunky.

Perhaps we differ on one of those points.

**Comment by StefanKarpinski** [comment]
Writing `dev X; activate X` doesn't seem that hard?

**Comment by 00vareladavid** [comment]
`activate -d Foo` (as an alias for `activate ~/.julia/dev/Foo`) seems more useful to me; given that `activate` is a more common operation than `dev`. I can see how writing out the full path every time you switch environments can get annoying.

**Comment by StefanKarpinski** [comment]
Perhaps related to @KristofferC's idea mentioned by @vchuravy in https://github.com/JuliaLang/IJulia.jl/issues/673#issuecomment-425306944 of activating a URL instead of a path? It seems like the annoying part in the original is the cloning step.

**Comment by ssfrr** [comment]
> Writing dev X; activate X doesn't seem that hard?

Ah, I didn't realize that you could use a Package name as the `path` argument to `activate`. That makes things simpler, though it still pollutes your current environment.

To @00vareladavid's point, I guess my idea of a flag on `dev` has the issue that it doesn't provide a convenient way to activate the package in the future. A flag on `activate` might make more sense. Then my "hack on a package" workflow would be

```
(v1.0) pkg> dev Foo
(v1.0) pkg> rm Foo
(v1.0) pkg> activate --dev Foo
```

and in the future I could just do `activate -d Foo` whenever I want to work on it.

That said, this is somewhat theoretical right now as most packages I hack on don't have their own `Project.toml`s yet, so I've been using per-package environments:

```
(v1.0) pkg> activate --shared FooDev
(FooDev) pkg> dev --local Foo
```

and maybe that will continue to be the right workflow anyways. I'd just thought that the intent was that people would use packages' environments for developing them.

**Comment by KristofferC** [comment]
I think the current way is ok.
