### ISSUE TITLE
BLue colour on black bacground - almost invisible

### ISSUE THREAD

**Issue by hearnsj** [JuliaLang/Pkg.jl#788]
When in the REPL I go to package mode. The prompt  (v1.0) pkg> is in a blue colour against a black background. I find this almost impossible to see. The other colours in the REPL are fine for me
(v1.0) pkg> add ImageMagick

I should say I am red-green colour blind.
Can I alter this colour and report back what a better one would be - at least for me?

**Comment by 00vareladavid** [comment]
Kristoffer recommended on JuliaLang/julia#28690 to use `--color=no` when output is difficult to read. But it seems that Pkg doesn't respect that flag. Perhaps it should?

**Comment by hearnsj** [comment]
Sorry to report - with Windows 10 and  Julia 1.0.1
--color=no  has no effect

**Comment by dalejordan** [comment]
Why not make the color customizable like it is for the other modes?

**Comment by StefanKarpinski** [comment]
Sure, if someone wants to make a PR to make color customizable, that would be great!

**Comment by 00vareladavid** [comment]
While customization is nice to have, IMO the root problem here are broken color schemes.

As a heavy user of CLI applications, it is easier to pick a sane color scheme than having to tweak each CLI. I am fond of both solarized and gruvbox.

**Comment by hearnsj** [comment]
A quick comment on this issue. With Julia 1.0.2 on the same laptop:
Windows 10 - the pkg> prompt is in a hard to see deep blue
Fedora Linux in Gnome Terminal - the pkg> prompt is in a nicely visible light blue

**Comment by hearnsj** [comment]
Of course, this is reflecting that the colors are actually set in the terminal color map.
I can loop and print out a phrase in all colors from 0 to 255
However colors are defined by name eg. :light_blue
How can I find which number in the color range :light_blue corresponds to?
The answer is probably obvious

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/791 should allow people to not use colors if they use terminals where for some reason blue is not visible. Pretty sure newer Windows have fixed their default colors.
