### ISSUE TITLE
access git revision of a package

### ISSUE THREAD

**Issue by jangorecki** [JuliaLang/Pkg.jl#793]
I would like to access precise information about package version in a form of git sha revision.
It is useful when subject of a processing workflow is a package itself and I need to log exact revision of a package together with its results and timings. I also sometimes use it for debugging to confirm I am on proper revision before verifying bug fix.
In python there is no unified way:
```py
pandas.__git_version__
dask.__git_revision__
datatable.__git_revision__
```
in R there is `Revision` field [reserved](https://github.com/wch/r-source/blob/f733c5886860c2573933a041471f6c28cc969b07/src/library/tools/R/utils.R#L1261) in DESCRIPTION file which can be used for that purpose.

**Comment by bkamins** [comment]
@jangorecki Is this what you wanted?
```
using Pkg

function getpkgmeta(name::AbstractString)
    fname = joinpath(dirname(Base.active_project()), "Manifest.toml")
    Pkg.TOML.parse(read(fname, String))[name][1]
end
```
and now e.g.
```
julia> getpkgmeta("DataFrmes")
Dict{String,Any} with 4 entries:
  "deps"          => ["CategoricalArrays", "CodecZlib", "Compat", "DataStreams", "Dates", "InteractiveUtils", "IteratorInterfaceExtensions", "LinearAlgebra", "Missings", "Printf"  …  "Reexport", "So…

  "git-tree-sha1" => "60c2820c9ae93cc33e98cd820e0b449d551c7874"
  "uuid"          => "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
  "version"       => "0.15.1"
```

**Comment by jangorecki** [comment]
@bkamins exactly that, thanks!
