### ISSUE TITLE
dev gets wrong branch

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaLang/Pkg.jl#800]
I'm using Julia 1.0.1, Windows 7, 64 bit.

I have an old Julia 0.6 compatible branch (J0.6) and a master branch that is Julia 1.0 compatible (repo at https://github.com/JuliaRheology/RHEOS.jl). It was all working fine yesterday when I ```dev```'ed in the repo. Today, it tries to get the J0.6 branch for some reason:

```
(v1.0) pkg> dev "https://github.com/JuliaRheology/RHEOS.jl"
  Updating git-repo `https://github.com/JuliaRheology/RHEOS.jl`
[ Info: Assigning UUID 4bf54d18-b41c-58dc-8574-a0581551535a to RHEOS
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package JLD [4138dd39]:
 JLD [4138dd39] log:
 ├─possible versions are: [0.5.0-0.5.9, 0.6.0-0.6.11, 0.8.0-0.8.3] or uninstalled
 ├─restricted to versions 0.0.0-* by RHEOS [4bf54d18], leaving only versions [0.5.0-0.5.9, 0.6.0-0.6.11, 0.8.0-0.8.3]
 │ └─RHEOS [4bf54d18] log:
 │   ├─possible versions are: 0.0.0 or uninstalled
 │   └─RHEOS [4bf54d18] is fixed to version 0.0.0
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

Which obviously doesn't work. When I navigate to the dev/RHEOS folder I find the J0.6 branch there downloaded. This seems bizarre because last week my master branch was 0.6 compatible and a separate branch was 1.0 compatible, and I was trying to figure out how to ```dev``` in the 1.0 compatible branch (I discovered you can't via discourse). Now my master branch is 1.0 compatible, and was working yesterday via ```dev```. But today it doesn't load in.

**Comment by moustachio-belvedere** [comment]
Just to add: JLD is not in the Project.toml or Manifest.toml of the (v1.0 compatible) master branch.

**Comment by moustachio-belvedere** [comment]
Playing around some more, running:

```dev "https://github.com/JuliaRheology/RHEOS.jl.git"```

Seems to work fine. So the difference in behaviour seems to dependent on the ```.git``` at the end

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/Pkg.jl/issues/465. FWIW, you can always clear out `.julia/clones` to fix this. We are currently not updating the cache there correctly.
