### ISSUE TITLE
Cann't Install IJulia

### ISSUE THREAD

**Issue by Roboid537** [JuliaLang/Pkg.jl#816]
Hey Guys,
I am already using Jupyter Notebook for python and now I want to switch to Julia. During installation of Julia Notebook using Pkg.add("IJulia") I am countering this error. Can anyone help me to resolve this? 
Thanks A lot in advance.
![ijulia](https://user-images.githubusercontent.com/34138037/46786643-21ed9c80-cd53-11e8-923e-24c870d3950b.PNG)

**Comment by Roboid537** [comment]
I deleted the ".julia" folder and installed all packages again. Even I tried Pkg.build() but the issue remained same.

**Comment by Whale-fall** [comment]
> I deleted the ".julia" folder and installed all packages again. Even I tried Pkg.build() but the issue remained same.

I meet the same question.Hope we can fix it

**Comment by KristofferC** [comment]
Please comment if this keeps happening.
