### ISSUE TITLE
To update TOML.jl v0.4.0 (or to fix the error - hex not defined)

### ISSUE THREAD

**Issue by wookay** [JuliaLang/Pkg.jl#835]
Hello, I got the `hex not defined` error on my windows.
I've investigated some code and I found the `hex` function (deprecated) is used in `TOML/src/parser.jl`

* https://github.com/JuliaLang/Pkg.jl/blob/master/ext/TOML/src/parser.jl#L588
```
 error(p, st, position(p), "unknown string escape: `$("\\x"*hex(ch,2))`")
```

Instead to fix that line alone, it probably better to update other code as TOML.jl v0.4.0.
see the how changes above line.
* https://github.com/wildart/TOML.jl/blob/v0.4.0/src/parser.jl#L592
```
error(p, st, position(p), "unknown string escape: `\\x$(UInt8(ch))`")
```

**Comment by 00vareladavid** [comment]
Resolved by #909
