### ISSUE TITLE
Adding a package version that is not supported does not error in all cases

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg.jl#836]
If you add a package with a given version, that is already present in the manifest (perhaps must be tracking a path) results in a no-op rather than an error. See https://discourse.julialang.org/t/modia-requires-modiamath-0-2-4-but-uses-0-2-5-dev-surprising-behaviour/16312/6

**Comment by 00vareladavid** [comment]
I have manually confirmed that #989 fixes this issue. Testing this case is tricky though

**Comment by 00vareladavid** [comment]
This also brings up an interesting point: it seems that the expected behavior on `rm` is an implicit `free`. Should we warn users this is not the case?
