### ISSUE TITLE
RequirementVersions

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/Pkg.jl#84]
A while ago tkelman helped me make RequirementVersions.jl, which via repeated testing automatically set version bounds on the packages in your REQUIRE file. It did this by progressively lowering the version numbers of the each required packages until it broke, then resetting versions to their initial values. Pkg2 made it pretty difficult to do this kind of thing. But since version bounds are essential to the stability of the package ecosystem, it might be worth considering whether this kind of thing would be possible to do in Pkg3.

**Comment by StefanKarpinski** [comment]
What about Pkg2 made this difficult?

**Comment by KristofferC** [comment]
I don't see finding the lowest compatible version by running tests a worthwhile effort. If the author specified a certain lower bound then it is probably for a reason. It might be for performance reasons or things not covered in tests.

**Comment by martinholters** [comment]
I think the target audience would be authors trying to figure out what minimum version of a dependency to require.

**Comment by bramtayl** [comment]
Maybe I'm misunderstanding, but I think KristofferC has got this backwards. This is to help out package authors. If minimum version boundaries are set too low then you get broken packages and if they are set too high it causes trouble for the package resolver.

Here are some issues we ran into:
https://github.com/bramtayl/RequirementVersions.jl/issues/3#issuecomment-326760379
https://github.com/bramtayl/RequirementVersions.jl/pull/4/commits/56f76c7ac11435c1e90b2da57f52ba808eeb8f64
https://github.com/bramtayl/RequirementVersions.jl/pull/5#issuecomment-326810937
