### ISSUE TITLE
Faster tests

### ISSUE THREAD

**Issue by 00vareladavid** [JuliaLang/Pkg.jl#858]
A lot of my time testing is spent waiting for the same registry to repeatedly download. AFAICT There is no real benefit to doing it the current way

Can we introduce a test utility that:
- copies a know-good depot directory to `/tmp`
- sets DEPOT_PATH to it
- sets `Pkg.UPDATED_REGISTRY_THIS_SESSION[] = true`

We can still leave a few integration tests that actually do the download

**Comment by fredrikekre** [comment]
#588 does something like this actually.

**Comment by 00vareladavid** [comment]
This had been bugging me for a while now, thanks a bunch!

**Comment by 00vareladavid** [comment]
Awesome, tests are now flying locally!
