### ISSUE TITLE
Trouble adding packages in JuliaPro 1.0.1

### ISSUE THREAD

**Issue by jaabadi** [JuliaLang/Pkg.jl#861]
I've been having trouble adding packages to JuliaPro 1.0.1 (on Mac OSX) despite having been able to add them in Julia 1.0.1. For example, if I type
`Pkg.add("Gadfly")`
in JuliaPro, I get 
`Updating registry at "/Applications/JuliaPro-1.0.1.1.app/Contents/Resources/pkgs-1.0.1.1/registries/JuliaPro"`
`Updating git-repo "https://pkg.juliacomputing.com/registry/JuliaPro"`
`ERROR: The following package names could not be resolved:`
`* Gadfly (not found in project, manifest or registry)`
`Please specify by known "name=uuid".`
However, this works fine in Julia.

I also have issues when trying to clone Github repos. For instance,
`pkg> add https://github.com/RJDennis/ChebyshevApprox.jl'`
returns
`Updating git-repo "https://github.com/RJDennis/ChebyshevApprox.jl"`
`[ Info: Assigning UUID 17a596ad-87cd-578c-9b6d-01108c31dc04 to ChebyshevApprox`
` Resolving package versions...`
`ERROR: The following package names could not be resolved:`
`* julia (not found in project, manifest or registry)`
`Please specify by known "name=uuid".`

I've already tried removing the registries directory to no avail. Does anyone happen to know what's going on? Also, would it be possible for me to change my package directory for JuliaPro to the one that Julia uses? This would resolve the issue as well, since all of the packages I want to use are already installed in Julia.

**Comment by KristofferC** [comment]
I think this is because JuliaPro does not include all packages in their registry.

**Comment by fredrikekre** [comment]
See https://discourse.julialang.org/t/physicalconstants-package-with-julia-1-0-1-1/16189 and the discussion in there. Closing since this is an issue with JuliaPro rather then the package manager.
