### ISSUE TITLE
Pkg.develop(PackageSpec(path=$(local repo))) does not build the package

### ISSUE THREAD

**Issue by bicycle1885** [JuliaLang/Pkg.jl#862]
`Pkg.develop(PackageSpec(path="local repository"))` does not build the package while `Pkg.develop(PackageSpec(url="remote repository"))` does. I noticed this while working on the migration of documentation deployment (see https://discourse.julialang.org/t/psa-use-a-project-for-building-your-docs/14974/11 for details). This may be intentional but this is unexpected to me.

**Comment by 00vareladavid** [comment]
I don't think this is intended, but this should be fixed on master: We map `path` to `url` during the construction of `PackageSpec` so there is not much room for both commands to become out of sync.

**Comment by fredrikekre** [comment]
> Perhaps we should info?

It could be annoying. Maybe just document that develop just points to the existing files? Or maybe detect that the package has a build script and only warn then.

**Comment by KristofferC** [comment]
I think this is just what we have to do. `build` is just kind of unfortunate that it exists at all.
