### ISSUE TITLE
Dependency on Pkg

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg.jl#863]
Most new releases of packages has a dependency on Pkg, because they now have `using Pkg` in their `travis.yml` files. https://github.com/JuliaLang/Pkg.jl/blob/9a53f24a0b00b04e5e901b8609437b5ff9cb12f8/bin/gitmeta.jl#L41 should only look in `.jl` files.

**Comment by StefanKarpinski** [comment]
Fixed by https://github.com/JuliaLang/Pkg.jl/pull/864/commits/b2ff7527a30f40ef18f7e340534bb8e5fc40b5a0, included with https://github.com/JuliaLang/Pkg.jl/pull/864/commits/82984c9adf5a2fbb3592595f525d8d67f3875882 because I needed that to get things working with an up-to-date Julia.

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/864#issuecomment-434065101
