### ISSUE TITLE
Allow coverage tests to be executed with option `inline=no`

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/Pkg.jl#865]
Hi!

It turns out that Julia reports very wrong coverage information in some cases if the data is generated without `--inline=no` (see JuliaCI/Coverage.jl#187). Hence, I think it is necessary to provide a way to execute the package test with this option. Otherwise, at least for my case, the coverage information generated at Travis for Coveralls and Codecov is really wrong.

**Comment by tkoolen** [comment]
While this would be good to have anyway, do note that https://github.com/JuliaLang/julia/issues/28192#issuecomment-418277362 reports that `--inline=no` is not a solution to the code coverage problems.

**Comment by fingolfin** [comment]
@tkoolen it is not clear from me that the comment you link to is accurate. In particular, it's not clear what exactly they "tried" to come to that conclusion. After all, the reason @ronisbr has filed this is issue is that simply passing `--inline-no` to julia is not enough, a change to `Pkg.test` is apparently needed.

**Comment by fingolfin** [comment]
PR #866 attempts to resolve this.

**Comment by ronisbr** [comment]
In my case (ReferenceFrameRotations.jl), in which the tests and the functions are somewhat simple, I can say that `inline=no` improved a lot the coverage results.

**Comment by 00vareladavid** [comment]
Resolved by #870
