### ISSUE TITLE
Equivalent of old Pkg.dependents (reverse dependencies)

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/Pkg.jl#871]
Is there one already? I couldn't find it.

**Comment by StefanKarpinski** [comment]
I don't think so but it would be a nice feature to add.

**Comment by IanButterworth** [comment]
The standard answer to this nowadays is that it's provided by the richer juliahub interface https://juliahub.com/ui/Packages/CSV/HHBkp/0.9.6?page=2

I assume this can be closed

**Comment by xgdgsc** [comment]
What if user want to find dependents in local packages?

**Comment by IanButterworth** [comment]
I think I was wrong in closing this. Implemented in https://github.com/JuliaLang/Pkg.jl/pull/4656
