### ISSUE TITLE
Excessive cloning: Part 2

### ISSUE THREAD

**Issue by ma-laforge** [JuliaLang/Pkg.jl#874]
I have one more data point regarding the huge jump in amounts of clones that are being performed on (my) registered packages.  It might not be an issue, but I do find the pattern odd...

I had forgotten to tag some of the changes to one of my packages, `GracePlot`.  I had previously released v0.3.0 on Aug 14th.  Since this time, #clones/#unique cloners has been relatively steady.  On a good day, I would get 19 clones for 11 unique cloners (roughly 2:1):

![image](https://user-images.githubusercontent.com/11205411/47863574-f435c980-ddcd-11e8-9c56-d5e868fb4dd3.png)

But as you can see with the green line, the number of clones dramatically jumped after my next release, v0.3.1, with attobot on Oct 27th (increase is very visible starting from the 28th).

| DATE | #clones | #unique cloners |
|--------|---|---|
| Oct 19 | 1 | 1 |
| Oct 20 | 1 | 1 |
| Oct 21 | 11 | 6 |
| Oct 22 | 4 | 3 |
| Oct 23 | 19 | 11 |
| Oct 24 | 0 | 0 |
| Oct 25 | 1 | 1 |
| Oct 26 | 2 | 2 |
| Oct 27 | 15 | 10 |
| Oct 28 | 198 | 7 |
| Oct 29 | 88 | 5 |
| Oct 30 | 133 | 1 |
| Oct 31 | 102 | 6 |

I used to think someone out there wrote a sort of mining 'bot to automatically clone Julia packages... but I don't think so anymore.  That does not explain why the number of clones only jumped up after I made this new release.  This package was already registered, so a mining 'bot should have already seen it (unless, possibly, it used some obscure piece of information to find the registered packages, or something).

My guess is that something happened with the package manager... or maybe how releases are registered now... I don't really understand enough to know, though.

I do know that now all my registered packages are exhibiting what I would argue are disproportionally high numbers of clones.  For reference, I am providing a link to the original issue I opened when I first saw this phenomenon: https://github.com/JuliaLang/Pkg.jl/issues/762.

**Comment by KristofferC** [comment]
When you make a new release, people who update their packages will download that release. Is that so strange?

**Comment by ma-laforge** [comment]
1) Maybe not.  I have simply never seen that many downloads clones per unique number of cloners (or even in absolute numbers, either).  I have a hard time imagining that people suddenly got that interested in my package given this new release (which only had minor fixes)....

 2) I also don't understand why nobody jumped on the bandwagon for release v0.3.0 on Aug 14th (given that everyone was eager to upgrade).  And I still see high cloning activity for `InspectDR.jl`, `MDDatasets.jl`, and `PSFWrite.jl` that were last released after September 9th (~2000 clones for only dozens of unique cloners).  None of those packages were recently released (last release was a month ago).

 3) What's even more strange is that `InspectDR.jl` depends on `NumericIO.jl` (***Everyone who uses `InspectDR` needs `NumericIO`***)... and although I see ~2000 weekly clones of `InspectDR`, I only still see roughly 58 clones for 15 unique cloners for the last two weeks on `NumericIO` (with a 2:1 ration for clones on a daily basis).

 4) I have a few other packages that have older releases: `LibPSF` (Aug 26) and `SpiceData` (Aug 15).  They are also still getting low cloning traffic, similar to that of `NumericIO`.

**Comment by ma-laforge** [comment]
...But at the end of the day, I am just pointing out an observation.

If you don't see this as being a real problem, feel free to close the issue.  I understand that this pattern might not look like an actual issue to someone in the know.

**Comment by StefanKarpinski** [comment]
@andreasnoack maybe CIBot?

**Comment by mortenpi** [comment]
It's listed on [Julia Observer](https://juliaobserver.com/packages/MDDatasets). It posts the README of the package, so probably also clones the repo regularly?

**Comment by andreasnoack** [comment]
I doubt that CIBot could have caused this. The activity is not as high. I'm wondering if https://bitbucket.org/unofficialjuliamirror/ could have caused this. I've been pinged a couple of times because of these repos.

**Comment by KristofferC** [comment]
Interesting to investigate but not really a Pkg bug so will close.
