### ISSUE TITLE
Whitespace harmonisation in Pkg display

### ISSUE THREAD

**Issue by tlienart** [JuliaLang/Pkg.jl#875]
## (small) Problem

At the risk of being a bit OCD ... 

```julia
(v1.0) pkg> generate PackageExample
Generating project PackageExample:
    PackageExample/Project.toml
    PackageExample/src/PackageExample.jl
```

* _no space_ in front of `Generating...`, _four spaces_ in front of `PackageExample...` and subsequent line
* see https://github.com/JuliaLang/Pkg.jl/blob/master/src/generate.jl#L19 (introduces 4 spaces explicitly)

```julia
(v1.0) pkg> dev ~/.julia/dev/PackageExample
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
  [afc87576] + PackageExample v0.1.0 [`~/.julia/dev/PackageExample`]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [afc87576] + PackageExample v0.1.0 [`~/.julia/dev/PackageExample`]
```

* _one (spurious) space_ in front of `Resolving...`, _one additional space_ in front of `Updating...`
* see https://github.com/JuliaLang/Pkg.jl/blob/master/src/Types.jl#L1113-L1118 (uses `lpad`)
* see also https://github.com/JuliaLang/Pkg.jl/blob/master/src/Operations.jl#L316

```julia
(v1.0) pkg> rm PackageExample
  Updating `~/.julia/environments/v1.0/Project.toml`
  [afc87576] - PackageExample v0.1.0 [`~/.julia/dev/PackageExample`]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [afc87576] - PackageExample v0.1.0 [`~/.julia/dev/PackageExample`]
```

* _two (spurious) spaces_ in front of `Updating...`
* same bit of code with `lpad`
* also https://github.com/JuliaLang/Pkg.jl/blob/8b821fb76f1b8b25f092ae17a5b2bc3420ed856c/src/Types.jl#L1154

## Suggestion

I'd happily suggest a PR for this tiny issue (it might not even be considered as such in which case feel free to close it) however I don't fully understand how `printpkgstyle` works, in particular the first line `indent = textwidth(string(:Downloaded))`, how does that get changed by the context?

Anyway this is probably very low priority but my eyes bleed when things are not properly vertically aligned.

**Comment by fredrikekre** [comment]
The idea with `printpkgstyle` is that all verbs should right align, e.g. `Removing`, `Cloning`, `Adding`:
```
  Removing registry `RegistryFoo` from /tmp/tmpOGymhP/registries/RegistryFoo
   Cloning registry from "/tmp/tmpGpNkff/RegistryFoo1"
     Added registry `RegistryFoo` to `/tmp/tmpLs4ojp/registries/RegistryFoo`
   Cloning registry from "/tmp/tmpGpNkff/RegistryFoo2"
```

> `indent = textwidth(string(:Downloaded))`, how does that get changed by the context?

This is just because `Downloaded` is the longest verb used in Pkg :stuck_out_tongue:

**Comment by KristofferC** [comment]
> no space in front of Generating..., four spaces in front of PackageExample... and subsequent line

Yes to show that the files are generated as a result of the generate command.

> one (spurious) space in front of Resolving..., one additional space in front of Updating...

They are not spurious, it is so multiple "verbs" that happen during one command will align.

> my eyes bleed when things are not properly vertically aligned.

Im confused, the things you complain about are the things that make things align:

```
  Updating registry at `~/.julia/registries/CustomReg`
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/KristofferC/Tensors.jl.git`
 Resolving package versions...
 Installed KernelDensity ─ v0.5.1
 Installed Atom ────────── v0.7.10
```

**Comment by tlienart** [comment]
Ha sorry for some reason I had not realised the verbs were right-aligned (thanks @fredrikekre for taking the time to explain it). 

I'll close this "issue", sorry for the spam!
