### ISSUE TITLE
Expand ~ in Pkg REPL completions

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg.jl#882]
The Julia REPL replaces `~` with `home/user` in tab-completions. Would be nice to do this in the Pkg REPL too for `activate`, `dev` and `add`.

Looks like it would be enough to handle it here: https://github.com/JuliaLang/Pkg.jl/blob/f65ef8fb53498bca0c8a63c479d610cb9d996beb/src/REPLMode.jl#L690

Reference for the Julia REPL implementation https://github.com/JuliaLang/julia/blob/099979931ce1e666e15ba090cf257bd4fbae8ede/stdlib/REPL/src/REPLCompletions.jl#L271

**Comment by mschauer** [comment]
And the warning to exercise care when removing directories containing the letter `~` (and not to remove the entire home directory `~`)

**Comment by KristofferC** [comment]
But `~` works to use directly in the REPL mode. So not sure why it has to be expanded.

**Comment by mschauer** [comment]
Example regarding the issue
```
(v1.1) pkg> activate  ~/dev/Trajectories/
[ Info: activating new environment at ~/julia/~/dev/Trajectories.
```

**Comment by KristofferC** [comment]
Hm, interesting. Something like

```
(v1.1) pkg> dev ~/.julia/dev/ForwardDiff
```

works.

**Comment by fredrikekre** [comment]
Yea, that works on Pkg master. I am only complaining about the lack of autocompletion.

**Comment by KristofferC** [comment]
Oh, +1 for autocompletion but there isn't a need to expand `~` for that (should be enough to do it for the internal `complete_path` call but perhaps that is exactly your point).

**Comment by tlienart** [comment]
> Hm, interesting. Something like
> 
> ```
> (v1.1) pkg> dev ~/.julia/dev/ForwardDiff
> ```
> 
> works.

is this something that is in an upcoming release? I'm having the same issue as @mschauer : 

```
shell> cd ~
/Users/tlienart

(v1.1) pkg> activate ~/.julia/dev/Example
[ Info: activating new environment at ~/~/.julia/dev/Example.
```
