### ISSUE TITLE
Add "pkg> precompile SomePackage"

### ISSUE THREAD

**Issue by carstenbauer** [JuliaLang/Pkg.jl#888]
A way to precompile only a specified subset of packages, i.e. `precompile [pkgs...]` would be nice!

Very much similar to #575. See also [this discourse thread](https://discourse.julialang.org/t/usability-tweak-for-pkg/17203/3).

If it's not just me who would find this useful I'd be also willing to implement it (now that I have some practice after #881 😃).

**Comment by KristofferC** [comment]
What's the advantage over `import pkgs`?

**Comment by asinghvi17** [comment]
Bump on this?  For something like a main project (v1.2) where there are a lot of things in the project, it would be nice not to have to wait for all the irrelevant packages that got updated to precompile, and only precompile the relevant ones.

**Comment by StefanKarpinski** [comment]
That's not how precompilation works—Julia doesn't support separate compilation. If any package changes, you have to recompile all the packages that depend on it.

**Comment by asinghvi17** [comment]
Right, but it might precompile, say, `DifferentialEquations`, when I know I won't be using that for some time; however, if I know I'll be using `Makie`, then I should be able to precompile only Makie without sitting through DifferentialEquations' precompilation step.

**Comment by IanButterworth** [comment]
Introduced in https://github.com/JuliaLang/Pkg.jl/pull/2724
