### ISSUE TITLE
Use compatibility constraints from packages listed in extras

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/Pkg.jl#895]
I was hoping that the `[compat]` constraint in `TestEnv` would constrain the versions I could install in `GPUEnv`.
The use-case where this would be interesting for is `Requires.jl`. `TestEnv` uses `Requires.jl` to load code that is dependent on a particular version of `CUDAnative`.

Alternatively instead of having a `extra` section one could have an `optional` section that has these stricter semantics.

```
name = "TestEnv"
uuid = "f59c4fb8-e42d-11e8-39b9-5d72c5061eb3"
version = "0.1.0"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
CUDAnative = "0.7"

[extras]
CUDAnative = "be33ccc6-a3ff-5ff2-a52e-74243cff1e17"
```

```
name = "GPUEnv"
uuid = "9eb97ce2-e42e-11e8-3709-85c2032a41b3"
version = "0.1.0"

[deps]
CUDAnative = "be33ccc6-a3ff-5ff2-a52e-74243cff1e17"
TestEnv = "f59c4fb8-e42d-11e8-39b9-5d72c5061eb3"
```

**Comment by 00vareladavid** [comment]
#989 should obviate this issue

**Comment by 00vareladavid** [comment]
I think soon. The feature is on master, but it has not been well tested yet. I should at least test this specific feature before we can close.
