### ISSUE TITLE
Output when running build.jl

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/Pkg.jl#910]
It currently shows
```julia
Building MyPackage → `~/.julia/dev/MyPackage/deps/build.log`
Resolving package versions...
```
while the script is downloading. It's a bit confusing and it actually made me abort the operation because I though the manager was stuck in the resolver while it was just downloading a big file.

**Comment by fredrikekre** [comment]
Ref #809 for Julia v1.1

**Comment by KristofferC** [comment]
Yeah, the output here is a bit misleading. We don't know we need to resolve until after we started building the package.

**Comment by KristofferC** [comment]
The verbose build should fix this.
