### ISSUE TITLE
status -m Package

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg.jl#915]
Opening an issue to track this: https://github.com/JuliaLang/Pkg.jl/pull/881#issuecomment-436942479 which would be nice to have with the 1.1 release.
cc @crstnbr since you wrote the original PR.

**Comment by crstnbr** [comment]
Can't promise anything but I'll try to work on this on the weekend.

**Comment by fredrikekre** [comment]
Didn't mean you have to do it, just if you were interested and had time!
