### ISSUE TITLE
Pkg seems to be able to remove exports

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/Pkg.jl#919]
This is a bit of a mystery bug, since it only happened around ~4 times to me, where 3 times where out of my control.
One case was very clear cut though - let me try to roughly summarize what happened:
```julia
]add Makie
> using Makie
> error SOME_GLOBAL_VAR_FROM_MODERNGL not defined
> using ModernGL
> SOME_GLOBAL_VAR_FROM_MODERNGL <- not defined even though it should be exported
> ModernGL.SOME_GLOBAL_VAR_FROM_MODERNGL <- does actually work
```
`]st` verified that the correct version of ModernGL was installed. Also, that variable got exported from ModernGL since the beginning of time, so a wrongly installed version is pretty unlikely! This was on a relatively fresh install, so packages should have been added freshly.

Now then, this is how I "fixed" it:
```Julia
]rm ModernGL; gc; add ModernGL # same version as previously got installed
>using Makie <- compiled fine
>using ModernGL; SOME_GLOBAL_VAR_FROM_MODERNGL <- works fine
```
This happened some weeks ago and I didn't report it because it was too shaky and a download error or something like that seemed more like...

By now though, a couple of other problems popped up that seemed similar:

* https://github.com/JuliaPlots/Makie.jl/issues/244#issuecomment-440639794
* I added IntervalSets and it didn't export Interval... I fiddled around with `add IntervalSets#master` etc it until it worked... this one is sadly not as clear, since I didn't check the version before and after, and it seems like some earlier versions in IntervalSets indeed don't export Interval
* @mkborregaard had some familiar sounding undefined variable errors recently
* I saw at least one other problem that could be explained with this bug

So the question is, does Pkg3 even have the ability to mess with the exports like this? Or must this be some weird other flake / download corruption, or whatever?

If it wasn't for the ModernGL.jl case, I'd just assume this is a mismatch of versions and that's why imports fail - and likely other people running into the same bug will assume the same and just fiddle with Pkg3 as long as it starts working.

**Comment by mkborregaard** [comment]
Yeah, my issue, described here: https://julialang.slack.com/archives/C7JT7HQAD/p1542744916231500 (as long as Slack saves it) was solved after `]st; rm Atom; resolve; add Atom` (same Atom version).

**Comment by SimonDanisch** [comment]
>This is a bit of a mystery bug, since it only happened around ~4 times to me, where 3 times where out of my control.

**Comment by StefanKarpinski** [comment]
I think there's some code somewhere that's resolving `using` bindings that shouldn't be. I've seen other symptoms of this recently. Not sure if it's Pkg-specific, however.

**Comment by KristofferC** [comment]
Pkg only installs packages and outputs Project + Manifest, the rest is up to code loading. Pkg cannot touch exports. I'm gonna close this since I am guessing this is mostly a red herring from some other effect which needs a repro.
