### ISSUE TITLE
Simultaneous support of 32-bit and 64-bit Julia versions

### ISSUE THREAD

**Issue by tshort** [JuliaLang/Pkg.jl#93]
Using 32-bit and 64-bit versions of Julia on one computer is clunky with Julia v0.6 / Pkg2. When alternating, between versions, all packages have to be recompiled. In addition, if packages load binary libraries, you generally have to manually do a `Pkg.build("MyPackage")`.

Does Pkg3 support this better? 

This use case is mainly for testing different versions of Julia.

**Comment by StefanKarpinski** [comment]
Not currently, but we should change precompilation to be per-Julia-binary instead of per-Julia-version as it currently is. Not really a Pkg3-related issue, but everyone seems to enjoy discussion precompilation here, so I guess why not.

**Comment by KristofferC** [comment]
In addition, for packages with a build folders, we could do the same (two different paths for the same package, chose depending on Int size so building will use different folders).

**Comment by KristofferC** [comment]
Ideally, there should be a separate path, completely outside the source where stuff get built.

**Comment by KristofferC** [comment]
>  In addition, if packages load binary libraries, you generally have to manually do a Pkg.build("MyPackage").

Probably fixed with the artifact system. The precompilation thing is not something that can be changed from here.
