### ISSUE TITLE
consistent use of `@env` vs `env`

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/Pkg.jl#930]
I'd like to propose consistently using `@env` as syntax for a named environment with name `env`. This would allow doing something like `pkg> activate @devtools` to activate `~/.julia/environments/devtools` no matter where you are. The main issue would seem to be conflicting with the `@1.1` version syntax, but I'm not sure that's an actual ambiguity anywhere. Thoughts?

**Comment by fredrikekre** [comment]
And remove `--shared`?

**Comment by StefanKarpinski** [comment]
This does seem like it would be more intuitive, doesn't it? I always forget about shared and I want to just call named environments `@env` everywhere.

**Comment by KristofferC** [comment]
Seems like a simplification. `@name` if you just want to identify it by name. `path/name` if you want to identify by path.

**Comment by StefanKarpinski** [comment]
Note that as part of this we should use `@env` consistently to _display_ shared environments as well. So the prompt should be `(@v1.1) pkg>` instead of the current `(v1.1) pkg>`. The idea is that if you do `pkg> activate @v1.1` then the prompt you get afterwards is `(@v1.1) pkg>`.
