### ISSUE TITLE
`--force` option for `dev`?

### ISSUE THREAD

**Issue by 00vareladavid** [JuliaLang/Pkg.jl#935]
We keep a cache when we clone, but the cache is liable to break. We could have a `--force` option which would simply remove the appropriate cached clone. I'm not set on the name `force`, just the first thing that came to mind.

or perhaps `--fresh`?

**Comment by KristofferC** [comment]
I think we should just fix the bug where the cache doesn't get updated. We probably just need to add something like

https://github.com/JuliaLang/Pkg.jl/blob/b90a08ac926885614e654de2ec443f541a7d7865/src/Types.jl#L1303

somewhere here

https://github.com/JuliaLang/Pkg.jl/blob/b90a08ac926885614e654de2ec443f541a7d7865/src/Types.jl#L672-L677

**Comment by 00vareladavid** [comment]
I'm concerned with storing the cache openly on the file-system. I'm not against doing that, but any process which has write access to it can mess it up in any number of ways.

I just think it would be nice to tell users: "if something goes wrong, just `--force` it".

**Comment by StefanKarpinski** [comment]
I prefer `--fresh` to `--force`; this would be fine by me, although I also think we should fix the bug.

**Comment by 00vareladavid** [comment]
Bonus is that we can now say: "just keep it `--fresh`, yo".

**Comment by KristofferC** [comment]
Not needed anymore since all usage is not `--force`.
