### ISSUE TITLE
bring back package naming guidelines into the docs

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/Pkg.jl#945]
When OldPkg was removed by https://github.com/JuliaLang/julia/pull/27095, the [Guidelines for naming a package](https://docs.julialang.org/en/v0.6/manual/packages/#Guidelines-for-naming-a-package-1) went with it. It would be useful for re-introducing it in the manual of this package.

**Comment by fredrikekre** [comment]
bors/github does not seem to autoclose things anymore...
