### ISSUE TITLE
Public `parse(::Type{PackageSpec}, ::String)` API

### ISSUE THREAD

**Issue by rofinn** [JuliaLang/Pkg.jl#950]
It might be nice if the REPL `PackageSpec` parsing was made public. Maybe via a `parse(::Type{PackageSpec}, ::String)` method? One use case is configuring Docker builds (e.g., `docker build --build-arg PKG_BRANCH="Pkg1#master, Pkg2#rf/myfeature" ...`). It'd be nice if we could just parse `PKG_BRANCH` strings using the same syntax as the Pkg REPL.

**Comment by KristofferC** [comment]
Why is not using a `Manifest` better for this? It feels like an ideal usecase.

**Comment by rofinn** [comment]
Currently, we're checking out specific branches in a separate docker `RUN` step, so that we can cache most of our built packages between `docker build` executions. Unfortunately, if we're just relying on a `Manifest` file then every time we modify the file it would re-run that entire build step. Is there an easy way to merge `Manifest` files? For example, if we used a `Project.toml` file to install all of our base packages, could we update the generated `Manifest` file with our customizations?

**Comment by StefanKarpinski** [comment]
Merging manifest files is a reasonable request (behaviorally, that's how `LOAD_PATH` works even though it's not implemented that way). The new `Manifest` data structure could implement `merge!` methods. For load path the earlier manifests are preferred in the overlay; for this it sounds like you'd favor the later ones?

**Comment by rofinn** [comment]
> For load path the earlier manifests are preferred in the overlay; for this it sounds like you'd favor the later ones?

Yep, we'd want anything in the `Manifest.dev` to take priority, roughly equivalent to manually performing a set of `Pkg.develop` calls after installing all of our dependencies.

**Comment by StefanKarpinski** [comment]
Can't you already have this effect by putting a project with all the relevant things dev'd earlier in the load path than the project? I.e. something like `LOAD_PATH == ["@devs", "@", "@v#.#", "@stdlib"]`? Where `~/.julia/environments/devs` is a named environment where you've dev'd all the right things.

**Comment by KristofferC** [comment]
Just use the API format for progammattically interacting with Pkg. That's why it is there.
