### ISSUE TITLE
`Pkg.add` with explicit URL ignores pin

### ISSUE THREAD

**Issue by 00vareladavid** [JuliaLang/Pkg.jl#951]
```
pkg> add Example@0.4.0
pkg> pin Example
pkg> add https://github.com/JuliaLang/Example.jl
```

`pin` is not respected in this case.

**Comment by 00vareladavid** [comment]
I'm thinking that we should refactor `handle_repos_add` so that, in the case where a package is specified by an explicit URL, we try to parse the clone for a UUID. We can then use the UUID to decide what to do e.g. look for a pin in the manifest.

**Comment by fredrikekre** [comment]
related to  #263
