### ISSUE TITLE
Feature request: `add MyPackage#fork:branch`

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/Pkg.jl#969]
A regular `Pkg` use case for me is to check out a PR branch of some package. Often, the PR branch lives on a different fork. So my current workflow is to first `dev MyPackage`, and then manually add the fork and check out the PR branch. However, for PR branches that live in the source repo, I can just do `add MyPackage#branch`. It'd be great if something like 

```
add MyPackage#fork:branch
```

were possible as well.

**Comment by fredrikekre** [comment]
Note that you can always add the fork with url:
```
pkg> add www.fork.com/Package.jl#branch
```

**Comment by tkoolen** [comment]
That's a good point. And I guess `add MyPackage#fork:branch` would have to make assumptions regarding where the fork lives. Still, it would be convenient to have with the vast majority of packages (and their forks) living on GitHub.

**Comment by 00vareladavid** [comment]
Duplicate of #740
