### ISSUE TITLE
Pkg won't let me install master versions of packages

### ISSUE THREAD

**Issue by Keno** [JuliaLang/Pkg.jl#972]
I tried the following:

```
(XLA) pkg> add https://github.com/sorpaas/HPack.jl#master
  Updating git-repo `https://github.com/sorpaas/HPack.jl`
 Resolving package versions...
  Updating `~/XLAHacks.jl/Project.toml`
 [no changes]
  Updating `~/XLAHacks.jl/Manifest.toml`
 [no changes]

(XLA) pkg> add https://github.com/sorpaas/HTTP2.jl#master
  Updating git-repo `https://github.com/sorpaas/HTTP2.jl`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package HPack [ac4eac4a]:
 HPack [ac4eac4a] log:
 ├─possible versions are: 0.1.0 or uninstalled
 ├─restricted to versions 0.2.0-* by HTTP2 [d274f558] — no versions left
 │ └─HTTP2 [d274f558] log:
 │   ├─possible versions are: 0.1.0 or uninstalled
 │   └─HTTP2 [d274f558] is fixed to version 0.1.0+
 └─HPack [ac4eac4a] is fixed to version 0.1.0+
```

I believe the problem is that HTTP2.jl declares a dependency on HPack 0.2.0 that never got tagged, so Pkg believes that HPack is at 0.1.0+ when it's actually at 0.2.0+ (arguably). However, I don't really care about either, I just want to try out the packages at my specified versions. I also tried `dev`'ing the HTTP2.jl URL, which fails with the same error. I figured at least that would be allowed.

**Comment by 00vareladavid** [comment]
I do think `Pkg` is working as intended though. The correct solution would be to introduce a `Project.toml` file upstream.

**Comment by Nosferican** [comment]
Aye. This issue can be closed.
