### ISSUE TITLE
Pkg command `registry-status` doesn't work

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/Pkg.jl#988]
This is on julia 1.1.0-rc1.0 on Windows.

The package manager tells me that there is a command ``registry-status`` when I look at the help with ``]help``. When I try to execute that command, I get an error though:
````
(v1.1) pkg> registry-status
ERROR: could not determine command
````

**Comment by fredrikekre** [comment]
It's not a mistake but a bit unintuitive. We should (i) not join with the dash and (ii) make `pkg>?registry status` work, as I discussed with @00vareladavid at some point.

**Comment by 00vareladavid** [comment]
Agreed. I can see how that is confusing.

I did get started on the changes when you mentioned it, it shouldn't be too hard to finish it up.

**Comment by fredrikekre** [comment]
Also, `?registry` and `?package` should work and show a filtered help with the sub-commands.
