### ISSUE TITLE
 Locally developed unregistred packages, that are then added to a registry, are shadowed

### ISSUE THREAD

**Issue by galenlynch** [JuliaLang/Pkg.jl#997]
This is probably a pretty unusual use case, but it seems like when you develop a package locally that is not registered, and then later add it to a registry without changing anything else with Pkg3, it becomes shadowed by the master branch of that package.

Specifically, I have been developing an unregistered package, which I then added to my own private registry. After adding the package to the registry, local modifications to the package would not be detected by Julia, as if it were using the master branch instead of my working directory. Looking at the status of the package using Pkg3 showed the package was listed at version v0.0.0 (unregistered), even though I could use the registry to install the package on other computers. Freeing the package with Pkg3, then developing it again, fixed the problem.

This is with Julia 1.0.3, official binaries.

**Comment by fredrikekre** [comment]
You probably had different uuids on the packages.

**Comment by galenlynch** [comment]
Ok! I fixed the problem and it's probably a very uncommon use case, so I just wanted to let you guys know. Happy to close the issue
